microsoft/PTVS

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180404154020085 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180404154020085 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180405154048378 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180405154048378 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180405214033373 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180405214033373 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180406034015880 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180406034015880 to master

- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
Partially fixes #3798 Importing module names does not work
Adds special case for getting module names.
> Partially fixes #3798 Importing module names does not work

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180408094227725 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180408094227725 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180409154344267 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180409154344267 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180409214026610 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180409214026610 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180410034246285 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180410034246285 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180410154512185 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180410154512185 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180410214418389 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180410214418389 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Django.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20180410234631378 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180410234631378 to master

- Python/Templates/Django/ProjectTemplates/Python/Web/PollsDjango/project-urls.py
- Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject/loginpartial.html
- Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject/project-urls.py
For #4035 
Also clean up an unnecessary line space in loginpartial template.
> Add missing $ to regex in template's urls.py

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20180412154054532 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180412154054532 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Django.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl
Fix https://github.com/Microsoft/PTVS/issues/4043
> Localization update for 15.7 branch.

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Only applies to 15.7.
Fix https://github.com/Microsoft/PTVS/issues/4044
> Always disable the live linting feature, ignoring the feature flag.

- Common/Tests/Utilities/EventTaskSource.cs
- Common/Tests/Utilities/TestUtilities.csproj
- Python/Tests/Core/CodeFormatterTests.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/Utilities.Python/EventTaskSources.cs
- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
- Fix CodeFormatterTests so that test waits until analyzer finish parsing
- Switch ExtractMethodTests to real editor (100% pass)
> Test improvements

- Python/Product/ProjectWizards/ImportWizard.cs
- Python/Product/PythonTools/PythonTools/Commands/ImportWizardCommand.cs
Fix https://github.com/Microsoft/PTVS/issues/4028
> Fix the Project From Existing Code wizard to handle adding to an existing solution

- Build/Common.Build.Core.settings
- Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Django.targets
- Python/Product/Cookiecutter/source.extension.vsixmanifest
- Python/Product/Core/source.extension.vsixmanifest
- Python/Product/Django/source.extension.vsixmanifest
- Python/Product/IronPython/source.extension.vsixmanifest
- Python/Product/Profiling/source.extension.vsixmanifest
- Python/Product/Uwp/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/source.extension.vsixmanifest
- Python/Product/Wsl/source.extension.vsixmanifest
Fix https://github.com/Microsoft/PTVS/issues/4057
@zooba does this require changes in VS repository as well?
> Update version to 15.8.

- Python/Product/VSInterpreters/PackageManager/CondaPackageManager.cs
Needs VS approval before merging (internal bug 601484)
> Prevent crash in conda package manager backport to 15.7

- Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20180420154037528 to 15.7 with localized lcls
> LEGO: Pull request from lego/hb_839_20180420154037528 to 15.7

- Python/Product/Debugger/Debugger.csproj
Ran all debugger UI tests and manually tested django templates.
> Updated ptvsd to 4.1.1a1

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180423154030678 to 15.7 with localized lcls
> LEGO: Pull request from lego/hb_839_20180423154030678 to 15.7

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180423214031332 to 15.7 with localized lcls
> LEGO: Pull request from lego/hb_839_20180423214031332 to 15.7

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180424214037941 to 15.7 with localized lcls
> LEGO: Pull request from lego/hb_839_20180424214037941 to 15.7

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180425034031810 to 15.7 with localized lcls
> LEGO: Pull request from lego/hb_839_20180425034031810 to 15.7

- Common/Product/SharedProject/Navigation/ModuleId.cs
- Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs
- Python/Product/Analysis/Values/IterableInfo.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Product/VSInterpreters/Interpreter/ExperimentalOptions.cs
> Bunch of minor fixes

- Common/Product/SharedProject/ProjectNode.cs
- Python/Product/PythonTools/PythonTools/Project/DefaultPythonProject.cs
- Python/Product/PythonTools/PythonTools/Project/IPythonProject.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncherOptions.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncherProvider.cs
> Fix for editing django debug/run breaks launch

- Python/Product/PythonTools/PythonTools/SearchPathManager.cs
> Prevent crash when search path changes.

- Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs
> Prevent ArgumentNullException unexpected error in CPythonCondaPackageManagerProvider

- Python/Product/IronPythonResolver/Resolver.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
- Python/Tests/Utilities.Python.Analysis/TestUtilities.Python.Analysis.csproj
> Add detection for IronPython 2.7.8

- Python/Product/PythonTools/PythonTools/Project/PythonProjectConfig.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
> Prevent crash when the default interpreter is broken.

- Python/Templates/Django/ItemTemplates/Python/DjangoNewAppFiles14/DjangoNewAppFiles.vstemplate
- Python/Templates/Django/ItemTemplates/Python/DjangoNewAppFiles19/DjangoNewAppFiles.vstemplate
- Python/Tests/DjangoUITests/DjangoProjectUITests.cs
Fix #4079
Update django project ui tests to ensure they use an environment with django installed.
> Update django app "new item templates" to include subfolder under templates dir

- Python/Product/PythonTools/PythonToolsPackage.cs
> Prevent crash on launch file

- Python/Product/IronPython/Debugger/IronPythonLauncher.cs
> Fixes crash with IronPython with native debug enabled

- Python/Product/PythonTools/PythonTools/Refactoring/VariableRenamer.cs
> Backport fix for refactor rename to 15.7

- Python/Product/Cookiecutter/CookiecutterPackage.cs
> Cleanup status bar when cookiecutter is launched from new project wizard

- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
Fixes #4213
Fixes #4176
Fixes #4219
> Bunch of fixes

- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterViewModelTests.cs
> Clear any cloning or loading error in cookiecutter window when a new search is performed.

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fix #4218 
See bug for details
> Avoid crash in Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
> Fix for NRE in AnalyzeBufferAsync

- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/scrape_module.py
Manifests when scraping `posix` module on Mac with Python 2.7
> Fix exception in scraper

- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
> Don't report unhandled error when REPL scripts directory is not found.

- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
I cherrypicked the original commit that fixes both of these.
Fixes #4213 NullReferenceException in Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations
Fixes #4176 System.InvalidOperationException: Collection was modified after the enumerator was instantiated
Wait for VS approval before merging.
> Backport LocationTracker fixes to 15.7

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fix #4307 
This is what it looks like:
> Order navigation results that are displayed in the drop down bar.

- Python/Product/BuildTasks/Microsoft.PythonTools.targets
- Python/Product/BuildTasks/PythonCommand.cs
- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
Added MessageRegex to CreatePythonCommandItem  (to display Messages in `Error List` Window)
And also extended pylint command so it displays `{category}`:
- error -> error window
- warning -> warning window
- others -> messages window
> CreatePythonCommandItem.MessageRegexp + Pylint

- Python/Templates/Core/ItemTemplates/Python/MyPyIni/mypy.ini
> Remove unsupported examples from mypy.ini template.

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
> Fix NullReferenceException in CompletionAnalysis.

- Common/Tests/Utilities/Mocks/MockTextView.cs
- Common/Tests/Utilities/Mocks/MockTextViewRoleSet.cs
- Common/Tests/Utilities/TestUtilities.csproj
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/ModuleResolver.cs
- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Analysis/LanguageServerTests.cs
> Fix build and LS tests

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
Fixes #4385 Some modules missing from import completions
Ensures builtin modules are shown as available even before import
Fixes completion analysis for various contexts
> Fixes #4385 Some modules missing from import completions

- Python/Product/Analysis/AnalysisUnit.cs
- Python/Product/Analysis/Analyzer/OverviewWalker.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #3842 Class decorators do not pass type to function
Adds decorator handling for class definitions
> Fixes #3842 Class decorators do not pass type to function

- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Fixes #4364 Send to Interactive creates a new interactive session
Searches all open windows in MRU order for a suitable one when sending from a project
> Fixes #4364 Send to Interactive creates a new interactive session

- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/Analysis/LanguageServerTests.cs
Fixes #4417 from completions incorrectly autocomplete
Fixes selection of applicable span for from names.
> Fixes #4417 from completions incorrectly autocomplete

- Python/Tests/Core/CPythonInterpreterTests.cs
- Python/Tests/Core/CondaEnvironmentManagerTests.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/Core/ReplEvaluatorTests.cs
- Python/Tests/DjangoTests/DjangoAnalyzerTests.cs
Lower priority on some tests that have been failing consistently for a long time. They have bugs assigned to them, which are all labeled 'regression'.
> A few tests update

- Python/Product/Analysis/Intellisense/ImportedModuleNameWalker.cs
- Python/Product/Analysis/OverloadResult.cs
Fixes #3276 Cross-path intellisense
Improves cross-path intellisense
> Fixes #3276 Cross-path intellisense

- Python/Product/Analysis/AnalysisUnit.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
Fixes #4429 Incorrect refactor rename of parameter with default value
Get correct location of parameter name.
> Fixes #4429 Incorrect refactor rename of parameter with default value

- Python/Product/Analysis/Analysis.csproj
Not sure what merge broke it, but anyway.
> Fix build break

- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
Fixes #4446 Snippets not appearing in completions
Reactivates "_allowSnippet" option
> Fixes #4446 Snippets not appearing in completions

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #4447 Message processing task did not exit
Remove assertion
> Fixes #4447 Message processing task did not exit

- Python/Product/Analysis/Intellisense/OutliningWalker.cs
- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/Analysis/LanguageServerTests.cs
Fixes #4437 with ... as should not autocomplete
Fixes completion analysis for with statements.
> Fixes #4437 with ... as should not autocomplete

- Python/Product/Analysis/Infrastructure/EnumerableExtensions.cs
Original extension was calling itself.
> Fix stack overflow with settings change

- Python/Product/Analysis/LanguageServer/DiagnosticsErrorSink.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/InvalidEncodingSquiggleProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/PythonToolsMockTests/MockPythonToolsPackage.cs
- Python/Tests/PythonToolsMockTests/SquiggleTests.cs
- Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs
Fixes #3829 Squiggles disappear when file is reopened
Fixes diagnostics not appearing.
Fixes too many task comments appearing
Remove unused names.
> [WIP] Fixes #3829 Squiggles disappear when file is reopened

- Python/Product/Analysis/Interpreter/Ast/AstPythonType.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #4502 Activity log error while editing
Adds null check for when no response is received for LSP message
Adds mutual-recursion check and improves MRO traversal for AstPythonType.GetMember
> Fixes #4502 Activity log error while editing

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Infrastructure/EnumerableExtensions.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Values/BuiltinFunctionInfo.cs
- Python/Product/Analysis/Values/BuiltinModule.cs
- Python/Tests/Analysis/AnalysisSaveTest.cs
Fixes #4509 Nested imports not resolving correctly
Corrects assigning submodules to analysis objects
Fixes references to unresolved module names
Fixes comparison of builtin functions
> Fixes #4509 Nested imports not resolving correctly

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Infrastructure/EnumerableExtensions.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Values/BuiltinFunctionInfo.cs
- Python/Product/Analysis/Values/BuiltinModule.cs
- Python/Tests/Analysis/AnalysisSaveTest.cs
Fixes #4509 Nested imports not resolving correctly
Corrects assigning submodules to analysis objects
Fixes references to unresolved module names
Fixes comparison of builtin functions
> [15.8] Fixes #4509 Nested imports not resolving correctly

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionComparer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fix #4178 Live completions in REPL not working
Fix REPL completions not respecting the "live completions only" option and not synchronizing the buffer.
> Fix REPL completions

- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes error squiggles not clearing when warnings or tasks remain.
Fixes unnecessary recursive self-imports.
> Fixes error squiggles not clearing when warnings or tasks remain.

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionComparer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fix REPL completions not respecting the "live completions only" option and not synchronizing the buffer.
> [15.8] Fix REPL completions

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionComparer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionResult.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExpansionCompletionSource.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Cherry picked the new commits from https://github.com/Microsoft/PTVS/pull/4566
> Forward port to master the CompletionResult comparison changes

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20180731154039997 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180731154039997 to master

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
Fixes #4627 Type stub info is not included in module cache
Ensures type stub info is merged before putting module in the cache.
> Fixes #4627 Type stub info is not included in module cache

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Cookiecutter/Shared/Infrastructure/OutputWindowRedirector.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/VSCommon/Infrastructure/OutputWindowRedirector.cs
Fixes #4625 General pane in output window is unlocalised
Adds string for pane name.
> Fixes #4625 General pane in output window is unlocalised

- Python/Product/Analysis/Infrastructure/DisposeToken.cs
- Python/Product/Analysis/Infrastructure/TaskCompletionSourceExtensions.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/LanguageServer/Structures.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.Lifetime.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Replace RPC SyncContext with priority queue
- Add support for asyncStartup
> [WIP] LS improvements

- Python/Product/Analysis/AnalysisLogWriter.cs
> Revert "Fixes #4608 Crash in Microsoft.PythonTools.Analysis.AnalysisLogWriterDump"

- Python/Product/Django.Analysis/DjangoAnalyzer.cs
- Python/Tests/DjangoTests/DjangoAnalyzerTests.cs
- Python/Tests/TestData/DjangoAnalysisTestApp/test_render/views.py
Fixes #4144 No completion for custom tags and filters in Django projects
Fixes specializations for Django 1.9 and later
Improves tests
> Fixes #4144 No completion for custom tags and filters in Django projects

- Python/Product/Analysis/LanguageServer/Server.WorkspaceSymbols.cs
As we do in the variables collection
> Limit recursion in symbol conversion

- Python/Product/Analysis/Values/BuiltinNamespace.cs
Fix #4687
Manual backport of fixes in master.
> [15.9] Fix 4687: PTVS code completion does not work

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Snippets/Python/class.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/def.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/except.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/for.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/if.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/main.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/try.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/while.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Python/with.snippet.lcl
- Python/loc/lcl/PTB/Snippets/Test/testclass.snippet.lcl
- Python/loc/lcl/PTB/arg_path.snippet.lcl
- Python/loc/lcl/PTB/arg_path_positional.snippet.lcl
- Python/loc/lcl/PTB/arg_str.snippet.lcl
- Python/loc/lcl/PTB/arg_str_positional.snippet.lcl
- Python/loc/lcl/PTB/arg_switch.snippet.lcl
- Python/loc/lcl/PTB/argparse.snippet.lcl
LEGO: Pull request from lego/hb_839_20180915034111618 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180915034111618 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.RunElevated.exe.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.VSCommon.dll.lcl
LEGO: Pull request from lego/hb_839_20180917214045535 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180917214045535 to master

- Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
LEGO: Pull request from lego/hb_839_20180925214036601 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180925214036601 to master

- Python/Product/Debugger/Debugger.csproj
debugger ui tests are passing.
> Update to ptvsd 4.1.3.

- Python/Templates/Core/ProjectTemplates/Python/ConsoleAppProject/PythonConsoleApp.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/FromExistingCode/FromExistingCode.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/ClassifierTemplate.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/ClusteringTemplate.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/RegressionTemplate/RegressionTemplate.vstemplate
- Python/Templates/Django/ProjectTemplates/Python/Web/DjangoProject/DjangoApp.vstemplate
- Python/Templates/Django/ProjectTemplates/Python/Web/PollsDjango/PollsDjango.vstemplate
- Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject/StarterDjangoProject.vstemplate
- Python/Templates/Django/ProjectTemplates/Python/Web/WebRoleDjango/WebRoleDjango.vstemplate
- Python/Templates/IronPython/ProjectTemplates/Python/ConsoleProject/ConsoleProject.vstemplate
- Python/Templates/IronPython/ProjectTemplates/Python/WinformsProject/WinformsApp.vstemplate
- Python/Templates/IronPython/ProjectTemplates/Python/WpfProject/WpfApp.vstemplate
- Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsBottle/PollsBottle.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlask/PollsFlask.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlaskJade/PollsFlaskJade.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterBottleProject/StarterBottleProject.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskJadeProject/StarterFlaskJadeProject.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskProject/StarterFlaskProject.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectBottle/WebProjectBottle.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectEmpty/EmptyWebProject.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectFlask/WebProjectFlask.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleBottle/WebRoleBottle.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleEmpty/WebRoleEmpty.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleFlask/WebRoleFlask.vstemplate
- Python/Templates/Web/ProjectTemplates/Python/Web/WorkerRoleProject/WorkerRoleProject.vstemplate
Fix #4720 
This is a request from VS IDE team, to support work they are doing in dev16.
> Add template ids to project templates.

- Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj
> Update native module template default python version and windows sdk.

- Python/loc/lcl/PTB/Snippets/Python/while.snippet.lcl
LEGO: Pull request from lego/hb_839_20180927034042896 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20180927034042896 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181003094106176 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181003094106176 to master

- Python/Product/Analysis/Interpreter/Ast/AstCachedPythonModule.cs
> Backport fix for UnauthorizedAccessException from language server.

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181019094048521 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181019094048521 to master

- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181023154034307 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181023154034307 to master

- Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs
Fix #4777 Python loads 6 binaries during UWP solution load with designer view on top
We still load some binaries because our MEF export is in Microsoft.PythonTools.dll, but at least we don't kick off an analysis, which would load even more dlls (and start the analyzer out of proc).
> Avoid analyzing xaml files that are not in python projects.

- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
Also deleting that code map test that is unreliable and low value
> Update to ptvsd 4.1.4.

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181105154042026 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181105154042026 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181106094045640 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181106094045640 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181106154047470 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181106154047470 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20181106214031747 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181106214031747 to master

- Python/Product/PythonTools/PythonToolsPackage.cs
> Save and allow debugging of unopened files

- Python/loc/lcl/CHS/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.LiveShare.dll.lcl
LEGO: Pull request from lego/hb_839_20181204135110786 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181204135110786 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.LiveShare.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.LiveShare.dll.lcl
LEGO: Pull request from lego/hb_839_20181205154040773 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181205154040773 to master

- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml.cs
> Add environment dialog - automatically set focus to the appropriate name control

- Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20181213154044600 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181213154044600 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_839_20181218034031856 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181218034031856 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_839_20181218154039556 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181218154039556 to master

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentView.cs
> Replace our custom progress with the VS progress control 

- Python/loc/lcl/CSY/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_839_20181218214023009 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181218214023009 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_839_20181219094023569 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181219094023569 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_839_20181219154038504 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20181219154038504 to master

- Build/Common.Build.Cpp.settings
- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttach.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttachX86.vcxproj
- Python/Product/VsPyProf/VsPyProf.vcxproj
- Python/Product/VsPyProf/VsPyProfX86.vcxproj
> Update platform toolset for C++ projects

- Python/loc/lcl/CHT/Microsoft.PythonTools.VSCommon.dll.lcl
LEGO: Pull request from lego/hb_839_20190107094028850 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190107094028850 to master

- Build/Common.Build.Cpp.settings
- Python/Product/DebuggerHelper/dllmain.cpp
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PyDebugAttach/dllmain.cpp
- Python/Product/VsPyProf/PythonApi.h
- Python/Product/VsPyProf/dllmain.cpp
Fix https://github.com/Microsoft/PTVS/issues/4991
> Compile C++ projects with warning level 4.

- Python/Product/Attacher/NativeMethods.cs
- Python/Product/VsPyProf/PythonApi.cpp
> Change LoadLibrary calls to use LoadLibraryEx instead.

- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
> Update to ptvsd 4.2.0.

- Python/Product/PythonTools/PythonTools/Options/AdvancedEditorOptions.cs
> Clear the list of default completion characters.

- Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs
Added brackets to icrease priority of "??" operator because its priority lower than priority  of "+" operator.
> Added brackets to icrease priority of "??" operator

- Python/Product/Common/Strings.resx
- Python/Product/VSInterpreters/PackageManager/PipRequirementsUtils.cs
- Python/Tests/VSInterpretersTests/PipRequirementsUtilsTests.cs
Fix: #4945 
Ignore head branch name.
> Fix regex that parses requirments.txt and update unit tests

- Python/Product/PythonTools/PythonTools.vsct
> Put the add environment button back on the tool window toolbar.

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
> Update info bar messages to conform to UI standards

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/WorkspaceAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluatorProvider.cs
- Python/Product/VSInterpreters/Interpreter/IPythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Tests/Core/WorkspaceTestHelper.cs
Fix #4850 
I have some UI tests that aren't quite ready yet. I'll do a follow up PR for that.
> Open folder: send to repl and execute to repl

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190207154057299 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190207154057299 to master

- Python/Product/PythonTools/PythonTools/Refactoring/ExtractMethodRequestView.cs
- Python/Product/PythonTools/PythonTools/Refactoring/MethodExtractor.cs
- Python/Product/PythonTools/PythonTools/Refactoring/RenameVariableRequestView.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
Allow renaming and extracting method functionality for unicode python 3.0+
> Allow renaming and extracting method functionality for unicode Python

- Python/Tests/ReplWindowUITests/ReplWindowSendUITests.cs
- Python/Tests/ReplWindowUITests/ReplWindowSettings.cs
- Python/Tests/ReplWindowUITests/ReplWindowUITests.cs
- Python/Tests/ReplWindowUITests/ReplWindowUITests.csproj
- Python/Tests/ReplWindowUITestsRunner/ReplWindowSendUITests.cs
- Python/Tests/ReplWindowUITestsRunner/ReplWindowSmokeUITests.cs
- Python/Tests/TestData/SendToInteractive/SendToInteractive.pyproj
- Python/Tests/TestData/SendToInteractiveWorkspace/ImportSearchPathPackage.py
- Python/Tests/TestData/SendToInteractiveWorkspace/ImportWorkspacePackage.py
- Python/Tests/TestData/SendToInteractiveWorkspace/PrintInterpreter.py
- Python/Tests/TestData/SendToInteractiveWorkspace/PythonSettings.json
- Python/Tests/TestData/SendToInteractiveWorkspace/package1/__init__.py
- Python/Tests/TestData/SendToInteractiveWorkspaceSearchPath/folder1/__init__.py
- Python/Tests/Utilities.Python/PythonVisualStudioApp.cs
- Python/Tests/Utilities.Python/ReplWindowProxy.cs
Fix #5069 
Only test changes, no product change.
> Add REPL window tests for workspaces support.

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190212214033314 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190212214033314 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddInstalledEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/EnvironmentViewBase.cs
> Fix mismatch between caption and automation name for the add environment dialog OK button

- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Wpf/ModernStyles.xaml
Fix internal bug 790208
Use the VS builtin HyperlinkButton, which reports itself as a Hyperlink rather than a Button.
> Fix incorrect role for hyperlinks in add environment dialog

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190213034042767 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190213034042767 to master

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190213094032876 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190213094032876 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190213154041442 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190213154041442 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190213214017142 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190213214017142 to master

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
> Set automation help text on text boxes with watermark in the add environment dialog.

- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
> Show keyboard focus on add environment dialog tabs.

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
> Fix null bounding rectangle issue with the progress control in the add environment dialog.

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190214094032950 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190214094032950 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190214154040240 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190214154040240 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190215094023761 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190215094023761 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190215154037686 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190215154037686 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Wpf/ModernStyles.xaml
> Add a tooltip to the browse buttons in the add environment dialog.

- Python/Product/PythonTools/PythonTools/Environments/ProjectView.cs
> Fix automation name (for narrator) of the project combo box entries in the add environment dialog

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
Fix internal bug 790286 (issue 1)
> Fix narrator announcement of conda "add packages from" label

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
> Label some fields in the add environment dialog as optional.

- Common/Product/SharedProject/ProcessOutput.cs
- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsPage.cs
Fix #4995 
Update calls to Process.Start()
> Update calls to Process.Start()

- Python/Templates/Django/ProjectTemplates/Python/Web/PollsDjango/modernizr-2.6.2.js
- Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsBottle/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlask/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlaskJade/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterBottleProject/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskJadeProject/modernizr-2.6.2.js
- Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskProject/modernizr-2.6.2.js
> Remove inappropriate words

- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentManager.cs
- Python/Product/VSInterpreters/PackageManager/CondaPackageManager.cs
- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
- Python/Tests/Core/CondaEnvironmentManagerTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Fix #5115 
Fix #5111 
Fix #4820 
(they're all variations of we need to activate conda environment for X to work)
> Activate conda environments before executing them.

- README.md
> Update readme for VS 2019.

- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentManager.cs
- Python/Product/VSInterpreters/PackageManager/CondaPackageManager.cs
- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
- Python/Tests/Core/CondaEnvironmentManagerTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Backport of https://github.com/Microsoft/PTVS/pull/5119
> 16.0: Activate conda environments before executing them

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190301034040774 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190301034040774 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190301094028734 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190301094028734 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190301154050031 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190301154050031 to master

- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190301214026436 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190301214026436 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190306154038935 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190306154038935 to master

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190307094031046 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190307094031046 to master

- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttachX86.vcxproj
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/VsPyProf.vcxproj
- Python/Product/VsPyProf/VsPyProfX86.vcxproj
Resolving the warnings generated by VS recommended rule set.
Fix #4999
> C++ static analysis 4999

- Python/Product/IronPython/IronPythonPipPackageManagerProvider.cs
- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Product/VSInterpreters/PackageManager/CPythonPipPackageManagerProvider.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageManager.cs
- Python/Tests/Core.UI/EnvironmentUITests.cs
- Python/Tests/Core/EnvironmentListTests.cs
- Python/Tests/Utilities.Python.Analysis/MockCondaLocator.cs
- Python/Tests/Utilities.Python.Analysis/MockCondaLocatorProvider.cs
- Python/Tests/Utilities.Python.Analysis/TestUtilities.Python.Analysis.csproj
Fix #5140 
Adds a test that reproduces the issue and fix some existing tests that were failing for other reasons (all EnvironmentListTests are passing now).
> Ensure a conda environment is activated before running pip commands.

- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
> Allow users to paste information into the interactive experimental debugger window

- Python/Product/PythonTools/PythonTools/Intellisense/WorkspaceAnalysis.cs
Fix #5160 
Add a missing check for null like the one in a similar function below.
> Fix IntelliSense in LiveShare

- Python/Product/VSInterpreters/PackageManager/CondaPackageManager.cs
Tested with Conda 4.5.12 and 4.6.8
Fix #5147
> Remove "-p" argument going into "conda search..."

- Python/Product/WebRole/WebSocketProxy.html
Fix #5182 
Update embedded CSS in html resource to not use * selector, which was breaking some internal tools used by our localization team.
(I've sent this fix to them for validation and it solves their issue)
> Add localization tool workaround

- Python/loc/lcl/TRK/Microsoft.PythonTools.WebRole.dll.lcl
LEGO: Pull request from lego/hb_839_20190325153008108 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190325153008108 to master

- Build/15.0/packages.config
- Build/16.0/packages.config
> Update LiveShare package references to 1.0.

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Project/PackageInstallInfoBar.cs
- Python/Product/PythonTools/missing_req_packages.py
- Python/Product/VSInterpreters/PackageManager/PipRequirementsUtils.cs
- Python/Tests/Core.UI/EnvironmentUITests.cs
- Python/Tests/Core.UI/InfoBarUITests.cs
- Python/Tests/Core/EnvironmentListTests.cs
- Python/Tests/Core/WorkspaceInterpreterFactoryTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
- Python/Tests/VSInterpretersTests/PipRequirementsUtilsTests.cs
Fix #5040 
Please review the overall implementation while I write test cases.
> Add a python script which parses requirements.txt

- Python/Product/PythonTools/PythonTools/Editor/BraceMatcher.cs
> Correctly highlight matching brackets 

- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190408094024521 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190408094024521 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190410214019448 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190410214019448 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190411034033087 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190411034033087 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190411154033701 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190411154033701 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190411214018430 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190411214018430 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190412154033317 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190412154033317 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190412214018487 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190412214018487 to master

- Python/Product/VSInterpreters/Interpreter/PythonRegistrySearch.cs
Always look for fixed registry keys in addition to enumerating sub keys, since store apps registry keys are not returned when enumerating.
Fix #5189
> Find interpreters that are installed from the store

- Python/Product/Debugger/Debugger.csproj
- Python/Product/PythonTools/PythonTools/Debugger/ProvideDebugAdapterAttributes.cs
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
* Updates ptvsd to 4.2.8
* Enables Set Next Statement
* Enables and updates tests for set next statement
* Enables and updates tests for exceptions
> Update to ptvsd 4.2.8 and some other stuff

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Tests/Core.UI/EnvironmentUITests.cs
- Python/Tests/PythonToolsUITestsRunner/EnvironmentUITests.cs
> Install Python in Conda Environment creation with no packages

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190423214030509 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190423214030509 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190424094024922 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190424094024922 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190424161011652 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190424161011652 to master

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190424214021091 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190424214021091 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190425094030203 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190425094030203 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190425154040891 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190425154040891 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190426034031852 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190426034031852 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190426094032862 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190426094032862 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190426155034035 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190426155034035 to master

- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttachX86.vcxproj
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/VsPyProf.vcxproj
- Python/Product/VsPyProf/VsPyProfX86.vcxproj
Fix #5219 
Reverting changes so 16.1 works with "attach to process". Will implement changes later and fix the problem.
> Reverting C++ static analysis fixes

- Python/Product/VCDebugLauncher/16.0/source.extension.vsixmanifest
Fix https://github.com/Microsoft/PTVS/issues/5248
I filed https://github.com/Microsoft/PTVS/issues/5275 to do a proper fix
> Increment VCLauncher version.

- Common/Product/SharedProject/ProjectNode.CopyPaste.cs
- Common/Tests/Utilities.UI/UI/SolutionExplorerTree.cs
- Python/Tests/Core.UI/BasicProjectTests.cs
- Python/Tests/PythonToolsUITestsRunner/BasicProjectTests.cs
- Python/Tests/TestData/AddProjectReference/NativeModule/NativeModule.vcxproj
- Python/Tests/TestData/ProjectReference/NativeModule/NativeModule.vcxproj
Fix #5150 
Also fixes several basic project tests, but not all. I've put Ignore on the ones I haven't fixed, there's no point in running them now.
FYI it turns out that we already had a failing test for this bug, it passes now :)
> Fix add existing folder

- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
Fix #5307 
Workaround for CA2213 that doesn't understand object?.Dispose syntax.
> Fix policy build

- Python/Tests/Core.UI/ProjectHomeTests.cs
Modify DragDropRelocatedTest in ProjectHomeTests.cs to run on the latest build for 16.2.
> Modify DragDropRelocatedTest.cs to run successfully on the latest build for 16.2.

- Python/Tests/TestAdapterTests/TestExecutorTests.cs
> Remove failing P0 unit test

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.VSCommon.dll.lcl
LEGO: Pull request from lego/hb_839_20190603094051282 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190603094051282 to master

- Python/Product/Workspace/PythonLaunchDebugTargetProvider.cs
Fix script path to include working directory and script name
> Fix script path to include working directory and script name (#5384)

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190702204023021 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190702204023021 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190703084025940 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190703084025940 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190703144035841 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190703144035841 to master

- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/TestExecutor.cs
- Python/Product/TestAdapter/testlauncher.py
> Intergrate PTVSD into test explorer

- Python/Tests/TestAdapterTests/ExecutionTestInfo.cs
- Python/Tests/TestAdapterTests/MockRunContext.cs
- Python/Tests/TestAdapterTests/MockRunSettings.cs
- Python/Tests/TestAdapterTests/MockRunSettingsXmlBuilder.cs
- Python/Tests/TestAdapterTests/PytestExecutionTestInfo.cs
- Python/Tests/TestAdapterTests/TestAdapterTests.csproj
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestEnvironment.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestAdapterTests/TestInfo.cs
- Python/Tests/TestData/TestExecutor/test_duration.py
- Python/Tests/TestData/TestExecutor/test_env_var.py
- Python/Tests/TestData/TestExecutor/test_teardown.py
The ones I added are passing, there will be more to do.
> Add/rework existing unit tests for pytest execution (part 1)

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapterLauncher.cs
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
> PTVS debuggers will not debug PTVS files while in release mode

- Python/Product/TestAdapter/TestContainerDiscoverer.cs
- fixes issue when editing mulitiple unittest properties at the save time causes double refresh of test discovery
- removed _isRefresh guard on notifiation sending, because I moved notifying out of LoadProject and RemoveProject and they return bool didChange instead that way when doing solution full refresh we dont try to sent any notifications.
- also removed calling RemoveTestContainers() from OnTestPropertiesChanged(..) because we are going to trigger a refresh, which will clear everything. previously I also deleted the files in this handler but now notifications are no longer guarding on _isRefresh
> Updating TestContainerDiscoverer to defer notifying VS of changes

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/__main__.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/report.py
> fix UnitTest discovery returning duplicate tests #5466

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Options/GeneralOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Project/PytestConfigureInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/WorkspaceInfoBarManager.cs
- Python/Product/TestAdapter/TestContainerDiscoverer.cs
- Python/Product/TestAdapter/TestContainerDiscovererWorskspace.cs
- Python/Product/VSCommon/Logging/PythonLogEvent.cs
- Python/Product/VSCommon/Logging/PythonToolsLoggerData.cs
> Issue 5419 configure pytest info bar

- Python/Product/PythonTools/PythonTools/PythonFeedbackDiagnosticFileProvider.cs
Only write diagnostics when Python package is loaded into VS.
(MEF export means we may execute that code even when our package is not loaded)
Fix #5452
> Prevent writing an empty diagnostics file when Python package is not loaded

- Common/Tests/Utilities/TaskObserver.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
> Update to ptvsd 4.3.0

- Build/16.0/packages.config
- Python/Product/LiveShare/LiveShare.csproj
- Python/Product/LiveShare/PythonLanguageServiceProviderCallback.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Core/LiveShareTests.cs
- Python/Tests/Core/PythonToolsTests.csproj
> Fix for LiveShare assembly changes.

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/TestAdapter/PackageManagerEventSink.cs
- Python/Product/TestAdapter/TestAdapter.csproj
- Python/Product/TestAdapter/TestContainerDiscovererProject.cs
- Python/Product/TestAdapter/TestContainerDiscovererWorkspace.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs
- Python/Product/VSInterpreters/PackageManager/CPythonPipPackageManagerProvider.cs
- Python/Product/VSInterpreters/Projects/PythonProject.cs
Fix #5424
See commit messages (it may be helpful to look at them individually).
> Trigger discovery on interpreter/package changes

- Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs
- Python/Product/VSInterpreters/PackageManager/CPythonPipPackageManagerProvider.cs
Fix #5517 
Will create a bug for the functionality that this is now breaking (install package doesn't trigger test discovery)
> Make the package managers multi instances again

- Python/Tests/TestAdapterTests/TestExecutorTests.cs
> Remove failing tests

- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/__main__.py
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/TestAdapter.Executor.csproj
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter.Executor/Utils/TestUtils.cs
- Python/Product/TestAdapter/testlauncher.py
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/Mocks/MockRunSettingsXmlBuilder.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
> Backport fix for large projects to 16.3

- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttachX86.vcxproj
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/VsPyProf.vcxproj
- Python/Product/VsPyProf/VsPyProfX86.vcxproj
Fix #4999 
Since it's confirmed that these changes didn't cause problems with debug attach, I'm putting them back in. 
This reverts commit 2d07286212a0151971738762b66d0427297c9c7d.
> C++ static analysis fixes (#5251)

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20190808024048954 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190808024048954 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190809144049050 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190809144049050 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190809204033753 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190809204033753 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
> changing the warning to include the project/workspace folder 

- Python/Product/TestAdapter/TestContainerDiscovererWorkspace.cs
> Exclude test files in virtual env or workspace cache

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190814024047455 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190814024047455 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190814204037272 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190814204037272 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190815024040037 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190815024040037 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190815144052269 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190815144052269 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190815204031450 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190815204031450 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190816084031660 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190816084031660 to master

- Build/16.0/packages.config
> Fix build.

- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter/testlauncher.py
Refactor the debug settings and debug attach so it is reused for both pytest and unittest.
Copied the code from the unittest launcher script to the pytest launcher script.
Fix #5613
> Enable native code debugging for pytest.

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190820144036289 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190820144036289 to master

- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
> Raise TestSettingChanged when the unittest framework settings are changed

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190820204030055 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190820204030055 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190821024036066 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190821024036066 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190821084028884 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190821084028884 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190821144040513 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190821144040513 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190822144042551 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190822144042551 to master

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190821204031513 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20190821204031513 to master

- Python/Product/Debugger/Debugger.csproj
> Update to ptvsd 4.3.2

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190829084408144 to 16.3 with localized lcls
> LEGO: Pull request from lego/hb_839_20190829084408144 to 16.3

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20190829204030350 to 16.3 with localized lcls
> LEGO: Pull request from lego/hb_839_20190829204030350 to 16.3

- Python/Product/TestAdapter.Executor/Config/PythonProjectSettings.cs
- Python/Product/TestAdapter.Executor/Config/RunSettingsUtil.cs
- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/PythonTestDiscoverer.cs
- Python/Product/TestAdapter.Executor/Services/DiscovererFactory.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
cherry picking discovery telemetry fix for unittest not having its own events
> Bschnurr/cherrypick telemetry16.3

- Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentView.cs
> Allow selecting language version 3.8 in the add/edit environment UI

- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Taking PR #5710 and merging it into 16.3. Going through QB process as well.
> Fix the start debugging command caption

- Python/Product/Profiling/Profiling.csproj
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/TestAdapter/PythonRunSettings.cs
- Python/Product/TestAdapter/TestAdapter.csproj
- Python/Product/VSInterpreters/Interpreter/LaunchConfigurationUtils.cs
- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
Run unit test does not activate conda environment - ImportError  Fix  #5289
> add env activate before test discovery and execution

- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Tests/Core.UI/TestExplorerTests.cs
- Python/Tests/PythonToolsUITestsRunner/TestExplorerTests.cs
- Python/Tests/Utilities.Python/PythonTestExplorer.cs
Fix #5633
Tests cover:
pytest/unittest
project/workspace
> Adding UI tests for debbugging Test Explorer tests.

- Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20190925204036505 to 16.3 with localized lcls
> LEGO: Pull request from lego/hb_839_20190925204036505 to 16.3

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191002084018046 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191002084018046 to master

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191003084027156 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191003084027156 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191005000812202 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191005000812202 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191013024050409 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191013024050409 to master

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20191015204033106 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191015204033106 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Options/GeneralOptions.cs
- Python/Product/PythonTools/PythonTools/Project/PythonNotSupportedInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/WorkspaceInfoBarManager.cs
- Python/Product/VSCommon/Logging/PythonLogEvent.cs
- Python/Product/VSCommon/Logging/PythonToolsLoggerData.cs
> Python not supported info bar

- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191017204028743 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191017204028743 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191018144048726 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191018144048726 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191022204023337 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191022204023337 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191022144054316 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191022144054316 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191021204034866 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191021204034866 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191023024048285 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191023024048285 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20191105084026229 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191105084026229 to master

- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
> Fix invalid path bug

- Python/Product/PythonTools/PythonTools/Debugger/CustomDebugAdapterProtocolExtension.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
> Fix debug interactive window bug

- Python/loc/lcl/CSY/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191118204020541 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191118204020541 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191119024041540 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191119024041540 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191119084025937 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191119084025937 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Profiling.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Profiling.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191119144057457 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191119144057457 to master

- Python/Tests/Utilities.Python/PythonTestExplorer.cs
- Python/Tests/Utilities.Python/PythonTestExplorerGridView.cs
- catching exceptions, increasing sleep and retries
fix #5899
> Fixing UI tests

- Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191120024044577 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191120024044577 to master

- Python/loc/lcl/RUS/Microsoft.PythonTools.Profiling.dll.lcl
LEGO: Pull request from lego/hb_839_20191120144040106 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20191120144040106 to master

- Python/Product/PythonTools/PythonTools/Editor/Formatting/LspDiffTextEditFactory.cs
- Python/Tests/Core/LspDiffTextEditFactoryTests.cs
newline inserts were being set to cover 2 lines in the start/end parameters instead of just 1 line.
fix #5878
> Fix for format document sometimes deleting lines of code.

- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
> Prevent crash when creating environment script directory

- Python/Product/LiveShare/PythonLanguageServiceProviderCallback.cs
Fix #5887 
Do not directly cast to TIn or TOut in implementation of ILanguageServiceProviderCallback, since we no longer have a guarantee that the types passed in will match the types in the version of Microsoft.VisualStudio.LanguageServer.Protocol that we reference. We now convert between the LiveShare types and ours by going through the JSON format, which is stable and backwards compatible.
> LiveShare fix

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
> changing “Visit the distributer window” to a link instead of a button

- Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200106024038164 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200106024038164 to master

- Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200107144056523 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200107144056523 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200107204029837 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200107204029837 to master

- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
> Bug Fix for Unexpected Error while loading Python project

- Python/Product/Debugger/Debugger.csproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterProcess.cs
> Delay launching web browser for debugging web projects

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
> Django option fix

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200115084026263 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200115084026263 to master

- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200115204027297 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200115204027297 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200116144048371 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200116144048371 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200116024053236 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200116024053236 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200116204025601 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200116204025601 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200117024049922 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200117024049922 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200117144055252 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200117144055252 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200117204026733 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200117204026733 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
- Python/Tests/Utilities.Python/PythonVisualStudioApp.cs
New interactive window titles are now unique
> [Accessibility] interactive window titles are now unique

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Debugger/Debugger.csproj
Fix #5984 
Internal fix 998981 and 999043
> Update PTVSD and string changes

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200205024052032 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200205024052032 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200205144055734 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200205144055734 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200205204033490 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200205204033490 to master

- Build/16.0/packages.config
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterProcess.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
Fix #5977
Note: Code will not be compiled or merged until the updated API's have been pushed to nuget and the versioning has been updated in ptvs.
> Monitor messages between ptvsd and debugged process

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200206024055096 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200206024055096 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200206204056510 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200206204056510 to master

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
> Exclude PTVS files from debugger

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200213204044110 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200213204044110 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200213144059465 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200213144059465 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200213084043475 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200213084043475 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200213024055546 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200213024055546 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200212205143769 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200212205143769 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200212024104122 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200212024104122 to master

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugPortSupplier.cs
> Update name and description of remote debugging port supplier for debugpy

- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
> Update to debugpy 1.0.0b4.

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200403024059947 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200403024059947 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200403144103059 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200403144103059 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200403204050836 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200403204050836 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200407024057098 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200407024057098 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200407144058242 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200407144058242 to master

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
> Added null check on completions

- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200417024056490 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200417024056490 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200423024122549 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200423024122549 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200505024111206 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200505024111206 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200505144046258 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200505144046258 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200506204047324 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200506204047324 to master

- Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200508144120622 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200508144120622 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200521024120464 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200521024120464 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200521084042665 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200521084042665 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200521144110612 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200521144110612 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200521204053169 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200521204053169 to master

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200522024118096 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200522024118096 to master

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200522084037725 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200522084037725 to master

- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200523024111569 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200523024111569 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200529024115872 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200529024115872 to master

- Build/16.0/packages.config
> Update Python nuget packages

- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
> debugpy beta 10

- Python/Product/Debugger/Debugger.csproj
I ran the debugger UI tests locally and they all passed.
> Update to debugpy 1.0.0b12.

- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_839_20200701204111327 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200701204111327 to master

- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
I've already run the policy pipeline and verified that this resolves the native code warnings.
> Resolve static analysis warnings in native code

- Build/16.0/packages.config
- Build/PreBuild.ps1
I ran the PR pipeline manually and verified that this builds successfully.
> Update python package dev dependencies.

- Build/CredScanSuppressions.json
Note: 'folder' type of suppression requires enabling both 'Debug Mode' and 'Folder Suppression' in the pipeline credscan task (which I have done).
> Add credscan suppressions file.

- Build/16.0/packages.config
- Python/Product/ProjectWizards/ProjectWizards.csproj
- Python/Product/PythonTools/PythonTools.csproj
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/IronPython/IronPythonTests.csproj
- Python/Tests/PythonToolsMockTests/PythonToolsMockTests.csproj
Fixes the build on dogfood VS and on the (microbuild) build machine.
> Add NuGet package and update version of Microsoft.VisualStudio.TemplateWizardInterface

- Common/Product/ReplWindow/Repl/InlineReplAdornment.cs
- Common/Product/ReplWindow/Repl/ReplWindow.cs
- Common/Product/SharedProject/CommonFolderNode.cs
- Common/Product/SharedProject/WebPiComponentPickerControl.cs
- Common/Tests/MockVsTests/MockVs.cs
- Python/Product/Debugger.Concord/ExpressionEvaluator.cs
- Python/Product/PythonTools/ptvsd/repl/__init__.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/__main__.py
- Python/Tests/ProjectUITests/ShowAllFiles.cs
The only ones left after this are in non-english .lcl files, where policheck is assuming english. I'm looking into how to deal with those and will do a separate PR.
Note that I also created a PR in vscode-python to make fix the same warning in `testing_tools` in their code.
> Fix some policheck warnings.

- Python/Product/Debugger/Debugger.csproj
I've manually tested debug unit test.
I've run the debugger ui tests:
> Update to debugpy 1.0.0rc1

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
- Python/Tests/TestData/DebuggerProject/DebuggerProject.pyproj
- Python/Tests/TestData/DebuggerProject/SteppingTest8.py
> Disable debugpy subprocess debugging option.

- Python/Product/PythonTools/PythonTools/Environments/UserSpecifiedCondaLocator.cs
> make sure we are on the UIThread before calling GetPythonToolsServer()

- Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200831204052812 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200831204052812 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200901024112983 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200901024112983 to master

- Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200901204105605 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200901204105605 to master

- Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200902024118359 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200902024118359 to master

- Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200902084054458 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200902084054458 to master

- Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200902144134980 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200902144134980 to master

- Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200902204056735 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200902204056735 to master

- Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_839_20200903024115378 to master with localized lcls
> LEGO: Pull request from lego/hb_839_20200903024115378 to master

- Python/Product/VSInterpreters/Interpreter/PythonRegistrySearch.cs
Remove Python 2 from interpreters detection
> Remove Python 2.x support

- Python/Product/PythonTools/ProvideFileFilterAttribute.cs
- Python/Product/PythonTools/ProvideLanguageTemplatesAttribute.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageServerPylance.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
- Python/Product/VSInterpreters/Interpreter/InterpreterOptionsService.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Also fixes reopening of folder with previously open files. 
- Minor code cleanup
> Support loose files in editor

- Python/Product/PythonTools/PythonTools/Environments/EnvironmentSwitcherWorkspaceContext.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/IPythonLanguageClientContext.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientContextFixed.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientContextGlobal.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientContextProject.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientContextRepl.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientContextWorkspace.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
- Send updates to Pylance
- Minor reformatting to more modern style
> Handle interpreter change

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Utility/Interpreters.cs
Fixed couple of `// TODO: Pylance`
> Fetch Python language version from text buffer or view

- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
> fix broken UI test

- Python/Product/PythonTools/PythonTools/Debugger/ProvideDebugAdapterAttributes.cs
> enable searching in symbols while debugging

- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
To fix accessibility bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1241756
> Make text higher contrast

- Common/Product/SharedProject/ProjectNode.cs
- Python/Product/Pylance/Pylance.csproj
- Python/Product/Pylance/source.extension.vsixmanifest
Test explorer executor was not included in the pylance vsix. This fixes that.
Also fixed a problem with right clicking on a project node.
> Get Test explorer working again

- .gitignore
- .npmrc
- Build/UpdateNpmrc.ps1
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- azure-pipelines.yml
This work lets pylance be installed on the build machine from the private feed that @jakebailey setup.
Finally got it working after about 100 different tries.
Fixes: https://github.com/microsoft/PTVS-Pylance/issues/171
> Get pylance bundled during the build step

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1289875?src=WorkItemMention&src-action=artifact_link
Don't run conda activation events on the main thread.
> Fix problem with running conda activation on the main thread.

- Python/loc/lcl/KOR/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210405031244565 to master with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210405031244565 to master

- Python/loc/lcl/CHS/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Miniconda.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Miniconda.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210406091239119 to master with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210406091239119 to master

- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools.vsct
- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Navigation/TextViewFilter.cs
- Python/Product/PythonTools/PythonTools/Navigation/TextViewFilterProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
Add keybinding that works in an editor.
Add a ITextViewFilter so can listen to keyboard events.
> Reimplement CTRL+ENTER support for Send to interactive

- azure-pipelines.yml
Create a new TestData artifact to speed up test running (don't need to unzip everything as binaries are already there)
> Create test data artifact

- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/VSCommon/Infrastructure/TaskDialog.cs
Task dialog wasn't setup to work with 64 bit. 
Listener had a bug on environment change.
> Fix task dialog and problem with listener

- Build/17.0/packages.config
- Build/PreBuild.ps1
- Build/pr_nuget.config
- Common/Product/SharedProject/ProjectNode.cs
- Common/Tests/MockVsTests/MockVsExtensibility.cs
- Common/Tests/Utilities.UI/UI/AutomationWrapper.cs
- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Product/Core/Core.csproj
- Python/Product/Core/Properties/AssemblyInfo.cs
- Python/Tests/DjangoUITests/DjangoProjectUITests.cs
For https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1333422?src=WorkItemMention&src-action=artifact_link
Bug was caused by recent changes in the Task API that we need to build against. 
Updating the versions of stuff also broke some other things so fixed those too.
> Fix task missing method issue

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
- Python/Tests/Core/App.config
- Python/Tests/Core/PythonWorkspaceContextTests.cs
- Python/Tests/Core/WorkspaceTestHelper.cs
Fixes: #6547 
SearchPaths were not being passed as extra paths to pylance. Also we weren't responding to configuration subrequests.
> Make sure to pass SearchPaths to pylance 

- Python/Product/Cookiecutter/Cookiecutter.cs
- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/Cookiecutter.vsct
- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/source.extension.vsixmanifest
- Python/Product/Profiling/Profiling.csproj
- Python/Setup/loclayout.proj
- Python/Setup/signlayout.proj
- Python/products.settings
Fixes: #6537 
CookieCutter vsix was not being generated.
> Add back in the building of the cookie cutter vsix

- Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210603151105931 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210603151105931 to main

- Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210604151022582 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210604151022582 to main

- Common/Product/SharedProject/Wpf/Controls.xaml
copying radio button style from shell just like intillicode does
Fix #1245054
https://devdiv.visualstudio.com/DevDiv/_git/IntelliCode-VS?path=%2Fsrc%2FVSIX%2FIntelliCode.VSIX%2FDialogs%2FThemedDialogResources.xaml&version=GBmain&line=110&lineEnd=110&lineStartColumn=17&lineEndColumn=28&lineStyle=plain&_a=contents
> fix contrast ratio for the radio buttons in Profiling Settings

- Python/Product/Cookiecutter/Shared/Interpreters/PythonLanguageVersion.cs
> Support 3.8 and 3.9 and for cookiecutter

- Build/17.0/packages.config
- Build/Common.Build.CSharp.targets
- Python/Product/PythonTools/PythonTools.csproj
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1346682
> Change where IFeedbackDiagnosticFileProvider comes from

- Python/Product/Core/Core.csproj
- Python/Product/PythonTools/ptvsd/repl/ipython_client.py
> Get ipython to work again in 3.9

- Python/Product/PythonTools/PythonTools/Project/ConfigureTestFrameworkInfoBar.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
> Handle different exceptions that can occur and cause VS crashes

- Build/Common.Build.Core.settings
- Python/Prerequisites/deploy_test_targets.cmd
- Python/Product/TestAdapter.Executor/UnitTest/UnitTestTestExecutor.cs
- Python/Product/VCDebugLauncher/VCDebugLauncher.csproj
Fixes: #6595
VC team switched to v170 recently. We need to update to this as well.
> Fix build path for debug launcher targets

- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
Fixes: #6608
Obvious invalid recursion
> Fix recursion issue

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/DidChangeWatchedFilesRegistrationOptions.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/FileSystemWatcher.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
Submission should be ready today
> Update ILanguageClient try 2

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
Some more changes from core team
> Update ILanguageClient again

- Python/Product/EnvironmentsList/PipExtension.xaml
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
Fixes 
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1351212
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1351247
> Two accessibility fixes

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
Fix this issue:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355277
> Fix wrapping for header labels

- Common/Product/SharedProject/Automation/VSProject/OAReferenceBase.cs
- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1351220
Essentially change this:
to this:
This allows the 'link' on the install button to actually have a high enough contrast.
> Change 'install' command to not have a background color in the list box

- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210803211053087 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210803211053087 to main

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804031102608 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804031102608 to main

- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804151041491 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804151041491 to main

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804211034274 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210804211034274 to main

- Python/Product/EnvironmentsList/images/images.xaml
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1351235
Shell team recommended this fix.
> Add background color for all images using knownmoniker

- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
- Python/Product/PythonTools/PythonTools/Wpf/ModernStyles.xaml
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355297
> Fix sizing of menu items

- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210805151008519 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210805151008519 to main

- Common/Product/SharedProject/Misc/NativeMethods.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Wpf/Utilities.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355302
> Fix escaping on dropdown to not jump to source file

- Python/Templates/Core/ItemTemplates/Python/EmptyPackage/package.vstemplate
- Python/Templates/Core/ItemTemplates/Python/EmptyPyFile/empty.vstemplate
- Python/Templates/Core/ItemTemplates/Python/MyPyIni/mypyini.vstemplate
- Python/Templates/Core/ItemTemplates/Python/PyClass/class.vstemplate
- Python/Templates/Core/ItemTemplates/Python/TextFile/textfile.vstemplate
- Python/Templates/Core/ItemTemplates/Python/UnitTestFile/test.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/ConsoleAppProject/PythonConsoleApp.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/FromExistingCode/FromExistingCode.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/ClassifierTemplate.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/ClusteringTemplate.vstemplate
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/RegressionTemplate/RegressionTemplate.vstemplate
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1333372
> Fix template package references

- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210805031027028 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20210805031027028 to main

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
internal bug 1355277
previously only changed the regular environment list, forgot conda packages list
> adding keyboard control to conda environment package list

- Python/Product/PythonTools/PythonTools/Wpf/ModernDialogHeaderControl.xaml
> Fixing dark mode close button in environments dialog

- Build/16.0/packages.config
- Build/17.0/packages.config
- cgmanifest.json
Fix vulnerabilities found by component governance scans
> Fix component governance bugs

- Build/17.0/packages.config
Updating versions as requested in LSP bug at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1398549
> Update LSP client and protocol versions

- Python/Product/Core/Properties/AssemblyInfo.cs
Related to https://github.com/microsoft/PTVS/pull/6720
> remove LSP dll from AssemblyInfo.cs per VS team instructions

- package-lock.json
- package.json
> update to pylance 2021.11.0

- .github/workflows/issues.yml
Added auto labeling workflow for new issues
> Add issue labeling workflow

- Build/templates/build.yml
- Build/templates/install_microbuild_plugins.yml
- Build/templates/install_pylance.yml
- Build/templates/publish_build_artifacts.yml
- Build/templates/publish_symbols.yml
- Build/templates/publish_test_data.yml
- azure-pipelines.yml
- Clean up stale yaml
- Use templates to separate logic and make the main yaml more readable
> yaml cleanup

- Build/Common.Build.Core.settings
- Python/Setup/swix/Packages/file_associations.swr
> Fix for file association launching from file explorer

- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Snippets/Python/class.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/def.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/except.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/for.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/if.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/main.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/try.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/while.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Python/with.snippet.lcl
- Python/loc/lcl/DEU/Snippets/Test/testclass.snippet.lcl
- Python/loc/lcl/DEU/arg_path.snippet.lcl
- Python/loc/lcl/DEU/arg_path_positional.snippet.lcl
- Python/loc/lcl/DEU/arg_str.snippet.lcl
- Python/loc/lcl/DEU/arg_str_positional.snippet.lcl
- Python/loc/lcl/DEU/arg_switch.snippet.lcl
- Python/loc/lcl/DEU/argparse.snippet.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220120101151705 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220120101151705 to main

- Build/UpdateNpmrc.ps1
- Build/templates/configure_pylance.yml
- azure-pipelines-policy.yml
Fixes #6861
Fixed the policy pipeline since it's been broken for a little bit.
- Fixed up the yaml
- Moved the pylance feed token secret to the `PTVS-Dev17` azdo environment, since variables on the pipeline itself isn't as sustainable
Manually ran the build at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5667983&view=results to verify it works, all is green.
> Fix policy pipeline

- azure-pipelines-policy.yml
This will only run in an internal pipeline that sets UseCodex = true
> Add a Yaml step to index source code

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220422095751319 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220422095751319 to main

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220423143853976 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220423143853976 to main

- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220424144852264 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220424144852264 to main

- Python/Tests/Core/WorkspaceTestHelper.cs
This branch doesn't currently compile, these changes fix that.
> Fix compile errors in old VS 16.11 branch

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220522152325660 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220522152325660 to main

- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220523105520560 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220523105520560 to main

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
- Python/Product/PythonTools/PythonTools/Repl/Completion/AsyncCompletionSource.cs
Fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1544818
> Update lsp protocol package and fix compile errors

- Build/17.0/packages.config
- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
And fix an issue with the integration test vsix.
> update lsp client package and dependencies

- Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220624095521909 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220624095521909 to main

- Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
- Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220625101239563 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220625101239563 to main

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.cs
> Add localization support to Options -> Python -> Debugging -> variable group categories.

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220707094914641 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220707094914641 to main

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220803101121946 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20220803101121946 to main

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptions.cs
> Set default presentation mode for Protected variables to Inline

- Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj
fixes https://github.com/microsoft/PTVS/issues/7150
> Fix default python version in python extension module template

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
fixes https://github.com/microsoft/PTVS/issues/7159
> Switch RefreshSearchPaths() to run on UI thread.

- Build/17.0/packages.config
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1599430
> upgdate lsp protocol version

- .github/workflows/issues.yml
Fix https://github.com/microsoft/PTVS/issues/7218
This reverts commit be6074fe4a019b75be5729199fc51a17df840263.
> Remove project board automation since we don't have org-level token

- Build/17.0/packages.config
> update lsp protocol version

- Python/Product/EnvironmentsList/ToolWindow.xaml
> don't allow the user to tab to the toolbar button

- Python/Product/Common/Infrastructure/ProcessOutput.cs
> silence codeql

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Calling and blocking on Conda was occuring while on the UI thread, make sure we're on a background thread before doing this.
Fixes: #1953945 (internally)
> Avoid freezing when calculating environments

- Build/templates/build.yml
- Build/templates/install_microbuild_plugins.yml
- Build/templates/publish_test_data.yml
- Python/Tests/TestData/DjangoAnalysisTestApp/DjangoAnalysisTestApp/settings.py
- Python/Tests/TestData/DjangoApplication/DjangoApplication/settings.py
- Python/Tests/TestData/DjangoDebugProject/DjangoDebugProject/settings.py
- Python/Tests/TestData/DjangoProject/settings.py
- Python/Tests/TestData/DjangoProjectWithSubDirectory/project/config/settings.py
- Python/Tests/TestData/DjangoTemplateCodeIntelligence/settings.py
- Python/Tests/TestData/DjangoTestApp/settings.py
- Python/Tests/TestData/WFastCgi/DjangoApp/DjangoApp/settings.py
- Python/Tests/TestData/WFastCgi/DjangoAppUrlRewrite/DjangoApplication/settings.py
- Python/Tests/TestData/WFastCgi/DjangoSimpleApp/DjangoApplication/settings.py
- Python/Tests/TestData/WFastCgi/DjangoSimpleAppUrlRewrite/DjangoApplication/settings.py
- Python/Tests/TestData/WFastCgi/DjangoTestApp/settings.py
- azure-pipelines.yml
Fixes https://github.com/microsoft/PTVS/issues/7815
- The build pipeline test run is at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9076892&view=results
- Published artifacts are at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9076892&view=artifacts&pathAsName=false&type=publishedArtifacts
- Test release and insertion PR checks are at https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/528636
I also installed the build from insertion PR comments and ensured PTVS work as expected.
> Migrate to 1es template

- azure-pipelines-compliance.yml
- Also removed api scan secret from https://devdiv.visualstudio.com/DevDiv/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=381&path=PTVS-Dev17
- Also removed ptvs-apiscan app registration from azure
> Removed apiscan since this is handled by VS

- Build/templates/publish_symbols.yml
fixes https://github.com/microsoft/PTVS/issues/7882
> Upgrade symbol archiving task version

- Build/Run_Azdo_Pipeline.ps1
- azure-pipelines.yml
- test.yml
- Remove weekly schedule which was only there to grab the latest pylance release (since pylance release pipeline now chains into the ptvs pipeline)
- Add some files used for testing the run-pipeline rest api
> Remove weekly schedule, add some test files

- Examples/PythonNative/.gitignore
- Examples/PythonNative/PythonNative.cpp
- Examples/PythonNative/PythonNative.sln
- Examples/PythonNative/PythonNative.vcxproj
- Examples/PythonNative/PythonNative.vcxproj.filters
- Examples/PythonNative/README.md
- Examples/PythonNative/drive_runner.py
- Examples/PythonNative/runner.py
- Examples/PythonNative/test.py
Adding an examples directory for future use
> Add native example

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/questions-and-help.md
- .github/workflows/issues.yml
Based on discussion in retrospective, changing the label to be `needs repro` and adding everyone to the rotation list.
> Change to `needs repro` label to update rotation list to include everone.

- Python/Product/TestAdapter/testlauncher.py
just flagging this incorrect usage of getattr
> fix exception caused by getattr calls without default value

- Build/templates/create_vs_bootstrapper.yml
- Build/templates/restore_packages.yml
- azure-pipelines.yml
Fixes https://github.com/microsoft/PTVS/issues/7994
> Disable CSV for bootstrapper since we don't ship it

- Python/loc/lcl/CHS/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/ITA/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.EnvironmentsList.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.EnvironmentsList.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20240925170123536 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20240925170123536 to main

- azure-pipelines-release.yml
Fixes #https://github.com/microsoft/PTVS/issues/8011
Initial port of the release pipeline to yaml
> port release pipeline to yaml

- Python/Product/PythonTools/ptvsd/repl/jupyter_client.py
fixes
https://github.com/microsoft/PTVS/issues/6853
https://github.com/microsoft/PTVS/issues/7118
https://github.com/microsoft/PTVS/issues/7219
https://github.com/microsoft/PTVS/issues/7064
> Fix interactive window hang by handling new type of exception

- Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
- Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20241101191308757 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20241101191308757 to main

- Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20241102191645236 to main with localized lcls
> LEGO: Pull request from lego/hb_00719690-99d0-4d46-875c-cfd2b9712715_20241102191645236 to main

- Build/glass/cache_glass.yml
- Build/templates/run_tests.yml
> add a new weekly pipeline to update the glass binaries from main branch.

- Build/templates/run_tests.yml
- azure-pipelines.yml
> cache glass binaries (#8107)

- Build/Get_Azdo_Build.ps1
Added an azdo api script to get build information for a specified build number
> Add azdo api script

- Python/Product/Common/Infrastructure/PathUtils.cs
- azure-pipelines.yml
> Add a guard on path

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- azure-pipelines.yml
fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2430556
Now the keyboard focus doesn't stop at the pane twice anymore.
> Fix accessibility bug

- Python/Product/Profiling/Profiling/LaunchProfiling.xaml
- Python/Product/Profiling/Strings.resx
- package.json
fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2477514
Based on expected behavior in the issue, I made the focus not move to the label, and also associated the label with the options.
> Fix accessibility issue

- Python/Tests/Core.UI/ErrorListTaskListTests.cs
- Python/Tests/PythonToolsUITestsRunner/ErrorListTaskListTests.cs
Fixes for Error list test. mostly updating the error count differences between pylance and the old LS.
> Fixes for Error list test. mostly updating the error count differences between pylance and the old LS.

- Common/Tests/Utilities.UI/UI/AutomationWrapper.cs
- Common/Tests/Utilities.UI/UI/VisualStudioInstance.cs
- Python/Tests/ProjectUITests/BasicProjectTests.cs
new PR to see if license/cla step will pass in the checks
> Fix project UI tests runner
