- Python/Product/Debugger/Debugger/PythonProcess.cs
We've started trying to read the source file when listing frames, but we weren't handling the case where we couldn't load the file.
> #42 Azure remote debugging - breaking doesn't work

- Common/Tests/MockVsTests/MockVs.cs
This fixes test errors where an assembly can't be loaded lazily, which we detect in GetTypes but it's still in the catalog, so MEF fails later on.
> Add assembly catalog _after_ verifying that the assembly can be loaded.

- Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
Fix #49: Deadlock while starting debugging
Raise the EngineAttached event before reporting LoadComplete to VS to prevent a race between the debug manager asynchronously querying breakpoints for hit count, and the REPL synchronously attaching to debuggee.
> Fix #49: Deadlock while starting debugging

- Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs
- Python/Tests/Core/EditorTests.cs
We spoke with the VS Team and it seems splitting collapsed regions
between \r\n can be a bit fragile. Code has been added to handle this
and our test cases have been edited to account for the adjustment.
> fixes #62 Crash collapsing region block

- Python/Product/Analysis/SaveAnalysis.cs
- Python/Product/Analysis/Values/BuiltinModule.cs
- Python/Tests/Analysis/AnalysisSaveTest.cs
It's possible (and with a recent change, likely) to have a special callable with no original value. To avoid crashing in this case, we add a check.
> Fixes null reference exception when saving analysis.

- Common/Product/SharedProject/Automation/VSProject/OAReferenceBase.cs
- Python/Product/PythonTools/PythonTools/Project/Automation/OAPythonExtensionReference.cs
Implements RefType so that the XAML designer no longer aborts initialization when getting our references.
There are other issues due to how the design host handles paths and a possible .NET bug relating to URIs, but this fix should clear up our side of the issue.
> #34 XAML designer doesn't work in VS 2015 RC

- index.html
- stylesheets/stylesheet.css
Looks like this:
Feel free to propose improvements in the form of a pull request.
> Adds Downloads section to top of gh.io page.

- Python/Product/Analysis/XamlProjectEntry.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs
Also prevents deadlock when updating object browser.
> Prevents XAML dependencies being updated while iterating over them.

- Python/Product/Uwp/Interpreter/PythonUwpInterpreterFactory.cs
- Python/Product/Uwp/Interpreter/PythonUwpInterpreterFactoryProvider.cs
- Python/Product/Uwp/Microsoft.PythonTools.Uwp.targets
- Python/Product/Uwp/Templates/Projects/BackgroundService/PythonBackgroundService.pyproj
Moving CPython.targets import into PTVS UWP targets file in lieu of the pyproj
Scanning for UWP interpreters and versions based on installed SDKs
> Scanning for UWP interpreters and moving CPython UWP targets import

- Common/Tests/Utilities/Mocks/MockClassificationTypeRegistryService.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Parsing/Ast/Parameter.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
Ensures AST walkers will walk parameter decorators.
Also fixes IntelliSense in functions that include lambda functions.
> #21 Types in annotations are not highlighted

- Python/Product/PythonTools/PythonTools/Project/PythonProjectLaunchProperties.cs
Previously, the code would construct a key,value pair both consisting
of empty strings, which in turn would cause an empty entry to be
added to the environment block used to launch the process.
This would result in VsShellUtilities.LaunchProcess() failing
internally when launching the interpreter (and it would print
"Exception : Could not launch <python-interpreter>" to the debug
console.
With this patch, we just do nothing if the search paths are empty.
> Don't add empty search paths to the environment.

- Python/Product/PythonTools/PythonTools/Intellisense/FuzzyCompletionSet.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/OVERRIDECOMPLETIONANALYSIS.CS
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Adds support to FuzzyCompletionSet to opt-out of committing by default.
Opts-out of committing by default for single element collections in case they are going to become a comprehension.
(The existing tests cover this case fine.)
> #155 Don't auto complete identifiers on first list/tuple element

- Python/Product/Analysis/Parsing/Parser.cs
Expands tuples on Python 2.7 and earlier when parsing exec statements.
> #172 Python 2.x qualified exec is detected as unqualified

- Common/Product/SharedProject/ProjectFactory.cs
- Python/Tests/Core/ProjectUpgradeTests.cs
Changes project factory to return empty GUIDs by default to avoid circular references.
> #97 Trouble 'upgrading' project from PTVS 2.1 to 2.2 RC

- Python/Product/Debugger/Debugger/DebugEngine/AD7Events.cs
Add Python Engine guid to EXCEPTION_INFO object in AD7 call to GetException.
This completes the exception object for the VS Debugger UI to properly process changes to this exception when the user modifies its break settings via the exception thrown dialog.
This change fixes an issue where a user changes the break when thrown setting for a thrown exception via the Exception Assistant (or Exception Thrown Dialog) and it does nothing. The debugger ui relies on the exception's guidType to find the exception changed. Without a guid, the debugger does nothing.
> Add Python Engine guid to EXCEPTION_INFO object in AD7::GetException()

- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Fixes detection of too many interpreters when testing.
This change reduced the test running time to less than 1 minute on my machine for the first run (mostly IO time, with the detection issue hurting that too), and down to 10 seconds on subsequent runs.
> Parallelises parser stdlib test to reduce running time.

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Fixes suggestions appearing when local variables are defined.
> Ensures missing imports calculate the target text on the UI thread.

- Python/Product/Analysis/PythonKeywords.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
Fixes statement range calculation to correctly handle empty statements.
Allows "await" to appear as a statement keyword.
> #272 await missing from completions

- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/ImportWizard/ImportSettings.cs
- Python/Product/PythonTools/PythonTools/Project/VirtualEnv.cs
- Python/Product/VSInterpreters/DerivedInterpreterFactory.cs
- Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs
Adds fallback to detection by path names when a virtual environment's base interpreter cannot be found by ID.
Moves some virtualenv related functions into DerivedInterpreterFactory.
> #263 Invalid interpreter when sharing the .pyproj file in VCS

- Python/Product/Analysis/Parsing/Ast/FunctionDefinition.cs
- Python/Product/Analysis/Parsing/Ast/NodeAttributes.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/PythonTools/PythonTools/Refactoring/ExtractedMethodCreator.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/IronPython/IronPythonDatabaseTest.cs
Fixes verbatim parsing of async def to preserve correct whitespace
Ensures extracted method bodies that use await generate async functions
Also fixes IronPythonDatabaseTest
> #256 Cannot extract async method

- Python/Product/Django/TemplateParsing/TemplateArtifactCollection.cs
- Python/dirs.proj
Fixes building when itemsInRange is not an `IReadOnlyList`.
Also has the build fix from another PR... whoops...
> Build issue

- Python/Product/PythonTools/visualstudio_py_debugger.py
- Python/Tests/DebuggerUITests/DebugProject.cs
- Python/Tests/TestData/DebuggerProject/DebuggerProject.pyproj
- Python/Tests/TestData/DebuggerProject/ImportLibException.py
Added '<frozen importlib._bootstrap_external>' to the list of modules to not debug on 3.5.
> Fix #275: Exceptions on python 3.5 when debugging

- Python/Product/PythonTools/visualstudio_py_debugger.py
- Python/Product/PythonTools/visualstudio_py_repl.py
- Python/Product/PythonTools/visualstudio_py_util.py
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/TestData/DebuggerProject/AttachOutput.py
Rewrote the test to only capture output while running, and assert afterwards.
Fixed bug exposed by the updated test with Python 3.4 and 3.5 where directly attaching to the process that hasn't imported threading module yet would cause an assert in that module to fail on process shutdown because it incorrectly identified a debugger helper thread as a main thread.
Changed the use of local imports in conjunction with 'global' to not rely on implementation details of that interaction.
> Fix #301: AttachWithOutputRedirection test asserting from incorrect thread

- Python/Product/Analyzer/PyLibAnalyzer.cs
I have seen issues on various machines where some packages (typically pip) always have 1-2 files deleted at the end of an analysis run and then display as out of date. This logging will help diagnose these issues in release builds (I'm yet to come across a debug build with the problem).
> Adds extra logging for diagnosing DB out of date issues.

- Python/Product/Analysis/Parsing/Parser.cs
Defaults to opening files with UTF-8 unless a coding comment is included.
> #298 Incorrect encoding detection

- Python/Product/Django/ProvideLanguageTemplatesAttribute.cs
- Python/Product/PythonTools/PythonTools/Project/ImportWizard/ProjectCustomizations.cs
- Python/Product/Uwp/Guids.cs
- Python/Product/Uwp/Templates/Projects/BackgroundService/PythonBackgroundService.pyproj
- Python/Tests/Core.UI/BasicProjectTests.cs
Changes the UWP project factory GUID to sort before the main Pyhton project factory to avoid failing a test during template search.
Removes an incorrect comment from ProvideLanguageTemplatesAttribute.
Adds a test to ensure templates can be found.
(ping @juanyaw)
> #188 Can't create web role or worker role

- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/TestData/DebuggerProject/AttachPtvsd.py
Helps AttachPtvsd test work better when test target already has ptvsd installed.
See #340
> Prevents timeout in AttachPtvsd test (only occurs for Python 2.5)

- Python/Product/PythonTools/ptvsd/attach_server.py
Use the older Thread.setDaemon API that is available on all supported Python versions, including 2.5.
> Fix #340: ptvsd.enable_attach causes process to never exit under Python 2.5

- Python/Tests/DebuggerTests/DebuggerTests.cs
Use predefined constant for timeout in AttachPtvsd test.
> Specify timeout when waiting for process exit in AttachWithOutputRedirection test

- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/TestData/Grammar/AwaitAsyncNames.py
- Python/Tests/TestData/Grammar/DecoratorsAsyncFuncDef.py
Improves handling of async and await as names rather than keywords.
Adds and improves tests.
> Fixes #338 Failing to parse async correctly

- Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
Fixes #379 Cannot change architecture of a custom environment
Converts architecture string to processor architecture, since the configurable provider expects different strings.
> Fixes #379 Cannot change architecture of a custom environment

- Common/Product/ReplWindow/Repl/OutputBuffer.cs
- Common/Product/ReplWindow/Repl/ReplOutputClassifier.cs
- Common/Product/ReplWindow/Repl/ReplWindow.cs
#351 Repl is slow when displaying lots of coloured output
Batches edits to the repl window buffer so that the updates all occur at once.
Removes unnecessary marshalling to the UI thread.
Fixes error when opening interactive window.
> #351 Repl is slow when displaying lots of coloured output

- Python/Product/PythonTools/PythonTools/Intellisense/FuzzyCompletionSet.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
#362 __init__ completion too aggressive
Makes commitByDefault argument optional to avoid overriding settings from the completion set.
Fixes Ctrl+Space throwing exceptions when completing a filtered name.
> #362 __init__ completion too aggressive

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseControllerProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSourceProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/SmartTagControllerProvider.cs
- Python/Product/PythonTools/PythonTools/Options/OptionsTreeView.cs
- Python/Product/PythonTools/PythonTools/Options/PythonFormattingOptionsControl.cs
Fixes #364 Tools | Options | Text Editor | Python | Formatting | Spacing can't be loaded
Removes folder images from treeview.
Also prevents IntelliSense providers from loading against the preview editor to avoid many assertions.
> #364 Tools | Options | Text Editor | Python | Formatting | Spacing can't be loaded

- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/TestData/Grammar/FromFuture35.py
Fixes #336 Do not recognise generator_stop future
Stops reporting an error for generator_stop on Python 3.5
(Meets the bar because it's a trivial fix for recent Python 3.5 additions.)
> Fixes #336 Do not recognise generator_stop future

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #121 IntelliSense suggestions in exceptions are missing
Only keep suggesting exceptions when the grouping is the first item.
(Doesn't meet the bar, but it's such a trivial fix to something new since 2.1 that if people want to convince me to take it I won't argue too hard.)
> Fixes #121 IntelliSense suggestions in exceptions are missing

- Common/Tests/Utilities/AssertUtil.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/PythonLanguageVersion.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/Analysis/PythonKeywords.cs
- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisQueue.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs
- Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/PythonEditor.cs
#370 Reverse expression parser needs updating for async
Always parses context-dependent keywords as keywords when parsing isolated expressions.
Improves stability of tests.
Fixes tokenizer crash when parsing invalid complex value.
#374 Local variables are not initially colorized
Ensures the event is hooked and classifications are calculated when analysis is complete before classifications are requested.
Improves test stability
(Originally wasn't going to look at #374 for 2.2, but needed the fix for test stability or we wouldn't ever get classifications.)
> Intellisense fixes

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/DecoratorCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExceptionCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/OVERRIDECOMPLETIONANALYSIS.CS
Fixes #393 NullReferenceException getting completions
Handles when GetAnalysisEntry() returns null.
Adds assertions to detect this case earlier.
> Fixes #393 NullReferenceException getting completions

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Fixes #395 Interactive Window DTE commands no longer accept arguments
Removes eager (and incorrect) handling of commands in the edit filter and lets the global handler deal with them.
Avoids crashing in IntellisenseController after failing to get the view adapter for a particular view.
(All the repl window tests depend on this, so it's well tested.)
> Fixes #395 Interactive Window DTE commands no longer accept arguments

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/PythonToolsMockTests/PythonEditor.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
Makes PythonEditor wait for analyzer to load before continuing. This stabilises (at least) the refactor rename tests.
> Makes PythonEditor wait for analyzer to load before continuing

- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
This test was failing as it has multiple files and we were providing the
incorrect filename for all files after the first.
> Fixes Failing RefactorRenameTests.CrossModuleRename

- Python/Product/PythonTools/PythonTools/Intellisense/SmartTagSource.cs
Fixes #402 NullReferenceException getting smart tags
Checks whether our session has a controller. If not, no tags. (This seems to occur while debugging.)
> Fixes #402 NullReferenceException getting smart tags

- Python/Product/PythonTools/PythonTools/Project/InterpretersNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #421 Unhandled Python-not-runnable exception
Adds unhandled exception type to try/catch statement.
Fixes #422 Unhandled exception in PythonProjectNode.RemoveInterpreter
Suppresses extra message box for "normal" errors when deleting directories.
> Fixes #421 and #422

- Python/Product/PythonTools/PythonTools/Options/GlobalInterpreterOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonInterpreterOptionsPage.cs
- Python/Product/PythonTools/PythonToolsService.cs
Fixes #407 Interactive options does not load environment list
Loads options dialog state when creating the Python Tool service.
> Fixes #407 Interactive options does not load environment list

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
Fixes #273 opened files don't completely refresh when switching between python 2 and 3
Corrects ordering of calls vs. updating _analyzer
Adds NewVersion function to PythonAnalysisClassifier
> Fixes #273 opened files don't completely refresh when switching between python 2 and 3

- Python/Setup/PythonToolsInstaller/UpgradeCodes.wxs
Fixes #423 Installer does not remove VS 2013 template
Corrects "elif" to "elseif" in WiX authoring.
> Fixes #423 Installer does not remove VS 2013 template

- Common/Product/SharedProject/IdleManager.cs
Fixes #431 Survey/News command crashes VS
Ensures IdleManager manipulates its events and accesses COM objects on the UI thread.
> Fixes #431 Survey/News command crashes VS

- Common/Tests/Utilities/VCCompiler.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Add Common7\IDE to PATH to pick up some DLLs for VC10.
- Prepend rather than append new entries to PATH to ensure that they override everything else there.
- Always use Win7 SDK for VC10 rather than Win8 SDK (the latter has headers that don't compile with VC10).
Add extra error logging to debugger tests for child properties to help diagnose test run issues.
> Some fixes for debugger tests that require compiling C++ code

- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
Increase number of retries while waiting for Error List to asynchronously update before giving up.
> Fix #419: ErrorListTaskListTests not seeing any items on VS 2013

- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs
- Python/Product/PythonTools/visualstudio_py_repl.py
Propagate debug options (that make sense in that context) to the REPL, and then from the REPL to the main debugger script, when using $attach command.
> Fix #411: Cannot attach debugger to interactive window

- Python/Tests/ReplWindowUITests/ReplWindowPythonTestEntryPoints.cs
> Fixes #412 ReplWindowPython354Tests are poorly named

- Python/Product/Uwp/Microsoft.PythonTools.Uwp.targets
Allows the project to load for UWP projects even if the SDK isn't installed and gives a build error indicating where to get CPython UWP SDK if not installed
> Uwp targets update to give error text

- Python/Product/Debugger/Debugger/IdDispenser.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
Fix IdDispenser issuing the same ID over and over again in some circumstances.
Do not crash on error response with unknown request ID.
> Fix #441: Crash debugging multithreaded project

- Common/Tests/Utilities.UI/UI/InteractiveWindow.cs
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Tests/Core.UI/VirtualEnvTests.cs
- Python/Tests/Utilities.Python/PythonVisualStudioApp.cs
Fixes #455 NullReferenceException in EnvironmentReplWorkingDirectory test
Fails test if we can't find the interactive window.
Fixes GetInteractiveWindow for VS 2015
> Fixes #455 NullReferenceException in EnvironmentReplWorkingDirectory test

- Python/Tests/Analysis/AnalysisSaveTest.cs
#415 Doc-strings need a stable ordering
Updates the test to not care about ordering.
Leaving the issue open so we can look at making the order stable after 2.2.
> #415 Doc-strings need a stable ordering

- Python/Product/Analyzer/PyLibAnalyzer.cs
Fixes #465 Analyzer does not follow .pth files when a library path is provided
Expands path files when handling the fallback case of a library path being passed to the analyzer.
As far as regressions go this one is pretty non-fatal, though it is a break with our old behaviour. It *shouldn't* affect normal use through the IDE, but the point was to keep the old behaviour when expected.
> Fixes #465 Analyzer does not follow .pth files when a library path is provided

- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
The space was missed when I changed this earlier this week. Whoops :(
> Fixes space not being added after new argument.

- Python/Product/VSInterpreters/DerivedInterpreterFactory.cs
- Python/Tests/Core.UI/VirtualEnvTests.cs
Fixes #469 Virtual environments always refresh DB even when option is disabled
Removes unnecessary call to GenerateDatabase
Updates virtual environment test that exposed this issue
> Fixes #469 Virtual environments always refresh DB even when option is disabled

- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
Fixes #472 Execute in REPL should not create a window in QueryStatus
Removes unnecessary call to EnsureReplWindow
> Fixes #472 Execute in REPL should not create a window in QueryStatus

- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
Fixes #475 NullReferenceException disposing TaskProvider
Switches from the instance variable that is cleared by the background thread to the local where we've already captured and checked the value.
> Fixes #475 NullReferenceException disposing TaskProvider

- Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluatorProvider.cs
- Python/Tests/Core.UI/VirtualEnvTests.cs
Fixes #457 Changing project working directory does not update REPL working directory
Makes ConfigurablePythonReplOptions always reflect current project setting unless overridden.
Simplifies project resolution when creating configurable evaluators.
Improves tests.
> Fixes #457 Changing project working directory does not update REPL working directory

- Python/Product/PythonTools/PythonTools/Project/DefaultPythonLauncher.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs
Fixes #508 Open Command Prompt here doesn't set PATH correctly
Sets the string comparer for environment dictionaries.
I want this for 2.2 because it fixes a regression and is a trivial/safe fix.
> Fixes #508 Open Command Prompt here doesn't set PATH correctly

- Python/Setup/PythonToolsInstaller/Strings14.0.wxl
Fixes #482 Fix "VS 2015 required" message in installer
Updates message to recommend Community edition.
> Fixes #482 Fix "VS 2015 required" message in installer

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Tests/PythonToolsMockTests/EditorTests.cs
Fixes #504 Should not auto-commit identifiers when comma-separating on LHS
Fixes #506 Should not be auto-listing identifiers in the `for` part of a complete statement
Updates the expression scanner to only look up to the caret and not take into account the rest of the statement.
Prevents recursing into parts of statements we have already skipped. This was in some cases causing the expression on (for example) a LHS to affect completions on a RHS when there's no point even walking the LHS.
(Personally, I will probably disable this feature for my own use without these fixes. That doesn't necessarily mean it meets the bar - the fact that it's a new feature for this release is the only thing that gives it any chance at all. I believe the change is safe.)
> Auto-list identifier fixes

- Python/Product/PythonTools/pip_downloader.py
Fixes #497 pip is not installing properly
Revises pip_downloader.py to use ensurepip if available, falling back on get-pip.py and then downloading directly.
Prevents execution on Python 3.0, which has no supported version of setuptools.
Adds separate links for Python 3.1 and a urlretrieve() implementation that correctly handles fwlinks.
Adds script restart if we are running on IronPython without -X:Frames
> #497 pip is not installing properly

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #454 NullReferenceException in CreateOrAddVirtualEnvironment
Improves (adds) null handling for the _interpreters variable, which is set to null when disposing.
> Fixes #454 NullReferenceException in CreateOrAddVirtualEnvironment

- Common/Setup/LaunchConditions.wxs
- Python/Setup/PythonToolsInstaller/Strings10.0.wxl
- Python/Setup/PythonToolsInstaller/Strings11.0.wxl
- Python/Setup/PythonToolsInstaller/Strings12.0.wxl
- Python/Setup/PythonToolsInstaller/Strings14.0.wxl
Fixes #517 Prevent installation on prerelease versions of VS
Fixes version check to avoid ordering issue.
Improves message.
There'll be one more update to this after the final VS build, but this way we can test the logic against older builds and the later change will be safer.
> Fixes #517 Prevent installation on prerelease versions of VS

- Python/Product/EnvironmentsList/EnvironmentsList.csproj
- Python/Product/EnvironmentsList/IEnvironmentViewExtensionProvider.cs
- Python/Product/PythonTools/Dev14OrLater/source.extension.vsixmanifest
- Python/Product/PythonTools/Properties/AssemblyInfo.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Project/ProjectResources.cs
- Python/Product/PythonTools/Resources.resx
Adds extensibility point to allow other VS extensions to provide panes in the environments list.
This may be used to provide conda or other package-related extensions independently of PTVS, simply by exposing a MEF component for `IEnvironmentViewExtensionProvider`.
> Environments window extensibility

- Python/Product/Analysis/Interpreter/IPythonInterpreterFactoryWithDatabase.cs
- Python/Product/PythonTools/Dev14OrLater/source.extension.vsixmanifest
- Python/Product/PythonTools/PythonTools/Navigation/PythonLanguageInfo.cs
Fixes API comment.
Fixes vsixmanifest.
Removes unnecessary reference to IComponentModel.
The last one has been triggering the MEF dialog on open. It'll be triggered by something eventually, but better that it isn't us, especially since we're loading on startup.
> Some minor fixes

- Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
- Python/Product/AnalysisMemoryTester/AnalysisMemoryTester.csproj
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/BaseAnalysisTest.cs
Fixes #542 Microsoft ptvs and db completion doesn't work for python 3
Skips invoking decorators that are defined by outer functions.
Also improves AnalysisMemoryTester build.
> Fixes #542 Microsoft ptvs and db completion doesn't work for python 3.4 64 bit

- Python/Product/Analysis/AnalysisDictionary.cs
- Python/Product/Analysis/Values/ModuleInfo.cs
Fixes #562 IndexOutOfRangeException in AnalysisDictionary
Avoids mutating the module members dictionary from the UI thread.
Adds a debug assertion to identify this case sooner (shortly before crashing...).
> Fixes #562 IndexOutOfRangeException in AnalysisDictionary

- Python/Product/Debugger/Debugger/DebugEngine/AD7BoundBreakpoint.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
Fixes #561 Hang stopping debugging
Adds a timeout for getting breakpoint hit counts so that we don't freeze the UI for too long when stopping debugging.
Also adds a TODO for the post-2.2 fix.
> Fixes #561 Hang stopping debugging

- Python/Product/PythonTools/visualstudio_ipython_repl.py
Fixes #577 IPython doc strings, question mark does not work
Handles the case where a response through the system channel contains data rather than simple text.
This only occurs on IPython 3.0 and later.
> Fixes #577 IPython doc strings, question mark does not work

- Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs
- Python/Tests/ReplWindowUITests/ReplWindowPythonSmokeTests.cs
Fixes #584 User prompts do not override IPython prompts
Ensures prompt variables are initialized whenever a new command thread is created.
> Fixes #584 User prompts do not override IPython prompts

- Common/Product/ReplWindow/Repl/OutputBuffer.cs
- Common/Tests/Utilities.UI/UI/ReplWindowProxy.cs
- Common/Tests/Utilities/Mocks/MockReplWindow.cs
- Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs
- Python/Tests/ReplWindowUITests/ReplWindowPythonSmokeTests.cs
Fixes #616 Visual Studio runs out of memory
Moves "escape" update outside of condition to ensure we always advance even when colour codes are invalid.
Adds test for printing all characters.
> Fixes #616 Visual Studio runs out of memory

- Common/Tests/Utilities/Mocks/MockSettingsStore.cs
- Python/Product/VSInterpreters/InterpreterOptionsService.cs
- Python/Tests/Core/EnvironmentListTests.cs
- Python/Tests/Utilities.Python.Analysis/MockPythonInterpreterFactoryProvider.cs
Fixes #300 Race condition refreshing environments
Adds enumerable implementation for getting the list of interpreters from the service. This enumerable will suppress change events during enumeration and try harder to get a coherent list of factories from the providers.
Adds a race-condition test to flush out threading issues.
Hardens mock classes to avoid causing false positives in the race-condition test. The actual VS classes are either thread-safe or marshal back to the UI thread, but there's no value in forcing that here.
> Fixes #300 Race condition refreshing environments

- Python/Product/Debugger/Debugger/DebugEngine/AD7MemoryAddress.cs
- Python/Tests/DebuggerUITests/DebugProject.cs
Always return some non-null, non-empty function name for IDebugCodeContext2, to enable debugger to correctly detect and clean up duplicate breakpoints (which it creates itself when "When Hit" action changes).
> Fix #604: Breakpoint gets a new child bound breakpoint every time its When Hit action changes

- Python/Product/PyKinect/PyKinect/pykinect/nui/structs.py
Correction of the bug #676: "Error getting the 'height' property of PlanarImage"
Removed the '.value' property from line 213.
> Correction of bug #676 - incorrect '.value'

- Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs
- Python/Product/Analysis/Parsing/Ast/NameExpression.cs
- Python/Product/Analysis/PythonAnalyzer.Specializations.cs
- Python/Product/Django/Project/DjangoAnalyzer.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #685 NullReferenceException in DjangoAnalyzer.GetArg
Adds assertion and safe fallbacks if null arguments appear in incorrect places in calls.
Adds test for null named arguments.
> Fixes #685 NullReferenceException in DjangoAnalyzer.GetArg

- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
Disable command when filename is null or empty.
> Fix #680: ExecuteInReplCommand does not validate filename

- Python/Product/PythonTools/PythonToolsPackage.cs
Add null checks for SComponentModel and IInterpreterOptionsService (most likely it was the former).
> Tentatively fix #687: NullReferenceException in GetReplCommands caused by registry change

- Python/Product/Debugger/DkmDebugger/TraceManagerLocalHelper.cs
- Python/Product/DebuggerHelper/dllmain.cpp
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
Add a flag that test launcher now uses to detect when the debugger is actually tracing execution (and not just attached to the process).
> Fix #705: Debugging unit tests in mixed mode skips breakpoints occasionally

- Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs
- Python/Product/Analysis/Parsing/PythonLanguageVersion.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
- Python/Tests/VSInterpretersTests/VSInterpretersTests.cs
Fixes #706: Should not detect unsupported interpreters
Adds validation through PythonLanguageVersion when constructing.
Ensures callers handle or correctly propagate the new ArgumentException.
Makes "0.0" a supported version (implies PythonLanguageVersion.None)
Adds test
Removes invalid test
I will backport this to 2.1.1 and 2.2.1 after it's merged.
> Fixes #706: Should not detect unsupported interpreters

- Common/Product/SharedProject/VsTaskExtensions.cs
- Python/Product/Analysis/Interpreter/SharedDatabaseState.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisQueue.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs
Fixes #682 Race condition in AddObjectTypeFixup
Adds double-checked locking (or equivalent) to fixups lists and object instance.
Improves error handling when an 'object' type cannot be found
Please review the changes to SharedDatabaseState.cs carefully - they took a lot of thought and *should* cover all the potential races for the three variables now.
> Fixes #682 Race condition in AddObjectTypeFixup

- Python/Product/Analysis/Parsing/Parser.cs
Fixes #712: Don't add Unicode BOM by default
Changes default encoding to be UTF-8 without a signature.
> Fixes #712: Don't add Unicode BOM by default

- Common/Product/SharedProject/ProjectResources.resx
- Common/Product/SharedProject/VsTaskExtensions.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml.cs
- Python/Setup/PythonToolsInstaller/PythonToolsInstaller.wxs
Fixes #669 Log all unhandled exceptions to Event Log
Creates an event source and writes errors to it.
Also handles errors better in code paths that I happened to be trying to test.
> Fixes #669 Log all unhandled exceptions to Event Log

- Python/Product/Profiling/vspyprof.py
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/VsPyProf.cpp
- Python/Product/VsPyProf/python.h
- Python/Tests/ProfilingUITests/ProfilingTests.cs
Fixes #725 PTVS 2.2 RTM can't profile Python 3.5.0rc1
Changes version check to allow profiling 3.5
Improves handling when unable to profile
Adds basic profiling tests for more Python versions
> Fixes #725 PTVS 2.2 RTM can't profile Python 3.5.0rc1

- Python/Product/PythonTools/PythonTools/Options/PythonDebugInteractiveOptionsPage.cs
- Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs
#678 NullReferenceException in SaveSettingsToStorage
Skips trying to update debug interactive prompts, since they don't work anyway.
Fixes extension methods to test the cast before using the object.
Filed #765 for a full fix in 3.0
> #678 NullReferenceException in SaveSettingsToStorage

- Python/Product/PythonTools/PythonTools.vsct
- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
Fixes #664 Excute File in Python Interactive -- wrong location and always appears
Moves command to near the bottom of the "execute" group.
Fixes logic to determine when command should be visible.
(Ping @Andrew-MSFT)
> Fixes #664 Excute File in Python Interactive -- wrong location and always appears

- Python/Product/Analysis/MemberResult.cs
- Python/Product/Analysis/ModuleAnalysis.cs
_vars was being set to null in at least on spot (ModuleAnalysis 455).
Now it is set as an empty list in cases where it could come as null.
> Fixes #688 by Handling null _vars

- Build/Common.Build.settings
Ensures dependencies are always built into the correct output directory.
> Ensures dependencies are always built into the correct output directory.

- Python/Product/BuildTasks/ConvertPathToModuleName.cs
- Python/Product/BuildTasks/Microsoft.PythonTools.targets
Fixes #784 Cannot have invalid module as startup file
Allows creation of $(StartupModule) to fail silently and set an empty string.
> Fixes #784 Cannot have invalid module as startup file

- Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Fixes #831 Unhandled exception in PythonNavigateToItemProvider
Prevents TaskCanceledException being raised while stepping through the task.
> Fixes #831: Unhandled exception in PythonNavigateToItemProvider

- Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs
Fixes #810 Referencing several Python extension modules does not work
Compares last modified time against the file referenced by the row, rather than the newly added extension.
> Fixes #810 Referencing several Python extension modules does not work

- Python/Product/Analysis/Values/BuiltinClassInfo.cs
- Python/Product/IronPython/Interpreter/IronPythonBuiltinFunction.cs
- Python/Product/IronPython/Interpreter/IronPythonBuiltinFunctionTarget.cs
- Python/Product/IronPython/Interpreter/IronPythonBuiltinMethodDescriptor.cs
- Python/Product/IronPython/Interpreter/IronPythonConstant.cs
- Python/Product/IronPython/Interpreter/IronPythonConstructorFunction.cs
- Python/Product/IronPython/Interpreter/IronPythonConstructorFunctionTarget.cs
- Python/Product/IronPython/Interpreter/IronPythonEvent.cs
- Python/Product/IronPython/Interpreter/IronPythonExtensionProperty.cs
- Python/Product/IronPython/Interpreter/IronPythonField.cs
- Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
- Python/Product/IronPython/Interpreter/IronPythonModule.cs
- Python/Product/IronPython/Interpreter/IronPythonNamespace.cs
- Python/Product/IronPython/Interpreter/IronPythonParameterInfo.cs
- Python/Product/IronPython/Interpreter/IronPythonProperty.cs
- Python/Product/IronPython/Interpreter/IronPythonType.cs
- Python/Product/IronPython/Interpreter/IronPythonTypeGroup.cs
- Python/Product/IronPython/Interpreter/PythonObject.cs
- Python/Product/IronPython/Interpreter/RemoteInterpreterProxy.cs
Fixes #802 VS crash with IronPython
Captures the remote interpreter proxy along with the object handle, and stops trying to call into the remote interpreter when we know it's been disposed.
> Fixes #802 VS crash with IronPython

- Common/Setup/LaunchConditions.wxs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluator.cs
- Python/products.settings
Looks like there's enough info available to build without having to lock to VSU1, so trying a build with RTM and running against the update.
> Removes strict VSU1 build/runtime requirement.

- Python/Product/Debugger/DkmDebugger/PyObjectNativeVisualizer.cs
Fixes #876 Viewing a watch of a PyUnicode with a 2.7 interpreter crashes MSVS
Ensures [Python View] node is not added for regular native debugging in VS 2013.
> Fixes #876 Viewing a watch of a PyUnicode with a 2.7 interpreter crashes MSVS

- Python/Product/Uwp/Project/PythonUwpProjectConfig.cs
- Python/Product/Uwp/Templates/Projects/BackgroundService/PythonBackgroundService.pyproj
- Update PTVS version number and directory location
- Fixed an issue where the VS cannot attach the python debugger due to a malformated tcp string.
@zooba - For bug fixes in update 1?  Do I commit them in Master or v2.2.1 branch?  The first commit (Update PTVS version number and directory location) probably doesn't need to go into the v2.2.1 branch.
> Fixing bug in PTVS for UWP python scenarios

- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
Fixes #957 Debug REPL commands don't show up in help
Adds role and content type to process evaluators so that correct commands are loaded.
> Fixes #957 Debug REPL commands don't show up in help

- Python/Product/PythonTools/PythonTools/Repl/DebugReplFrameDownCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplFrameUpCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplFramesCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplGoCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplStepIntoCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplStepOutCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/DebugReplStepOverCommand.cs
Fixes #960 REPL command aliases do not work
Adds aliases to list of names returned by Names.
> Fixes #960 REPL command aliases do not work

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #962 Django shell REPL input 2 characters for every character
Prevents an exception due to null buffer parser.
> Fixes #962 Django shell REPL input 2 characters for every character

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #965 Pasting into django shell causes activity log error
Adds early-exit after assertion to avoid runtime exceptions.
> Fixes #965 Pasting into django shell causes activity log error

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #967 Open command prompt here confused about selection
Removes unnecessary path from PATH when overriding the factory.
Prevents extra exception when interpreter path has been overridden and environment is invalid.
> Fixes #967 Open command prompt here confused about selection

- Python/Product/PythonTools/visualstudio_ipython_repl.py
Fixes #976 IPython REPL will not start
Adds missing str->bytes conversion for Python 3.x.
> Fixes #976 IPython REPL will not start

- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
This fixes issue when trying to run unit tests on 64bit python in visual studio 2015.
https://docs.python.org/2/library/ctypes.html states that WinError is a wrapper that raises WindowsError which is the builtin python exception that is trying to be trapped.
I have opened a bug #1032, which this pull request should fix.
> Should be WindowsError not WinError

- Python/Product/WFastCgi/wfastcgi.py
Django depends on SCRIPT_NAME and PATH_INFO adhering to PEP333 (http://www.python.org/dev/peps/pep-0333/)
See issue: #1029
> Fixing SCRIPT_NAME and PATH_INFO for non-root applications

- .hgeol
- Build/BuildReleaseHelpers.psm1
- Build/BuildReleaseMockHelpers.psm1
- Python/Setup/BuildRelease.ps1
Fixes signing certificates.
Disables default VS 2013 build.
Prevents hg users from changing line endings
> Build process fixes

- Python/Product/Attacher/PyAttacher.cs
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/PyDebugAttach/dllmain.cpp
Fixes #1064 Debug-Attach to Python 3.5
Enables attaching to Python 3.5
Uses new _PyThreadState_UncheckedGet function in place of _PyThreadState_Current data when available.
> Fixes #1064 Debug-Attach to Python 3.5

- Python/Product/VSInterpreters/DerivedInterpreterFactory.cs
Fixes #1097 Cannot add existing virtualenv when home has no trailing backslash
Ensures backslashes are trimmed from paths before comparing.
> Fixes #1097 Cannot add existing virtualenv when home has no trailing backslash

- Python/Product/dirs.proj
- Python/Setup/PythonToolsInstaller/PythonToolsInstaller.wixproj
- Python/Setup/PythonToolsInstaller/PythonToolsInstaller.wxs
- Python/Setup/setup.proj
- Python/Tests/dirs.proj
- Python/products.settings
Temporarily work around #1110 Can't create or load IronPython project
Exclude IronPython support from builds.
Fixes inconsistencies with other exclusions.
> Temporarily work around #1110 Can't create or load IronPython project

- Python/Product/Common/Infrastructure/PythonToolsInstallPath.cs
- Python/Product/Profiling/Profiling/ProfiledProcess.cs
Fixes #1161 Cannot find Python install dir when profiling
Allows callers to PythonToolsInstallPath.GetFile to override the assembly used for locating files.
> Fixes #1161 Cannot find Python install dir when profiling

- Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs
- Python/Product/PythonTools/PythonTools/Commands/DiagnosticsCommand.cs
Fixes #1166 Crash opening diagnostic info
Improves exception handling when generating diagnostic info
Also improves output when some errors occur getting logs.
> Fixes #1166 Crash opening diagnostic info

- Python/Product/Analysis/ModuleTable.cs
- Python/Tests/Analysis/AnalysisTests.csproj
- Python/Tests/Analysis/ModuleTableTests.cs
- Python/Tests/Utilities.Python.Analysis/MockPythonInterpreter.cs
Fixes #590 NullReferenceException reinitializing modules
Fixes handling where ReInit() encounters a module that is listed in module names but cannot be imported.
Adds test.
> Fixes #590 NullReferenceException reinitializing modules

- Python/Product/PyDebugAttach/PyDebugAttach.cpp
> Fix #1236: Crash in PyDebugAttach.dll when attaching to Blender

- Build/Common.Build.VSSDK.targets
- Build/MicroBuild.props
- Build/MicroBuild.targets
Fixes #1247 unable to load solution using vs2015
Makes imports optional. The code to automatically install dependencies already exists and works correctly from within VS.
> Fixes #1247 unable to load solution using vs2015

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs
Fixes #1268 Crash in ReverseExpressionParser
Handles * and ** appearing first on a line.
Also fixes a potential null reference when monitoring a new buffer.
> Fixes #1268 Crash in ReverseExpressionParser

- Python/Product/IronPython/IpyToolsPackage.cs
Previously we were implicitly generating this GUID, which means it's hard to find out what it is from looking at source.
This does not change the GUID from our previous release - it just puts it into source.
> Explicitly sets IpyToolsPackage GUID so that the value is visible within sources

- Python/Product/EnvironmentsList/FileNameLabel.xaml
Fixes #1258 Gap in environments list for short filenames
Adds column definition style to switch the minimum width based on the filename body.
> Fixes #1258 Gap in environments list for short filenames

- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Fixes #1272 Ctrl+C, Ctrl+V on empty line pastes in the middle of the line
Check whether we are pasting a complete line with no selection, and if so move to the start of the line before pasting.
> Fixes #1272 Ctrl+C, Ctrl+V on empty line pastes in the middle of the line

- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonFileLibraryNode.cs
Fix #1275 - we just need to null out of the buffer parser when we stop monitoring
Also improves some error handling w/ the out of proc analyzer, and improves the experience when opening a file with the Python editor that aren't .py files.
> Fix #1275 and improve editing files w/ odd extensions

- Python/Product/PythonTools/source.extension.vsixmanifest
Fixes #1285 BreaksExistingExtensionException when attempting to install new Roslyn vsix on Dev 15 Preview
Changes version specifier for interactive components.
> Fixes #1285 BreaksExistingExtensionException

- Python/Product/PythonTools/PythonTools/Project/PythonFileNode.cs
Fixes #1297 File Cut/Past null reference exception with data loss
Allows analysis to be null when renaming a file.
> Fixes #1297 File Cut/Past null reference exception with data loss

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes command prompt not including global environment variables.
(Most critically, it blanks out `PATH`, which breaks many commands.)
> Fixes command prompt not including global environment variables.

- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Fixes #1269 Removing calls to GetZipFileName, and GetPathInZipFile. They were called but the return value was never used.
> Fixes #1269 Removing calls to GetZipFileName, and GetPathInZipFile. 

- Python/Product/Analysis/Interpreter/IInterpreterRegistryService.cs
- Python/Product/Analysis/Interpreter/IPythonInterpreterFactoryProvider.cs
- Python/Product/Analysis/Interpreter/InterpreterRegistryService.cs
- Python/Product/CanopyInterpreter/CanopyInterpreterFactoryProvider.cs
- Python/Product/IronPython/Interpreter/IronPythonInterpreterFactoryProvider.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/Uwp.Interpreter/PythonUwpInterpreterFactoryProvider.cs
- Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
- Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs
- Python/Tests/Core/ReplEvaluatorTests.cs
- Python/Tests/Utilities.Python.Analysis/MockInterpreterOptionsService.cs
- Python/Tests/Utilities.Python.Analysis/MockPythonInterpreterFactoryProvider.cs
Fixes #1251 No completions in virtual env REPL
Enables getting the project associated with an interpreter ID so that we can flow settings through to the interactive window.
Also fixes a potential crash on VS shutdown.
> Fixes #1251 No completions in virtual env REPL

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNodeProperties.cs
Added a set method on the PythonProjectNodeProperties.CommandLineArguments to allow extensions to modify this property.
I wanted to add support to Python Projects for https://github.com/MBulli/SmartCommandlineArgs/issues/9.
However, I couldn't find an easy way to modify the CommandLineArguments property without messing with your internal objects.
I don't know if there was a good reason not to put the `set` method, but I figured it might just be because there was no need before.
Closes #1078 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/ptvs/1335)
> Allow to modify PythonProjectNodeProperties.CommandLineArguments

- Python/Product/Uwp/PythonUwpPackage.cs
- Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs
Fixes #1355 UWP package cannot find Microsoft.PythonTools.dll
Stop autoloading the UWP package to avoid loading it before the PythonTools package.
Also fix some null references that were preventing Python projects opening early in startup.
> Fixes #1355 UWP package cannot find Microsoft.PythonTools.dll

- Python/Product/PythonTools/visualstudio_py_repl.py
Fixes #1365 _ReplOutput has no attribute 'closed'
Adds closed attribute.
Also makes encoding property into a class attribute.
> Fixes #1365 _ReplOutput has no attribute 'closed'

- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
Fixes #1363 Crash reformatting code
The only way to get a null reference error in that function is when the fromVersion is not in the chain. To prevent it, we'll stop at the earlier available version.
> Fixes #1363 Crash reformatting code

- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
- Python/Product/PythonTools/PythonTools/Navigation/DropDownBarClient.cs
- Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs
- Python/Tests/Core/EditorTests.cs
- Python/Tests/ReplWindowUITests/SendToReplTests.cs
- Python/Tests/TestData/SendToInteractive/Cells.py
- Python/Tests/TestData/SendToInteractive/SendToInteractive.pyproj
- Python/Tests/Utilities.Python/PythonVisualStudioApp.cs
Fixes #88 Support code cells
Adds support for marking code cells with "#%%", including collapsing them and sending the entire cell to the REPL when pressing Ctrl+Enter on the cell header.
Also fixes some threading issues.
See #88 for a screenshot of how it looks.
> Fixes #88 Support code cells

- Python/Product/Analysis/Parsing/Ast/FunctionDefinition.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analyzer/Intellisense/ClassifierWalker.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
Fixes #1249 Highlighting for async is wrong when a decorator is used
Preserves the original start index of a function so it can be used even if a decorator later changes it.
> Fixes #1249 Highlighting for async is wrong when a decorator is used

- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/StringLiteralCompletionList.cs
- Python/Tests/Core/EditorTests.cs
Fixes #1473 Directory/File IntelliSense on multi level folder
Updates string literal completions to only operate on string contents
Specialized completion triggering for filenames.
> Fixes #1473 Directory/File IntelliSense on multi level folder

- Python/Product/Uwp.Interpreter/PythonUwpInterpreterFactoryProvider.cs
FYI @alanch-ms - the call is what triggers the FileNotFoundException (when loading the types required to JIT the function body), so it needed to be one level deeper.
> Fixes analysis crash due to UWP factory provider.

- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/PythonTools/PythonTools/Editor/LanguagePreferences.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Navigation/CodeWindowManager.cs
- Python/Product/PythonTools/PythonTools/Options/GlobalInterpreterOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonInteractiveOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonToolsOptionsService.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
- Python/Product/PythonTools/PythonToolsService.cs
Ensures text manager is not loaded before the shell is initialized. (This helps prevent the Tab setting from being incorrect)
Switches to correct parsing of Unicode identifiers.
> Ensures text manager is not loaded before the shell is initialized.

- Python/Setup/signlayout.proj
FYI @alanch-ms - I missed it as well, so hopefully next time we add a new assembly we'll remember between us.
> Adds missing Microsoft.PythonTools.Uwp.Wizards.dll to signing script

- Python/Product/PythonTools/visualstudio_py_repl.py
Fixes #1070 Cannot debug script that uses colorama
Adds closed attribute to repl output.
This has been in 3.0 for a while, but wasn't backported.
> Fixes #1070 Cannot debug script that uses colorama

- Python/Product/WFastCgi/wfastcgi.py
When the wfastcgi.py file is in a folder with spaces (default for Python 3.5), `enable` and `disable` don't properly quote the filename, so it gets passed to python.exe unquoted (and only "C:\Program" counts as the filename.
> Allow IIS working with Python 3.5

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #1574: Add enter at end of fully typed word is ignored
Use applicable span rather than trigger point to determine if full word has been entered.
> Fixes #1574: Add enter at end of fully typed word is ignored

- Python/Product/Common/Infrastructure/StringExtensions.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Project/VsPackageManagerUI.cs
Fixes #1572 pip install shows double spacing within output
Moves TrimEndNewline into StringExtensions
Trims newline in PipExtensionProvider.
Removes output for operation started event.
> Fixes #1572 pip install shows double spacing within output

- Python/Product/VSInterpreters/PythonRegistrySearch.cs
Fixes #1576 PythonCore default description does not match 3.6 description
Updates default description format.
> Fixes #1576 PythonCore default description does not match 3.6 description

- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
https://github.com/Microsoft/PTVS/issues/1608
Fixes copying of files after generating them in temp folder. I forgot that the default value for recursion on PathUtils.EnumerateFiles is true.
Without this fix, the root of the output folder contains all the files from all the subfolders.
> Fix 1608 Cookiecutter post-gen file copy creates duplicate files

- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/View/CookiecutterControl.xaml.cs
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml.cs
Don't prepopulate the output folder, as to not mislead the user into generating templates in their documents folder.
We'll need to decide on a better policy later on.  I suspect that if cookiecutter is invoked from Add -> From Cookiecutter on an existing project/folder, we'll want to prepopulate it with that folder path.
Hide the process window that detects git that was showing up on dev14.
> Fix 1612 - cookiecutter should make it more obvious when it doesn't create a subdirectory

- Python/Product/Analyzer/PyLibAnalyzer.cs
- Python/Product/Ipc.Json/Connection.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Improves logging when analyzer process does not start.
Ensures messages are not missed because of races between process exit and event hookup.
Ensures messages are sent to stderr and so not misinterpreted as packages.
Ensures messages on stdout are not misinterpreted as a series of invalid headers.
> Improves logging when analyzer process does not start.

- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Model/ProcessOutputResult.cs
- Python/Product/Cookiecutter/Shared/Infrastructure/NativeMethods.cs
- Python/Product/Cookiecutter/Shared/Infrastructure/PathUtils.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Resolve symbolic link in the git folder path.
In case of a process error, always print out the executable and exit code.
Check strictly for exit code 0 for our python scripts. Cookiecutter will return positive value for error. We now have much better error reporting for iknite/cookiecutter-ansible-role template which fails during post hook, and other templates now report errors when they were ignored before.
> Fix 1620: cookiecutter templates failing to clone

- Python/Product/Cookiecutter/Commands/GitHubHomeCommand.cs
- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/View/CookiecutterControl.xaml.cs
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml.cs
Fixes https://github.com/Microsoft/PTVS/issues/1619
More importantly, the selection is now correctly updated to match the selection. Before, if you selected a template, did a search, didn't select a template, you'd still be able to click Next (or other toolbar buttons). It would use whatever you had selected before the search.
> Fix 1619 - github buttons are always active in cookiecutter window

- Python/Product/Analysis/Parsing/Ast/ForStatement.cs
- Python/Product/Analysis/Parsing/Ast/WithStatement.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Tests/Analysis/ParserRoundTripTest.cs
- Python/Tests/Core.UI/FormattingUITests.cs
- Python/Tests/TestData/FormattingTests/FormattingTests.pyproj
- Python/Tests/TestData/FormattingTests/async.py
Fixes #1601: async for/with not formatted correctly
Enables round-tripping of async for/with statements
Adds tests
> Fixes #1601: async for/with not formatted correctly

- Python/Product/Django.Analysis/DjangoAnalyzer.cs
Hi,
Just adding a tiny condition, avoiding _url()_ calls without _name_ in the keyword arguments to be displayed during completion of a url django template block.
Cheers,
David
> Django urls intellisense - mini fix

- Python/Templates/SharedFiles/ConfigureCloudService.ps1
When this script runs multiple times, it throws error as below.
> ERROR ( message:New application object missing required attributes. Cannot add duplicate collection entry of type 'application' with combined key attributes 'fullPath, arguments' respectively set to 'D:\\Python27\\\\python.exe, "F:\\sitesroot\\0\\bin\\wfastcgi.py"'. )
So, I added a line to remove previous config by following similar solution; http://stackoverflow.com/a/35506641/361100
It tested in Azure Web Role + Flask project.
> fix "Cannot add duplicate collection entry" error

- Python/Product/Core/Core.csproj
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/python.h
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/ProfilingUITests/ProfilingTests.cs
Fixes #1648 Fix debug-attach and profiling for Python 3.6
Also enables profiling and debug tests for 3.6.
> Fixes #1648 Fix debug-attach and profiling for Python 3.6

- Python/Product/Cookiecutter/CookiecutterFeed.txt
- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
- Python/Product/Cookiecutter/Model/CookiecutterClientProvider.cs
- Python/Product/Cookiecutter/Model/ICookiecutterClient.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/UrlConstants.cs
- Python/Product/Cookiecutter/View/CookiecutterControl.xaml.cs
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/View/MissingDependencies.xaml
- Python/Product/Cookiecutter/View/MissingDependencies.xaml.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterClientTests.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
- Python/Tests/CookiecutterTests/MockCookiecutterClient.cs
Our only external requirement is Python 3.3 or later.
Don't bother notifying for missing git, we know it's installed. In rare error case (like dev14), message in output window will be sufficient.
Virtual environment + cookiecutter package go in  %localappdata%/Microsoft/CookiecutterTools/env
Please check the strings/messages in missing dependencies xaml, and in strings.resx, I'm open to more detailed or better strings.
I've updated the feed so we don't recommend third party templates we haven't really tested.
> Install cookiecutter on demand

- Python/Product/Profiling/Profiling/ProfiledProcess.cs
Fixes search for profiler tools and improves the error message when they aren't found.
We still need to properly handle the case where it is not found - the call logic is crazy and handling the exception in the right place for all entry points is not trivial.
> Profiler issues

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs
- Python/Product/Analysis/get_search_paths.py
- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Tests/Analysis/AnalyzerTests.cs
Fixes #1585 All .pyd files are listed in Intellisense view for venvs
Correctly marks paths that are used for DB generation as stdlib.
> Fixes #1585 All .pyd files are listed in Intellisense view for venvs

- Common/Tools/BuildTasks/BuildTasks.csproj
The imported `Common.Build.settings` file sets it to 4.6, and this project was overwriting it with 4.5.
This was the reason I was getting these build errors:
`MSB3030: Could not copy file "C:\program Files (x86)\Reference Assemblies\Microsoft\.NETFramework\v4.5\norm*.nlp" because it was not found `
I was getting them only on Dev 15 Preview 5, but starting today I am also seeing the error on Dev 14 Update 3.
> Use default framework version for BuildTasks project.

- Python/Product/TestAdapter.Executor/TestExecutor.cs
Fixes #1748: Debug unit test confused about which debugger to use
Uses correct boolean when parsing boolean values.
> Fixes #1748: Debug unit test confused about which debugger to use

- Common/Tests/Utilities.UI/UI/ReplWindowProxy.cs
- Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Tests/Utilities.Python/PythonReplWindowProxySettings.cs
Fixes #1751 Smart indent does not work in REPL
Removes old compatibility code
Removes duplicate REPLs opening during tests and tries harder to close the one we just finished using.
> Fixes #1751 Smart indent does not work in REPL

- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestAdapterTests/TestInfo.cs
- Python/Tests/TestData/TestAdapterLibraryOar/TestAdapterLibraryOar.pyproj
- Python/Tests/TestData/TestAdapterTestB/TestAdapterTestB.pyproj
- Python/Tests/TestData/TestAdapterTests/LoadErrorTest.pyproj
- Python/Tests/TestData/TestAdapterTests/LoadErrorTestImportError.py
- Python/Tests/TestData/TestAdapterTests/LoadErrorTestNoError.py
Fixes https://github.com/Microsoft/PTVS/issues/1727
It fixes some of the existing test adapter tests (unrelated to 1727).  Inheritance related tests are still failing, so I've moved them to a separate test so that the main tests `Run` and `RunAll` now pass.
> Fix 1727 test not executing

- Build/Common.Build.CSharp.targets
- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/Resources/Images.imagemanifest
Fixes #1759 No cookiecutter icons on VS 15
Had to move the location of the imagemanifest on deployment and insert the full assembly name.
> Fixes #1759 No cookiecutter icons on VS 15

- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestAdapterTests/TestInfo.cs
- Python/Tests/TestData/TestAdapterTests/LoadErrorTest27.pyproj
- Python/Tests/TestData/TestAdapterTests/LoadErrorTest34.pyproj
- Python/Tests/TestData/TestAdapterTests/LoadErrorTest35.pyproj
Fixes https://github.com/Microsoft/PTVS/issues/1727 for Python 3.5
Implementation of unittest changed for 3.5, they now handle import errors and create fake test cases for them.  Problem is that the implementation of id() on the fake test cases doesn't match the id that VS has for the test.
> Fix test launcher handling of import errors on Python 3.5

- Common/Product/SharedProject/UIThread.cs
- Common/Tests/MockVsTests/MockVs.cs
- Common/Tests/MockVsTests/MockVsServiceProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
- Python/Tests/Core/CPythonInterpreterTests.cs
- Python/Tests/PythonToolsMockTests/EditorTests.cs
- Python/Tests/PythonToolsMockTests/MockPythonToolsPackage.cs
Fixes #1795 New 'enter' in comment feature indents incorrectly
Fixes indentation
Fixes issues with mock test infrastructure
Prevents deadlock on exit due to error task providers (attempt #3)
> Fixes #1795 New 'enter' in comment feature indents incorrectly

- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Model/GitClientProvider.cs
- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
Use the VS running instance location in order to locate git.exe, instead of using registry.
That's not always possible (tests, dev 14), so we still fallback to registry and global git.exe.
Don't merge yet, I still need to test on Dev 15.
> Cookiecutter git.exe location

- Python/Product/Common/Infrastructure/EnumerableExtensions.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Product/Debugger/DkmDebugger/CallStackFilter.cs
- Python/Product/Debugger/DkmDebugger/LocalComponent.cs
- Python/Product/Debugger/DkmDebugger/Proxies/DataProxy.cs
- Python/Product/Debugger/DkmDebugger/Proxies/StructProxy.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyByteArrayObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyBytesObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyDictObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyDictObject27.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyDictObject33.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyDictObject36.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyFrameObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyInterpreterState.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyListObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PySetObject.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyTupleObject.cs
- Python/Product/Debugger/DkmDebugger/PythonRuntimeInfo.cs
- Python/Product/Debugger/DkmDebugger/SourceLocation.cs
- Python/Product/Debugger/DkmDebugger/TraceManagerLocalHelper.cs
- Python/Product/Debugger/VsPackageMessage.cs
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PythonTools/PythonTools/Debugger/CustomDebuggerEventHandler.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #1634 Fix mixed-mode debugging for 3.6
Enables MMD for 3.6 via eval_frame hook
Fixes PyDictObject implementation
Removes PGO block to evaluate whether it is still necessary
I want to leave the PGO checks commented out for now, in case we have to bring them back before final release. In my testing, I encountered no problems with Python 3.6 x64, which was compiled with PGO, so either the PDBs are now more valid or the code that was relying on valid FuncDebugEnd values is totally gone (I definitely removed some in the past).
I ran this change through the internal VS test infrastructure for debuggers and it passed 100%.
> Fixes #1634 Fix mixed-mode debugging for 3.6

- Python/Product/VSInterpreters/PipPackageCache.cs
- Python/Product/VSInterpreters/PipPackageManager.cs
Prevent UI delay caused by not returning to UI thread after downloading package data
Switch to using a fwlink as the base URL for PyPI
> Prevent UI delay caused by not returning to UI thread after downloading package data

- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml.cs
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
These operations navigate to the search page, clear the search term and refreshes the search results.
- Click Home on toolbar
- Click Cancel on options page
- Successful file creation
Fixes https://github.com/Microsoft/PTVS/issues/1817
> Reset search when navigating to home page

- Python/Product/VSInterpreters/PipPackageCache.cs
Fixes #1834 Environment package window oddity
Needed to change the regex to handle slightly different /simple format on pypi.org vs. pypi.python.org.
> Fixes #1834 Environment package window oddity

- Python/Product/TestAdapter/PythonRunSettings.cs
- Python/Product/TestAdapter/TestAdapter.csproj
- Python/products.settings
Fixes #1836 Isolate code coverage
Removes direct dependency on code coverage assembly
Removes IncludeCodeCoverage property
> Fixes #1836 Isolate code coverage

- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Fixes #1831 Cookiecutter output when checking for updates
Disables update messages unless an error occurs (or we are in a debug build)
Removes unnecessary newlines from output messages.
> Fixes #1831 Cookiecutter output when checking for updates

- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
Fixes #1850 Use pip's JSON format for list
Uses JSON format by default, falling back on the regex if passing the JSON option fails.
> Fixes #1850 Use pip's JSON format for list

- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Fix #1849 Cookiecutter check for updates progress bar should be determinate
Fix #1832 Cookiecutter check for update doesn't properly detect errors
Here's an example of the output window when I pull the cord in the middle of a check for updates.
RELEASE
```
----- Checking for update to template 'cookiecutter-flask' from 'https://github.com/sloria/cookiecutter-flask' -----
git.exe returned an exit code of 128.
fatal: unable to access 'https://github.com/sloria/cookiecutter-flask/': Unknown SSL protocol error in connection to github.com:443 
Error checking for an update.
----- Checking for update to template 'cookiecutter-ptvs-bottle' from 'https://github.com/huguesv/cookiecutter-ptvs-bottle' -----
git.exe returned an exit code of 128.
fatal: unable to access …
```
> Cookiecutter template update improvements

- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Tests/Core/ReplEvaluatorTests.cs
Fixes #1840 Syntax error when sending/typing comment to REPL
Checks for empty AST when determining whether to evaluate code.
> Fixes #1840 Syntax error when sending/typing comment to REPL

- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Tests/CookiecutterTests/CookiecutterTests.csproj
- Python/Tests/CookiecutterTests/GitClientTests.cs
> Detect fatal errors when cloning a cookiecutter template.

- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
- Python/Product/Cookiecutter/Model/CookiecutterClientProvider.cs
- Python/Product/Cookiecutter/Model/ICookiecutterClient.cs
- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterClientTests.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
- Python/Tests/CookiecutterTests/MockCookiecutterClient.cs
Fixes #1611 cookiecutter should default to user's projects path
Sets a default project path when moving to the template.
We still need to add support for using the current project's path when "Add new item" entry point is used. I'll file a new issue for that.
> Fixes #1611 cookiecutter should default to user's projects path

- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Shared/Wpf/ConfigurationControl.cs
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
- Python/Product/Cookiecutter/ViewModel/ContextItemViewModel.cs
Fix #1799
Also updates git clone implementation to fix tests that were passing a mock redirector, ending up with null StandardErrorLines.
By the way, cookiecutter always uses the first entry in a list as the default.
I considered having an extra combo box item (first in list) for selecting default value (basically treat it as 'unset'), but since that would always be the same as the second item (the true first item in the list), there didn't seem to be much benefit.
> Cookiecutter default list selection

- Python/Product/Cookiecutter/Shared/Infrastructure/StringExtensions.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
Fix #1861
I double-checked the data types (using the debugger) in the properties dictionary at the point where TelemetrySession.PostEvent is called, to make sure it's sending the class instance, not a string representation.
> Send PII values properly using TelemetryPiiProperty.

- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Commands/DiagnosticsCommand.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Logging/InMemoryLogger.cs
- Python/Product/PythonTools/PythonTools/Logging/VsTelemetryLogger.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
- Python/Product/VSCommon/Logging/PythonLogEvent.cs
- Python/Product/VSInterpreters/InterpreterOptionsService.cs
Fixes #1739 Analysis does not restart if Python is installed while VS is running
Fixes notifications when going from "no interpreters" to "global default" interpreter
Fixes analyzer not starting when no interpreters are available
Fixes errors being swallowed by analyzer
Fixes thread safety issues when loading the default interpreter
Excludes some logged events from telemetry collection
Excludes (slow) Event Log data from diagnostics when Shift is held
> Fixes #1739 Analysis does not restart if Python is installed while VS is running

- Python/Product/BuildTasks/Microsoft.PythonTools.Web.targets
- Python/Product/WFastCgi/wfastcgi.py
Fixes target dependencies in Web.targets
Removes broken up-to-date check flag
Enables debugging in wfastcgi if ptvsd is available and specified.
> Minor fixes for web changes

- Python/Product/PythonTools/PythonTools/Logging/InMemoryLogger.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs
There's another (correct) LogEvent in PythonWebLauncher a few lines up, so I removed the extra (incorrect) one.
> Fix 1887: Assertion failed: Unhandled exception when launching web project

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/TestAdapter.Executor/TestExecutor.cs
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
Fixes #1394 Test adapter should not list all tests on command line
Adds support for passing tests in a plain-text file.
> Fixes #1394 Test adapter should not list all tests on command line

- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs
- Python/Tests/Core/EnvironmentListTests.cs
Fixes #1897 Python Environments only shows one venv in case of same venv name in two projects
Updates ordering function to sort by ID if descriptions are equal.
Displays project name for the company for virtual environments.
Fixes oddly named function.
> Fixes #1897 Python Environments only shows one venv

- Python/Product/Analysis/Interpreter/InterpreterArchitecture.cs
- Python/Product/EnvironmentsList/ConfigurationExtension.xaml
- Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/EnvironmentView.xaml
- Python/Product/EnvironmentsList/ToolWindow.xaml
- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/pip_downloader.py
- Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
- Python/Product/VSInterpreters/InterpreterOptionsService.cs
- Python/Tests/Core/EnvironmentListTests.cs
Fixes #1906 New custom environment does not land user in configure
Fixes #1943 Creating Python environment forcibly prepends it with "VisualStudio"
Fixes #1944 Changing environment library path does not toggle Apply button
Reworks how environments are created so that we don't eagerly save any details. Allows much easier cancellation.
Removes the UI for Library Path
Fixes the registry key where we save the display name.
Auto-detect will now fill in the description
Adds a button to the Overview tab to jump to the configure panel.
> Custom environment fixes

- Common/Product/SharedProject/CommonProjectNodeProperties.cs
- Python/Product/Django/Project/DjangoProject.cs
- Python/Product/PythonTools/PythonTools/Options/IPythonToolsOptionsService.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsPage.cs
- Python/Product/PythonTools/PythonTools/Options/SuppressDialogOptions.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNodeProperties.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebProject.cs
Fixes #1920 No way of clearing "do not show this again" for publish warning
Adds button to General options to reset all suppressed dialogs
Fixes #1921 Keep the Azure warning around by default
Changes default state of the "do not show this warning again" checkbox to unchecked.
Also enables the dialog for Django projects
Fixes IOleCommandTarget chain for Django projects
Avoids raising many NotImplementedErrors because of Azure Tools.
Handles error when reanalyzing project that is not fully loaded.
Makes options service public.
> Publish warning dialog fixes

- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/classifier.py
- Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/clustering.py
This is the quick fix for #1926.
We still need to figure out why the regression sample is broken (seems like a temporary server error rather than a broken link), and really ought to switch these samples over to our own datasets so that we know they won't disappear.
> Fixes the classifier and clustering templates with the new URL.

- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/ViewModel/ContextItemViewModel.cs
- Python/Product/Cookiecutter/ViewModel/TemplateViewModel.cs
- Python/Product/EnvironmentsList/DBExtension.xaml
- Python/Product/EnvironmentsList/DBExtension.xaml.cs
- Python/Product/EnvironmentsList/EnvironmentView.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml.cs
- Python/Product/EnvironmentsList/PipPackageView.cs
Fixes #1951 Cookiecutter treeviewitem Names are not accessible to Screen Readers
Fixes UI automation properties in cookiecutter and environments list.
Also make it so pressing Enter in the search box will start installing based on the current text.
> Fixes #1951 Cookiecutter treeviewitem Names are not accessible to Screen readers

- Python/Product/Debugger/Debugger.csproj
- Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7Events.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7Exceptions.cs
- Python/Product/Debugger/Debugger/ExceptionRaisedEventArgs.cs
- Python/Product/Debugger/Debugger/PythonDebugOptions.cs
- Python/Product/Debugger/Debugger/PythonException.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/Debugger/Debugger/PythonStackFrame.cs
- Python/Product/PythonTools/visualstudio_py_debugger.py
Fixes #1916 Exception popup doesn't show exception name
Provides detailed information to the new exception dialog in VS 2017
Adds a new (optional) exception message format to ptvsd.
This is still in validation, but feel free to weigh in with comments.
> Fixes #1916 Exception popup doesn't show exception name

- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Fix https://github.com/Microsoft/PTVS/issues/1941 Potentially confusing cloning status message: "installing cookiecutter..."
> Improve cookiecutter installation message.

- Python/Product/EnvironmentsList/PipExtension.xaml.cs
Fixes #1913 Installing packages sometimes causes a crash
Ensures package search results are only updated on the UI thread.
> Fixes #1913 Installing packages sometimes causes a crash

- Python/Setup/swix/Packages/Microsoft.PythonTools.Core.Vsix.swixproj
- Python/Setup/swix/Packages/debug_symbols.swr
Fixes #1939 MMD breakpoint in Python file gives weird call stack
Ensures the symbols for Microsoft.PythonTools.Debugger.Helper are included.
> Fixes #1939 MMD breakpoint in Python file gives weird call stack

- Python/Product/Analysis/Interpreter/InterpreterArchitecture.cs
- Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
- Python/Product/Common/Infrastructure/ObservableCollectionExtensions.cs
- Python/Product/Cookiecutter/Shared/Infrastructure/ObservableCollectionExtensions.cs
- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/AddInterpreterView.cs
- Python/Product/VSInterpreters/InterpreterOptionsService.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
- Python/Tests/Core/EnvironmentListTests.cs
Fixes #1911 Default environment does not stick
Fixes issue where we were recreating environment views too often.
Simplifies default interpreter handling to avoid cyclic and repeated event triggers.
> Issue 1911

- Python/Product/EnvironmentsList/PipExtension.xaml.cs
- Python/Product/EnvironmentsList/PipExtensionProvider.cs
Fixes #1931 Packages list not synced after pip install
Subscribes to the "installed packages changed" event to update the environments window list of packages.
> Fixes #1931 Packages list not synced after pip install

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/InterpreterView.cs
- Python/Product/PythonTools/PythonTools/Project/AddInterpreter.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/AddInterpreterView.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Project/InterpretersNode.cs
- Python/Product/PythonTools/PythonTools/Project/InterpretersNodeProperties.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #1864 Missing environments are no longer show in solution explorer
Switches to using IDs in a number of places in the UI so that we can support missing environments
Massively simplifies the view objects for environments in certain dialogs
Allows removing missing environments from a project
> Fixes #1864 Missing environments are no longer show in solution explorer

- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Tests/CookiecutterTests/CookiecutterViewModelTests.cs
Fix #1974 Cookiecutter automatic check for updates may be clearing the open in solution explorer section
> Fix the Open in Solution Explorer link disappearing

- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonFunction.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonType.cs
- Python/Product/PythonTools/PythonTools/Logging/InMemoryLogger.cs
- Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs
- Python/Product/TestAdapter.Analysis/TestCaseInfo.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
Fixes #1918 We don't discover unit tests while analysis is running
Adds fallback to use AST to guess at available unit tests.
Also fixes race condition in InMemoryLogger.
> Fixes #1918 We don't discover unit tests while analysis is running

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Analyzer/InterpreterScope.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #1948 Crash on Go To Definition
Checks for nulls and quietly ignores them (with an assert in debug builds)
Fixes #1466 F12 doesn't take me to definition of function but rather proposes a choice
Stops creating Definitions for from...import names.
> Fixes #1948 Crash on Go To Definition

- Python/Product/Cookiecutter/UrlConstants.cs
Fixes #1998 cookiecutter recommended feed should use HTTPS by default
Changes fwlink constants to be HTTPS
> Fixes #1998 cookiecutter recommended feed should use HTTPS by default

- Python/Product/Common/Infrastructure/ProcessOutput.cs
- Python/Product/RunElevated/RunElevated.csproj
- Python/Product/RunElevated/app.manifest
- Python/Product/VSInterpreters/PipPackageManager.cs
Fixes #1909 Cancelling elevation during uninstall throws error
Adds an elevation manifest to RunElevated and improves logging of Win32Exception messages.
Fixes "installing" string displayed when uninstalling packages.
> Fixes #1909 Cancelling elevation during uninstall throws error

- Python/Product/Profiling/PythonProfilingPackage.cs
Fixes #1991 .vsp files generated by profile give sharing violation
Waits up to 1 second for file to become accessible before opening.
I can't reproduce the actual issue, so I'm assuming it's a race with the profiling process closing. This change defers the open until we've successfully opened the file without sharing.
As far as I can tell, nothing to do with Anaconda.
> Fixes #1991 .vsp files generated by profile give sharing violation

- Common/Product/SharedProject/Navigation/Library.cs
- Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Fixes #1603 Race condition in PythonNavigateToItemProvider
Makes StartSearch more robust to races in the cancellation token.
> Fixes #1603 Race condition in PythonNavigateToItemProvider

- Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
- Python/Product/VSInterpreters/ConfigurablePythonInterpreterFactoryProvider.cs
Fixes #1565, #1994, #2005 Auto-detect crashes with Python 3.6 64-bit
Improves handling when loading invalid version numbers from the registry
Prevents unsupported version numbers being auto-detected when configuring an environment.
> Fixes #1565, #1994, #2005 Auto-detect crashes with Python 3.6 64-bit

- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Fixes #2010 Interpreter link crashes when path variable not set
Checks path variable before adding a variable with no name into the environment.
This doesn't affect VS 2017 because we automatically change empty variable names to `PYTHONPATH`.
> Fixes #2010 Interpreter link crashes when path variable not set

- Python/Product/Cookiecutter/CookiecutterToolWindow.cs
- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml.cs
Add From Cookiecutter was basically ignored when the command was ending up creating the tool window for the first time. Due to the tool window performing its actual initialization on idle, the NewSession() which was passing in the target project location was a no-op due to the control not being ready.
> Fix 2015 Add From Cookiecutter sometimes reverts to global mode

- Common/Product/SharedProject/Automation/OAProperties.cs
- Python/Product/Django.Analysis/DjangoAnalyzer.cs
- Python/Product/Django.Analysis/DjangoUrl.cs
- Python/Product/Django/TemplateParsing/DjangoBlocks/DjangoUrlBlock.cs
Hey hey,
Hesse commits:
- Fix a small typo
- Remove a redundant cast
- add the PTVS Apache License in a file where it should be
but more importantly, it improves the way django url parameters are completed.
It will propose the context variables as completion, as long as not enough parameters have been provided to the url template tag. And it will propose the unused named parameters also as completion.
Some changes are a "preparation"  to the django url namespace support I'm working on.
Cheers,
David
> Improve django url intellisense parameters completion

- Python/Product/Analysis/ModulePath.cs
- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Tests/Analysis/ModulePathTests.cs
Fixes #2041 Constantly creating processes while checking packages
Checks whether the file change is a Python source or compiled file before retriggering package scan.
> Fixes #2041 Constantly creating processes while checking packages

- Common/Product/SharedProject/TaskDialog.cs
- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Interpreter/GlobalInterpreterOptions.cs
- Python/Product/Analysis/Interpreter/IPythonInterpreterFactoryWithDatabase.cs
- Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs
- Python/Product/Analyzer/Analyzer.csproj
- Python/Product/Analyzer/App.config
- Python/Product/Analyzer/Intellisense/AnalysisQueue.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntry.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/InterpretersNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonFileNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/VSCommon/Infrastructure/TaskDialog.cs
- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/PythonEditor.cs
Prevents a few crashes at shutdown
Improves encapsulation/creation of BufferParser instances (doesn't quite fix all the races here, but it's a necessary start point - more work coming here)
Avoids sending too many AnalysisComplete events
Avoids creating filesystem watchers and package managers in analyzer process
Fixes analyzer not resetting after database update
Fixes retriggering package scan because of a package scan
Prevents OOM when analyzing delphixpy package
> Range of important fixes

- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
Fixes #2045 Code snippets don't expand in REPL
Exclude snippets from completion list in the repl.
> Fixes #2045 Code snippets don't expand in REPL

- Python/Product/Analysis/Values/BuiltinInstanceInfo.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #2057 Multiple project IntelliSense does not work
Stops trying to share analyzer processes between projects.
Also fixes incorrect hash code when strongly merging object values.
> Fixes #2057 Multiple project IntelliSense does not work

- Python/Product/Analyzer/Intellisense/AnalysisQueue.cs
Fixes #2064 Analyzer null reference in queue worker
Stops changing the event handler reference in the closure.
> Fixes #2064 Analyzer null reference in queue worker

- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemDisplay.cs
- Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Partially fixes #2602 No navigate to results of object browser items
Switches to an analyzer command for Navigate To results. Object browser is still busted.
> Partially fixes #2602 No navigate to results of object browser items

- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonType.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/Analyzer/Intellisense/AnalysisQueue.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/Navigation/DropDownBarClient.cs
Fixes a range of IntelliSense issues
Fixes #1932 Navigate To probably crashing
Fixes #1547 Navigate To shows too many items
Fixes #1988 Navigation Bar does not navigate to classes
Prevents analyzers from getting stuck when they crash, and forces them to crash completely so we hear about it
Fixes some analyzer crashes that were preventing finding all tests in Azure SDK project
Prevents a race condition getting members from AST analysis
Prevents environments list from resetting the listener so often
Reduces duplication in Navigate To results
> Fixes a range of IntelliSense issues

- Python/Product/PythonTools/PythonToolsService.cs
Fix #2066 devenv.exe ran out of memory
The initialization code that was called constantly was:
- enumerating snippets (using up some memory)
- logging events (which were ignored for memory logger, but not ignored for vs logger)
I'll have to repeat my experiment to ensure this resolves the leak I was seeing, but it's likely to be this, and even if not, this is bad enough that it needs to be fixed.
One regression with this fix:  If you import code snippets using the snippet manager, you won't see the updated snippet list in completions until you restart VS.  You can expand them by manually typing the name + TAB, but they don't appear in completion list.  I don't think that would be a common enough problem to worry about it, but I can file it.
> Prevent OnIdle initialization from occurring more than once.

- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
Fixes #2046 REPL window unexpectedly disappears when opening new project
Only closes interactive windows when they have not changed.
Fixes #2047 Debug interactive reset command brings down its REPL 
Display a message instead of throwing when reset is selected.
> Fixes #2046 REPL window unexpectedly disappears when opening new project

- Common/Tests/MockVsTests/MockVs.cs
- Common/Tests/Utilities/SharedProject/SolutionFile.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Tests/Core.UI/PythonProjectProcessor.cs
- Python/Tests/IronPython/ReplEvaluatorTests.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/ProjectTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Fixes a couple of tests.
Only product impact is defaulting to PYTHONPATH when no variable name is set. This should only affect tests, as we already default to PYTHONPATH elsewhere in the actual product.
> Test fixes

- Build/PreBuild.ps1
- Python/Product/Debugger/Debugger/DebugEngine/AD7Exceptions.cs
I'm on build 26130.1 and one of the debug interfaces has been changed. I updated the build tools while I was thinking of it, but it wasn't strictly necessary for it to build.
I suspect you'll want to update the build machine before merging this.
> Fix build and update build tools.

- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Model/GitClientProvider.cs
Fix #2104 Cookiecutter clone broken in latest VS 2017 builds
Make sure that the dependent dlls can be found by adding the folder to the PATH. That seems safer than changing the working dir, which would also work but requires adding more params to the command line to tell git which folder to really work in.
> Fix cookiecutter git client

- Common/Product/SharedProject/VsExtensions.cs
- Python/Product/PythonTools/PythonTools/SurveyNewsService.cs
- Python/Product/PythonTools/PythonToolsService.cs
Fixes #2110 Invalid call to GetPythonToolsService in SurveyNewsService
Ensures PythonToolsService is available and adds locking around event handling.
> Fixes #2110 Invalid call to GetPythonToolsService in SurveyNewsService

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #2142: NullReferenceException when using lightbulb extract method
Adds null checks.
> Fixes #2142: NullReferenceException when using lightbulb extract method

- Common/Product/SharedProject/HierarchyNode.cs
Fixes #2111 RemoveNonDocument ordering issue
Correctly traverses the linked list while removing elements.
This was reported by NTVS team when they discovered a crash in their version of this file.
> Fixes #2111 RemoveNonDocument ordering issue

- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
Fixes #2160 Custom commands cannot detect installed packages
Switches check to treat package specs as requirements rather than names.
> Fixes #2160 Custom commands cannot detect installed packages

- Python/Product/Debugger/DkmDebugger/LocalComponent.vsdconfigxml
- Python/Product/Debugger/DkmDebugger/RemoteComponent.vsdconfigxml
Filter by EngineId, or use CallOnlyWhenLoaded, as appropriate.
> Fix #1289: PTVS Concord components should avoid using NoFilter in their .vsdconfigxml

- Python/Product/Common/Infrastructure/TaskExtensions.cs
- Python/Product/Django/Intellisense/AnalyzerExtensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExceptionCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExpansionCompletionSource.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/OVERRIDECOMPLETIONANALYSIS.CS
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Logging/InMemoryLogger.cs
- Python/Product/PythonTools/PythonTools/Logging/VsTelemetryLogger.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonFileLibraryNode.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLanguageInfo.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonNonCodeFileNode.cs
- Python/Product/PythonTools/PythonTools/Refactoring/ExtractMethodRequestView.cs
- Python/Product/PythonTools/PythonTools/Refactoring/VariableRenamer.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSCommon/Logging/PythonLogEvent.cs
- Python/Product/VSCommon/Logging/PythonToolsLoggerData.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/EditorTests.cs
- Python/Tests/PythonToolsMockTests/MockPythonToolsPackage.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
- Python/Tests/PythonToolsMockTests/SquiggleTests.cs
- Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs
Fixes #2043 Intellisense performance issues
Broadly, this reduces the timeouts based on telemetry information, but the more significant change is consistency in how we wait for out-of-proc analysis messages and also adding telemetry points for these waits.
To do this, we need direct access to the analyzer earlier in the call, so this resulted in a few functions changing from static to instance methods.
As usual, all telemetry-only code is (or should be) protected by catch-all handlers that assert in debug builds. Telemetry failures should _never_ cause the product to break.
> Fixes #2043 Intellisense performance issues

- Common/Product/SharedProject/Automation/OAProject.cs
- Python/Product/ProjectWizards/InstallRequirementsWizard.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Tests/Core.UI/PythonToolsUITests.csproj
- Python/Tests/Core/PythonProjectProcessor.cs
- Python/Tests/Core/PythonTestDefinitions.cs
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/PythonToolsMockTests/ProjectTests.cs
Fixes #1542 Create virtual env dialog doesn't always come up via new project
Exposes IOleCommandTarget via the DTE Project so we can invoke the command without going through DTE.
Adds test ensuring project has the right types exposed.
Fixes implicit circular dependency between PythonToolsTests and PythonToolsUITests.
Validated with manual testing:
* I found that creating Flask project, Django project, Flask project would somehow get VS stuck not showing the dialog
* After this change, I can no longer reproduce this
* Over 100 projects were created and deleted in the process of fixing this bug :)
> Fixes #1542 Create virtual env dialog doesn't always come up via new project

- Common/Product/SharedProject/IDEBuildLogger.cs
- Common/Product/SharedProject/ProjectNode.cs
- Common/Product/SharedProject/ProjectResources.cs
- Common/Product/SharedProject/ProjectResources.resx
Fixes #1266 Deadlock invoking MSBuild internally
Ensures build settings are only retrieved while on the UI thread.
Also moves error message into resources.
> Fixes #1266 Deadlock invoking MSBuild internally

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/VSCommon/Infrastructure/TaskDialog.cs
Fixes #2319 Unexpected error dialog needs version number
Adds version number to details.
Moves strings to resource files so they will be localized.
Note that the details string is deliberately non-localized, since the intent is to send it back to the development team for review (and we all speak English right now).
> Fixes #2319 Unexpected error dialog needs version number

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Project/PythonProjectFactory.cs
- Python/Tests/Core/ProjectUpgradeTests.cs
- Python/Tests/TestData/ProjectUpgrade/OldPythonTargets.pyproj
- Python/Tests/TestData/ProjectUpgrade/UnknownInterpreterId.pyproj
- Python/Tests/TestData/ProjectUpgrade/UnknownInterpreterReference.pyproj
Fixes #2320 Unknown interpreter ID keeps causing upgrades
Removes unknown IDs rather than ignoring them
> Fixes #2320 Unknown interpreter ID keeps causing upgrades

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/PipExtensionProvider.cs
- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Fixes #2280 EnvironmentList ToolWindow crashes on invalid environment
Handles errors creating a view for an environment, including retrying the entire update to exclude "bad" entries rather than leaving them visible and unusable
Improves handling on the online help item, to avoid static construction
Also fixes layout of "make default" label.
> Fixes #2280 EnvironmentList ToolWindow crashes on invalid environment

- Python/Product/Debugger/Debugger/DebugConnection.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
Reverts to old syntax to satisfy FxCop.
Disposes of readonly event.
> Reverts to old syntax to satisfy FxCop.

- Python/Product/Ipc.Json/Connection.cs
The packet was only read partially before it was deserialized as JSON. This ensures that the whole packet is read first.
Example: content-length was around 1800 chars, but the first call to ReadAsync was only getting about 1400 chars.
> Fix #2342 Crash during remote debugging. 

- Python/Product/Debugger/Debugger/DebugConnection.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Fix https://github.com/Microsoft/PTVS/issues/2357
Add error handling so that VS doesn't crash when attach to debug repl is refused or there's any other error around that request.
This will allow us to turn off the debug repl attach feature in attach_server.py, if necessary.
> Add better error handling around attach to debug repl

- Common/Product/SharedProject/Wpf/ConfigurationControl.cs
- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Cookiecutter/Shared/Wpf/ConfigurationControl.cs
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
- Python/Product/EnvironmentsList/ConfigurationExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentView.xaml
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
- Python/Product/Profiling/Profiling/LaunchProfiling.xaml
- Python/Product/Profiling/Strings.Designer.cs
- Python/Product/Profiling/Strings.resx
Fixes #2234 No screen reader output when tabbing through New Environment Config Form UI
Fixes similar bug in the profiling dialog
This uses the AutomationProperties.LabeledBy attribute to associate a control with its label.  When tabbing to the control, the label is now read by narrator.
This also sets AutomationProperties.Name on the browse buttons so that for example narrator reads "Browse for interpreter path" followed by "button" instead of just reading "button" (because the button text is `...` which is not read).
Prevents options pane from receiving focus, as it's a container and non-interactive.
Prevent focus from going to images in labels and buttons in environments window.
> Accessibility fixes for environment window and profiling dialog

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #2381 VS crashed after new python project
Ensures strings are not null or empty before using as dictionary keys.
> Fixes #2381 VS crashed after new python project

- Common/Product/SharedProject/FileNode.cs
- Common/Product/SharedProject/FolderNode.cs
- Common/Product/SharedProject/HierarchyNode.cs
Fixes #2395 VSHPROPID_Name should not return caption
Adds Name property to allow overriding node names.
Override name by default for files and folders.
> Fixes #2395 VSHPROPID_Name should not return caption

- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Fixes #2374 IPython does not work in specific project
Changes script locator to look in interpreter's directory for projects.
> Fixes #2374 IPython does not work in specific project

- Python/Product/PythonTools/PythonTools/Options/PythonAdvancedEditorOptionsControl.resx
Fixes #973 Text Editor Advanced options layout expands
Enables auto-scroll on options page
Also reduces control margins to match other pages
> Fixes #973 Text Editor Advanced options layout expands

- Python/Product/Ipc.Json/Connection.cs
- Python/Product/Ipc.Json/Ipc.Json.csproj
- Python/Product/Ipc.Json/Properties/AssemblyInfo.cs
- Python/Product/Ipc.Json/ProtocolReader.cs
- Python/Product/PythonTools/visualstudio_py_ipcjson.py
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/IpcJsonTests/IpcJsonTests.cs
- Python/Tests/IpcJsonTests/IpcJsonTests.csproj
- Python/Tests/IpcJsonTests/PacketReadTests.cs
- Python/Tests/TestData/Ipc.Json/socket_handle_request.py
Add lower-level tests for the reading of packets on C# side, fix issues discovered and refactor as necessary for tests.
Change the protocol to be closer to the VSC base protocol (ascii headers, `\r\n` separators).
The new reading code no longer allocates a char array based on the value of Content-Length, which could have caused out of memory errors if that value was incorrect.  In the new code an incorrect large value won't cause as much damage.
Fixes https://github.com/Microsoft/PTVS/issues/2402
> Fixes and tests for IPC JSON

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
Fixes #2424 Padding on "This environment cannot be made the default"
Removes unnecessary padding.
Also adjusts margin on support URL so spacing is correct when hidden.
> Fixes #2424 Padding on "This environment cannot be made the default"

- Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
Fixes #2426 Cannot disambiguate Anaconda installs
Adds a DisambiguateDescriptions function to InterpreterConfiguration and makes the current description part of the configuration identity.
> Fixes #2426 Cannot disambiguate Anaconda installs

- Python/Product/EnvironmentsList/PipExtension.xaml
404497 Accessibility : MAS40B : INSPECT : Python+ Python Environments : Name property for the Search edit in Packages window is null
404519 Accessibility : MAS36 : Keyboard : 'Delete(X)' and 'Upgrade To set up tools(Up Arrow mark) buttons are not accessible in Packages window of Python Environment
> Some accessibility fixes for pip package view

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/StringLiteralCompletionList.cs
Fixes #2352 Intellisense hangs VS when interacting with filepath that contains many files
Filters by partial name once items exceed 10000
Since the completion is synchronous and the disk IO causes the hang, we also disable automatic triggering for paths. You now need to Ctrl+Space/J to trigger completions in a string literal.
> Fixes #2352 Intellisense hangs VS when interacting with filepath that contains many files

- Python/Product/Common/Infrastructure/PathUtils.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
Fixes #2447 Opening the Python Environments tab causes VS 2017 to crash
Handles error due to invalid path rather than crashing.
Also fixes unhandled NormalizePath failure.
> Fixes #2447 Opening the Python Environments tab causes VS 2017 to crash

- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml.cs
- Python/Product/Cookiecutter/ViewModel/CategorizedViewModel.cs
- Python/Product/Cookiecutter/ViewModel/ContinuationViewModel.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Product/Cookiecutter/ViewModel/ErrorViewModel.cs
- Python/Product/Cookiecutter/ViewModel/TemplateViewModel.cs
- Python/Product/Cookiecutter/ViewModel/TreeItemViewModel.cs
More reasonable TAB and SHIFT-TAB behavior
- Cycles through all controls forward and backward, no longer takes you to the toolbar
- Load more is no longer a tab stop, just go to the tree node by navigating the tree with arrow keys
Focus now remains in the tree view after clicking load more, instead of going to the output window.
Toolbar is accessed with Shift-Alt (standard in VS)
405000 Accessibility : MAS05 : Keyboard : Python + Cookiecutter : Focus order improper for tool-bar in Cookie cutter window
403507 Accessibility : MAS05 : Keyboard : Python + Cookiecutter : Focus order improper in CookieCutter window after refreshing or loading the page
404511 Accessibility : MAS07 : Keyboard : Python+Cookiecutter : Keyboard trap found over 'Search' edit box when perfoming reverse tab (Shift …
> Cookiecutter accessibility fixes

- Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs
Fixes #2481 No AnalysisEntryService in tests
Ensures the entry service is added to the mock component model.
> Fixes #2481 No AnalysisEntryService in tests

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #2479 Exception raised while editing
Safely handles cases where we cannot correctly map outlining tags to the latest version.
> Fixes #2479 Exception raised while editing

- Python/Product/ProjectWizards/CloudServiceWizard.cs
- Python/Product/ProjectWizards/ProjectWizards.csproj
Fixes #2464 Create Azure Cloud Service project error
Explicitly checks for an installed package rather than inferring it from a loadable type.
Removes dead code
> Fixes #2464 Create Azure Cloud Service project error

- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/View/CookiecutterContainerPage.xaml.cs
- Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/ViewModel/CategorizedViewModel.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Bug 410725: Usability : Unable to invoke the context menu in Cookie cutter window using Shift key + F10
Bug 404076: Accessibility : MAS40B : INSPECT : Python + Cookiecutter : Name property is inappropriate for the interactive elements in Templates present in Cookiecutter window
Fixes alignment of search text box / button.
Prevents changing the selection if there's already a node that is selected.
> More cookiecutter accessibility fixes

- Python/Product/EnvironmentsList/PipExtension.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml.cs
Fixes #2495 InvalidOperationException when pip is not installed
Prevents installing packages when pip is not available
Ensures "Download and install pip" is correctly shown
Disables search box when pip is not installed
> Fixes #2495 InvalidOperationException when pip is not installed

- Common/Tests/Utilities/Mocks/MockTextBuffer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CodeCellAnalysis.cs
- Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs
- Python/Tests/Core/CodeCellTests.cs
- Python/Tests/Core/PythonToolsTests.csproj
Fixes #2492 Empty code cells prevent code cells being collapsible
Fixes OutliningTaggerProvider to prevent getting stuck in infinite loops
Fixes FindEndOfCell to correctly exclude comments while including whitespace
Adds tests for code cells
> Fixes #2492 Empty code cells prevent code cells being collapsible

- Python/Product/PythonTools/PythonToolsService.cs
Fixes #2513 NullReferenceException when profiling script with custom interpreter path
Validates non-null config
Handle null Interpreter safely
> Fixes #2513 NullReferenceException when profiling script with custom interpreter path

- Python/Tests/Core.UI/AddImportTests.cs
- Python/Tests/Core.UI/RemoveImportTests.cs
- Python/Tests/Utilities.Python/EditorWindowExtensions.cs
- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
'Remove import' tests failures were easy to repro on my machine, and adding the wait for analyzer makes them succeed consistently.
'Add import' tests were not failing on my machine. On test machine they fail waiting for the lightbulb session, so adding a wait on the analyzer makes some sense.
> Fix add/remove import tests noticed on test machine

- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Tests/Core/ReplEvaluatorTests.cs
Fixes #2510 REPL SyntaxError when sending/typing only comments
Improves logic for identifying non-executable statements
Adds test for problematic code
> Fixes #2510 REPL SyntaxError when sending/typing only comments

- Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
Now ignores the project if the file is not in it (or is not visible), and selects the right project if it's not in the startup project.
> Fixes #2493 Execute File in Interactive executes wrong file

- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
Extend the range of valid count for GitHub results so that we don't have to keep adjusting the value as GitHub returns more or less results over time.
> Fix cookiecutter integration test

- Python/Tests/TestData/Ipc.Json/parsing_test.py
Don't print the message, as it may contain unicode chars that cannot be printed to the console.
I was testing an unrelated code page issue on my desktop machine at the time I wrote the test, and ended up with a false positive because of it.
The intention with printing the message was that the test could validate the message read. It only checks if the message was read and deserialized successfully. If we ever want to validate more than that, we could print in base64, or write to a file.
> Fix ipc json unicode tests failures

- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/PythonTools/PythonTools/Commands/DkmDebuggerCommand.cs
Fixes #2365 Mixed mode debugging on 3.6 gives exe_common.inl not found
Fixes build options so that debug helpers are usable.
Fixes source of PythonDeveloper registry value.
Might also be nice to filter all the stack below the `invoke_main` call, since it's really not relevant. I'm not sure how to do that, but maybe it's easy for @int19h ?
> Fixes #2365 Mixed mode debugging on 3.6 gives exe_common.inl not found

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
- Python/Product/EnvironmentsListHost/MainWindow.xaml
- Python/Product/EnvironmentsListHost/MainWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Make the 2 buttons for enable IPython mode into a real checkbox.
404495 Accessibility : MAS40B : INSPECT : Python+ Python Environments : Control type is incorrect for the checkbox in Python Environments window
403510 Accessibility : MAS05 : Keyboard : Python + Python Environment : Focus order improper in Python Environment Window
> Accessibility fixes for environment window

- Common/Product/SharedProject/CommonPackage.cs
- Common/Product/SharedProject/ProjectResources.cs
- Common/Product/SharedProject/ProjectResources.resx
- Python/Product/PythonTools/PythonTools/Commands/AzureExplorerAttachDebuggerCommand.cs
- Python/Product/PythonTools/PythonTools/Commands/OpenWebUrlCommand.cs
- Python/Product/PythonTools/PythonTools/Debugger/CustomDebuggerEventHandler.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Project/AddInterpreter.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml.cs
- Python/Product/PythonTools/PythonTools/SurveyNewsService.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
Remaining calls to OpenVsWebBrowser are:
- CommonNonCodeFileNode.DoDefaultAction
- OpenNoInterpretersHelpPage
> Use external web browser

- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/EnvironmentsList/DBExtension.xaml
- Python/Product/EnvironmentsList/DBExtension.xaml.cs
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
405004: Accessibility : MAS40B : INSPECT : Python+Python Environments : Name property for the items in the database does not contain the number of modules
404512: Accessibility : MAS36 : Keyboard : Python+Cookiecutter : 'Installed/Recommended/GitHub' expand collapse buttons are not accessible in CookieCutter window
Also prevents some images from getting focus.
> Accessibility fixes

- Common/Tests/SccPackage/TestSccPackage.csproj
- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Django/Django.csproj
- Python/Product/Profiling/Profiling.csproj
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/Uwp/Uwp.csproj
I upgraded a machine from 15.3 build 26507 to 26526, and it required adding a referenced assembly.  It still builds on the older build even with these changes (the 'new' assembly was there before).
Also fixes a REPL test (I forgot which one) which was failing with NRE.
> Build and test fix

- Common/Tests/Utilities/Mocks/MockTextImageVersion.cs
- Common/Tests/Utilities/Mocks/MockTextVersion.cs
- Common/Tests/Utilities/TestUtilities.csproj
TestComprehensions was failing with this error:
```
Test method PythonToolsTests.ExtractMethodTests.TestComprehensions threw exception: 
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'TestUtilities.Mocks.MockTextVersion' to type 'Microsoft.VisualStudio.Text.ITextVersion2'.
```
> Fix ExtractMethodTests

- Common/Tests/Utilities/Mocks/TextVersionWorkaround.cs
- Common/Tests/Utilities/TestUtilities.csproj
This will keep us building with the current version of VS while we figure out how to deal with the brokenness in the next update.
We'll just have to ignore the failed tests for now until we can get all the build machines upgraded properly (which they probably won't do for us, so we're back to maintaining our own build infrastructure...)
> Adds workaround for building against stable VS.

- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
When an exception occurred in ProcessLoaded event handler (on background thread), it wasn't caught and that was causing the test agent to terminate. Not a big deal when using Test Explorer, as it only affects that one test.  On the test machine, that is causing a whole bunch of tests to not be executed.
> Debugger test run improvement

- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Product/Cookiecutter/ViewModel/TemplateViewModel.cs
- Python/Product/Cookiecutter/ViewModel/TreeItemViewModel.cs
Fixes #2240 Screen reader does not read what template section a selected cookiecutter template is in
Enhances help text for templates.
> Fixes #2240 Screen reader does not read what template section

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Editor/ReplPromptHelpers.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Tests/Core/EditorTests.cs
Fixes #2398 Paste adds extra whitespaces at the end
Replaces prompt removal with a two-step process so that Paste works properly.
Expands prompts to include IPython-style prompts
> Fixes #2398 Paste adds extra whitespaces at the end

- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
I ran all the debugger tests twice and did not see a single failure (compared to 3-5% failure before).
Changes the callback passed to CreateProcess to be `Func<Task>` instead of `Action`, and ensure that it is awaited on. This ensures proper order of execution during process load event handling.
The callers that were already passing an async delegate didn't have to change, just the ones that were passing non-async delegate.
> Improve debugger tests reliability.

- Common/Tests/Utilities/AssertListener.cs
- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
Fix #2628 DebuggerTests that log warnings to event viewer
> Disable logging of ObjectDisposedException in debugger tests

- Python/Product/Cookiecutter/Shared/Infrastructure/OutputWindowRedirector.cs
- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
- Python/Product/VSCommon/Infrastructure/OutputWindowRedirector.cs
Fixes #1434 Try to launch PyLint crashes my PTVS
Makes failure to open output/error windows a silent failure, as there is nothing we can do at that stage to fix it.
> Fixes #1434 Try to launch PyLint crashes my PTVS

- Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs
fixes #2473 - Tooltip is shown for indentation
Reverse expression parser "fix" (in quotes due to my own uncertainty) to attempt and catch whitespace-strings identified for type hover over.
> fixes #2473 - Tooltip is shown for indentation

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Debugger/Debugger/DebugConnection.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteProcess.cs
- Python/Product/Debugger/Debugger/LegacyDebuggerProtocol.cs
- Python/Product/Debugger/Debugger/OutputEventArgs.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/Debugger/Debugger/PythonStackFrame.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/PythonTools/ptvsd/__init__.py
- Python/Product/PythonTools/ptvsd/__main__.py
- Python/Product/PythonTools/ptvsd/attach_server.py
- Python/Product/PythonTools/ptvsd/setup.py
- Python/Product/PythonTools/visualstudio_py_debugger.py
- Python/Product/PythonTools/visualstudio_py_ipcjson.py
- Python/Product/PythonTools/visualstudio_py_launcher.py
- Python/Product/PythonTools/visualstudio_py_repl.py
- Python/Product/PythonTools/visualstudio_py_util.py
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
- Python/Tests/DebuggerTests/DebugExtensions.cs
Makes the DebugReplEvaluatorTests* pass more reliably, and add some more coverage.
Change the protocol to be the debugger's, which is JSON, instead of the REPL's, which is binary.
Note that IntelliSense is broken in debug repl prior to these changes (the 2 IntelliSense related methods that are marked TODO are never called).
Need to decide how to increment the ptvsd version (this is breaking change, so 4.0?)
I've added an intermediate base class `PythonCommonInteractiveEvaluator` that the regular repl and debug repl now derive from, so that debug repl doesn't inherit any of the binary repl protocol specific code. A lot of that code is the same, but it's now split between the new base class and the original `PythonInteractiveEvaluator`.
> Debug interactive window protocol changes

- Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs
Fixes #2691 NullReferenceException getting test case info
Checks all values for null before using them.
> Fixes #2691 NullReferenceException getting test case info

- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
Fixes #2692 Exception in TaskProvider.Refresh()
Replace potential out of range exceptions with safe behaviour and assertions
> Fixes #2692 Exception in TaskProvider.Refresh()

- Common/Product/SharedProject/ConfigProvider.cs
- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Tests/Core.UI/BasicProjectTests.cs
- Python/Tests/Core.UI/PythonToolsUITests.csproj
- Python/Tests/TestData/NoConfigurations/HelloWorld.pyproj
- Python/Tests/TestData/NoConfigurations/Program.py
Fixes #2622 VS cannot handle when ConfigProvider returns no configurations
Adds default configurations for when projects do not have any conditions.
Allows VisualStudioApp.OpenProject() to also open projects
Adds test
Removes unnecessary references from PythonToolsUITests
> Fixes #2622 VS cannot handle when ConfigProvider returns no configurations

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/MemberResult.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Values/SyntheticDefinitionInfo.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Fixes #2389 Cannot go to definition of variables
Ensures all definition locations are made available for variables.
Improves MemberResult implementation using Lazy.
Fixes MemberResult not ignoring Unknown type information properly.
> Fixes #2389 Cannot go to definition of variables

- Python/Product/EnvironmentsList/DBExtension.xaml
Fixes #1694 Intellisense packages are not sorted
Displays full package name in list so it is obvious that they are sorted.
> Fixes #1694 Intellisense packages are not sorted

- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
- Python/Product/PythonTools/visualstudio_ipython_repl.py
Fixes #2648 REPL code analysis does not include variables
Fixes handling of empty expression completion for IPython mode
Fixes error in heartbeat channel
Prevents invalid names being shown in completion list (since they do not filter properly)
Fixes debug mode failing due to incorrect use of ShellExecute.
> Fixes #2648 REPL code analysis does not include variables

- Common/Tests/Utilities.UI/TestUtilities.UI.csproj
- Common/Tests/Utilities.UI/UI/NewItemDialog.cs
- Common/Tests/Utilities.UI/UI/NewProjectDialog.cs
- Python/Tests/Core.UI/UITests.cs
- Python/Tests/Django.UI/DjangoEditingTests.cs
- Python/Tests/Django.UI/DjangoProjectTests.cs
- Python/Tests/Django/DjangoDebuggerTests.cs
- Python/Tests/TestData/DjangoProject/Oar/views.py
Fixes #2716 TestUtilities.UI.NewItemDialog.get_ProjectTypes throws InvalidOperationException
NewItemDialog was implemented in NewProjectDialog.cs and vice-versa, so I renamed the files, making the changes look larger than they really are.
I just changed the control type for ProjectItems to be ListView instead of DataTable. That was already correct for NewProjectDialog, but hadn't been updated for NewItemDialog yet.
Fix debugger test data for latest django (use dict instead of Context).
Skip some failing django editing tests that have been filed.
With this, there is just one failing Django test left (the one that creates an Azure Cloud Service project - I'm installing Azure workload to see if it passes with it).
Edit: DjangoUITests.DjangoAzureProjectTests.AddCloudProject passes with Azure …
> Django test fixes

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/ModulePath.cs
- Python/Product/Analysis/ModuleReference.cs
- Python/Product/Analysis/ModuleTable.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/Analysis/Values/SyntheticDefinitionInfo.cs
- Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Fixes #2085 Cannot see imports from search paths
Adds background task to enumerate packages/modules in search path directories (ZIP files not yet supported)
Makes unimported modules lazier
Fixes NullReferenceException in Navigate To.
> Fixes #2085 Cannot see imports from search paths

- Python/Product/Analyzer/Analyzer.csproj
- Python/Product/Analyzer/Intellisense/ImportedModuleNameWalker.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #794 go to definition (F12) on sympy
Adds special handling for non-variables to enable go-to-definition and relevant tooltips when they are module names.
> Fixes #794 go to definition (F12) on sympy

- Common/Product/SharedProject/FolderNode.cs
Fixes #161 Rename directory error message
Stops raising on non-fatal failure to refresh property browser.
As far as I can tell, this is the only place we can get an `E_FAIL` from this code path. It's certainly not a big deal, but no need to scare the user with a dialog.
> Fixes #161 Rename directory error message

- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseControllerProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #2727 Editors opened by LSL are not associated with the project
Updates open editors on project reanalysis to ensure they are associated with the correct project
Ensures squiggles are cleared.
Prevents overlapping asynchronous requests to out-of-proc analyzer.
Prevents unnecessary notifications after disconnecting a buffer parser
Some minor code cleaning.
> Fixes #2727 Editors opened by LSL are not associated with the project

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fix #2798 NullReferenceException during analysis
> Handle null response in GetProximityExpressionsAsync.

- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/VSCommon/Infrastructure/TextExtensions.cs
Fix #2790 Visual Studio 2017 error
I didn't find how to repro the original bug, where the file path was null. According to `TextExtensions .GetFilePath`, this happens when the text buffer doesn't have the property of key `typeof(TextDocument)`.
While testing the source control compare window,  I noticed that the pane that was an in-memory file was returning a file path that didn't exist. If you tried to start debugging, the console would start and immediately complain that the file doesn't exist.
Adding the File.Exists check should prevent both cases.
> Disable start debugging command for a text view that doesn't have a valid file path

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fix #2803 NullReferenceException in IntellisenseController.UpdateCurrentParameter
> Handle PythonService.GetSignatures() returning null.

- Python/Product/PythonTools/PythonTools/Navigation/PythonLanguageInfo.cs
> Prevent NullReferenceException when request returns null in GetProximityExpressions

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fix #2802 IntelliSense stops working and devenv.exe CPU usage goes up
I added a bunch of tracing code and found out that when this bug occurred, the code right after TrySetResult wasn't getting executed (because the thread was executing the continuation).
I tested almost all afternoon with and without the fix, and was getting consistent results (ie no repro with the fix, always repro without).
> Fix broken IntelliSense and high CPU

- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
Fix #2816 VS crash when error points to a missing file
Here's the fix in action:
```
---------------------------
Visual Studio - Python support
---------------------------
The document cannot be opened. It has been renamed, deleted or moved.
---------------------------
OK   
---------------------------
```
> Fix VS crash when error points to a missing file

- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
Fix #2820 
Exceptions come from `UpdatePropertiesFromProjectMoniker`, I catch the same exceptions as other callers to that function.
Tested both "Switch this window" and "Open new window" options. Behavior is consistent after failure in both cases: error message is printed, and combo box shows "Unknown".
> Prevent crash when switching REPL to missing interpreter

- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
Fixes 4 failing tests.
It was trying to determine the module name from the file name `"<string>"`, which was determined to be an invalid path and throwing an exception.
> Fix failing test adapter tests.

- Python/Product/PythonTools/ptvsd/attach_server.py
- Python/Product/PythonTools/ptvsd/debugger.py
Fix initial frame list when attaching not including enable_attach frame, causing incorrect stack traces if enable_attach is called from another function.
Add missing modules to DONT_DEBUG list.
> Fix #2837: Debugger breaks inside ptvsd

- Python/Product/TestAdapter.Executor/TestExecutor.cs
- Python/Product/TestAdapter.Executor/TestProtocol.cs
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestAdapterTests/TestInfo.cs
- Python/Tests/TestData/TestAdapterTests/DurationTest.py
- Python/Tests/TestData/TestAdapterTests/DurationTest.pyproj
Fix #2822 After running tests, elapsed time is incorrect
(will wait to merge - this is a 3.2 bug)
> Fix test result duration

- Python/Product/Debugger/Debugger/DebugConnection.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/TestData/DebuggerProject/AttachPtvsdUnitTest.py
Prevent deadlock when disposing debugger connection.
Gracefully handle cancellation from debugger event handlers to prevent asserts during connection teardown.
> Fix #2842: Stop Debugging asserts while debugging unit tests

- Python/Tests/PythonToolsMockTests/App.config
- Python/Tests/PythonToolsMockTests/PythonToolsMockTests.csproj
Fixes https://github.com/Microsoft/PTVS/issues/2610
On 15.3, all tests from PythonToolsMockTests were failing trying to load an older version of Microsoft.VisualStudio.Validation. Now a lot of the tests are passing again, and those who don't are failing for a different reason.
Note that we do not directly reference that assembly from our projects.
> Add binding redirect for Microsoft.VisualStudio.Validation.

- Python/Product/Debugger/Debugger.csproj
- Python/Product/Debugger/Debugger/LegacyDebuggerProtocol.cs
- Python/Product/Debugger/Debugger/OutputEventArgs.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/ptvsd/debugger.py
Disable tracing while importing stdlib modules.
> Fix #2797: Import tensorflow module in PTVS is very slow

- Python/Product/PythonTools/ptvsd/setup.cfg
- Python/Product/PythonTools/ptvsd/setup.py
Fixes #2400 Publish ptvsd with next update
Updates ptvsd to use setuptools instead of distutils.
Enables building universal wheel for ptvsd
Once this is merged, I'll roll the change forward to master and up the ptvsd version.
It's already been published to https://pypi.org/project/ptvsd/3.2.0/ - note that the ptvsd and PTVS version numbers are not required to be in sync anymore.
> Fixes #2400 Publish ptvsd with next update

- Python/Product/PythonTools/ptvsd/debugger.py
Originally https://github.com/Microsoft/PTVS/pull/2249; recreating to account for debugger changes since then.
> Fix stackless schedule callback.

- Python/Product/Analysis/Parsing/PythonLanguageVersion.cs
- Python/Product/Debugger/DkmDebugger/LocalComponent.cs
- Python/Product/Debugger/DkmDebugger/PythonRuntimeInfo.cs
- Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/python.h
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/ProfilingUITests/ProfilingUITests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Fixes #2904 Mixed-mode debugger does not support 3.7
Adds support for version 3.7 to whole system
I don't think I missed any lists of versions - in general everything should go through the `PythonLanguageVersion` enum (which is now easier to maintain).
I checked the diff between 3.6 and 3.7 as well and there don't seem to be any changes needed in the structures just yet, but there's still time :)
Biggest value of this is that when combined with the VC debug launcher we'll be able to actively use this when working on CPython.
> Fixes #2904 Mixed-mode debugger does not support 3.7

- Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
- Python/Product/Cookiecutter/View/LiveTextBlock.cs
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
- Python/Product/EnvironmentsList/DBExtension.xaml
- Python/Product/VSCommon/Infrastructure/LiveTextBlock.cs
Fixes #2900 Preparing cookiecutter message not themed
Removes (broken) live text blocks
Makes status image spinnable.
> Fixes #2900 Preparing cookiecutter message not themed

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/EncodedLocation.cs
- Python/Product/Analysis/Interpreter/Ast/AstAnalysisFunctionWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstBuiltinsPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstNestedPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonBuiltinType.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonConstant.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonFunction.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonFunctionOverload.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonParameterInfo.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonType.cs
- Python/Product/Analysis/Interpreter/Ast/AstScrapedPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/NameLookupContext.cs
- Python/Product/Analysis/ModulePath.cs
- Python/Product/Analysis/scrape_builtins.py
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSource.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/TestData/AstAnalysis/ReturnValues.py
Fixes #2908 Ast interpreter needs to scrape its own builtin types
Adds builtin type scraper to be run with current environment. (A future change will cache this output, and there is more work to make the default results better on pre-3.6 interpreters or those that cannot be executed.)
Adds initial function walker to do return value analysis
> Fixes #2908 Ast interpreter needs to scrape its own builtin types

- Python/Product/Django/Project/DjangoPropertyPageControl.resx
Fix #2928 Django properties do not scale with high DPI
Changed font to Segoe 8.25pt to match other project settings (the designer changed a bunch of margins automatically, but it all looks fine to me).
> Fix font in django project settings

- Python/Product/PythonTools/ptvsd/attach_server.py
- Python/Product/PythonTools/ptvsd/setup.py
Adds ptvsd.repl package to setup.py
Removes unused reference in attach_server
This will also need to be backported to the 3.1 branch, and then I'll republish ptvsd as 3.2.1
> Adds ptvsd.repl package to setup.py

- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntryService.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/PythonClassifier.cs
- Python/Product/PythonTools/PythonTools/PythonClassifierProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
Fixes #2949 Unexpected error after closing split view
Correctly counts references to buffers so they are not released too soon.
Also fixes a double-free and an incorrect assertion.
> Fixes #2949 Unexpected error after closing split view

- Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
Fixes #2921 Crash in PythonAnalysisClassifier
Switches to Linq OrderBy and key selection to order the values.
Same as #2957 but for the master branch.
> Fixes #2921 Crash in PythonAnalysisClassifier

- Python/Setup/dirs.proj
- Python/Setup/swix/Packages/Microsoft.PythonTools.NativeDevelopment.VCDebugLauncher.Vsix.swixproj
- Python/Setup/swix/Packages/dirs.proj
- Python/Setup/swix/swix.generate.targets
- Python/Setup/swix/swix.targets
- Python/Setup/swix/swix_vsix_payload.py
Fixes #1651 How to cross debug python and C++
Adds the VC debug launcher to the generated manifest file.
This required a bit of infrastructure for handling payload files (where we reference a normal VSIX file), so future additions (and if/when we convert the entire project to use the VSSDK build) won't require so much code.
> Fixes #1651 How to cross debug python and C++

- Python/Product/Analysis/AnalysisVariable.cs
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
Fix #2973 Peek definition shows duplicate entries
I ran all of AnalysisTest test class and there's no regression there.
In the navigable tests, `ParameterDefinition` test was a repro for this bug. The tests now validate all results instead of just first one, so without the fix, that test would now fail.
> Prevent duplicate results in peek definition

- Common/Product/SharedProject/Navigation/LibraryManager.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntryService.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExtractMethodSuggestedActionSourceProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs
- Python/Product/PythonTools/PythonTools/Navigation/CodeWindowManager.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSource.cs
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSourceProvider.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Tests/Core.UI/BasicProjectTests.cs
- Python/Tests/PythonToolsMockTests/PythonEditor.cs
Fixes #2976 Failed to get classifier from buffer
Fixes #2978 Unable to resolve package defined inside project
Ensures that analyzer and filename are returned from GetAnalyzer even when the file has not yet been loaded.
Fixes #2968 Failed to create entry for file
Fixes #2982 Typing in a text file causes InvalidOperationException
Uses the shared AnalysisComplete event from the analyzer rather than hooking each file individually.
> Analysis fixes

- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
Fixes #2970 Failed to get classifier from buffer in debug interactive
Adds reinitialization code for the language buffer.
> Fixes #2970 Failed to get classifier from buffer in debug interactive

- Python/Product/Debugger/DkmDebugger/ExpressionEvaluator.cs
- Python/Product/Debugger/DkmDebugger/Proxies/Structs/PyDictObject.cs
Fix #3000: C++ nodes not displaying
Use module-qualified name for PyObject when determining the object type for [C++ view] node.
Fix #3004: MMD: PyDictKeyEntry not found on 2.7
Re-add StructProxy attributes to look up PyDictEntry instead on 2.7.
> Fix #3000, #3004

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #2992 Buffer must have a project entry before parsing error
Adds additional protection against what are likely race conditions.
> Fixes #2992 Buffer must have a project entry before parsing error

- Python/Product/Analysis/LocationInfo.cs
- Python/Product/TestAdapter.Analysis/TestAdapter.Analysis.csproj
- Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs
- Python/Product/TestAdapter.Analysis/TestMethodWalker.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
Fixes #16 Tests with decorators do not appear in the test explorer view
Enhances the code path that extracts test names using analysis to also use the current AST.
> Fixes #16 Tests with decorators do not appear in the test explorer view

- Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs
Fixes #3009 Crash when analyzing invalid path
Handles exceptions when attempting to cache database paths.
> Fixes #3009 Crash when analyzing invalid path

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
- Python/Product/Analysis/Interpreter/InterpreterFactoryCreationOptions.cs
- Python/Product/Analysis/scrape_module.py
- Python/Tests/Analysis/AstAnalysisTests.cs
Fixes #3023 Failed to scrape builtins for Python 2
Updates module scraper to handle Python 2 builtins properly.
Adds tests for supported CPython versions
> Fixes #3023 Failed to scrape builtins for Python 2

- Python/Product/EnvironmentsList/PipExtension.xaml
Fixes #2969 Tabbing to "Search PyPI" text box does not give it focus
Changes style back into an actual text box to avoid multiple nested text boxes.
> Fixes #2969 Tabbing to "Search PyPI" text box does not give it focus

- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Product/VSInterpreters/StringListReader.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
- Python/Tests/VSInterpretersTests/StringListReaderTests.cs
- Python/Tests/VSInterpretersTests/VSInterpretersTests.csproj
Fixes #3010 Crash collecting output from pip
Uses a reader subclass to avoid concatenating large JSON files in memory.
Tests are still coming, but I was so pleased that this worked first time I figured I'd get the PR out so someone can tell me what I missed :)
> Fixes #3010 Crash collecting output from pip

- Python/Product/Analysis/Parsing/Ast/ComprehensionFor.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analyzer/Intellisense/ClassifierWalker.cs
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/Core.UI/FormattingUITests.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
- Python/Tests/TestData/FormattingTests/async.py
- Python/Tests/TestData/Grammar/AsyncFor.py
Fixes #1638 Support PEP 530 syntax
Adds parser support for "async for" in comprehension syntax
Add classifier support for "async" in comprehensions
Adds tests
> Fixes #1638 Support PEP 530 syntax

- Common/Tests/Utilities.UI/UI/AutomationWrapper.cs
- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
Detects open dialogs at the start of a test and closes them.
This should prevent one failed test from causing many subsequent failures.
> Detects open dialogs at the start of a test and closes them.

- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #622 Don't show tooltips for string literals
Check the expression when generating quick info to not include literal or error expressions in result
There are no regressions from this, but we still do not correctly display str/Unicode/bytes for multiline triple-quoted strings. This requires ReverseExpressionParser to do a much better job of parsing to see whether we're in a string, which is certainly not worth the churn right now.
> Fixes #622 Don't show tooltips for string literals

- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/Analysis/CompletionDBTest.cs
- Python/Tests/Analysis/DatabaseTest.cs
- Python/Tests/Analysis/MutateStdLibTest.cs
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/IpcJsonTests/IpcJsonPacketReadPythonTests.cs
- Python/Tests/ProfilingUITests/ProfilingUITests.cs
- Python/Tests/ReplWindowUITests/ReplWindowPythonTestEntryPoints.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Don't waste time running tests on Python 2.5 and 3.0 which we've decided not to support anymore.
Some of them were previously failing (Python 3.0), so removing them helps our test results.
> Remove Python 2.5 and 3.0 related tests.

- Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj
Fixes failure to create extension module template when Python is not installed
Also enables Python debugging by default
> Extension module template fixes

- Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs
- Python/Tests/Core/CPythonInterpreterTests.cs
Fix missing terminating slash when looking up directory entries inside .zip files
> Fix #2031: Cannot import subpackages from zip file

- Python/Product/Profiling/Profiling/SessionNode.cs
- Python/Product/Profiling/Strings.Designer.cs
- Python/Product/Profiling/Strings.resx
Fixes #3067 "Reports" in profiling is not localized
Moves string literal into resource.
Ideally should be ported to 3.2.1, but we need to wait for the loc team to merge their translations first.
> Fixes #3067 "Reports" in profiling is not localized

- Common/Tests/Utilities.UI/HostedPythonToolsTestRunner.cs
- Python/Tests/DebuggerUITests/VSPackage.cs
- Python/Tests/DjangoUITests/DjangoProjectUITests.cs
- Python/Tests/DjangoUITests/VSPackage.cs
- Python/Tests/ProfilingUITests/ProfilingUITests.cs
- Python/Tests/ProfilingUITests/VSPackage.cs
Django and Profiling UI tests were having issues loading dependent package assemblies.
> Add loading of dependent VS packages to UI test runner.

- Python/Product/PythonTools/PythonTools.vsct
Change 2 command names back to use Python prefix instead of Edit.
No test was using FillCommentParagraph, but I figured it was best to change it anyway. I can take it or leave it.
fix #3114
> Fix send to repl tests

- Common/Tests/Utilities/Mocks/MockServiceProvider.cs
- Python/Tests/Core/CodeFormatterTests.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs
Disables task provider in mock tests by default.
Makes MockServiceProvider properly handle lazy creation.
> Fixes non-UI tests

- Common/Tests/MockVsTests/MockCodeWindow.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
All CompletionTests were broken after #3133, this restores them and fixes 2 that were previously failing. It's down to 2 "failed to see entry finish analyzing" failures now (MemberCompletions and SignatureHelp)
> CompletionTests fixes.

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
Fix #2548 Can not goto definition
This final implementation is what I started with initially, then explored the idea of changing ReverseExpressionParser instead, but that wasn't working out.
The logic "check left and right of caret" is nicely expressed the way it is, so I feel alright about it.
I made it conditional because there are other use cases than go to definition that call `GetApplicableExpression` and I didn't want to potentially affect them.
There are no regressions in `CompletionTests` but they are as flaky as they were (run them enough times and they pass).
I did a bunch of manual testing around go to definition for identifiers around operators and such, as well as test editor/debugger tooltips and it all seems fine.
> Enable go to definition when caret is on the right of identifier

- Common/Tests/Utilities/WpfProxy.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/Core/EnvironmentListTests.cs
Attempts to make WPF proxy-based tests less likely to time out.
Protects against crashes due to corrupted registry keys
Skips some regularly failing modules when doing scrape test.
> Attempts to make WPF proxy-based tests less likely to time out.

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
> Prevent NullReferenceException when PYTHONPATH environment variable is not defined

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Repl/ReplEditFilter.cs
Fixes #2756 Escape to cancel completions also clears REPL text
Intercept Esc command and do not forward if we just closed a session.
> Fixes #2756 Escape to cancel completions also clears REPL text

- Python/Product/Analysis/Analyzer/IsInstanceScope.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #2801 Assert in ExpressionEvaluator.set_Scope
Do not nest scopes inside IsInstance scopes.
Adds test
> Fixes #2801 Assert in ExpressionEvaluator.set_Scope

- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
- Python/Product/PythonTools/PythonTools/Editor/EditorExtensions.cs
- Python/Tests/ReplWindowUITests/ReplWindowSendUITests.cs
- Python/Tests/ReplWindowUITestsRunner/ReplWindowSendUITests.cs
- Python/Tests/TestData/SendToInteractive/SelectOutput.py
- Python/Tests/TestData/SendToInteractive/SendToInteractive.pyproj
Fix #2454 
Port back some improvements that were made in RTVS so submission works even when there's selected read-only text.
> Send to REPL when prior selection in REPL

- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml.cs
- Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentView.cs
Fix #526 
Once you know how to repro, it was pretty easy to trigger the bug as it may take up to 2 secs for the detection of venv/virtualenv to finish. That's enough time to change the base interpreter combo box selection from Python 2 to Python 3, and click Create.
> Fix timing issue with creation of virtual environment

- Common/Product/SharedProject/UIThread.cs
- Common/Tests/MockVsTests/MockVs.cs
- Common/Tests/MockVsTests/MockVsTests.csproj
- Python/Product/Analysis/Values/MemberReferences.cs
- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/Analyzer/Intellisense/ProjectEntryMap.cs
- Python/Product/Ipc.Json/Connection.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSCommon/Infrastructure/UIThreadBase.cs
- Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
- Python/Tests/Core/CodeFormatterTests.cs
- Python/Tests/Core/ExtractMethodTests.cs
- Python/Tests/Core/PythonProjectTests.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/EditorTests.cs
- Python/Tests/PythonToolsMockTests/ProjectTests.cs
- Python/Tests/PythonToolsMockTests/PythonEditor.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
- Python/Tests/Utilities.Python/MockUIThread.cs
- Python/Tests/Utilities.Python/PythonProjectProcessor.cs
Fixes VsProjectAnalyzer to be created safely and awaitable on successful initialization
Changes UIThread to use JoinableTaskContext, creating one for the current thread if the global one does not exist
Change random failures due to out-of-order messages into more sensible errors when arguments are known invalid
Fixes MockVs to create everything on its UI thread and to dispose everything correctly
Disable registry watchers when container is disposed
Validates caret position in refactor rename tests
Avoid ArgumentNullException for member references with no location
> A range of threading and concurrency fixes

- Python/Product/Debugger/Debugger/DebugEngine/AD7Module.cs
- Python/Product/Debugger/Debugger/LegacyDebuggerProtocol.cs
- Python/Product/Debugger/Debugger/PythonModule.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/Ipc.Json/Connection.cs
- Python/Product/PythonTools/ptvsd/debugger.py
- Python/Product/PythonTools/ptvsd_launcher.py
Fixes #2675 Module names in the Modules debugger window are unqualified
Includes full module name when we have it
Correctly marks non-user modules
Fixes ptvsd directory not being excluded
> Fixes #2675 Module names in the Modules debugger window are unqualified

- Python/Product/PythonTools/PythonTools/Intellisense/FuzzyCompletionSet.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #2965 Error on Ctrl+space after string literal
Hardens SelectSingleBest against unexpected errors
Ensures completions are un-filtered before selecting the best for immediate completion.
Refactor FuzzyCompletionSet.Filter() into more manageable methods.
> Fixes #2965 Error on Ctrl+space after string literal

- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstBuiltinsPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstNestedPythonModuleMember.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstScrapedPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/NameLookupContext.cs
- Python/Product/Analysis/Values/FunctionInfo.cs
- Python/Product/Analysis/scrape_module.py
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
Fixes #3180 Some scraped types lie about their name
Adds quick test for numpy.ndarray to detect whether we are handling types with incorrect names
Adds list of known-bad types to scrape_module.py
Fixes "from . import module" pattern
Enhances logging during AST analysis
Enhances handling of common expression types during value lookup
> Fixes #3180 Some scraped types lie about their name

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Interpreter/Ast/AstNestedPythonModuleMember.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonBoundMethod.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonConstant.cs
- Python/Product/Analysis/Interpreter/IPythonFunction.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/Analysis/Values/BoundBuiltinMethodInfo.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/TestData/AstAnalysis/InstanceMethod.py
Fixes #3027 No IntelliSense info for instance method "pointers"
Enables member lookup via AstPythonConstant
Fixes recursion in lazy members
Fixes bound method info not displaying correctly
Updates tests
> Fixes #3027 No IntelliSense info for instance method "pointers"

- Python/Product/PythonTools/PythonToolsPackage.cs
Fix #3176 
In launch script (PythonToolsPackage.LaunchFile), match the exception handling that's used in launch project (PythonProjectConfig.DebugLaunch)
> Handle missing interpreter when launching with script

- Python/Product/Analysis/Analyzer/ClassScope.cs
- Python/Product/Analysis/Analyzer/FunctionScope.cs
- Python/Product/Analysis/Analyzer/InterpreterScope.cs
- Python/Product/Analysis/Analyzer/IsInstanceScope.cs
- Python/Product/Analysis/Analyzer/StatementScope.cs
- Python/Product/Analysis/ExpressionFinder.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Parsing/Ast/PythonAst.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/SourceLocation.cs
- Python/Product/Analysis/Parsing/SourceSpan.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/ImportRemover.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExpressionAtPoint.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
- Python/Product/PythonTools/PythonTools/Intellisense/UnresolvedImportSquiggleProvider.cs
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSource.cs
- Python/Product/PythonTools/PythonTools/PythonClassifier.cs
- Python/Tests/Analysis/ExpressionFinderTests.cs
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
Fixes #2869 Go to definition fails for named argument
Enable GTD for argument names.
Fixes bug in FindScopes where we were selecting function scopes incorrectly.
> Fixes #2869 Go to definition fails for named argument

- Python/Product/Cookiecutter/Shared/Interpreters/PythonLanguageVersion.cs
I kept getting exceptions on startup during environment discovery.
The code in python.h that's supposed to be in sync with this class had already been updated.
> Update PythonLanguageVersion for Python 3.7.

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonSequence.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonTuple.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonType.cs
- Python/Product/Analysis/Interpreter/Ast/NameLookupContext.cs
- Python/Product/PythonTools/PythonTools/Navigation/TextViewFilter.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
Fixes #3076 Some tests do not appear
Adds correct MRO to scraped analysis types.
Fixes handling of multiple definitions of the same class
Fixes minor crash when tool tips time out.
Fixes #3211 GetTypeFromValue() doesn't handle AstPythonBoundMethod type 
Adds IPythonBoundFunction handling
> Fixes #3076 Some tests do not appear

- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/PythonClassifier.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/ReplEditFilter.cs
- Python/Tests/ReplWindowUITests/ReplWindowUITests.cs
- Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs
- Python/Tests/ReplWindowUITestsRunner/ReplWindowBasicUITests.cs
Fixes #2488 Pasting into the REPL triggers immediate execution
Simplify semantics of paste to:
* when REPL buffer is not empty, never submit
* otherwise, submit all except the last statement, unless the source text ends with a newline (when multiline is supported, the whole buffer is "the last statement")
Fixes #2682 REPL comments handling different from command line Python
Exposes reason for being able to execute text so that we can better handle Empty statements
Re-enables tests
Also fixes submitting updates to analyzer to avoid incorrect validation.
> Fixes #2488 and #2682

- Python/Product/Analysis/Projects/PythonProject.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/TestAdapter/TestContainerDiscoverer.cs
Fixes #3024 GetAnalyzer() called on closed project assert
Enhances PythonProject API to allow null return
> Fixes #3024 GetAnalyzer() called on closed project assert

- Common/Product/SharedProject/ProjectNode.CopyPaste.cs
- Common/Tests/Utilities.UI/UI/SolutionExplorerTree.cs
- Python/Tests/ProjectUITests/DragDropCopyCutPaste.cs
- Python/Tests/ProjectUITestsRunner/DragDropCopyCutPaste.cs
Fix #3225 
Also fixes cut/paste from Python to C#, where the file wasn't deleted in source Python project after paste was done.
Adjustments to the long file name tests where msbuild was refusing to load the project due to the project file path being too long (so I've made it slightly shorter and increased the length of the files within the project to get the same result).
Both sets of drag & drop tests are all passing.
> Project system cut and paste fixes

- Python/Product/PythonTools/PythonTools/TokenCache.cs
Fixes #3243 Mismatched line number assert while editing
Removes assertion, as it is triggering when it should not.
> Fixes #3243 Mismatched line number assert while editing

- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
Fixes #3099 Assert when starting VS with REPL visible
Filters out REPL settings that have not been saved correctly.
> Fixes #3099 Assert when starting VS with REPL visible

- Python/Product/Analysis/Parsing/Ast/PythonAst.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7MemoryAddress.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7StackFrame.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLanguageInfo.cs
Enables full line highlighting for breakpoints and call stack locations.
Prevents setting breakpoints on empty lines.
Make LocationToIndex and IndexToLocation functions public
Make LocationToIndex deliberately support columns well beyond the line length.
The LocationToIndex and IndexToLocation functions were always meant to become public - it's the only reliable way to translate between the two formats.
> Enables full line highlighting for breakpoints and call stack locations.

- Python/Product/PythonTools/ptvsd/debugger.py
- Python/Product/PythonTools/ptvsd_launcher.py
- Python/Tests/DebuggerTests/DebuggerTests.cs
Don't add the ptvsd_launcher.py parent folder to the PREFIXES array of standard library folders. The ptvsd files are already in the DONT_DEBUG array of files to never debug.
> Fix debugger test failures

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/SearchPathManager.cs
- Python/Tests/Core.UI/BasicProjectTests.cs
- Python/Tests/PythonToolsUITestsRunner/BasicProjectTests.cs
Fixes #3269 Changes in search paths are not automatically noticed by the analyzer
Adds file watcher for search paths in the IDE. The notifications flow into the analyzer and cause it to rescan search paths as necessary.
> Fixes #3269 Changes in search paths are not automatically noticed by the analyzer

- Python/Product/Debugger/Debugger/PythonProcess.cs
Fix https://github.com/Microsoft/PTVS/issues/3252
Fix https://github.com/Microsoft/PTVS/issues/3251 (not sure how, but I've gone back and forth several times and the bug no longer occurs with this fix)
Edit: For 3251 it's probably because of the following code where `os.error` ended up with a space:
```
def isdir(s):
"""Return true if the pathname refers to an existing directory."""
try:
st = os.stat(s)
except os.error:
return False
return stat.S_ISDIR(st.st_mode)
```
> Ensure that exception type names don't have any pre/post whitespace.

- Python/Product/Cookiecutter/Shared/Interpreters/PythonRegistrySearch.cs
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntryService.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluatorProvider.cs
- Python/Product/VSInterpreters/PythonRegistrySearch.cs
Fixes #3264 NullReferenceException in GetExpressionSpanAtPointAsync_BypassTelemetry
Adds missing null check in caller.
Adds ArgumentNullException to callee.
Fixes #3250 Null reference in PythonRegistrySearch.Search
Checks for null results from GetSubKeys
Extends wait times between attempts to get subkeys
Ports fixes to cookiecutter
Fixes #3249 Threading issue in PythonCommonInteractiveEvaluator.GetScriptsPath
Ensures calls come from the UI thread.
Fixes #2065 Assert on completions when REPL env is unknown
Fixes #1788 Failed to get project entry for buffer error in debug repl
Ensures REPL properly handles the "no analyzer" case, which fixes multiple issues.
Fixes newlines in debug REPL errors
For #2953, enables returning locals
> Fix a number of P0 issues

- Python/Product/Debugger/Debugger/DebugConnection.cs
- Python/Product/Debugger/Debugger/DebugConnectionListener.cs
- Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugPort.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugPortSupplier.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugProcess.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteProcess.cs
- Python/Product/Debugger/Debugger/PythonDebugger.cs
- Python/Product/Debugger/Debugger/PythonProcess.cs
- Python/Product/Ipc.Json/Connection.cs
- Python/Product/Ipc.Json/DebugTextWriter.cs
- Python/Product/Ipc.Json/Ipc.Json.csproj
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
- Python/Tests/DebuggerTests/DebugExtensions.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
Capture output and only print it if there's a test failure.
This eliminates most output from attach tests and debugger tests.
I can do something similar (separately) for analysis tests if this looks ok.
> Reduce the amount of text in test output

- Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs
- Python/Product/Analyzer/PyLibAnalyzer.cs
- Python/Tests/Analysis/CompletionDBTest.cs
Copied parts of our existing AssertListener (test framework parts removed since we can't access them from here)
> Prevent assertion dialogs from appearing during test runs

- Python/Product/Analysis/Parsing/Ast/GlobalStatement.cs
- Python/Product/Analysis/Parsing/Ast/NonlocalStatement.cs
- Python/Tests/Analysis/ExpressionFinderTests.cs
> Fixes nonlocal and global names not being resolved for refactor-rename.

- Python/Product/PythonTools/PythonTools/Intellisense/CodeCellAnalysis.cs
- Python/Tests/Core/CodeCellTests.cs
Fixes #2450 Ctrl+Enter on empty cell fails to step forward
Fixes early-exits from search loops finding cell extents.
> Fixes #2450 Ctrl+Enter on empty cell fails to step forward

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #1245 Renaming decorators does not always work
Ensures references are added to decorators applied to classes.
> Fixes #1245 Renaming decorators does not always work

- Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
Fix #3331 : removing the line where the NRE occurred. The result of that check is never used.
Testing this process out with a NRE fix.
> NRE in SendToReplCommand

- Python/Product/Analysis/AnalysisUnit.cs
- Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
- Python/Product/Analysis/EncodedLocation.cs
- Python/Product/Analysis/ILocationResolver.cs
- Python/Product/Analysis/LocationInfo.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #499 Out of memory while editing
Prevents CalledFunctionAnalysisUnit being used as location resolvers.
> Fixes #499 Out of memory while editing

- Python/Product/Analysis/AnalysisUnit.cs
- Python/Product/Analysis/Analyzer/DependencyInfo.cs
- Python/Product/Analysis/Values/ClassInfo.cs
- Python/Product/Analysis/Values/FunctionInfo.cs
- Python/Product/Analysis/Values/IteratorInfo.cs
- Python/Product/Analysis/Values/PartialFunctionInfo.cs
- Python/Product/Analysis/Values/SuperInfo.cs
- Python/Tests/Analysis/AnalysisTest.cs
Work towards #3298
Improves memory usage by better clearing out old values.
Fixes some values that were not managing their version properly.
Ensures correct MRO references are created.
This is certainly not all of the leakage we can see in #3298, but it looks like a lot of it. I'll leave that bug open as we continue working through reductions.
> Reducing memory leaks

- Python/Product/Analysis/Interpreter/IPackageManager.cs
- Python/Product/Analysis/Interpreter/NoPackageManager.cs
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/EnvironmentsList/PipExtension.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml.cs
- Python/Product/EnvironmentsList/PipExtensionProvider.cs
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
- Python/Product/PythonTools/PythonTools/Options/ExperimentalOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.resx
- Python/Product/VSInterpreters/CondaEnvironmentFactoryConstants.cs
- Python/Product/VSInterpreters/CondaEnvironmentFactoryProvider.cs
- Python/Product/VSInterpreters/CondaPackageManager.cs
- Python/Product/VSInterpreters/CondaUtils.cs
- Python/Product/VSInterpreters/ExperimentalOptions.cs
- Python/Product/VSInterpreters/PipPackageManager.cs
- Python/Product/VSInterpreters/PythonInterpreterInformation.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
- Python/Tests/Core/EnvironmentListTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
- Python/Tests/Utilities.Python/MockPackageManager.cs
I broke out of bug jail for a few hours to bring this up to date and have it disabled by default using experimental options registry keys.
- If a global Anaconda installation is found, it uses it to automatically detect Conda environments.
- When conda is available for an environment, it uses it as the package manager.
There are some TODOs that explain what remains to be done, as well as potential upcoming changes to conda that will require some work on our part (our contact will let us know about them when ready).
I had to make some changes to the package manager interfaces and UI in order to make it more generic (remove any reference to PyPI). Hopefully they don't break anything, since that's not behind the experimental flags.
I hadn't gotten to this yet, but I wanted to make it so that …
> Experimental conda support

- Python/Product/Analysis/Analyzer/FunctionScope.cs
- Python/Product/Analysis/ExpressionFinder.cs
- Python/Product/Analysis/Parsing/Ast/ErrorParameter.cs
- Python/Product/Analysis/Parsing/Ast/Parameter.cs
- Python/Product/Analysis/Parsing/Ast/SublistParameter.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/Analyzer/Intellisense/ExtractedMethodCreator.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Refactoring/VariableRenamer.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/ExpressionFinderTests.cs
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs
- Python/Tests/TestData/Grammar/FuncDefTrailingComma.py
Fixes #1645 Cannot parse trailing commas in function definitions
Rewrites function definition parser to be more reliable. We now parse all syntax valid in any version and then raise errors later.
Fixes formatting/round-trip of parameters.
Fixes finding variables to rename.
Ensures more error messages are returned from analyzer initialization.
> Fixes #1645 Cannot parse trailing commas in function definitions

- Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs
Forward port of the 3.2.1 fix.
> Avoid null reference errors when opening XAML files.

- Python/Tests/IpcJsonTests/IpcJsonConnectionTests.cs
- Python/Tests/IpcJsonTests/IpcJsonTests.csproj
This ought to be enough to prevent our test runs from timing out due to that VSTest bug.
> Fixes IPC tests to prevent lingering processes.

- Python/Product/PythonTools/PythonTools/Navigation/Peek/PythonPeekResultSource.cs
Remove peek definition workaround that was put in place so that promote to document functionality opens with the Python editor. No longer needed now that we register the Python editor/file extension for peek (Steve added the registration in a PR last week).
> Remove peek definition workaround

- Python/Product/IronPython/Interpreter/IronPythonInterpreterFactory.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
In IronPython 2.7.8, we will be changing the file names for the 32-bit specific and Any CPU executables. ipy.exe will now be Any CPU and ipy32.exe will be the 32-bit (x86) executable. This is to make the Any CPU the default build.
> Update executable name for IronPython 2.7.8 and above.

- Common/Tests/MockVsTests/MockVs.cs
- Common/Tests/MockVsTests/MockVsTestExtensions.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonMultipleMembers.cs
- Python/Product/Analysis/Interpreter/PythonMemberType.cs
- Python/Product/Analysis/MemberResult.cs
- Python/Product/Analysis/Parsing/Ast/FunctionDefinition.cs
- Python/Product/Analysis/Parsing/Ast/LambdaExpression.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Values/InstanceInfo.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageCache.cs
- Python/Tests/Analysis/AnalysisSaveTest.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/ParserRoundTripTest.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonAnalysis.cs
Fixes #3421 Analysis can't keep up
Fixes correction of source location for getting completions.
Fixes #679 Named arguments in completion list should be visually different from other items
Adds trailing '=' to parameter name completions.
Fixes a few test failures and round-trip problems.
> Fixes correction of source location for getting completions.

- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Fix #3431
Trim the quotes from the File.OpenProject command arguments before passing it to an API that expects a file path.
> Fix cookiecutter add to solution failure

- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/IronPython/Debugger/IronPythonLauncher.cs
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonTools/Debugger/NoStartupFileException.cs
- Python/Product/PythonTools/PythonTools/Project/DefaultPythonLauncher.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectConfig.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs
- Python/Product/Wsl/Debugger/WslLauncher.cs
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
Fix #3434 
I had previously fixed this but only for the default launcher and didn't realize that some of the others, like web launcher, were still broken.
Slightly improve the error message when the startup file is set but the file doesn't exist.
> Fix launch when startup file is missing or not set

- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Tests/Analysis/ParserTests.cs
Fixes #3338 Tokenizer mishandles grouping recovery
Ensures leading whitespace is restored when recovering from an invalid grouping.
> Fixes #3338 Tokenizer mishandles grouping recovery

- Python/Product/TestAdapter/TestContainerDiscoverer.cs
Fixes #3450 No UIThread service but shell is not shutting down
Replaces UIThread service with ThreadHelper (since we should never be using this class outside of VS)
> Fixes #3450 No UIThread service but shell is not shutting down

- Python/Product/Analysis/MemberResult.cs
- Python/Product/Analysis/Values/BoundMethodInfo.cs
- Python/Product/Analysis/Values/FunctionInfo.cs
- Python/Product/Common/Infrastructure/EnumerableExtensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSignature.cs
Fixes #3456 Parameter info does not include types
Improves generation of bound method signatures to preserve information from the underlying function.
Fixes #3453 Duplication in help strings when documentation string is present
Skips adding additional type label when only one value is present.
Also improves selection of signature parameter.
> Signature help improvements

- Python/Product/Django/Intellisense/TemplateTextViewConnectionListener.cs
Fixes #3467 Incorrectly exported TemplateTextViewConnectionListener
Updates exports for text view connection listener.
As a transitional step, explicitly implements the interfaces to ensure correct behaviour on current builds.
> Fixes #3467 Incorrectly exported TemplateTextViewConnectionListener

- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Fixes #3460 PTVS crash in 15.6 preview
Ensures buffer.Filename is never null.
> Fixes #3460 PTVS crash in 15.6 preview

- Python/Product/PythonTools/ptvsd/debugger.py
Fix #3475 
This was causing really bad performance and 1000s of warnings to be displayed during import of pandas/numpy/matplotlib.
Updated the check so that it's no longer incorrectly displaying for non-user code, and so it doesn't display it more than once per thread.
> Stop warning the user that breakpoints are disabled while importing stdlib

- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.resx
> Fix typo and tab order in Python general options page

- Python/Product/Analysis/QualifiedFunctionNameWalker.cs
- Python/Product/Debugger/Debugger/PythonStackFrame.cs
- Python/Product/TestAdapter/PythonStackTraceParser.cs
Fix #3508 
DebugProjectUITests and TestExecutorTests all pass.
See commit description for details.
> Fix debugger and test explorer qualified function names

- Python/Product/IronPython/IronPythonPipPackageManagerProvider.cs
- Python/Product/VSInterpreters/PackageManager/CPythonPipPackageManagerProvider.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageManager.cs
Fix #3555 
Reverts to the old logic prior to package manager refactor.
Install from requirements sends a PackageSpec with FullSpec set to `-r requirements.txt`, which produced a full arguments list:
`-m pip install -U "-r requirements.txt"`
instead of the expected:
`-m pip install -U -r requirements.txt`.
> Fix quoting of arguments for pip install

- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
- Python/Product/Cookiecutter/Model/CookiecutterClientProvider.cs
- Python/Product/Cookiecutter/Model/CookiecutterPythonInterpreter.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
Fix #3485 
When selecting a Python interpreter for use with cookiecutter, prefer CPython over others.
When creating a virtual environment fails, try again using --without-pip option (workaround for Anaconda), then install pip.
Delete the virtual environment folder before creating a new one, to ensure that broken virtual environments are repaired (such as when the base environment was removed/moved).
Also, send all output from environment creation and installation of packages to output window to help diagnose future issues.
> Cookiecutter virtual environment creation fixes

- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
Fixes #3572 LocationTracker.GetLineLocations error
Avoids incrementing line number eagerly.
> Fixes #3572 LocationTracker.GetLineLocations error

- Python/Product/Analysis/LanguageServer/ParseQueue.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/Analysis/ProjectEntry.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/Analyzer/PyLibAnalyzer.cs
- Python/Product/Ipc.Json/Connection.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Analysis/AnalysisTest.Perf.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/BaseAnalysisTest.cs
- Python/Tests/Analysis/ThreadingTest.cs
- Python/Tests/Core.UI/EditorTests.cs
- Python/Tests/Core/LocationTrackerTests.cs
- Python/Tests/DjangoTests/DjangoAnalyzerTests.cs
- Python/Tests/IronPython/IronPythonAnalysisTest.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/Utilities.Python.Analysis/MockPythonProjectEntry.cs
- Python/Tests/Utilities.Python.Analysis/PythonAnalysis.cs
Currently, this fixes multiple parses being started simultaneously for the same document. I still need to verify that this was the underlying cause, but it's not too early to start reviewing this.
In short, the problem we had before is that `ConcurrentDictionary.AddOrUpdate` does not guarantee that it will only call one of the factory functions, so we could end up with two parsers for the one counter increment, as well as two conflicting results that _may_ have been causing incorrect responses and hence comparisons leading to the assertion.
> Fixes #3570 Buffer mismatches

- Python/Product/Analysis/Intellisense/ClassifierWalker.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSignature.cs
Fixes #3603 Error after using snippet
Ensures the correct line length is used to calculate newlines after a deletion
Also fixes an unnecessary assertion and incorrect argument highlighting.
> Fixes #3603 Error after using snippet

- Python/Product/Analysis/Parsing/Ast/TypeAnnotation.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #3604 Analyzer stops responding
Handles incomplete type annotations that were previously causing the analyzer to crash.
Adds registry key to enable trace logging, currently only to the Trace system.
> Fixes #3604 Analyzer stops responding

- Python/Product/Debugger/DebugAdapterProcess.cs
- Python/Product/Debugger/DebugAdapterProcessStream.cs
- Python/Product/Debugger/Debugger.csproj
Fixes #3537
This is partial fix because there is a change needed in VSC debugger where we fire `exitedEvent` with correct error code on program exit.
> Partial fix to the error message after program exit with VSC debugger

- Python/Product/Analysis/Intellisense/LineInfo.cs
- Python/Product/Analysis/Intellisense/LinePreservingCodeReplacer.cs
- Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Core/CodeFormatterTests.cs
- Python/Tests/Core/ExtractMethodTests.cs
Fixes #3634 Buffer synchronization issue after deleting block of text
Reverses order of changes when doing line length calculation.
(Includes changes from #3632 to help repro - the one word fix for this issue is [here](https://github.com/Microsoft/PTVS/pull/3642/commits/1bb8989e5be471df14b875e704a0ce8925c05057))
> Fixes #3634 Buffer synchronization issue after deleting block of text

- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs
- Python/Product/Analysis/Analyzer/ExpressionEvaluatorAnnotationConverter.cs
- Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
- Python/Product/Analysis/Analyzer/InterpreterScope.cs
- Python/Product/Analysis/Intellisense/ClassifierWalker.cs
- Python/Product/Analysis/Parsing/Ast/TypeAnnotation.cs
- Python/Product/Analysis/Values/ProtocolInfo.cs
- Python/Product/Analysis/Values/Protocols.cs
- Python/Product/Analysis/Values/TypingTypeInfo.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/TypeAnnotationTests.cs
Fixes #3646 Assertion on nested sequences in type annotation
Switches type annotation evaluations from real types to ProtocolInfo instances
Also fixes generator evaluation
This means we don't have to be as careful about minimizing instantiation, as the values will be fully recreated when we re-evaluate the annotation. So we can dispense with the node value storage completely and just store the entire evaluated annotation.
> Fixes #3646 Assertion on nested sequences in type annotation

- Common/Product/SharedProject/ProjectNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fixes #3630 Error after completing import wizard
Reduces likelihood of a race condition when setting a new ProjectHome
Avoids code path leading to error dialog.
> Fixes #3630 Error after completing import wizard

- Python/Product/Common/Infrastructure/StringExtensions.cs
- Python/Product/Django/TemplateParsing/TemplateArtifactCollection.cs
One `IndexOfOrdinal` in Django was passing in a count but we didn't have that overload.
`newText` is `ITextProvider`, not a `string`, I've reverted back to how it was before.
> Fix build.

- Python/Product/Analysis/Analyzer/ExpressionEvaluatorAnnotationConverter.cs
- Python/Product/Analysis/Values/TypingTypeInfo.cs
- Python/Tests/Analysis/TypeAnnotationTests.cs
Fixes #3667 Handle string literals in type annotations later
Defers name lookup as late as possible for type annotations so that names are not misinterpreted as forward references.
> Fixes #3667 Handle string literals in type annotations later

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fix #3696 
I checked that we don't want to proceed with a null entry, the server will throw invalid operation if it gets a null document uri.
Calling code already knows how to deal with GetQuickInfoAsync returning null.
> Protect against possible null AnalysisEntry in GetQuickInfoAsync.

- Python/Product/PythonTools/PythonTools/Debugger/ProvideDebugAdapterAttrributes.cs
Implements #3620
I am reusing the registrations that we do for the current debug engine.
> Adding existing exception settings registrations to debug adapter

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Tests/Core/CondaInterpreterFactoryTests.cs
- Python/Tests/Core/PythonToolsTests.csproj
Fix #3659 Create conda environment doesn't appear in list after creation for the first ever created env
If the `.conda` folder doesn't exist, we can't setup a watcher on that folder, so we create one for the parent folder (which is the user home folder) and when we get notification that `.conda` is created, we then start watching that folder.
> Conda environment detection fix

- Python/Product/Analysis/IHasRichDescription.cs
- Python/Product/Analysis/Values/ConstantInfo.cs
- Python/Product/Analysis/Values/ProtocolInfo.cs
- Python/Product/Analysis/Values/Protocols.cs
- Python/Product/Analysis/Values/TypingTypeInfo.cs
- Python/Tests/Analysis/TypeAnnotationTests.cs
Fixes #3706 Type hint isn't properly recognized for complex types
Fixes handling of tuple type annotation
Improves handling of protocol object descriptions
Improves unary operation on numeric literals.
> Fixes #3706 Type hint isn't properly recognized for complex types

- Python/Product/Analysis/ProjectEntry.cs
- Python/Product/PythonTools/PythonTools/Navigation/WaitForCompleteAnalysisDialog.xaml.cs
Fixes #3719 NullReferenceException in ProjectEntry.RemovedFromProject
Protects aggregates hashset under lock and safely handles unexpected null elements
Fixes #3720 Unhandled dispatcher cancellation when waiting for analysis
Handles cancellation error.
> Fixes #3719 and #3720

- Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs
Fixes #3722 REPL indent is not calculated properly
Maps back to correct line location to properly handle variable length REPL prompts.
Validates final return value and adds assertions in debug builds to help detect these cases.
> Fixes #3722 REPL indent is not calculated properly

- Common/Tests/Utilities.UI/HostedPythonToolsTestRunner.cs
- Common/Tests/Utilities/Ben.Demystifier/ILReader.cs
- Common/Tests/Utilities/Ben.Demystifier/StringBuilderExtensions.cs
- Common/Tests/Utilities/Ben.Demystifier/TypeNameHelper.cs
- Common/Tests/Utilities/Ben.Demystifier/readme.txt
- Common/Tests/Utilities/MSTestEnvironment.cs
- Common/Tests/Utilities/TaskObserver.cs
- Common/Tests/Utilities/TestEnvironment.cs
- Common/Tests/Utilities/TestUtilities.csproj
- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Infrastructure/ITestEnvironment.cs
- Python/Product/Analysis/Infrastructure/TaskExtensions.cs
- Python/Product/Analysis/Infrastructure/TestEnvironment.cs
- Python/Product/Common/Common.csproj
- Python/Product/Common/Infrastructure/ITestEnvironment.cs
- Python/Product/Common/Infrastructure/TaskExtensions.cs
- Python/Product/Common/Infrastructure/TestEnvironment.cs
- Python/Tests/Core.UI/VSPackage.cs
- Python/Tests/Core/AssemblySetup.cs
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/DebuggerUITests/VSPackage.cs
- Python/Tests/DjangoUITests/VSPackage.cs
- Python/Tests/ProfilingUITests/VSPackage.cs
- Python/Tests/ReplWindowUITests/VSPackage.cs
- Python/Tests/Utilities.Python.Analysis/MSTestEnvironment.cs
- Python/Tests/Utilities.Python.Analysis/TestUtilities.Python.Analysis.csproj
This approach helps tests catch exceptions in tasks that aren't awaited or run too for long.
For example, imagine the following code:
```cs
public void Run() {
RunThenFailAsync().DoNotWait();
RunForeverAsync().DoNotWait();
}
private async Task RunThenFailAsync() {
await Task.Delay(1000);
throw new InvalidOperationException();
}
private async Task RunForeverAsync() {
while (true) {
await Task.Delay(500);
}
}
```
If we create a simple test for it, it will successfully pass:
```cs
[TestMethod]
public void SomeTypeTest() {
new SomeType().Run();
}
```
But, with `TaskObserver` enabled:
```cs
[TestInitialize]
public void Initialize() => MSTestEnvironment.TestInitialize(5);
[TestCleanup]
public void Cleanup() => MSTestEnvironment.TestCleanup();
[TestMethod]
public void SomeTypeTest() {
new …
```
> Port TaskObserver into PTVS

- Python/Tests/DebuggerUITests/DebuggerUITests.csproj
- Python/Tests/DebuggerUITests/MixedModeDebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebuggerUITestsRunner.csproj
- Python/Tests/DebuggerUITestsRunner/MixedModeDebugProjectUITests.cs
- Python/Tests/TestData/MixedModeHelloWorld.sln
- Python/Tests/TestData/MixedModeHelloWorld/MixedModeHelloWorld.pyproj
- Python/Tests/TestData/MixedModeHelloWorld/Program.py
Fix #3713 
This is sufficient to catch the regression with 64-bit mixed-mode debugging.
We can add more later, for example a test that involves C++ code ;)
> Add UI test for mixed-mode debugger.

- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Fix #3761: Parser with Verbatim=false throws assert for function definition
- Cache field value in Tokenizer.Peek (+3%)
- Optimize IsIdentifierChar for Latin1 case (+7%)
> Fix #3761 & some more perf turning

- Python/Product/Cookiecutter/Model/GitHubClient.cs
- Python/Product/Cookiecutter/Model/GitHubTemplateSource.cs
Fix #3785 cookiecutter crash parsing invalid JSON
> Fix crash in cookiecutter due to unhandled JsonException.

- Common/Product/SharedProject/CommonPackage.cs
- Common/Product/SharedProject/Navigation/LibraryManager.cs
- Common/Product/SharedProject/ProjectReferenceNode.cs
- Common/Product/SharedProject/VsExtensions.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs
- Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryNode.cs
Fix #2411 Assert clicking on Output in Test Results
Fix #3787 COMException opening XAML editor
Most callers were handling a `null` return value, only one was handling exception and `null`, and some were handling neither. I changed them to all handle `null`. I also removed the assert because in some cases it's normal that there's no project (test explorer output window).
> Change GetProject() to always return null in case of failure

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
- Read from .version instead of calling conda -V when trying to determine which global conda.exe is the latest
- Do some parallel environment creation (instead of serially calling python.exe for each environment)
Fix #3540 
Timing of complete discovery of all conda environments varies quite a bit from run to run, but it seems to be slightly better on average (for me by about 1 sec)
As far as fixed cost of finding which global conda.exe to use, I don't know that it's worth doing a lot more than this (like caching results), especially if we plan on having a private conda at some point.
> Small optimizations for conda discovery

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/AnalysisLogWriter.cs
- Python/Product/Analysis/ExpressionFinder.cs
- Python/Product/Analysis/IHasQualifiedName.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/LanguageServer/Structures.cs
- Python/Product/Analysis/MemberResult.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Parsing/Ast/CallExpression.cs
- Python/Product/Analysis/Parsing/Ast/FunctionDefinition.cs
- Python/Product/Analysis/Parsing/Ast/LambdaExpression.cs
- Python/Product/Analysis/Parsing/CodeFormattingOptions.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/ParserOptions.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/Analysis/Values/BoundMethodInfo.cs
- Python/Product/Analysis/Values/BuiltinClassInfo.cs
- Python/Product/Analysis/Values/ClassInfo.cs
- Python/Product/Analysis/Values/FunctionInfo.cs
- Python/Product/Analysis/VariablesResult.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExpressionAtPoint.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/ExpressionFinderTests.cs
- Python/Tests/Analysis/LanguageServerTests.cs
- Python/Tests/Analysis/ParserTests.cs
Fixes #3793 Migrate hover to server
Implements the Hover() command on server
Also disables verbatim parsing by default, as it was interfering with tests. Some work for lambda was required to restore the previous behaviour.
> Fixes #3793 Migrate hover to server

- Common/Product/SharedProject/CommonFileNode.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/PythonNonCodeFileNode.cs
- Python/Product/VSCommon/Infrastructure/IXamlDesignerSupport.cs
- Python/Product/XamlDesignerSupport/WpfEventBindingProvider.cs
Fixes #3791 Error adding WPF event handler using XAML designer
Ensures document is open before adding handler
Skip finding AnalysisEntry on newly opened buffer
> Fixes #3791 Error adding WPF event handler using XAML designer

- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Fixes #3816 Deleting conda environment output has too many newlines
Adds trim code like we use elsewhere
> Fixes #3816 Deleting conda environment output has too many newlines

- Common/Product/SharedProject/UIThread.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Fixes #3786 OOM adding text to the repl
Ensures our search for color codes always makes forward progress.
Improves handling of debug assertions when in a context that doesn't handle dialogs well.
> Fixes #3786 OOM adding text to the repl

- Python/Product/VCDebugLauncher/source.extension.vsixmanifest
Fixes #3841 15.6 broke mixed mode debugging
Updates version of the VCDebugLauncher package to ensure the newer build is installed.
For the forward-port we should update all VSIX versions to 15.7
> Fixes #3841 15.6 broke mixed mode debugging.

- Python/Product/Cookiecutter/source.extension.vsixmanifest
- Python/Product/Core/source.extension.vsixmanifest
- Python/Product/Django/source.extension.vsixmanifest
- Python/Product/IronPython/source.extension.vsixmanifest
- Python/Product/Profiling/source.extension.vsixmanifest
- Python/Product/Uwp/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/source.extension.vsixmanifest
- Python/Product/Wsl/source.extension.vsixmanifest
Updates all VSIX version numbers to 15.7.0 for next release.
Note that most of these are not used, but for the ones that are, it is essential for some to ensure they are installed.
> Updates all VSIX version numbers to 15.7.0 for next release.

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fixes #3826 Fails to unload file with null property
Validates path and URI properties before treating them as keys.
> Fixes #3826 Fails to unload file with null property

- Python/Product/Debugger/Debugger/DebugConnection.cs
Fix #3788 
Ideally we'd have a more localized fix where the InvalidOperationException is thrown, but we don't know where that is.
The other thread proc (EventHandlingThread) also catches all and asserts, so I guess it's not so bad to do here too.
Fortunately this whole class will go away soon enough.
> Prevent crash in MessageProcessingThreadAsync.

- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.cs
Fix #3784 
Hiding the control is sufficient, the table is smart enough to move everything up so there's no gap.
> Hide the Automatically generate completion DB on first use option

- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Fixes #3835 Start and End must be well ordered
Verifies AST spans are at least one character long before returning as navigation locations.
> Fixes #3835 Start and End must be well ordered

- Python/Templates/IronPython/ProjectTemplates/Python/WpfProject/WpfApp.pyproj
It seems that in Visual Studio 2017 I need to explicitly add PresentationFramework 4.0.0.0 as a reference to Python projects to display the UI in the editor window and get IntelliSense working in XAML.
#2943
> Fix display of UI and IntelliSense in Visual Studio 2017

- Python/Product/Debugger/DebugAdapterProcess.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Product/PythonTools/ptvsd_launcher.py
- Python/Product/VSInterpreters/Interpreter/ExperimentalOptions.cs
Fixes #3536 VS code debugger installation
Embeds the latest release of ptvsd into the bundle.
This needs to be changed at some point to lock to a specific release, but as the only available release right now is not suitable for embedding.
> Fixes #3536 VS code debugger installation

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Fixes #3883 Database check not triggered assert
Ensures IsCurrent check is triggered when creating conda environment factories.
> Fixes #3883 Database check not triggered assert

- Python/Product/PythonTools/PythonTools/Editor/BraceMatcher.cs
Fixes #3915 IndexOutOfRangeException from BraceMatcher
Raise correct error when `brace` string is empty.
> Fixes #3915 IndexOutOfRangeException from BraceMatcher

- Python/Product/Analysis/Infrastructure/EnumerableExtensions.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSource.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/LanguageServerTests.cs
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
Fixes #3919 Imported modules do not allow go to definition
Attempt to read local path from documentUri if file path is missing
Return class/function and external values as definitions rather than values
> Fixes #3919 Imported modules do not allow go to definition

- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/PipExtension.xaml.cs
- Python/Product/EnvironmentsList/ToolWindow.xaml.cs
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Fix https://github.com/Microsoft/PTVS/issues/3905
Stop initializing all extensions for all environments on window startup. Extensions are now initialized as needed, when an environment is selected the first time.
There were 2 difficulties, which have been resolved.
A. Install package from solution explorer brings up the package manager extension and sets focus to the search box. Before when everything was initialized early, that worked fine but now that everything is delayed it was trying to focus on the text box before the package manager was 'ready' ie the textbox was disabled.
B. When pip extension was selected from drop down and you clicked a different environment, it was skipping the refresh packages because its state wasn't ready yet, so no packages appeared and it never attempted …
> Improve environments window startup time

- Python/Product/TestAdapter/PythonRunSettings.cs
> Ensure that GetLaunchConfigurationOrThrow() is called from the UI thread in test adapter.

- Python/Product/TestAdapter/TestContainerDiscoverer.cs
Fix #3637 A test with the same name already exists warning
> Avoid pending analysis of the same file multiple times during test discovery

- Python/Product/TestAdapter/TestContainerDiscoverer.cs
Previous fix (https://github.com/Microsoft/PTVS/pull/3979) was breaking the pending/submit mechanism.
Fix #3992 Too many test discoveries
> Fix duplicate test discovery again 

- Python/Product/ProjectWizards/AzureDebugWebConfigWizard.cs
Fix #3997 Azure debug template puts WebRole in wrong location
> Add the webrole dll to the project bin folder.

- Common/Product/SharedProject/FolderNode.cs
- Python/Tests/Core.UI/BasicProjectTests.cs
- Python/Tests/PythonToolsUITestsRunner/BasicProjectTests.cs
Fix #4011
I ran all of our project system related tests that could potentially be affected. There are some failures, but nothing related to this change.
> Fix rename folder to save relative path in .pyproj, instead of absolute.

- Python/Product/Analysis/AnalysisHashSet.cs
- Python/Product/Analysis/AnalysisSet.cs
- Python/Product/Analysis/AnalysisValue.cs
- Python/Product/AnalysisMemoryTester/Program.cs
- Python/Tests/dirs.proj
Make analysis sets immutable by default
Make AnalysisHashSet.Clone() thread safe
Add peak memory usage to memory tester output
In my testing so far, this is looking around 2x improvement in analysis time (for e.g. bokeh and conda sources) with minor improvement in memory usage (as opposed to the huge regression I was expecting).
Please test and see if you notice values disappearing from your own code (imported packages are not affected). I'm keen to take this, provided we can't see regressions in results. The tests still pass.
> Make analysis sets immutable by default

- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugProgram.cs
- Python/Product/TestAdapter.Executor/TestExecutor.cs
Right now debug unit test is completely broken with the experimental debugger.
This is a workaround that makes the debug unit test feature work until we can properly use the new debugger.
> Force use of the old debugger for unit test debugging.

- Python/Product/Analysis/Values/BuiltinInstanceInfo.cs
- Python/Product/Analysis/Values/FunctionInfo.cs
- Python/Product/Analysis/VariableDef.cs
Fixes #3866 Endlessly analyzing sympy
Fixes 'type' comparison
Reduces analysis when merging all function calls
Adds simple cache for VariableDef to improve performance when a function has many callers
> Fixes #3866 Endlessly analyzing sympy

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
Changes Live Linting default value (again?)
Ensures we do not try to filter non-started completion sessions
These shouldn't need to go into 15.7, but I'm wondering how many times we need to disable live linting?!
> Minor bug fixes

- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Python/Product/Analysis/LanguageServer/ParseQueue.cs
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Core.UI/EditorTests.cs
- Python/Tests/Core.UI/ErrorListTaskListTests.cs
- Python/Tests/PythonToolsUITestsRunner/EditorTests.cs
- Python/Tests/PythonToolsUITestsRunner/ErrorListTaskListTests.cs
- Python/Tests/TestData/Typings.sln
- Python/Tests/TestData/Typings/Typings.pyproj
- Python/Tests/TestData/Typings/mymod.pyi
- Python/Tests/TestData/Typings/usermod.py
Fixes #4096 Add test that default analyzer is used for non project file
Make default analyzer files follow environment changes
Ensures stub files are always parsed correctly.
> Fixes #4096 Add test that default analyzer is used for non project file

- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
- Python/Tests/Core/CodeFormatterTests.cs
- Python/Tests/Utilities.Python/EditorTestToolset.cs
- Python/Tests/Utilities.Python/PythonToolsOptionsImporter.cs
- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
This change also changes `CodeFormatterTests` so that they cover whole command execution
> Fix #4129: Format document doesn't do anything

- Python/Product/VSInterpreters/Interpreter/InterpreterRegistryService.cs
- Python/Tests/Core/EnvironmentListTests.cs
This is a workaround for a VS MEF regression where the metadata object isn't filled in when using a concrete dictionary type.
They're fixing it, but this makes it work until their fix is available. https://github.com/Microsoft/vs-mef/pull/89
> Fix missing environments on 15.8 preview 2

- Python/Product/Analysis/Analyzer/OverviewWalker.cs
- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
- Python/Product/Analysis/LanguageServer/Structures.cs
- Python/Product/Analysis/Parsing/Ast/EmptyStatement.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Tests/Analysis/ExpressionFinderTests.cs
Fixes #4115: Completions dropdown shouldn't appear after def and class
Fixes handling of incomplete def and class statements
Fixes default commit of overrides
Fixes references to import names
> Fixes #4115: Completions dropdown shouldn't appear after def and class

- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
- Python/Product/Analysis/Parsing/Ast/PythonAst.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/Parsing/Tokenizer.cs
- Python/Product/PythonTools/PythonTools/Extensions.cs
- Python/Product/PythonTools/PythonTools/Intellisense/NormalCompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/PythonSignature.cs
- Python/Tests/Analysis/ParserTests.cs
- Python/Tests/PythonToolsMockTests/CompletionTests.cs
Fixes #4120 Editing in comments should not bring up completions
Tracks comment locations in AST so we can easily suppress completions
Fixes #4123 Completion or formatting mangles string
Fixes applicable span calculation to avoid triggering completion on wrong word
Removes unnecessary assertion in invalid signatures.
> Fixes 4120, 4123

- Python/Product/Analysis/Interpreter/PythonLibraryPath.cs
> Prevent crash due to ArgumentNullException when parsing search paths.

- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Fix #4193 
`kind` was `null`, and `PythonNavigateToItemDisplay` was only initializing the item location if one of the results had `loc.kind == "definition"`.
Don't know if that's too simplistic or not. The function I'm changing is called only from `GetAllMembers`, so presumably it's only definitions that we are getting.
> Fix navigation in Go To All

- Python/Product/Django/Microsoft.PythonTools.Django.targets
Fix #4184 
Our Django templates define `STATIC_ROOT`, but when you import from existing code a project created using `django-admin startproject`, settings.py doesn't have `STATIC_ROOT` defined.
People are starting to `startproject` templates rather than our own since our templates don't target Django 2.0.
> Skip static file collection when STATIC_ROOT is not defined

- Python/Product/Analysis/LanguageServer/DocumentationBuilder.cs
- Python/Product/Analysis/LanguageServer/Server.Hover.cs
- Python/Product/Analysis/Values/TypingTypeInfo.cs
- Python/Tests/Analysis/AnalysisSaveTest.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/LanguageServerTests.cs
- Update baselines 
- Don't display long class doc for built-in types (i.e. display just 'int' for the int constant)
- Minor tweak in the tooltip to match the test for simple types.
- Fix fetching arg types for named tuple (looks like `_args` can now be empty and not always null)
> Fix failing tests

- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
I'm not sure if we should move string literal logic to server, but this fix for P0 bug will work.
> Fix #4188: File and folder path completions no longer work 

- Python/Product/Cookiecutter/Model/GitHubClient.cs
- Python/Tests/CookiecutterTests/CookiecutterTests.csproj
- Python/Tests/CookiecutterTests/GitHubClientTests.cs
> Specify correct encoding in WebClient when calling into GitHub API.

- Common/Tests/Utilities/VCCompiler.cs
- Python/Product/Profiling/vspyprof.py
- Python/Product/PyDebugAttach/PyDebugAttach.cpp
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/python.h
- Python/Tests/DebuggerTests/AttachTests.cs
Fixes #4145 AD7 debugger can't attach to Python 3.7
Corrects structures for Python 3.7
Allows profiling on 3.7
> Fixes #4145 AD7 debugger can't attach to Python 3.7

- Python/Product/Analysis/Infrastructure/TaskExtensions.cs
- Python/Product/Common/Infrastructure/TaskExtensions.cs
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Cookiecutter/Shared/Infrastructure/TaskExtensions.cs
- Python/Product/ProjectWizards/CookiecutterWizard.cs
- Python/Product/ProjectWizards/ImportWizard.cs
- Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/Core/TaskExtensionsTests.cs
- Log OperationCanceledException as information instead of error in CustomCommand.RunInRepl
- Switch DoNotWait to explicit implementation to ensure that OperationCanceledException is ignored
- Add test for DoNotWait
> Fix #4075: TaskCanceledException in Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.ExecuteCodeAsync

- Python/Product/Debugger.Concord/Debugger.Concord.csproj
- Python/Product/Debugger.Concord/LocalComponent.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyRuntimeState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger.Concord/PythonRuntimeInfo.cs
- Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs
Fixes #4146 Mixed-mode debugger fails on Python 3.7
Updates data structures to enable Python 3.7 debugging
> Fixes #4146 Mixed-mode debugger fails on Python 3.7

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analyzer/Interpreter/LegacyDB/CPythonInterpreter.cs
- Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
- Python/Product/IronPython/Interpreter/IronPythonModule.cs
- Python/Product/IronPython/Interpreter/RemoteInterpreter.cs
- Python/Product/IronPython/Interpreter/RemoteInterpreterProxy.cs
- Python/Product/IronPythonResolver/Resolver.cs
- Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs
- Python/Tests/Analysis/AnalysisTest.Perf.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/Analysis/AnalysisTests.csproj
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/IronPython/IronPythonAnalysis.cs
- Python/Tests/IronPython/IronPythonAnalysisTest.cs
- Python/Tests/IronPython/IronPythonDatabaseTest.cs
- Python/Tests/IronPython/IronPythonTests.csproj
- Python/Tests/IronPython/ReplEvaluatorTests.cs
- Python/Tests/PythonToolsMockTests/PythonToolsMockTests.csproj
- Python/Tests/PythonToolsMockTests/SquiggleTests.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
Fixes IronPython intellisense
Fixes IronPython tests
Removes unnecessary IronPython dependencies from test projects
Makes Ast.PythonModuleLoader public API
This is a prerequisite for #2943, though it's not a fix for it. Feel free to make architectural suggestions - I've gone for minimum top-level public APIs, but if you really hate the nested classes/enums then let me know why and I'll reconsider :)
> Fixes IronPython intellisense

- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/LanguageServer/DocumentationBuilder.cs
- Python/Product/Analysis/LanguageServer/MarkdownDocumentationBuilder.cs
- Python/Product/Analysis/LanguageServer/PlainTextDocumentationBuilder.cs
- Handle documentation that is one-liner like `""" comment """`
- Make separate tooltip for constants to avoid extra empty lines
> Handle single-line module documentation better

- Python/Product/EnvironmentsList/PipExtension.xaml.cs
Fix an oversight from my pip changes last week (it still worked, but I'd rather have the good name there).
> Fix WPF dependency property name.

- Python/Tests/Utilities.Python/PythonTestExplorer.cs
partial fix for #4290 
In 15.8, behavior of the commands has changed, and they added a new NextGroupBy command to cycle through all. The default grouping for GroupBy is now Class, and previously it was Namespace.
There's an additional UI automation problem with their tree view that prevents the test from passing (tree nodes fail to expand via automation)
> Update the code that sets test explorer grouping to namespace.

- Common/Tests/Utilities.UI/HostedPythonToolsTestRunner.cs
Fix #4311 DebugPurePythonProject test fails due to task not completed
> Do test cleanup after the test arguments are disposed. 

- Common/Product/SharedProject/Wpf/Controls.cs
- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/EnvironmentsList/PipExtension.xaml
Fix #4325
We already had a style definition for TextBlock which forced window text color, so I define a new style to use within info tip.
Also, it turned out that while ThemeResourceKey for InfoBackground was working fine, InfoText wasn't. I changed both to use VsBrushes/VsColors for consistency.
I checked all 4 themes + high contrast (black) + high contrast (white), and they're all fine.
> Fix colors used for info tip in package manager.

- Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsPage.cs
Fixes #4274 Crash when saving diagnostics to file
Ensures no null-reference errors can emerge from SaveToFile.
> Fixes #4247 Crash when saving diagnostics to file

- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/TestAdapter/TestContainerDiscoverer.cs
Fixes both the symptom and the bug:
- Reference to `PythonEditorServices` is saved before its first use instead of resolving it every time
- `UpdateTestCasesAsync` uses analyzer that raised `AnalysisComplete`. If analyzer is disposed, `SendExtensionCommandAsync` request will be canceled.
> Fix #4352: An unexpected error occurred

- Python/Product/Debugger.Concord/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs
Fixes #4323 Debug unit test no longer works with native code debugging enabled
Moves language version argument to helper functions so that the object can still be constructed remotely.
> Fixes #4323 Debug unit test no longer works with native code debugging

- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseControllerProvider.cs
Fixes #4378 Crash due to UriFormatException when editing condition on breakpoint
Prevent crash
Avoid trying to analyze debug view elements.
> Fixes #4378 Crash due to UriFormatException when editing condition on breakpoint

- Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/ModulePath.cs
- Python/Product/Analysis/scrape_module.py
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/Analysis/ModulePathTests.cs
Fixes #4373 socket completions are not correct
Updates list of modules/types that lie about where they are defined
Adds test to verify standard library extension modules have no external dependencies
Adds ability to detect whether ModulePath represents a debug module
Removes typing members from type stubs
Fixes case sensitivity of generated cache paths.
Stops returning very generic overloads when more specific ones are available.
> Fixes #4373 socket completions are not correct

- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
> Prevent crash when the root scripts path or the environment name have invalid path characters.

- Python/Product/Debugger/Debugger.csproj
Visible known regressions:
https://github.com/Microsoft/ptvsd/issues/491 Same breakpoint hit multiple times (2.7 only)
https://github.com/Microsoft/ptvsd/issues/459 Break on normal exit is not respected
Our test run has a lot of failures due to that first bug, but the rest looks okay (when running on 3.6).
I'm not convinced myself I want to take this, but getting it ready in case we do want to take it.
> Update to ptvsd==4.1.1a7

- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
- Python/Tests/Analysis/LanguageServerTests.cs
Fixes #4387 unittest.skip missing from completions
Adds fallback to tokens and reparsing when showing completions in an error node
Fixes applicable span when starting to type
> Fixes #4387 unittest.skip missing from completions

- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITests/MixedModeDebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Previous behavior for the tests was to use whatever happened to be the default on that machine.
Since we're seeing version specific bugs right now, it will be useful to see results for both 2.7 and 3.6.
I didn't duplicate the old debugger tests, not as much benefit there since the code isn't changing much / at all and that would increase the test run time.
> Duplicate experimental debugger ui tests into separate 2.7 and 3.6 tests

- Python/Product/Analysis/AnalysisNetStandard.csproj
- Python/Product/Analysis/LanguageServer/IServer.cs
- Python/Product/Analysis/LanguageServer/Messages.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
- Python/Product/Analysis/LanguageServer/Server.WorkspaceSymbols.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/LanguageServer/ServerBase.cs
- Add OnCommand event to the server (for handling `CompletionItem.command` in extension)
- Register LS as command provider and register command for post-completion
- Suppress 'async without await' warning in .NET Core build
- Fix Linux URI handling (must always use absolute)
Works in VSC. Looking at how to update VS part.
> Add command handling for LS extensions

- Python/Product/PythonTools/PythonTools/PythonAnalysisClassifierProvider.cs
- Python/Product/PythonTools/PythonTools/PythonClassifier.cs
- Python/Product/PythonTools/PythonTools/TokenCache.cs
Fixes #3959 Colorisation bug after pasting XML
Clear caches properly for edits that only remove text
Clarifies priorities of analysis classifier formats
> Fixes #3959 Colorisation bug after pasting XML

- Python/Product/Debugger/Debugger.csproj
This has the fix for Python 2.7 breakpoint on line 1 being hit twice.
Both 2.7 and 3.6 sets of UI tests pass*
* modulo the 'task not completed' failures that sometimes occur when cleaning up the test at the end.
> Update to ptvsd==4.1.1a9

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentManager.cs
- Python/Tests/Core/CondaEnvironmentManagerTests.cs
Fix #4416 
To work across different machine setups (different install location and different versions of conda), stop guessing where environments are created and ask conda.exe for the information instead.
> Fix conda environment manager tests

- Common/Tests/Utilities/AssertUtil.cs
- Python/Product/Analysis/Interpreter/Ast/AstCachedPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonModule.cs
- Python/Product/Analysis/Interpreter/Ast/AstScrapedPythonModule.cs
- Python/Product/Analysis/Interpreter/SentinelModule.cs
- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
- Python/Product/Analysis/ModulePath.cs
- Python/Product/Analysis/scrape_module.py
- Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageManager.cs
- Python/Tests/Analysis/AstAnalysisTests.cs
- Python/Tests/TestData/AstAnalysis/Package-stubs/Module.pyi
- Python/Tests/TestData/AstAnalysis/Package/Module.py
- Python/Tests/TestData/AstAnalysis/Stubs/Package/Module.pyi
- Python/Tests/Utilities.Python.Analysis/PythonAnalysis.cs
Fixes #4406 PEP 561 support
Adds support for locating type stub packages.
Makes AstPythonInterpreterFactory import process fully async and cancelable
Fixes minor bugs in import completion and module scraping
> Fixes #4406 PEP 561 support

- Python/Product/Analysis/LanguageServer/CompletionAnalysis.cs
Fixes #4422 import completions are not filtered for submodules
Fixes applicable span when completing import statements.
> Fixes #4422 import completions are not filtered for submodules

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Fixes #4192 Quick Info tooltip follows the mouse as it moves
Only dismisses quick info if we have moved outside the applicable span.
> Fixes #4192 Quick Info tooltip follows the mouse as it moves

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Logging/ActivityLogLogger.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/VSCommon/Infrastructure/VSTaskExtensions.cs
Fixes #3729 Report analyzer errors in activity log
Adds ActivityLogLogger for certain logged events.
Fixes failure to log abnormal termination events
Fixes cross-threading issue.
> Fixes #3729 Report analyzer errors in activity log

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Debugger/PtvsdVersionHelper.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonTools/Options/DebuggerOptions.cs
- Python/Product/PythonTools/PythonTools/Options/ExperimentalOptions.cs
- Python/Product/PythonTools/PythonTools/Options/IPythonOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsPage.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsPage.cs
- Python/Product/PythonTools/PythonTools/PythonAutomation.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/PythonTools/ptvsd_launcher.py
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/Utilities.Python/PythonDebuggingGeneralOptionsSetter.cs
- Python/Tests/Utilities.Python/PythonExperimentalGeneralOptionsSetter.cs
Fix #4479 
Use legacy instead of experimental when mentioning the ptvsd debuggers.
Move the option from experimental page to debugger page.
Add Python 3.3 as an incompatible environment.
I kept the storage of the option in VSInterpreters, we still need to access it from the Debugger project which doesn't have access to DebuggerOptions.
> Change legacy/experimental debugger messages

- Python/Product/Analysis/Intellisense/LinePreservingCodeReplacer.cs
- Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
- Python/Tests/Core/CodeFormatterTests.cs
Fixes #3705 Format selection breaks code
Ensures formatting edits are offset by correct starting location.
> Fixes #3705 Format selection breaks code

- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Fixes #4033 Remote attach with source reference crashes VS
Handles non-absolute paths by generating a false URI
> Fixes #4033 Remote attach with source reference crashes VS

- Python/Product/Analysis/AnalysisLog.cs
- Python/Product/Analysis/AnalysisUnit.cs
- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
- Python/Product/Analysis/Analyzer/InterpreterScope.cs
- Python/Product/Analysis/Analyzer/ModuleScope.cs
- Python/Product/Analysis/ModuleAnalysis.cs
- Python/Product/Analysis/Parsing/Parser.cs
- Python/Product/Analysis/PythonAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Refactoring/LocationPreviewItem.cs
- Python/Product/PythonTools/PythonTools/Refactoring/VariableRenamer.cs
- Python/Tests/Analysis/AnalysisTest.cs
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
Fixes #4229 Refactor rename incorrect when using import *
Use correct references when importing modules or members
Streamlines import analysis code
Fixes dependencies not being notified of new module members
Fixes transitive module dependencies
Fixes analysis log not recording all messages
Fixes some handling of private name prefixes
> Fixes #4229 Refactor rename incorrect when using import *

- Python/Product/Analysis/Deque.cs
- Python/Product/Analysis/Intellisense/AnalysisQueue.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/PythonAnalyzer.cs
Fixes #4497 Asserts on go to definition
Add asserts when modifying the analyzer queue from the wrong context.
Allow the caller to re-enqueue modules when unloading an entry.
> Fixes #4497 Asserts on go to definition

- Python/Product/Analysis/Intellisense/ClassifierWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonMultipleMembers.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
Fixes #4493 Class name not colorized in import ... as
Adds imported 'as' name as resolvable name for classifications.
Also fixes member with no types being treated as a function.
> Fixes #4493 Class name not colorized in import ... as

- Python/Product/TestAdapter.Analysis/TestCaseInfo.cs
Fixes #1865 Unit tests refresh too often
Makes TestCaseInfo use value equality.
> Fixes #1865 Unit tests refresh too often

- Python/Tests/Analysis/AstAnalysisTests.cs
Fixes #4515 Use bundled typeshed for tests
Removes use of _TESTDATA_TYPESHED variable in favour of bundled typeshed.
> Fixes #4515 Use bundled typeshed for tests

- Python/Product/Analysis/Intellisense/AnalysisSynchronizationContext.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/PythonAnalyzer.cs
Fixes #4526 Assert while/after creating a virtual env
Ensures module reload occurs on analysis thread
Prevent exceptions when attempting to enqueue operations after the analyzer is closed
> Fixes #4526 Assert while/after creating a virtual env

- Python/Product/Analysis/Deque.cs
- Python/Product/Analysis/Intellisense/AnalysisQueue.cs
- Python/Product/Analysis/Intellisense/AnalysisSynchronizationContext.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/PythonAnalyzer.cs
Fixes #4497 Asserts on go to definition
Add asserts when modifying the analyzer queue from the wrong context.
Allow the caller to re-enqueue modules when unloading an entry.
> [15.8] Fixes #4497 Asserts on go to definition

- Python/Product/Analysis/Intellisense/ClassifierWalker.cs
- Python/Product/Analysis/Interpreter/Ast/AstPythonMultipleMembers.cs
- Python/Tests/PythonToolsMockTests/ClassifierTests.cs
Fixes #4493 Class name not colorized in import ... as
Adds imported 'as' name as resolvable name for classifications.
Also fixes member with no types being treated as a function.
> [15.8] Fixes #4493 Class name not colorized in import ... as

- Python/Product/Django.Analysis/DjangoAnalyzer.cs
- Python/Product/Django.Analysis/DjangoUrl.cs
Fix #4557 Intellisense not working when using composed regex in Django url pattern
> Prevent crash in analyzer when django url() first parameter is not a string constant

- Python/Product/Analysis/AggregateProjectEntry.cs
Fixes #4533 NullReferenceException when switching active environment
Prevent analyzer crashing when referencing deliberately uninitialised variable.
> Fixes #4533 NullReferenceException when switching active environment

- Python/Product/Analysis/AggregateProjectEntry.cs
Fixes #4533 NullReferenceException when switching active environment
Prevent analyzer crashing when referencing deliberately uninitialised variable.
> [15.8] Fixes #4533 NullReferenceException when switching active environment

- Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionComparer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/CompletionResult.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ExpansionCompletionSource.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Fix REPL completions not respecting the "live completions only" option and not synchronizing the buffer.
A bit simpler than https://github.com/Microsoft/PTVS/pull/4564 but produces same results.
> [15.8] Alternate fix for repl completions

- Python/Product/Debugger/Debugger.csproj
Debugger UI tests are passing on 2.7 and 3.6
> Update to ptvsd==4.1.1a10

- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
Fix #4513 
Adding the same type of protection we already had in `ProcessExited` handler to the `StdErrReceived` and `StdOutReceived` handlers.
> Prevent crash due to NullReferenceException in interactive window component

- Python/Product/Analysis/Analysis.csproj
- Python/Product/Analysis/Analyzer/DDG.cs
- Python/Product/Analysis/Infrastructure/TaskCompletionSourceExtensions.cs
- Python/Product/Analysis/LanguageServer/EditorFiles.cs
- Python/Product/Analysis/LanguageServer/Server.Completion.cs
- Python/Product/Analysis/LanguageServer/Server.FindReferences.cs
- Python/Product/Analysis/LanguageServer/Server.Hover.cs
- Python/Product/Analysis/LanguageServer/Server.SignatureHelp.cs
- Python/Product/Analysis/LanguageServer/Server.WorkspaceSymbols.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/ProjectEntry.cs
- Python/Product/Analysis/SingleDict.cs
Create a `TaskCompletionSource` at the beginning of parsing to be able to wait for the corresponding analysis.
>  Fix #4560: IntelliSense completions don't reliably appear

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/PythonAnalyzer.cs
Fixes https://github.com/Microsoft/vscode-python/issues/2017
Make sure interpreter is initialized before attempting to import types
> Fix #2017  Language service fails when using Python 2.7 interpreter

- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs
Fixes #4610
The issue was that file watcher ctor throws when folder in search paths does not exist.
I was able to repro the issue in VS but it was much harder, the reason is different. Most probably adding 'hello.py' first leads to creation of unresolved 'imported' and later, when 'imported' is actually added the module table is not updated.
> Relative import fails in Python 2.7

- Common/Tests/Utilities/TestEnvironmentImpl.cs
- Common/Tests/Utilities/VisualStudioPath.cs
Many tests are failing on our v16 builds because this crashes. We can fall back on the environment variable in most cases.
> Make tests run without a Visual Studio instance.

- Python/Product/Analysis/AnalysisLogWriter.cs
Fixes #4608 Crash in Microsoft.PythonTools.Analysis.AnalysisLogWriterDump
Handle unexpected IOExceptions.
> Fixes #4608 Crash in Microsoft.PythonTools.Analysis.AnalysisLogWriterDump

- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/Analysis/LanguageServer/ServerSettings.cs
- Python/Product/Analysis/LanguageServer/Settings.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.Lifetime.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServerSettings.cs
Addresses https://github.com/Microsoft/vscode-python/issues/2270
> Introduce LS setting to delay diagnostic publishing to idle

- Python/Tests/Core/EnvironmentListTests.cs
Fixes unstoppable race condition test.
It looks like even after cancellation hits we can still end up infinitely triggering new tasks. This change should prevent that.
> Fixes unstoppable race condition test.

- Python/Product/Analysis/AnalysisLogWriter.cs
Fixes #4608 Crash in Microsoft.PythonTools.Analysis.AnalysisLogWriter.Dump
Handle unexpected IOExceptions.
> Fixes #4608 Crash in Microsoft.PythonTools.Analysis.AnalysisLogWriter.Dump

- Python/Product/Analysis/LanguageServer/Server.WorkspaceSymbols.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/VSCode/AnalysisVsc/AnalysisVsc.csproj
- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Python/Product/VSCode/PythonVsc.sln
Addresses https://github.com/Microsoft/vscode-python/issues/2224
Symbols nature is currently not always known until analysis completes. However, blindly waiting for analysis to complete does not make sense. So added cancellable wait - VSC does not cancel request for document symbols, but user command (as in Palette -> Go To Symbol) can be canceled.
VSC does not provide API to update document outline. It simple asks for symbols when document changes.
> Improve reliability of document outline population in VS Code

- Python/Product/ExternalProfilerDriver/DWJsonModel.cs
- Python/Product/ExternalProfilerDriver/ExternalProfilerDriver.csproj
- Python/Product/ExternalProfilerDriver/Program.cs
- Python/Product/ExternalProfilerDriver/VTuneInvoker.cs
- Python/Product/ExternalProfilerDriver/VTuneStackParser.cs
- Python/Product/ExternalProfilerDriver/VTuneToDWJSON.cs
- Python/Product/ExternalProfilerDriver/VTuneUtils.cs
Generates diagsession traces, still unstable on source file/line number information because need to account for symbols generated by setup.py-based builds.
> Vtune sourcemap (cleaned up to account for 15.8)

- Python/Product/Analysis/Infrastructure/StringExtensions.cs
- Python/Product/Analysis/LanguageServer/Enums.cs
- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/VSCode/AnalysisVsc/Core/Shell/ICoreShell.cs
- Python/Product/VSCode/AnalysisVsc/Core/Shell/IProgressService.cs
- Python/Product/VSCode/AnalysisVsc/Core/Shell/ITelemetryService.cs
- Python/Product/VSCode/AnalysisVsc/Core/Shell/IUIService.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Python/Product/VSCode/AnalysisVsc/Services/UIService.cs
Address user feedback per https://github.com/Microsoft/vscode-python/issues/2405
- Reduce noise in the output window. 
- Related setting was added to VSC extension.
- Default level is now 'error'.
- Added 'general' level for messages that we always want to be displayed.
> Reduce noise in LS output

- Python/Product/Cookiecutter/source.extension.vsixmanifest
- Python/Product/Core/source.extension.vsixmanifest
- Python/Product/Django/source.extension.vsixmanifest
- Python/Product/IronPython/source.extension.vsixmanifest
- Python/Product/Profiling/source.extension.vsixmanifest
- Python/Product/Uwp/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/15.0/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/16.0/source.extension.vsixmanifest
- Python/Product/Wsl/source.extension.vsixmanifest
- Python/Templates/source.extension.vsixmanifest
- Python/Tests/Core.UI/source.extension.vsixmanifest
- Python/Tests/DebuggerUITests/source.extension.vsixmanifest
- Python/Tests/DjangoUITests/source.extension.vsixmanifest
- Python/Tests/ProfilingUITests/source.extension.vsixmanifest
- Python/Tests/ProjectUITests/source.extension.vsixmanifest
- Python/Tests/ReplWindowUITests/source.extension.vsixmanifest
- Python/Tests/Utilities.Python/source.extension.vsixmanifest
Fixes #4668 Incorrect version in vsix manifest
Fixes version numbers.
> Fixes #4668 Incorrect version in vsix manifest

- Python/Product/Debugger/Debugger.csproj
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
Ran 2.7 and 3.6 Debugger UI tests. These were the failed tests. They don't seem to be related to ptvsd.
> Update ptvsd to 4.1.1

- Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs
- Python/Product/Analysis/PythonAnalyzer.cs
Fix https://github.com/Microsoft/PTVS/issues/4660 for 15.9 (already fixed in master)
> 15.9: Language service fails when using Python 2.7 interpreter

- Python/Product/Analysis/LanguageServer/Server.cs
- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
- Eliminate double analysis enqueue on file open (`AddFileAsync` already does it)
- Do not load the entire directory if user is interested in 'open files only'
> Optimize file loading in VS Code

- Python/Product/Analysis/AnalysisUnit.cs
- Python/Product/Analysis/Values/ModuleInfo.cs
- Python/Tests/Analysis/AnalysisTest.cs
Fixes #4679 Analyzer stuck in psutil
Uses ephemeral variables for imported module members, and only clears out non-ephemeral variables.
> Fixes #4679 Analyzer stuck in psutil

- Python/Product/VSCode/AnalysisVsc/LanguageServer.cs
Optimization does not work in all cases, such as when A.py import B.py we don't actually load B.py. A different approach is needed.
> Re-enable all file loading

- Common/Product/SharedProject/Wpf/Controls.cs
- Common/Product/SharedProject/Wpf/Controls.xaml
- Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
- Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
- Python/Product/EnvironmentsList/ToolWindow.xaml
- Python/Product/PythonTools/PythonTools/Options/LanguageServerOptionsControl.resx
Fix narrator for language server option browse button (I checked the tab order, it is correct)
Fix contrast for environments window listbox selected items (it was a slightly different blue than seen in the rest of VS - toolbox, error list, etc)
Remove the help button from environments view
> Some accessibility fixes for environments window, language server options

- Python/Product/Analysis/ModuleResolver.cs
Original fix: https://github.com/Microsoft/python-language-server/pull/88/files
Original bug: https://github.com/Microsoft/python-language-server/issues/72
Reported on 15.8 at https://developercommunity.visualstudio.com/content/problem/346930/vs-158-intellisense-for-python-37-not-working.html
> Backport fix for NullReferenceException in GetModuleFullName.

- Common/Product/TestAdapter/ServiceProviderExtension.cs
- Python/Product/TestAdapter.Executor/TestDiscoverer.cs
- Python/Product/TestAdapter.Executor/TestExecutor.cs
- Python/Product/TestAdapter/TestContainerDiscoverer.cs
ValidateArg utility from test explorer assembly is no longer public (that changed in dev16 in the past couple of days).
> Fix build error. 

- .gitattributes
Fix #4900 
https://github.com/github/linguist#overrides
Didn't bother doing that with typeshed folder, since Analysis project will be removed soon.
> Mark the miniconda distro folder as vendored.

- Python/Product/LiveShare/LiveShare.csproj
This matches the setting for the other projects.
Hopefully helps avoid the build machine getting stuck when building live share project.
> Don't deploy live share extension when building outside of VS. 

- Python/Product/Common/Infrastructure/PathUtils.cs
- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
- Python/Tests/Core/WorkspaceInterpreterFactoryTests.cs
Fix #4879
Work space interpreters will properly refresh on rename or delete. If the selected interpreter is renamed or deleted, the default interpreter should be selected.
> Issue 4879: Workspace interpreters not updated after rename or delete

- Python/Product/PythonTools/PythonTools/Environments/VirtualEnv.cs
Fix #4937
FYI `PathUtils.GetRelativePath` returns an absolute path if a relative path cannot be determined (I've tested it).
> Store relative path to virtual env in workspace settings.

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Environments/EnvironmentSwitcherManager.cs
- Python/Product/PythonTools/PythonTools/Environments/EnvironmentSwitcherWorkspaceContext.cs
- Python/Product/PythonTools/PythonTools/Environments/ProjectView.cs
- Python/Product/PythonTools/PythonTools/Environments/VirtualEnv.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Intellisense/WorkspaceAnalysis.cs
- Python/Product/PythonTools/PythonTools/Intellisense/WorkspaceAnalyzer.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonToolsService.cs
- Python/Product/VSCommon/Logging/PythonToolsLoggerData.cs
- Python/Product/VSInterpreters/Interpreter/IPythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/IPythonWorkspaceContextProvider.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
- Python/Product/VSInterpreters/PythonWorkspaceContextEventArgs.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
- Python/Product/VSInterpreters/WorkspaceExtensions.cs
- Python/Product/Workspace/PythonLaunchConfigurationProvider.cs
- Python/Product/Workspace/PythonLaunchDebugTargetProvider.cs
- Python/Tests/Core/PythonToolsTests.csproj
- Python/Tests/Core/PythonWorkspaceContextProviderTests.cs
- Python/Tests/Core/PythonWorkspaceContextTests.cs
- Python/Tests/Core/WorkspaceInterpreterFactoryTests.cs
- Python/Tests/Core/WorkspaceTestHelper.cs
Fix #4853 Open Folder: analysis needs to use folder settings
Also:
Automatically restart analyzer when it quits abnormally (for projects as well).
Adds a "SearchPaths" string array setting to PythonSettings.json
Adds a "env" object setting to launch.vs.json
> Fix analysis for workspaces.

- Python/Product/Workspace/PythonLaunchDebugTargetProvider.cs
Fix #5054
Allow the working directory setting to be relative path to the root of the workspace and make the default value be the root of the workspace.
Previously, a relative path ended up calculated relative to the VS installer dir (quite wrong) and the default working directory was the running script's parent folder, rather than the root.
> Open folder working directory fixes

- Python/Product/PythonTools/PythonTools.vsct
Assign a text/automation name to the Python environment combo box.
Change its keyboard shortcut to CTRL-K,E because CTRL-K,CTRL-E was conflicting with another command.
Fixes internal bug 780657
> Fix Python toolbar accessibility

- Common/Product/SharedProject/Wpf/ConfigurationControl.cs
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Wpf/ModernStyles.xaml
Fix internal bug 790717
FYI @RaymonGulati1 :
`IsRequiredForForm` is used when setting it on our helper control (which consists of multiple controls), it passes it down to the combo or text box
`AutomationProperties.IsRequiredForForm` is used when setting it on the raw combo or text box.
> Add the IsRequiredForForm automation property to controls in the add environment dialog.

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
Fix duplicate automation names and add a tooltip to the textboxes labeled by a checkbox or radio button.
Fix internal bug 790771
> Tooltip and automation name fixes for text boxes in add environment dialog

- Build/15.0/packages.config
- Build/16.0/packages.config
- Common/Tests/MockVsTests/MockVsFolderWorkspaceService.cs
- Common/Tests/MockVsTests/MockVsTests.csproj
- Python/Tests/PythonToolsMockTests/NavigableTests.cs
Fix #4703 by integrating updated language server
See language server PR at https://github.com/Microsoft/python-language-server/pull/681
Also fixes tests:
- Fix MEF composition error in mock tests.
- Fix go to navigation tests to reflect the updated language server behavior for get definition.
> Fix outlining

- Common/Tools/BuildTasks/BuildTasks.csproj
- Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs
- Common/Tools/BuildTasks/Properties/AssemblyInfo.cs
- Python/Product/Cookiecutter/Attributes.cs
- Python/Product/Cookiecutter/Shared/Interpreters/InterpreterConfiguration.cs
- Python/Product/PythonTools/PythonTools/Project/Attributes.cs
- Python/Product/VSInterpreters/Interpreter/VisualStudioInterpreterConfiguration.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageManager.cs
- Python/Product/VSInterpreters/PackageManager/PipRequirementsUtils.cs
Fix #5005 
Fix BuildTask to include assembly information such as title, name, version. 
Update strings to compare with culturally invariant process
> Resolving Roslyn Analyzer Issues

- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
> Fix crash when triggering completions in a text view with multiple carets

- Build/Common.Build.Core.settings
Background: When we release in a x.y update, we increment x.y in file version to match VS version. This has proven to be useful in bug reports, about box, etc.
As a reference, this is the commit for when we went from 15.8 to 15.9: https://github.com/Microsoft/PTVS/commit/bded477e28b3c9b96f9aae94b96a136fbfb33f4f
> Update file version to 16.1.

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Environments/AddInstalledEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddInstalledEnvironmentView.cs
Fix #5179 
Integrates the 'none' entries into the items list as appropriate, so that visibility is controlled by the presence in the list.
Narrator was previously not respecting the visibility of the separate text block control. This works around that.
> Fix narrator behavior in the installed page of the add environment dialog

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
When starting project analyzer, don't analyze files that are listed in the project but don't really exist on disk.
> Don't request to analyze non-existent files

- Python/Product/VCDebugLauncher/VCDebugLauncher.csproj
- Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj
Fix #5243 
Update extension module template and VC debug launcher msbuild install location to both use the VC v142 platform toolset. 
FYI platform toolset v142 = VS 2019, v141 = VS 2017, v140 = VS 2015
Update the template to default to use the latest installed Win10 SDK rather than a specific version.
The VCTargets install location has been deprecated. The VC msbuild files now go under the standard MSBuild folder, but now we have to manually specify which platform toolset we want to install into. The v160 folder is for the v142 platform toolset.
> Fix VC debug launcher

- Python/Product/PythonTools/ptvsd/repl/jupyter_client.py
- Both execute(..) and get_shell_msg(..) act on the same shell socket and having a blocking call to get_shell_msg(..) no longer works with the newer pyzmq.
- temporary fix was to downgrade pyzmq to 17.1.3
- Changed get_shell_msg(..) to use a timeout instead of blocking.
related to bug  #5233
> fix for repl hang when using  with pyzmq => 18.0.0

- Build/Common.Build.CSharp.settings
- Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs
-had to add a workaround msbuild property due to build machine using VS 2017 with msbuild 15.0
first main issue
##[error]E:\A\_work\139\s\Python\Product\Cookiecutter\ExtractLambdasFromXaml.cs(114,15): Error CA1031: Modify 'Execute' to catch a more specific exception type, or rethrow the exception. [E:\A\_work\139\s\Common\Tools\BuildTasks\BuildTasks.csproj]
ExtractLambdasFromXaml.cs(114,15): error CA1031: Modify 'Execute' to catch a more specific exception type, or rethrow the exception. [E:\A\_work\139\s\Common\Tools\BuildTasks\BuildTasks.csproj] [E:\A\_work\139\s\Python\Product\Cookiecutter\Cookiecutter_ljs5eifo_wpftmp.csproj]
second issue with Roslyn itself
"CSC(0,0): Error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of …
> Fix the newly detected Roslyn Errors #5197

- Python/Product/Debugger/Debugger.csproj
All UI tests passed on both 2.7 and 3.6, except for PendingBreakPointLocation which has unrelated failure (regarding analysis not running).
> Update to ptvsd 4.2.9b0

- Python/Product/PyDebugAttach/PyDebugAttach.cpp
Account for terminating null when allocating string buffer.
> Fix #5219: Attach to a running python.exe does not work

- Build/16.0/packages.config
Not required, as there are binding redirects, but I prefer to target the latest available.
> Update LiveShare NuGet packages.

- Python/Product/Profiling/PythonProfiling.vsct
Fix #5340 
On request from VS IDE team, the profiling menu items are moving out of the analyze menu. Diagnostics team will remove their Analyze > Performance Profiler... menu item (they already have a copy under Debug).
I've placed ours right below the generic profiling commands.
FYI the long term solution is to integrate with the Performance Profiler window and remove our custom commands, but the integration interfaces for doing that are not yet public.
> Move the Python profiling commands from the Analyze to the Debug menu.

- Python/Tests/Core.UI/EnvironmentUITests.cs
- Python/Tests/Core.UI/WebProjectTests.cs
- Python/Tests/Core/DebugReplEvaluatorTests.cs
- Python/Tests/Core/EnvironmentListTests.cs
- Python/Tests/Core/ReplEvaluatorTests.cs
- Python/Tests/DebuggerTests/AttachTests.cs
- Python/Tests/DebuggerTests/BaseDebuggerTests.cs
- Python/Tests/DebuggerTests/DebuggerTests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/MixedModeDebugProjectUITests.cs
- Python/Tests/ProfilingTests/ProfilingTests.cs
- Python/Tests/ProfilingUITests/ProfilingUITests.cs
- Python/Tests/ProfilingUITestsRunner/ProfilingUITests.cs
- Python/Tests/ReplWindowUITests/ReplWindowSettings.cs
- Python/Tests/ReplWindowUITestsRunner/ReplWindowSmokeUITests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
- Python/Tests/VSInterpretersTests/PipRequirementsUtilsTests.cs
Also updating tests to use the latest version (where applicable).
Fix #5313
> Remove tests using Python versions 2.6, 3.1-3.4. 

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapterLauncher.cs
> For new debugger, break on system exit exception of 0

- Python/Product/TestAdapter.Executor/Services/DiscoveryService.cs
helps with debugging issues.  already have these logs in test execution.
> Add test window ouput logs for discovery command line variables 

- Python/Tests/Core.UI/TestExplorerTests.cs
- Python/Tests/PythonToolsUITestsRunner/TestExplorerTests.cs
- Python/Tests/TestData/TestExplorerPytest.sln
- Python/Tests/TestData/TestExplorerPytest/TestExplorerPytest.pyproj
- Python/Tests/TestData/TestExplorerPytest/test_fixture.py
- Python/Tests/TestData/TestExplorerPytest/test_mark.py
- Python/Tests/TestData/TestExplorerPytest/test_pt.py
- Python/Tests/TestData/TestExplorerPytest/test_ut.py
- Python/Tests/Utilities.Python/PythonTestExplorer.cs
- Python/Tests/Utilities.Python/PythonTestExplorerGridView.cs
- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
Fix #5400 
Add end-to-end test for both project and workspace scenarios.
I've commented out the old one for unittest, we can work on that when support is ready. I filed a separate issue for it https://github.com/microsoft/PTVS/issues/5431
Note that the test relies on grouping to be set to Project, Namespace, Class. Unfortunately, I can't change it via automation. It's the default, so unless you've changed it at some point, it should work.
> Add UI tests for pytest

- Python/Tests/TestAdapterTests/DiscoveryTestInfo.cs
- Python/Tests/TestAdapterTests/MockRunSettingsXmlBuilder.cs
- Python/Tests/TestAdapterTests/TestAdapterTests.csproj
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
Add a test for pytest framework and one for unittest framework (currently failing but should pass once discovery is implemented), on supported versions of Python.
It's reusing test data from the UI tests, I might change that later.
I still have to update/rewrite the ITestExecutor tests which might lead to more refactoring, so I didn't optimize code reuse just yet.
Comments on the RunSettingsXmlBuilder may/are wrong, I'll have more work to do to reuse that from executor tests later.
> ITestDiscoverer unit tests

- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestEnvironment.cs
Now that we can discover unittest without pytest being installed, I've adjusted the test to make sure 'pytest' is not installed in the environment when testing 'unittest' support. Also fix for Python 2.7 error validation.
> Few test improvements

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/unittest/_discovery.py
> fix for Unittest discovery not working on Python 2.7

- Python/Setup/swix/Microsoft.PythonTools.vsmanproj
- Python/Setup/swix/swix.generate.targets
Fix #5457 
Confirmed that the vsix manifest.json built on the build machine now is 16.2.<build> instead of 16.0.<build> previously, so I think this is good to go.
> Fix version number in vsix/swix

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/unittest/_discovery.py
- Python/Product/TestAdapter.Executor/UnitTest/UnitTestExtensions.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestData/TestDiscoverer/Decorators/test_decorators_ut.py
-now we append the last two elements from the testId which should be classname and functionname to the module relative path.
-Gathering the source file of the test proved difficult. Previous version was using the module file but for anything in a package it was returning __init__.py.
Then trying getsourcefile on the test object would return the wrong file is the test was decorated.
My solution is to call getsourcefile on the test's parent, which should be the class object, which still returns the correct filename even if the class is decorated.
Fix #5477
> Unit test discovery assert when test in sub folder bug #5477

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Fix #5511 
Added some try/catch, as well as some `?.Dispose` which we've started doing elsewhere as a precaution, since `Process.Start` can return `null`.
> Add error handling in environment window.

- Python/Product/PythonTools/PythonTools/WorkspaceInfoBarManager.cs
- Python/Product/TestAdapter.Executor/Pytest/PytestExtensions.cs
- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
Fix improved runing pytests in ptvsd. Now passing just pytestId instead of path+pytestId
Fix missing traits on pytests. Removed by mistake in a previous change.
since currently we only support running tests under the project/workspace folder.
Currently it works up to 318 tests from ptvsd
auto adding search paths were messing up pytest's discovery
however we needed to manually add /src folder to the search paths for everything to work
ie.
PythonSettings.json
{
"TestFramework": "pytest",
"SearchPaths": [ "D:\\dev\\ptvsd\\src\\" ]
}
> Fix for pytest discovery in workspace mode not working on ptvsd

- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/TestAdapter.Executor.csproj
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter.Executor/Utils/TestUtils.cs
- Python/Product/TestAdapter/testlauncher.py
- now passing pytestIds to run in a file just like unittest execution
- testlaunch.py now parses out testids from any testlist file
> fix for pytest execution hitting 32k command line limt.

- Common/Tests/Utilities/SharedProject/SolutionFile.cs
UI tests that used dynamic project generation were causing a project upgrade when the project was loaded. This was due to ToolsVersion being incorrect. This forces it after the MSBuild has saved the file, since we couldn't figure out how to get msbuild to set the version in the first place.
> Fix dynamic project file generation in tests to force ToolsVersion="4.0"

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/__main__.py
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter/testlauncher.py
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/TestAdapterTests/Mocks/MockRunSettingsXmlBuilder.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
Add tests for test file usage.
`open` builtin on Python 2.7 doesn't take a `encoding` parameter. `io.open` works on both 2.7 and 3.7. I've removed the `< 2.6` conditional import since we haven't supported 2.5 for unittests in a while.
Fix #5534
> Fix reading of test file on Python 2.7.

- Python/Product/TestAdapter.Executor/Config/PythonProjectSettings.cs
- Python/Product/TestAdapter.Executor/Config/RunSettingsUtil.cs
- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/PythonTestDiscoverer.cs
- Python/Product/TestAdapter.Executor/Services/IPythonTestDiscoverer.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter/PythonRunSettings.cs
Changing runtime settings to write project/workspace info once for all sub testcontainers
-Now we also use a dictionary lookup, instead of linear search,  for verifying filepaths from discovery match a TestContainer.
> Changed discovery test warning 

- Python/Tests/TestAdapterTests/Mocks/MockRunSettingsXmlBuilder.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestData/TestDiscoverer/BasicUnittest/test_runtest.py
- Python/Tests/TestData/TestDiscoverer/ConfigUnittest/Product/prefix_not_included.py
- Python/Tests/TestData/TestDiscoverer/ConfigUnittest/Test/prefix_included.py
- Python/Tests/TestData/TestDiscoverer/ConfigUnittest/Test/test_not_included.py
Fix #5537 Add unittest discovery test for root dir and pattern
Fix #5494 Add discovery/execution test for unittest runTest()
Also fixes a test that was being ignored due to failing, it now passes
> Test discoverer and executor tests

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/discovery.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/info.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/pytest/_discovery.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/pytest/_pytest_item.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/report.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/util.py
- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/run_adapter.py
- Python/Product/TestAdapter/testlauncher.py
Grabbed the latest from VsCode. 
Eric Snow  Send "relpath" back for all test files/folders. (#6877)
Eric Snow  Make sure filenames are not norm-cased on Windows. (#6856)
Eric Snow Return relfile and location as-is (do no normcase). (#6781)
Kim-Adeline Miguel Fix overwriting of cwd in test discovery path list (#6713)
Rainer Dreyer Fixes pytest discovery: Not all pytest items have `own_markers` (#6514)
Min ho Kim Fix typos (#6470)
Eric Snow Show equivalent pytest command (#6363)
> Updating python test adapter with the latest version from vscode.

- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
adding commandline print to be at informational level instead and to do it always for unittest/pytest discovery and execution
> Changing commandline logging for test discovery and execution 

- Python/Templates/Core/ItemTemplates/Python/UnitTestFile/test.vstemplate
Fix #5592 
Now the default name will match both unittest and pytest file patterns.
ex: `test_1.py`
> Change default file name for unit test item template.

- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
that added another node called testsuites
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite errors="0" failures="1" hostname="MININT-K8R65DJ" name="pytest" skipped="0" tests="3" time="0.050" timestamp="2019-08-16T12:05:17.455766">
<testcase classname="test_pt" file="test_pt.py" line="0" name="test_pt_pass" time="0.000"> 
</testcase>
```
> fix missing pytest results due to pytest xml change 

- Python/Product/Common/Infrastructure/ProcessOutput.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
-Fixes the hang but not the underlining issue of why newline is coming back as a special character
-Changed ProcessOutput to wrap StreamReader in a using incase exceptions are thrown inside.
the last new line is coming back as not null but IMessageLogger.SendMessage thinks it is null and throws arugmentException
In bottle.py line 189
text = "Warning: Use of deprecated feature or API. (Deprecated in Bottle-%d.%d)\n"\
"Cause: %s\n"\
"Fix: %s\n" % (major, minor, cause, fix)
Fix #5531
> Partial fix for pytest test does not complete (bottle repo)

- Python/Product/TestAdapter.Executor/Pytest/TestResultParser.cs
- Python/Tests/TestAdapterTests/TestResultParserTests.cs
- global functions from a relative path didn't have the right pytestId
Fix #5598 
Fix #5603
Fix #5604
Fix #5605
> fix for no pytest result for flake8

- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/Services/PythonDebugMode.cs
- Python/Product/TestAdapter.Executor/TestAdapter.Executor.csproj
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Product/TestAdapter/PythonRunSettings.cs
- Python/Product/TestAdapter/testlauncher.py
- Python/Tests/TestAdapterTests/ExecutorServiceTests.cs
- Python/Tests/TestAdapterTests/TestAdapterTests.csproj
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Python/Tests/TestData/TestExecutor/Coverage/test_coverage.py
Fix #5444 
In order to avoid duplicating a bunch of code, I moved several methods from `TestExecutorUnitTest` to `ExecutorService` (as static methods) so it can be reused between both unittest and pytest execution code.
> Add support for code coverage for pytest.

- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/PythonTestDiscoverer.cs
- Python/Product/TestAdapter/PythonRunSettings.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
- Fix runsettings so that we dont write out the "Project" field until we know we can get a valid launch config.
- Added better null checking on the discoverer around missing or empty projectsettings.
Related:
Test explorer displays confusing error when Python environment is missing Fix #5614
> Fix Test explorer displays confusing error when Python environment is missing

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/PythonTools/PythonTools/Project/ConfigureTestFrameworkInfoBar.cs
- Python/Product/TestAdapter/TestContainerDiscovererWorkspace.cs
- Python/Product/VSInterpreters/Interpreter/IPythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Tests/Core/WorkspaceTestHelper.cs
Fix #5508 
Regex will handle most cases correctly, but it might encounter some edge cases it cannot correctly parse. For example, "test.test.py" or "test.txtfpp" result in false positives.
These cases will be correctly parsed:
> Implement exclude file regex for projects and workspace

- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
Issues: Pytest execute will search up the parent folders for a config .ini file which will change the rootdir from the project to the subfolder.  This will cause a mismatch between discovered test filepaths and results.
now force both disocvery  and execution to set the rootdir so that .ini location wont override it.
also note it appears the user can't set the rootdir from inside the .ini file
ie
addopt = --rootdir=XXX
or
rootdir = XXX
both appear to have no effect so it should be safe to force it to be the project/workspace location.
Users can still set "testpaths = testing" to optimize the search but the paths will be relative to the project/workspace dir from now on.
https://docs.pytest.org/en/2.8.7/customize.html
> pytest not found in azure-cli Fix #5626

- Python/Product/TestAdapter.Executor/Config/PythonProjectSettings.cs
- Python/Product/TestAdapter.Executor/Config/RunSettingsUtil.cs
- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/PythonTestDiscoverer.cs
- Python/Product/TestAdapter.Executor/Services/DiscovererFactory.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestExecutorUnitTest.cs
- Python/Tests/TestAdapterTests/TestDiscovererTests.cs
- Python/Tests/TestAdapterTests/TestExecutorTests.cs
testdiscovery session telemetry data relies on DefaultExecutorUri so we need 2 separate classes to get separate telemetry for unittest and pytest
Fix #5688
> fix testdiscoverysession telemetry 

- Build/16.0/packages.config
Fix #5700 as well as analyzer failing to start
Need to stay with the version that is used by the analyzer executable.
> Revert update of Newtonsoft.Json

- Python/Product/VSInterpreters/PackageManager/CondaUtils.cs
- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/python.h
- Python/Tests/ProfilingUITests/ProfilingUITests.cs
- Python/Tests/ProfilingUITestsRunner/ProfilingUITests.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
Fix #5683 
Fix #5341
I added version specific project profiling tests, to ensure that Python 2.7...3.8 are covered (and the 3.8 test fails without my changes)
> Add support for profiling on Python 3.8.

- Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Properly forward the QueryStatus to the next command filter when we don't handle a command.
Fix #5211 
Fix #2423
> Fix the start debugging command caption

- Python/Product/TestAdapter.Executor/Config/ITestConfiguration.cs
- Python/Product/TestAdapter.Executor/Pytest/PytestConfiguration.cs
- Python/Product/TestAdapter.Executor/Pytest/TestExecutorPytest.cs
- Python/Product/TestAdapter.Executor/Services/ExecutorService.cs
- Python/Product/TestAdapter.Executor/TestAdapter.Executor.csproj
- Moved pytest specific  execution arguments to its own config class
Fix #5609
> Cleanup Services\ExecutorService.cs of pytest specific code

- Common/Product/TestAdapter/TestContainer.cs
- Python/Product/TestAdapter/Model/ProjectInfo.cs
replacing testcontainer version number with cached timeStamp because on settings change, when we refresh, we are clearing all testContainers, so version was always being reset to 0 incorrectly.
Alternatively I could of changed refresh logic to not clear all testcontainers but I think this is simplier logic.
In the bug below what was happening on setting the pattern to test_1.py, both test_1 and test_2 were deleted and version numbers were both then rebuilt as 0 and their compare functions were returning 0 for no change, so Test Explorer thought it should keep test_2.py tests around.  But then discovery would only return tests matching test_1.py,
cannot discover the tests immediately after update the configuration in "Test" tab for unittest Fix #5734
> replacing testcontainer version number with cached timeStamp 

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/TestAdapter.Executor/Pytest/PytestExtensions.cs
- Python/Product/TestAdapter.Executor/Pytest/TestDiscovererPytest.cs
- Python/Product/TestAdapter.Executor/UnitTest/TestDiscovererUnitTest.cs
- Python/Tests/TestAdapterTests/TestAdapterTests.csproj
- Python/Tests/TestAdapterTests/TestDiscovererParseTests.cs
- Now that Test Explorer is no longer sending our discovery task a list of all sources, our logic around warning the user when tests are found in files not in the project is not valid.
- I spoke with Eric about incremental pytest, limiting discovery to just the source files that changed, but I still dont think its a good idea, because users can specify filename patterns in their pytest.ini and then when we pass files in to pytest as arguments they bypass those settings.
Fix #5743
> Removing "Test container source not found" warning

- Python/Product/TestAdapter.Executor/Pytest/JunitXmlTestResultParser.cs
- Python/Tests/TestAdapterTests/JunitXmlTestResultParserTests.cs
- German locales use commas for decimal points and period for thousand makers
- added testing around german locale
fix #5753
> fix TestExplorer displays wrong duration with pytest

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs
fix #5768 
- Adding a project reference was calling SearchPathManger.AddorReplace with isPeristed set to false
- normal right click add a serach path flow uses SearchPathManger.Add with persited set to true.
Setting  isPeristed to true will cause SearchPathManger.SavePathsToString to add the path to the list of saved setting values.
Note: removing a project reference still removes the search path.
> Python Projects losing Search Paths on reload

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs
This reverts commit f4243e09b47884bede88aada587dfc158eafe330.
there would be issues with c++ references being saved because they contain debug/release folders in the path.
> Revert "Python Projects losing Search Paths on reload fix #5768 (#5781)"

- Python/Product/PythonTools/PythonTools/Project/CondaEnvCreateInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/ConfigureTestFrameworkInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/PackageInstallInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/PythonInfoBar.cs
- Python/Product/PythonTools/PythonTools/Project/VirtualEnvCreateInfoBar.cs
- Moved the call to get the pythontoolssevice into the constructor of the base class so that is occurs on the mainthread
Invalid cross-thread call when opening workspace Fx #5617
> Info bar fix for cross thread call warning

- Python/Product/PythonTools/PythonTools/Project/InterpretersNode.cs
- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Now that we share packageManagers we can't call disablenotifications or dispose on it from the project scrope because we dont know if others are relying on it.
> Package manager stops working after closing project Fix #5795

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Tests/Core/WorkspaceInterpreterFactoryTests.cs
Fix #5811 
Replace ThreadHelper usage with a MEF import to avoid failure when running non UI tests.
> Fix new test failures

- Python/.editorconfig
Fix #5835 
Creating an editorconfig file to establish a coding stand and formatting the existing tests (under "tests" folder) to adhere to the new standard. 
You can see the main changes in .editorconfig. I used a tool with this .editorconfig to automatically format certain portions of the code base. You can look at these files for examples of what the new coding style is like. Once the PR is ready to be approved, I'll undo all the formatting changes and only merge in the .editorconfig file.
> Editorconfig and codebase cleanup

- Python/Product/Profiling/PythonProfiling.vsct
…to avoid conflict with attach to process menu item. The conflict was introduced when we moved the command from the analyze menu to the debug menu.
I checked that no other debug menu item used 'u' as its accelerator.
fix #5806
> Change accelerator key from 'p' to 'u' for launch profiling menu item

- Python/Product/EnvironmentsList/FileNameLabel.xaml
Text like "Visit the distributor's website" used 3 textblocks with 2 of them having width 0 but still being rendered. Now the style trigger will set empty textblocks to visibility collapsed
Fix #5864
> Accessibility fix: Hide unused textblocks in Environments Window

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/get_search_paths.py
- Python/Product/VSInterpreters/PackageManager/PipPackageManager.cs
- Python/Product/VSInterpreters/PythonLibraryPath.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
fix #5775 LSC: fallback to file/folder enumeration in pip package manager
fix #5844 LSC: after installing package, it does not appear in solution explorer
Re-enable some commented out code in PipPackageManager. Include copy of PLS implementation of PythonLibraryPath.cs and its dependent get_search_paths.py
> Package manager fixes

- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
Fix #5809 Unhandled exception in WorkspaceInterpreterFactoryProvider
Mark unrecognized versions of Python as 0.0 in workspace factory provider, like it is done by the registry factory provider (PythonRegistrySearch.cs). This avoids crashes later, for code that tries to convert interpreter version to Python language version.
Also allow debugging on unrecognized version ie 0.0.
> Fix crash on unrecognized/unsupported python versions

- Python/Product/PythonTools/PythonTools/Repl/Completion/ReplAsyncCompletionSource.cs
fix #5930 
Fix InvalidCastException caused by conflicting properties used by VS implementation of completions and REPL completion code.
> Fix REPL completion exception

- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/ReplDocument.cs
- Python/Product/PythonTools/PythonTools/Repl/Completion/ReplRemoteCompletionBroker.cs
- Python/Product/PythonTools/PythonTools/Repl/IPythonInteractiveIntellisense.cs
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs
Fix #5873 
REPL evaluator now takes care of initializing and shutting down language server, and that makes it easy to handle reset directly from the REPL evaluator implementation.
Also moved the initialization and ownership of that "stitched repl document" to the evaluator.
Pushed down the code that does the LS call for completion, from the broker to the "repl document", which simplified that REPL intellisense interface.
I've disabled language server and analysis completions for debug REPL. Well, before it was probably crashing, now it doesn't.
Ownership and responsabilities for debug REPL LSC stuff was quite bad before, hopefully it makes more sense now.
> Handle reset repl + changing repl environment

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Fix #5944 
Promote the code that used to execute for UWP projects only.
> Set the msbuild global platform variable to the active configuration platform

- Build/Common.Build.Core.settings
- Python/Setup/swix/Packages/file_associations.swr
Adding a temporary build property to update the registery file assocation value to point to VS16
typescrip had a similar issue
WorkItem
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/987704
PR
https://dev.azure.com/devdiv/DevDiv/_git/TypeScript-VS/pullrequest/204555?_a=files&path=%2FVS%2FSetup%2FVSIX%2FFileAssociations%2Fext.typescript.swr
Fix # 5411
Python file association - VS does not open the file when double click / Open With from Windows File Explorer
> Fix the VS16 file association for .py .pyw .pyi

- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContext.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
Fix intialization order of Python workspace object in relation to workspace interpreter factory provider. This fixes the workspace interpreter being incorrect for the first workspace that is loaded after VS has started. #5931
> Fix workspace interpreter on first load

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/pytest/_discovery.py
Handle missing pytest function by setting default attribute and printing error instead of throwing AttributeError
Fix #5968
> Handle missing pytest function

- Python/Product/Debugger.Concord/ExpressionEvaluator.cs
> Fix async get children in native debugger

- Build/16.0/packages.config
- Build/Common.Build.VSSDK.targets
- Common/Tests/Utilities.UI/UI/ExceptionHelperAdornment.cs
- Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
- Common/Tests/Utilities/TaskObserver.cs
- Python/Product/Debugger/Debugger.csproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Product/TestAdapter/testlauncher.py
- Python/Product/TestAdapter/visualstudio_py_testlauncher.py
- Python/Tests/DebuggerUITests/DebugProjectUITests.cs
- Python/Tests/DebuggerUITestsRunner/DebugProjectUITests.cs
Fix #6051
`BoundBreakpoint` test fails but it is unrelated to this change (fails with legacy debugger too). Will retest whenever I can successfully build on 16.6. https://github.com/microsoft/PTVS/issues/6059
> Update from debugpy 1.0.0 b1 to b3

- Python/Product/PythonTools/PythonTools/Navigation/CodeWindowManager.cs
Fix #6061
If navigation bar option is off, it was trying to `Unadvise()` on a cookie that wasn't initialized aka `Advise()`.
> Prevent exception when closing file

- Python/Product/Profiling/Profiling/SessionNode.cs
Fix #6042 
Change itemid type to int instead of uint for VSHPROPID_FirstChild and VSHPROPID_NextSibling in profile explorer to fix a regression in expansion of tree nodes.
VS got more strict for the type of those properties.
They should accept both int and uint, and will likely get back to doing that, but until then, int is apparently the more correct type to return, so it's best to change it.
> Fix profiling tool window tree node expansion

- Python/Product/PythonTools/PythonTools/Environments/VirtualEnv.cs
new versions of python >= 3.8 from the windows store have a different executable name (ie. python3.8.exe) in the registry InstallPath, compared to what is in the venv folder (python.exe) so search for both if interpExe is not found.
Fix #6082
> fix for python 3.8 from microsoft store failing to add new venv

- Python/Product/BuildTasks/Microsoft.PythonTools.targets
Fix #6113 
Fix verified on the latest available version of pylint on both Python 2.7 and 3.x.
> Fix pylint command 

- Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs
After fixing up our policy build, it started reporting this static analysis error. It is safe to disable since that's just an internal utility that we use for the building of PTVS source code.
> Prevent localization related static analysis check in the Xaml build utility

- Build/PoliCheckExclusions.xml
I've already run the policy pipeline and verified that this excludes all the miniconda related warnings.
This exclusion file is specified as a parameter to the policheck azure devops pipeline task.
> Add policheck exclusion file.

- Build/PoliCheckExclusions.xml
The localization team is in charge of doing PoliCheck on their translations, and they have told us we should exclude them from our PoliCheck task (which uses the English term table).
> Add .lcl files to PoliCheck exclusions.

- Python/Product/PythonTools/PythonTools/Environments/UserSpecifiedCondaLocator.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
- Python/Tests/Core/PythonWorkspaceContextProviderTests.cs
Remove UI thread dependency from the MEF constructor, which was a violation of threading guidelines.
Ensure we are on UI thread in `OnActiveWorkspaceChanged`.
Fixes internal bug 1168894
> Fix deadlock when loading a workspace.

- Python/Product/VsPyProf/PythonApi.cpp
- Python/Product/VsPyProf/python.h
Trivial fix to allow profiling (I compared CPython 3.8 and 3.9 header files, there were no changes to the C structures we redefine in our python.h between the 2 versions).
> Allow profiling on Python 3.9.

- Build/16.0/packages.config
NuGet package now has enum members for versions 3.9, 3.10, 3.11.
That means we can now properly detect Python 3.9 as version 3.9 (instead of 0.0).
- Banner warning now appears for 3.9
- Package manager works correctly for 3.9
Fix #6049
> Update to newer Microsoft.VisualStudio.Python.LanguageServer version.

- Python/Product/PythonTools/PythonTools/Options/LanguageServerOptionsControl.Designer.cs
They were lost when I added the new checkbox for Disable IntelliSense, probably when I got rid / moved controls out of the groupbox.
Fix #6206
> Add the missing event handlers for the textbox and button in language server option page.

- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
Use our own FileWatcher class instead of FileSystemWatcher, to avoid deadlock on dispose.
See https://github.com/microsoft/PTVS/blob/master/Common/Product/SharedProject/FileWatcher.cs#L112
Fix #6203
> Fix deadlock when adding python file to empty workspace

- Python/Product/PythonTools/PythonTools/Environments/UserSpecifiedCondaLocator.cs
- Python/Product/VSInterpreters/Interpreter/PythonWorkspaceContextProvider.cs
- Python/Tests/Core/PythonWorkspaceContextProviderTests.cs
We may have to fix this in 16.7 servicing release, so preparing the backport in case.
> [16.7] Fix deadlock when loading a workspace.

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugPort.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugPortSupplier.cs
- Python/Product/Debugger/Debugger/DebugEngine/Remote/PythonRemoteDebugProgram.cs
- Python/Product/Debugger/Debugger/IPythonDebugOptionsService.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterRemoteProcess.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugPyVersionHelper.cs
- Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebugOptionsService.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.resx
- Python/Product/PythonTools/PythonTools/PythonAutomation.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
- Python/Product/PythonTools/PythonToolsService.cs
Remove legacy debugger option. Does not remove actual code, only Tools | Options related part. Also removes options that are configured in Pylance differently.
> Remove legacy debugger option

- Common/Product/SharedProject/ProjectNode.cs
We already do the same elsewhere in the same file.
Fix #6289
> Don't assert if one of the event sink does not implement OnPropertyChanged

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Wpf/ModernStyles.xaml
VS fixed the use of ThemedDialogTextBoxStyleKey in 16.9 (internal bug 1198412) so we can now use it.
Also remove some unnecessary style attributes.
> Minor add environment dialog style cleanup

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PylanceLanguageServer.cs
We used to bundle the dist folder of packages\vscode-pylance but now it's packages\pylance, and the server startup file is different on that one.
> Update the pylance startup file.

- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
- Python/Product/PythonTools/PythonTools/Options/DebuggerOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.resx
Fixes #6334
Fixes #6342 
Definitely open to UI changes or approvals if we need, I'm not familiar with the process.
Here's what it looks like:
It also fixes the immediate window from showing too much information:
> Customize variable presentation using tools options page

- Python/Product/Debugger/Debugger.csproj
- Python/Product/Debugger/Debugger/IPythonDebugOptionsService.cs
- Python/Product/Debugger/Debugger/PresentationMode.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterLauncher.cs
- Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugInfo.cs
- Python/Product/PythonTools/PythonTools/Options/PythonDebugOptionsService.cs
Fixes #6369 
This is a fix for a regression I introduced when reading variable presentation options from the options page. The bug occurs when attaching to a remote debugpy process instead of launching the debugger directly, which is a case I did not test.
> Use global debug options instead of project-specific ones

- Build/16.0/nuget.config
- azure-pipelines.yml
This yaml will drive our CI and PR builds once we create a new AzDO pipeline that consumes it. Right now, the file is not being consumed, but it must be in the repo before it can be used by AzDO 😄 
This yaml should be functionally equivalent to the old classic build definition. The only difference is that both CI and PR builds are enabled, and PR builds only perform a subset of the build steps, for speed.
The yaml build was tested at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4442296&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9 and seems to be working just fine.
> Added azure-pipelines.yml to replace the classic AzDO pipeline

- Python/Product/EnvironmentsList/EnvironmentView.cs
- Python/Product/EnvironmentsList/Resources.Designer.cs
- Python/Product/EnvironmentsList/Resources.resx
- Python/Product/EnvironmentsList/ToolWindow.xaml
For bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1243179
Make the automation name for the list view item include the word 'broken' if the environment is busted.
> Fix automation name for strikethrough environments

- Python/Product/PythonTools/ProvideEditorExtension2Attribute.cs
Fixes #6304 
Fixes #6402 
Apparently all editors were opted-in by default to this by the Editor team a while ago, and Python was probably missed.
From an email chain: "Basically that means until C# projects are loaded and analyzed (ready to provide intellisense), opening any document whose chosen editor factory has not opted out of DeferUntilIntellisenseIsReady is blocked (by showing the “Waiting for IntelliSense to finish initializing…” wait frame). The recommendation is for all text editor based editor factories (not designers) to opt out of DeferUntilIntellisenseIsReady (even C# editor factory is opting out)."
> Disable DeferUntilIntellisenseIsReady

- Common/Product/SharedProject/CommonProjectNodeProperties.cs
- Common/Tests/Utilities.UI/TestUtilities.UI.csproj
- Common/Tests/Utilities.UI/UI/EditorWindow.cs
- Python/Product/Core/Core.csproj
- Python/Product/Core/Properties/AssemblyInfo.cs
- Python/Product/Core/source.extension.vsixmanifest
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/LanguageServer.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
- Python/Tests/Core.UI/IntellisenseTests.cs
- Python/Tests/Core.UI/PythonToolsUITests.csproj
- Python/Tests/PythonToolsUITestsRunner/IntellisenseTests.cs
- Python/Tests/PythonToolsUITestsRunner/PythonToolsUITestsRunner.csproj
For: https://github.com/microsoft/ptvs-pylance/issues/96
Implemented support for filewatchers with either the workspace object or the System.IO.FileWatcher class (for solutions).
Also fixed a bug when opening a single project that confuses the 'workspace' for pylance (rootPath should not be set when using workspaceFolders)
Added a UI test to verify pylance is working.
I'd like to do more testing after this to verify all scenarios are working, but this is the base file watching support.
> Implement support for watching files

- Python/Prerequisites/deploy_test_targets.cmd
- Python/Product/BuildTasks/BuildTasks.csproj
- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Core/Core.csproj
- Python/Product/Core/Properties/AssemblyInfo.cs
- Python/Product/Core/source.extension.vsixmanifest
- Python/Product/Debugger/Debugger.csproj
- Python/Product/Django/Django.csproj
- Python/Product/EnvironmentsList/EnvironmentsList.csproj
- Python/Product/Profiling/Profiling.csproj
- Python/Product/ProjectWizards/ProjectWizards.csproj
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/TestAdapter.Executor/TestAdapter.Executor.csproj
- Python/Product/TestAdapter/TestAdapter.csproj
- Python/Product/VCDebugLauncher/VCDebugLauncher.csproj
- Python/Product/VSCommon/VSCommon.csproj
- Python/Product/VSInterpreters/VSInterpreters.csproj
- Python/Product/Workspace/Workspace.csproj
- azure-pipelines.yml
This didn't matter when the VS Interop was the same version as was shipped in VS
I upgraded this morning and our VS interop is older and the Solution Explorer broke when our package loads (it was loading the VS interop from our extension folder first)
We don't need to ship this and just consuming the types should be fine.
> VS interop should not be included in our VSIX

- Build/16.0/nuget.config
- Build/17.0/nuget.config
- azure-pipelines.yml
Make sure to use a single package source for nuget feeds. 
I'll back port this to 16.10 after the build passes.
> Use single package source

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/WorkspaceConfiguration/ConfigurationArgs.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/WorkspaceConfiguration/ConfigurationItem.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/WorkspaceConfiguration/ConfigurationParams.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Change to responding to 'workspace/configuration' so that we can have a different interpreter per project.
> Support the 'workspace/configuration' message from Pylance.

- Python/Product/PythonTools/PythonTools/Project/PythonProjectPackage.cs
Fixes: #6546 
The package registration for the custom editor extension was also adding the template dirs. I used a different one instead.
> Fix new item templates not being used

- Build/17.0/packages.config
- Build/Common.Build.CSharp.targets
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
- Python/Tests/Core.UI/EnvironmentListTests.cs
- Python/Tests/Core.UI/PythonToolsUITests.csproj
- Python/Tests/Core/PythonToolsTests.csproj
Seems like references can't be found from the actual build environment. We have to explicitly download all of our references now.
This PR adds the missing modules so that you can build locally.
> Fix building with D17

- Build/17.0/packages.config
- Build/PreBuild.ps1
- Build/nuget.config
Hopefully this will fix the symbol publish error here:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1331578/
The root cause (or at least one of the causes) was that the pdbs for the Microsoft.Python.Parsing dlls were portable pdbs. The symbol archiver in the build doesn't support portable, only windows pdbs.
> Add conversion step for python.parsing pdbs

- Build/17.0/packages.config
- Build/Common.Build.CSharp.targets
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Logging/LogHubLogger.cs
At a recent meeting with the LSP team in Visual Studio, it was suggested that all ILanguageClient implementers should use LogHub logging.
I followed the directions here that they suggested:
https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/23437/Using-LogHub
> Add LogHubLugging for python tools events.

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/DidChangeWatchedFilesRegistrationOptions.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/FileSystemWatcher.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
ILanguageClient is changing (well because it can) and we need to change with it.
Fixes: #6609 
Tested with bits here:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=4998492&view=ms.vss-build-web.run-extensions-tab
However we need to wait for that submission to go into main (or put this submission in at the same time) before we finish the PR into VS main.
Miguel should provide a branch we can insert into after Wednesday.
> Add support for ILanguageClient new methods

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/LandscapePortraitConverter.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355288
When in portrait mode dialog looks like this:
and this
> Support portrait mode on the add environment dialog

- Python/Product/EnvironmentsList/EnvironmentView.xaml
for the Open Interactive Window button.
Use the fact that narrator will concat  Automation Name and HelpText automatically if both present
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties
internal bug 1362535
> Fix for Narrator not mentioning the corresponding environment 

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
Now forcing a selection of label "IsDefaultMessage" after button press, and triggering narrator to update in the code behind so that it reads "This is the default environment for new projects".
fix internal bug 1351252
Actual Result:​
Narrator/NVDA is not announcing the status (This is the default environment for new projects) which is available on screen on selecting 'Make this the default environment for new projects' button.
Expected Result:​
Narrator/NVDA should announce the status as "This is the default environment for new projects" after selecting 'Make this the default environment for new projects' button.
> fix for narrator in packages windows.

- Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
- Python/Product/EnvironmentsList/EnvironmentView.xaml
- Python/Product/EnvironmentsList/PipExtensionProvider.cs
there was an accessibility issue around using names that include 'Microsoft.*.*'
Added a ToString() function on the view's to override the Name to the localized version.
ie. "Overview" and "Packages (PyPi)"
Fix #6661
> Class name was being used for the ListBoxItem's Name field

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.resx
- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.resx
Fixes: #6667
Old dialog looked like this:
New dialog looks like this:
> Fix size of controls to allow for localization

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Navigation/Navigable/NavigableSymbolSource.cs
- Python/Product/PythonTools/PythonTools/Repl/Completion/AsyncCompletionSourceProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
- Python/Product/PythonTools/PythonToolsService.cs
Fixes: #6668 
Basically don't wait on the repl when opening the window.
Also made sure to actually load the language server even when a python file isn't open (the reason I wasn't able to repro this was I had a python file already open in my solution). Prior to this change, the language server would only load for straight .py files and not if you opened the interactive window by itself.
> REPL window is hanging because of waiting for language server to start

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/LandscapePortraitConverter.cs
- Python/Product/PythonTools/PythonTools/Environments/ScreenAdjustingConverter.cs
- Python/Product/PythonTools/PythonTools/Wpf/Utilities.cs
Second pass for:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1355277?src=WorkItemMention&src-action=artifact_link
Here's what it looks like at 200% scaling and 1280x800
1920x1080 and 200%
> Respond to different screen widths and scaling for AddEnvironment dialog

- Python/Product/VCDebugLauncher/16.0/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/17.0/source.extension.vsixmanifest
Increment version numbers for VCDebugLauncher VSIX manifest.
> Fix #6712: The option "Python/Native Debugging" is missing.

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
fixes keyboard arrows not scrolling when zoomed.
Changes:
- fixed by adding a height value to the scroll `Height ="300"`
- added a stackpanel for better alignment.
- reformatted doc
internal issue 1355277
Conda environment_Resize Text: Content present in 'Packages preview' section is not visible at different zooming conditions (150%, 175%, 200%).
> fix addcondaenvironment window scroll with keyboard, when zoomed

- azure-pipelines.yml
Fix an error with publishing symbols. This was suggested over email from VSEng and it seems to be working fine. 
Manually verified by running a full build from the PR branch at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5455245&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=8e355ed5-37f3-5c2a-bb8d-5efc727482d6
> try to fix publish symbols step

- Python/Product/BuildTasks/Microsoft.PythonTools.targets
Fixes #6747
This targets file is imported by the pyproj template, so any pyproj files (new or existing) will get the fix once the user updates Visual Studio and gets the latest Python Tools workload.
Tested though both msbuild and visual studio, and the error is now gone.
> Override target framework version to 4.7.2, since the default (4.0) is not supported in VS2022.

- Build/nuget.config
- Build/templates/restore_packages.yml
- azure-pipelines-policy.yml
- azure-pipelines.yml
Fixes #6866 
This change moves from the nuget multi-feed approach to the single azure artifacts feed, which is safer (and now required).
Build has been tested at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5710837&view=results and the restore packages step worked, which is what needed to work.
The build also runs the `Nuget Security Analysis (auto-injected by policy)` step, and shows no errors.
> Move to azure artifacts feed

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
This commit adds BoldActiveEnvironment() to the end of ActiveInterpreter setter to bold the active environment properly.
I did a few tests to verify the change:
1. Switch from one environment to another:
2. The global default interpreter will be activated after deleting all environments.
3. Add a new environment to the list and activate it.
4. Delete all the envs so only the global default remains. Then add a new one.
> Fixing Issue #6636

- Python/Product/PythonTools/PythonTools/Environments/AddEnvironmentDialog.xaml.cs
This pull request fixes internal issue #1486766 and #1486787 where after invoking the add environment dialogue box, the focus is on the second element of that page.
The focus is now on the first element after opening the environment dialogue box.
> Fixes the internal issue where after invoking add environment dialogue box, focus is directly on second element.

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
This PR fixes internal issue #1486790 where no name property is provided for Packages preview pane.
Previous in Accessibility Insights:
Now:
> fixes internal issue #1486790

- Python/Product/EnvironmentsList/PipExtension.xaml
This PR fixed internal bug #1489308 where focus is not clearly visible on remove packages button.
Currently the background color of the button will change and become more visible when focus is on it.
> Fix internal bug #1489308

- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
Fixes #6904 
This bug seems to be due to a race condition on the _rpc instance in the file listener. Since all calls using the rpc are async, the _rpc_Disconnected callback (which sets _rpc to null) can be triggered at any time during or between these calls.
The crash happens in two different ways, depending on the timing:
1. The _rpc is set to null in between rpc calls. This causes a NullReferenceException the next time the rpc is attempted to be used. 
* The solution for this is to check for null before using it, every time. While this doesn't technically eliminate the race condition (since we're not using a mutex), the chance of an NRE is very small.
3. The _rpc is disposed during an rpc call. This causes the rpc call to throw a ConnectionLostException, which was unhandled. 
* The …
> Fix VS crash when creating virtual environment

- Python/Product/Common/Common.csproj
- Python/Product/Common/Infrastructure/JsonRpcWrapper.cs
- Python/Product/Common/Infrastructure/TaskExtensions.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
I fixed these previously in the Listener but I was able to consistently repro the same issues in the PythonLanguageClient, so these need to be caught there too.
I know there's a better way to generically handle this exception for all these different rpc calls, but that code ended up really messy so I opted to just duplicate the try catch since there's only a few of them. If anyone has any ideas on how to wrap each of the calls without it being super ugly, I'm all ears 😄
> Fix crashes due to rpc connection being lost

- Python/Product/TestAdapter.Executor/Pytest/PytestTestDiscoverer.cs
This PR fixes issue #6836.
Changes made in this PR:
- Follow pytest usage: ```pytest [options] [file_or_dir] [file_or_dir] [...]``` to get rid of ```rootdir=``` when specifying the tests root directory.
- Specify the tests root directory in ```PytestTestDiscoverer``` if ```UnitTestRootDirectory``` is set in config file.
Tests:
- ran the test for RunPytestSubmoduleWithIniAndDiscovery
- test pytest.ini in a sub-folder
- config file with no  ```UnitTestRootDirectory``` specified:
- config file with different  ```UnitTestRootDirectory``` specified:
> Fix UnitTestRootDirectory setting not working in PythonSettings.json 

- Python/Product/TestAdapter.Executor/Pytest/PytestTestDiscoverer.cs
This PR reverts the commit I did for this issue: #6948 and this [PR](https://github.com/microsoft/PTVS/pull/6948).
The `UnitTestRootDirectory` property in PythonSetting.json should only be used to configure unittest, and should be ignored for pytest.
Check [this doc](https://github.com/microsoft/PTVS/pull/6948) for pytest configuration. Tests below use `pytest.ini` as an example to config pytest test directory.
Extra tests are performed to verify pytest works in VS and resolve the issue #6952.
1. Folder View
- ![folder_view_1](https://user-images.githubusercontent.com/100439259/162498929-97d950b3-7d1b-473e-939e-44912a3ded02.png)
- ![folder_view_2](https://user-images.githubusercontent.com/100439259/162498931-a558a400-e84f-42bb-9aca-a617a8e1b094.png)
- …
> Undo changes I made for specifying pytest test directory.

- Python/Product/Core/source.extension.vsixmanifest
PythonTools were triggering a watson/fault in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1505871 due to the duplicated Microsoft.VisualStudio.Assembly,Microsoft.PythonTools.ProjectWizards.dll asset. This asset has already been referenced earlier in the file via a reference to the project itself.
> Remove duplicated VSIX asset

- Python/Product/Common/Infrastructure/ProcessOutput.cs
- Python/Product/PythonTools/PythonTools/Editor/Formatting/LspDiffTextEditFactory.cs
- Python/Product/PythonTools/PythonTools/Editor/Formatting/PythonFormatter.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs
This PR fixes issue #6785 
Formatters in PTVS were not able to format special characters such as Chinese and Germany characters correctly. Not sure what encoding/decoding is used on PTVS/formatter end, which might be the cause, so pass in UTF-8 to decode patch returned from formatters.
Test 1:
Test 2 with Black:
Test 3 with autopep8:
Test 4 with yapf:
> Fix formatter not formatting special characters

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Fixes #6977 
This bug only happens when the user manually installs a conda environment, but doesn't install python that environment. This fix makes it so conda environments that do not have python installed do not show up anywhere. Installing python in the environment and reloading the solution will cause the environment to show up as normal.
> Don't try to show conda environments that do not have python installed

- Python/Product/Profiling/Profiling.csproj
- Python/Product/Profiling/Profiling/CustomPythonInterpreterView.cs
- Python/Product/Profiling/Profiling/StandaloneTargetView.cs
- Python/Product/Profiling/PythonProfilingPackage.cs
- Python/Product/VSInterpreters/Interpreter/LaunchConfigurationUtils.cs
fixes #6769 
The issue was caused by two reasons:
- The `Interpreter Path` is entered after `Python Interpreter`, so the interpreter properties including id, name, and path never get updated. Manually set the properties in `Interpreter Path` setter to handle to ordering issue.
- The `CanSpecifyInterpreterPath` is not set correctly after constructing the custom python interpreter, so `InterpreterPath` is always returned as `null` from `GetTarget()`
Some tests:
1. Custom interpreter
2. Existing interpreter
3. Open project
> Fix profiling standalone script error

- Python/Product/Profiling/Profiling.csproj
- Python/Product/Profiling/Profiling/ProfiledProcess.cs
- Python/Product/Profiling/getArch.py
fixes #6775 
The issue was that PTVS tries to get the architecture of the python interpreter and use that to determine which dll to use for profiling, but it's getting an access denied when trying to call `kernel32.GetBinaryTypeW` when pointing at the windows store install. So I added extra call to get Python print out its architecture.
Note that the python script I added can only distinguish between 32bit and 64bit, but it can't distinguish between ARM64 and AMD64.
I have tested with 32bit python from python.org, 64bit python from python.org, python downloaded from Windows Store, python 3.6, 3.7, 3.8, 3.9, 3.10.  Hope that can capture all the scenarios.
> Add python script to detect python architecture

- Python/Product/Common/Parsing/PythonLanguageVersion.cs
- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/Commands/ImportCoverageCommand.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Project/PythonNotSupportedInfoBar.cs
- Python/Product/VSInterpreters/Interpreter/AstPythonInterpreterFactory.cs
- Python/Product/VSInterpreters/Interpreter/PythonRegistrySearch.cs
- Python/Product/VSInterpreters/Interpreter/WorkspaceInterpreterFactoryProvider.cs
- Python/Tests/VSInterpretersTests/VSInterpretersTests.cs
Fixes #7009
To repro this, I installed python 3.11 beta from python.org. Then I commented out `V311` from the `PythonLanguageVersion` enum and verified that `ToLanguageVersion()` returned `PythonLanguageVersion.None`, which is what we would expect if the version is not supported. This breakpoint gets hit when the installed environments are being enumerated (which is used to populate the environments window).
Then I added python 3.11 as an existing environment and activated it. I saw the environment in the project just fine. I got a warning in the debugger output about breakpoints might not hit, but they did. Profiling didn't work, but the error is "graceful"
So I think this fix is viable. VS no longer crashes, I'm able to add 3.11 as an existing environment, as well as a virtual …
> Fix VS crash when user's Python version is not in PythonLanguageVersion enum

- Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptions.cs
fixes #6831 
This option is now remain checked after restarting Visual Studio.
> Save "Ignore system-wide PYTHONPATH variable" option when closing Visual Studio.

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Fixes #7013
I was unable to repro this bug, and Watson didn't really give me any more information besides the line that causes the exception. So I just made sure we don't allow the conda environment (nor its associated configuration) to be null. This will prevent the NRE from being thrown.
> fix VS crash with bad conda environments

- Python/Product/Common/Core/OS/ProcessServices.cs
- Python/Product/VSInterpreters/PythonLibraryPath.cs
When trying to open a solution containing a windows store python environment, we get an `Access is denied` when trying to run the python.exe within it. There's no good workaround for this that I know of. This prevents the project from loading in the solution explorer, and the user has to manually reload it.
So this change catches the `Win32Exception` thrown when this happens and defaults to no search paths, similar to what happens if the `get_search_paths.py` file isn't found. This causes the project to load correctly.
> Fix solution load when project contains windows store python environment

- Python/Tests/Utilities.Python/TestUtilities.Python.csproj
Related to #7039, but does not fix it completely.
This PR contains two fixes:
1. This vsix contains common code referenced by other integration tests packages. It was not being generated nor being installed into the Exp hive, so the other UI tests were erroring out with assembly load errors. Now we do build and deploy it, but the assembly load errors persist, leading to the next step
2. Even with the vsix being deployed, it didn't include dependencies, so we still got the assembly load errors. We had to make sure the project references were included in the vsix as well.
With these two steps done, the assembly load errors are gone. Many integration tests are still failing, but those can be fixed on a case by case basis.
> Deploy TestUtilities.Python vsix so other integration tests packages can see it

- Python/Product/Cookiecutter/Cookiecutter.csproj
- Python/Product/Cookiecutter/Model/GitClient.cs
- Python/Product/Cookiecutter/Model/GitRunException.cs
- Python/Product/Cookiecutter/Strings.Designer.cs
- Python/Product/Cookiecutter/Strings.resx
- Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
fixes #6872 
Print out the error when user fails to clone Cookiecutter templates because git is not installed or not on the PATH.
Here's what happens after the fix:
When git is installed and on the PATH:
When it's not installed or on the PATH:
> Output the error when git is not installed or not on the PATH

- Python/Product/PythonTools/PythonTools/Repl/Completion/AsyncCompletionSource.cs
fixes #6943
See response under this issue. Wrong `ITextSnapshot` object is passed to `ToSnapshotSpan()`, which throws and `ArgumentOutOfRangeException` when the line number and snapshot.length doesn't match.
Now the intellisense is working again properly in interactive window with this fix:
> Fix intellisense not working in interactive window

- Python/PythonTools.sln
Get rid of the annoying need to set the default startup project every time you open the .sln with no .suo file present (after a git clean, for example)
> set default startup project to core

- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PythonTools/ptvsd/repl/__init__.py
There are small typos in:
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PythonTools/ptvsd/repl/__init__.py
Fixes:
- Should read `occurred` rather than `occured`.
- Should read `communicated` rather than `communucated`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/LanguageServerSettings.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.resx
fixes #7107 
fixes #7105 
Update the settings in PTVS to match what Pylance currently has. See https://github.com/microsoft/pyrx/blob/bcfcc39bdb1fd85fcbf2eb0fc19f657bc2a2f2d3/packages/vscode-pylance/package.json#L883
Two new settings are now visible to users:
- Indexing
- Import Format (Note that this new enhancement is not in the stable version yet, it's only tested on prerelease pylance)
Absolute:
Relative:
Just creating the PR for now, will wait until import format is in pylance stable to merge it in.
> Add some new settings to PTVS

- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Fixes #7137
This fixes a bug where the version being returned for a Conda python environment was wrong. It was taking the first package that had "python" in the name, not doing an exact match on "python". Works like a charm now.
> Look for package named 'python' when getting conda envinronment version

- Python/Product/DebuggerHelper/DebuggerHelper.vcxproj
- Python/Product/DebuggerHelper/DebuggerHelperX86.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttach.vcxproj
- Python/Product/PyDebugAttach/PyDebugAttachX86.vcxproj
- Python/Product/VsPyProf/VsPyProf.vcxproj
- Python/Product/VsPyProf/VsPyProfX86.vcxproj
This PR addresses the binskim compliance issues at https://devdiv.visualstudio.com/DevDiv/_queries/query/?wiql=%20%20%20%20%20SELECT%20ID%2CSeverity%2CState%2C%5BAssigned%20To%5D%2CTitle%20FROM%20WorkItem%20WHERE%20Tags%20Contains%27TSA%239718578-Python%20VS%20IDE%20PTVS-BinSkim-52695775%27%20%20%20%20%20
- For ControlFlowGuardCheck, `/guard:cf` needs to be passed on both the compiler and linker command lines. I saw a dropdown option in VS project properties for the compiler, but I didn't see one for the linker, so I added it explicitly.
Compiler:
Linker:
- For EnableSpectreMigrations, just set a compiler flag:
However, you also need to install C++ libs that support Spectre Mitigrations so this flag can select the appropriate libs to use. This is done through the VS installer, and you …
> Fix binskim compliance issues

- Python/Product/Cookiecutter/Model/FeedTemplateSource.cs
- Python/Product/Cookiecutter/Model/GitHubClient.cs
- Python/Product/Debugger/Debugger/Transports/WebSocketTransport.cs
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/ProjectWizards/CookiecutterWizard.cs
- Python/Product/PythonTools/PythonTools/Project/FtpPublisher.cs
- Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageCache.cs
Fix semmle warnings at https://devdiv.visualstudio.com/DevDiv/_queries?tempQueryId=bdca2043-7ac3-4421-93d8-88acb6ee3405
Most have to do with checking the revoked cert list when creating web requests, but there is also a missing null check.
> Fix CodeQL static analysis compliance warnings

- Python/Product/BuildTasks/Microsoft.PythonTools.targets
fixes #6864 
A small PR to close this issue out. 
Tested through both msbuild and visual studio, and Python project can be created and opened without errors.
Also found a reference on targeting an application to run on the specified  .NET framework version: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019
> Remove TargetFrameworkMoniker from targets file

- Python/Product/PythonTools/PythonTools/Editor/Formatting/LspDiffTextEditFactory.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs
- Python/Tests/Core/PythonFormatterTests.cs
Fixes #6752
- Removes the offending line from the diff we get back from the formatter
- Properly dispose of the ITextEdit when applying edits
> Fix formatter crash when file doesn't end in newline

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
fixes #7115 
Pylance used to require a new open notification after a workspace folder change (not sure if it still requires now). The code in `PythonLanguageClient.cs` was a requirement of pylance to force a reopen on all documents whenever the current workspace folder changed (opening a solution would provide the base folder for the workspace).
This makes sense in VSCode, because VS Code allows you to open multiple folders at a time. So adding or removing WorkspaceFolders makes sense there. But in VS, it does not support opening multiple workspace folders at the same time. When you close the current workspace (i.e. close all open folders) and open a new one in VS, we just start a new instance of Pylance.
The [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/ls …
> Remove extra didOpen message sent from our end

- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentView.cs
fixes https://github.com/microsoft/PTVS/issues/7172
Per discussion in the scrum meeting, we no longer support creating custom environments for the python versions < 3.7.
Only officially supported python versions are supported: https://devguide.python.org/versions/
> Dropping support for creating custom environments for older Python versions

- .github/workflows/issues.yml
Add new PTVS issues to the [Triage list](https://github.com/orgs/microsoft/projects/145/views/17) automatically. Logic is the same as [the similar action in pylance-release](https://github.com/microsoft/pylance-release/pull/3427).
I'll request the `PROJECT_BOARD_ACTIONS_TOKEN` secret from github-operations in parallel to this PR.
@judej
> Action to add new issues to scrum board

- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentOperation.cs
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentView.cs
- Python/Product/PythonTools/PythonTools/Environments/VirtualEnv.cs
fixes #6718 
There are 2 separate issues under this ticket.
1. In project view, the newly created environment will always replace the global default, whether "set as current" is checked or not, so I added some checks to disable the checkbox when user is using the global default environment. 
2. In folder view, the newly created environment will always be the current environment, whether "set as current" is checked or not, so I added some checks to fix it.
Some tests I ran:
- Project view - when using global default environment
- Project view - when not using global default environment & set as current
- Project view - when not using global default environment & not set as current
- Folder view - set as current
- Folder view - not set as current
> Fix set as current option in virtual environment creation

- Build/PreBuild.ps1
When trying to pull the latest pylance into the public feed, I noticed that just running `npm install` without deleting the `node_modules` folder didn't install the latest pylance if there was one already there.
So we just delete the `node_modules` folder, if it exists, before calling `npm install`
> Ensure PreBuild always installs latest pylance

- Python/Product/PythonTools/PythonTools/LanguageServerClient/LanguageServerSettings.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
There are changes needed on the pylance side to pipe these settings through (see https://github.com/microsoft/pyrx/pull/2899).
Adding them to PTVS first won't break anything, since they are not used in pylance yet.
> Add task list tokens to settings retrieved from pylance via getConfiguration

- Common/Product/SharedProject/ProjectResources.resx
- Common/Product/SharedProject/Utilities.cs
- Python/Product/PythonTools/VisualStudio.Project.resx
These characters are actually valid in file names, and the restriction is being dropped removed from Solution Explorer which previously blocked this. After that block has been removed, there is a further block inside Python tools that prevents files, folders and projects to be renamed to contain these characters.
Note: Unlike other projects, Python had already allowed "&" despite the error message not being updated to reflect that.
See: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/431541
> Allow '%', '&', '#' in file names in Python projects

- .github/workflows/stale.yml
Add a bot to close the 'waiting for response' issues after 30 days inactivity.
fixes #7344
> Add bot to repo that closes stale issues

- Python/Product/VCDebugLauncher/17.0/source.extension.vsixmanifest
- Python/Product/VCDebugLauncher/VCDebugLauncher.csproj
Fixes #6712
We had a remaining hardcoded `v160` install path for the `VCDebugLauncher` vsix that was causing files to be installed to the wrong location. These files were xaml files that add UI to Visual Studio, and our targets file was trying to include these files from the `v170` location, if they exist.
The problem is that they never exist because they go to the wrong place, which means the mixed mode debugging option is always missing from VS2022. This fixes that problem.
Unfortunately, this problem doesn't repro when building locally and deploying to the exp hive, it's a "VS Setup Only" problem. So I can't really test to make sure that this works before merging in this PR. The steps to test are:
1. Merge in this PR
2. Wait for the CI build to finish from the main branch
3. Wait for …
> Restore missing mixed-mode debugging option

- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- ignore VS temp files starting with ~
- ignore pycache folders
- fix pylance crash by removing TextDocumentDidClose and TextDocumentDidOpen on rename.. LSP client sends this. Plus we we're sending an incomplete textDocumentItem on open. we were missing the content causing Pylance to crash.
- delay settings change by 5 seconds
- fix dispose crash relayed to calling GetService()
fixes https://github.com/microsoft/PTVS/issues/7068
note: this doesn't fix responding to pip installing modules. Another fix coming
> LSP client changes, fix pylance crashing

- Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
- Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
- Python/Product/VSInterpreters/Interpreter/IInterpreterRegistryService.cs
- Python/Product/VSInterpreters/Interpreter/IPythonInterpreterFactoryProviderAsync.cs
- Python/Product/VSInterpreters/Interpreter/InterpreterRegistryService.cs
- Python/Product/VSInterpreters/VSInterpreters.csproj
- Python/Tests/Core/WorkspaceTestHelper.cs
- Python/Tests/Utilities.Python.Analysis/MockInterpreterOptionsService.cs
Fixes #7444
There are some bugs around environment loading and selection when the environments are discovered asynchronously, like with conda environments. There are lots of edge cases that need to be tested. See comments below for each scenario.
Specifically, conda environments weren't being shown in solution explorer because the currently selected environment was the global default, and the existing conditional was not behaving properly in that case. We were also showing an infobar for "missing conda environment" before they had a chance to be discovered.
> Fix asynchronous environment discovery and selection

- azure-pipelines.yml
Fixes https://github.com/microsoft/PTVS/issues/7601
Add a weekly scheduled run of the PTVS CI pipeline. This is to make sure PTVS ships with the latest pylance / debugpy release.
Note that this will always run even if there are no changes. This is because Pylance/debugpy releases do not generate changes in the PTVS repo.
> Add weekly pipeline schedule to coincide with pylance releases

- azure-pipelines.yml
I forgot that PDT is 7 hours behind UTC. The new time (1 am on Friday UTC) equals 6pm on Thursday PDT.
> Fix pipeline schedule

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools/Repl/Completion/AsyncCompletionSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1823538
[CompletionItem.TextEdit](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/462902?path=/src/product/Protocol/LanguageServer.Protocol/CompletionItem.cs&_a=files) has been changed from 
```C#
public TextEdit? TextEdit
```
to
```C#
public SumType<TextEdit, InsertReplaceEdit>? TextEdit
```
so I needed to fix up the code a little to account for this breaking change.
> Update lsp protocol package and fix compile errors

- Build/17.0/packages.config
- Python/Product/PythonTools/PythonTools/Commands/FillParagraphCommand.cs
- Python/Product/PythonTools/PythonTools/Editor/CodeSnippet/PythonSnippetManager.cs
- Python/Product/PythonTools/PythonTools/Editor/Comment/CommentHelper.cs
- Python/Product/PythonTools/PythonTools/Editor/EditorExtensions.cs
- Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
- Python/Product/PythonTools/PythonTools/Editor/TokenCache.cs
- Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
- Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs
Fix for Perfathon Bug #1837322
Updated the package for Microsoft.VisualStudio.Text.Data to allow access to GetContainingLineNumber(), then changed instances of GetContainingLine().LineNumber() to GetContainingLineNumber() as per instructed in the bug description.
> Fix for Perfathon Bug #1837322

- Python/Product/EnvironmentsList/PipExtension.xaml.cs
- Python/Product/VSInterpreters/PackageManager/PipPackageCache.cs
When a new environment was selected we were creating a pip package list around 400k items but we're clearning the previous list.
fixe: https://github.com/microsoft/PTVS/issues/7485
> Fix Excessive memory usage in Environments View

- Python/Product/Common/Infrastructure/JsonRpcWrapper.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/FileWatcher/Listener.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- also change `JsonRpcWrapper` to an extension class so that we dont have multiple references to the the `JsonRPC` instance
fixes: https://github.com/microsoft/PTVS/issues/7651
> Fix FileWatcher and JsonRPC teardown

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
The root cause was because the paths that client returns contain leading slashes.
1. **fixes https://github.com/microsoft/PTVS/issues/7827**
2. **fixes https://github.com/microsoft/PTVS/issues/7830**
3. **fixes https://github.com/microsoft/PTVS/issues/7832**
> Fix PTVS Regressions

- Build/templates/create_vs_bootstrapper.yml
- azure-pipelines.yml
Related to https://github.com/microsoft/PTVS/issues/7835
The point of the bootstrapper is to avoid having to do a VS insertion for our test team to consume our bits. I'm assuming the team can access our build artifacts, I'm waiting to hear back from them.
I ran a full build from this PR branch and the bootloader artifacts can be found at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9371793&view=artifacts&pathAsName=false&type=publishedArtifacts
> Create and publish bootstrapper for our test team

- Build/templates/publish_symbols.yml
Fixes #7870
I created an insertion PR at https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/544016 and waiting for the Symbol Check task to be done.
The Verify Symbols job is all green at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9417375&view=results.
> remove publish symbols task so we can get rid of pat

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
fixes https://github.com/microsoft/PTVS/issues/7864
In the code action requests that VS client sends, the `_vs_selectionRange` is supposed to be the `range` property that Pylance can understand, so intercept the messages and modify the property to make code actions work.
> Listen and modify client messages to make code actions work

- Python/Product/PythonTools/PythonTools/Project/DefaultPythonLauncherOptions.Designer.cs
- Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncherOptions.Designer.cs
fixes https://github.com/microsoft/PTVS/issues/7849
Different narrators understand different accessibility properties. The previous `accessibilityDescription` is only recognized by NVDA but not JAWS. Now changed to something that NVDA, JAWS, Windows Narrator all understand.
> Fix accessibility bug

- Build/PreBuild.ps1
- Build/templates/restore_packages.yml
- azure-pipelines.yml
- package.json
I've changed the logic in PreBuild.ps1 to no longer rely on npm's behavior when specifying "latest" for the version. "Latest" only seems to pull latest stable, which is what we want most of the time. But if there's a stable hotfix, "latest" won't pull it, which is bad.
Here's how the new logic works:
- If the user specifies a specific pylance version, we try to install it. In this case, `pylanceReleaseType` is ignored.
- If the user specifies "latest", we look for the latest version that matches the specified `pylanceReleaseType`. We can tell by the patch number.
- Finally, we tag the build with either `Pylance Stable` or `Pylance Preview`. 
- This new tag will be used to control triggering of our release pipeline. We will only want to trigger releases (which insert into VS) on builds …
> Enable ingesting preview builds of pylance

- Python/Product/Common/Strings.Designer.cs
- Python/Product/Common/Strings.resx
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptions.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.Designer.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.cs
- Python/Product/PythonTools/PythonTools/Options/PythonAnalysisOptionsControl.resx
- package.json
fixes https://github.com/microsoft/PTVS/issues/7888
Added these 2 options with tooltips that allow users to enable inlay hints in PTVS.
Tooltips:
With inlay hints:
Without inlay hints:
This UI and behavior is now consistent with other languages that support inlay hints in VS such as typescript.
> Support inlay hints

- Python/Product/TestAdapter.Executor/PythonFiles/testing_tools/adapter/pytest/_discovery.py
- Python/Product/TestAdapter/testlauncher.py
- package.json
Fixes https://github.com/microsoft/PTVS/issues/7959
The patch was originally added to address the issue where `::` was not supported in pytest parameterized arguments. See https://github.com/microsoft/PTVS/pull/5644
I discovered that pytest now supports `::` in parameterized arguments. See https://github.com/pytest-dev/pytest/pull/9642.
In this PR, I removed the patch that replaced `::` with an alternative syntax compatible with pytest. You may notice that the patch also patched some other special characters such as `.`, `\r`, etc., I have verified that both test discovery and test execution via the Test Explorer work as expected for test names containing those characters.
**Test Discovery:**
**Test Execution:**
Although tests run as expected, the test hierarchy displayed in the Test …
> Remove the pytestId patch

- Build/install_debugpy.py
We ran into an issue where this script was failing because of an incomplete release to PyPi. I tried yanking the release but this script was still failing.
Upon investigating, it's because this script gets all the releases for debugpy, even the yanked ones. This was causing `latest` to still refer to the yanked release, which is no good.
The new logic removes all yanked releases from the list of available releases, before trying to download anything.
> Ignore yanked releases when installing debugpy

- Python/Product/PythonTools/PythonTools.csproj
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClientCustomTarget.cs
- Python/Product/PythonTools/PythonTools/LanguageServerClient/WorkspaceFolders/WorkspaceFoldersArgs.cs
- package.json
Newer versions of pylance make a 'workspace/workspaceFolders' request when workspaces change. This allows for the detection of renames. 
However PTVS wasn't handling this request, which causes Pylance to skip all workspaces and make it behave like it was in single file mode.
> Add support for workspace/workspaceFolders request

- azure-pipelines-release.yml
`$(Build.BuildNumber)` returns the build number of the release pipeline. This isn't what we want.
We need the build number of the PTVS-Build pipeline resource that being consumed. To get that, we need to use `$(resources.pipeline.PTVS-Build.runName)`, where `PTVS-Build` is the ID of the pipeline resource (line 35). It does NOT have to match the actual name of the build pipeline, but in this case, it does.
> Use the build number of the pipeline resource

- azure-pipelines-release.yml
There are two places that tags need to be set in a pipeline resource. The first is used when the pipeline is triggered manually or through a schedule. The second controls what tags need to be set in order for the current pipeline to be triggered by the completion of the pipeline resource.
In this case, the bug was with running the release pipeline manually.
Now, the release pipeline will look for a build pipeline with BOTH tags set. It will do this both when being run manually and when being triggered by PTVS-Build pipeline completion.
> Fix issue when running release pipeline manually

- azure-pipelines-release.yml
Tag the release pipeline with the build number of the PTVS-Build run that is being consumed.
> add tag to identify what build was consumed

- Python/Product/PythonTools/PythonTools/Editor/LanguagePreferences.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
- package.json
Fixes https://github.com/microsoft/PTVS/issues/8023
We've received the same issue that the line numbers are not showing up multiple times, so I agree with Erik that it makes sense to set the default value to `true` for consistency with other languages like C#.
> Set `enable line number` to `true` by default.

- Examples/PythonCallingNative/PythonApplication/PythonApplication.pyproj
- Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs
The previous fix I made turned out to be because when using the release version of python, Concord has a hard time finding the parts of a function.
This change causes us to use the debug version of python instead when launching under mixed mode.
> Use the debug version of python if available

- Examples/PythonCallingNative/PythonApplication/PythonApplication.pyproj
- Examples/PythonNative/PythonNative.cpp
- Examples/PythonNative/PythonNative.vcxproj
- Python/Product/Cookiecutter/Shared/Interpreters/PythonLanguageVersion.cs
- Python/Product/Debugger.Concord/Debugger.Concord.csproj
- Python/Product/Debugger.Concord/Proxies/Structs/CFrameProxy.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger.Concord/PythonRuntimeInfo.cs
- Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs
- Python/Tests/Utilities.Python.Analysis/PythonPaths.cs
It seems 3.10 was a lot easier than I thought it would be. 
This gets mixed mode working with 3.10. I tested a Python app calling C++ and a C++ app calling Python.
> Support mixed mode for 3.10

- Python/Product/Cookiecutter/Shared/Interpreters/PythonRegistrySearch.cs
- Python/Product/VSInterpreters/Interpreter/PythonRegistrySearch.cs
Fixes https://github.com/microsoft/PTVS/issues/7923
PTVS find Python installations by checking the registry entries. The python.org python has some subkeys that PTVS uses to get the version number, while conda python does not.
Fix the issue by extracting the first 4 characters of the `tag` if python version is > 3.10, and the first 3 characters otherwise.
> Fix wrong Conda Python version being displayed in the UI

- Examples/PythonCallingNative/PythonApplication/PythonApplication.pyproj
- Examples/PythonNative/PythonNative.vcxproj
- Python/Product/Debugger.Concord/Debugger.Concord.csproj
- Python/Product/Debugger.Concord/DebuggerOptions.cs
- Python/Product/Debugger.Concord/ModuleManager.cs
- Python/Product/Debugger.Concord/Proxies/DataProxy.cs
- Python/Product/Debugger.Concord/Proxies/StructProxy.cs
- Python/Product/Debugger.Concord/Proxies/Structs/CFrameProxy.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyCodeObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyCodeObject310.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyCodeObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyDictObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyDictObject310.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyDictObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject310.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFunctionObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterFrame.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyThreads.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyTupleObject.cs
- Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs
- Python/Product/DebuggerHelper/trace.cpp
- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
This gets the two test apps we have in the [examples](https://github.com/microsoft/PTVS/tree/main/Examples) folder working with 3.11.
Breakpoints, callstacks, locals, and stepping all work. Probably need more testing around different types of variables, but that shouldn't be 3.11 specific.
> Get 3.11 to work in mixed mode

- Python/Product/Debugger.Concord/CallStackFilter.cs
- Python/Product/Debugger.Concord/CppExpressionEvaluator.cs
- Python/Product/Debugger.Concord/Debugger.Concord.csproj
- Python/Product/Debugger.Concord/Proxies/StructProxy.cs
- Python/Product/Debugger.Concord/Proxies/Structs/CFrameProxy.cs
- Python/Product/Debugger.Concord/Proxies/Structs/ImportState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyCodeObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject310.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyFrameObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterFrame.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyInterpreterState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyLongObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyRuntimeState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyThreadState.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyUnicodeObject.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyUnicodeObject311.cs
- Python/Product/Debugger.Concord/Proxies/Structs/PyUnicodeObject312.cs
- Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs
- Python/Product/DebuggerHelper/trace.cpp
This should get 3.12 mixed mode debugging working. I tested with the two mixed mode examples we have with stepping and adding some extra types as variables. 
3.12 made a rather difficult change to handle. No longer could we just WriteProcessMemory the `use_tracing` flag on the PyInterpreter. `use_tracing` was replaced with sys.monitoring. Using sys tracing required a function call now.
I first attempted to do this on startup and func eval the `PyEval_SetTraceAllThreads` function but I couldn't find the right spot to actually eval this that wouldn't throw an exception. 
So instead, the trace helper when it first sees a python eval, it injects the tracing then.
There was also a bunch of changes with other data types, like unicode objects and longs.
> Support for 312 mixed mode debugging

- Build/PreBuild.ps1
Fixes https://github.com/microsoft/PTVS/issues/8102
Remove unsigned file from the etwtrace package after we install it. This change can be reverted once https://github.com/microsoft/python-etwtrace/issues/7 is closed.
> Remove unsigned file

- Build/templates/run_tests.yml
Instead of new pipelines. just add caching to the test runner
> cache glass binaries

- Build/templates/publish_symbols.yml
This release branch was snapped from an older commit in main, and some of the yaml steps have changes since then. Fix those steps so the build passes. I ran the build manually at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10852216&view=results to make sure these changes work.
> Fix release build

- Python/Product/PythonTools/PythonTools/Editor/Formatting/PythonFormatter.cs
- Python/Product/PythonTools/PythonTools/Editor/Formatting/PythonFormatterBlack.cs
fixes https://github.com/microsoft/PTVS/issues/8155
Black is the default formatter for Python in VS, it only supports formatting a file, not a selection VS and/or GH Copilot is assuming the default formatter can always be used to format the selection.
I’ve filed an issue upstream and as a workaround, I removed the error message since it was unnecessarily appearing every time a user accepts Copilot edits. This change won’t affect the current user workflow, as the `Format Selection` command is already disabled for `Black` (see code below). Users won’t be able to manually trigger `Format Selection` with `Black`, so the error wouldn’t be shown in those cases anyway.
https://github.com/microsoft/PTVS/blob/9e5040e6f346f796a0e6d2ad492e2f45dd0d299e/Python/Product/PythonTools/PythonTools/Editor/For …
> Get rid of the `Black doesn't support the Format Selection command" error message.

- Python/Product/Profiling/Guids.cs
- Python/Product/Profiling/PythonProfilingPackage.cs
- package.json
fixes https://github.com/microsoft/PTVS/issues/8166
The diagnostics hub team just deleted all that code since nothing actually uses `perfpkg` anymore, even Python experience goes through the new profiler, so changing the GUID to be the Diagnostics Hub Package (new profiler)'s GUID.
Verified the existing profiling experience works now.
> Update Diagnostics Hub Package Guid

- Python/Product/Profiling/Profiling/CommandArgumentBuilder.cs
- Python/Product/Profiling/Profiling/IPythonProfilerCommandService.cs
- Python/Product/Profiling/Profiling/PythonProfilerCommandService.cs
- Python/Product/Profiling/Profiling/UserInputDialog.cs
- Python/Product/Profiling/PythonProfilingPackage.cs
Addresses the 3rd issue in https://github.com/microsoft/PTVS/issues/8168.
This issue is that when Diagnostics Hub calls `GetCommandArgsFromUserInput` they 're getting a `nullref` exception, specifically `PythonProfilingPackage.Instance` is null. 
This PR changes `GetcommandArgsFromUserInput` to be async and query the VS shell for the package.
> Load PythonProfilingPackage from shell

- Python/Product/Profiling/Profiling/CommandArgumentBuilder.cs
- Python/Product/Profiling/Profiling/IPythonProfilerCommandService.cs
- Python/Product/Profiling/Profiling/PythonProfilerCommandService.cs
- Python/Product/Profiling/Profiling/UserInputDialog.cs
- Python/Product/Profiling/PythonProfilingPackage.cs
- Python/Product/Profiling/source.extension.vsixmanifest
Addresses part of https://github.com/microsoft/PTVS/issues/8168
This PR:
1.  lets VS know Microsoft.PythonTools.Profiling.dll exposes a MEF component. 
2. load `PythonProfilingPackage` from VS shell to avoid package load sequence issue.
The feedback regarding package resolution will be addressed in separate PRs. This PR is focused on getting the fix into VS main so they can proceed with their work in parallel, as they have a workaround for the package resolution issue.
> Address feedback from Diagnostics Hub team

- azure-pipelines-release.yml
Addresses https://github.com/microsoft/PTVS/issues/8177
This PR updates the release pipeline to download the NuGet package generated as a build artifact from the build pipeline and uses the 1ES command to publish it to an internal feed for the partner team to consume.
I've tested it on the feature branch, confirming that the package is successfully pushed to the feed. (See pipeline run at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=11097600&view=results). Next after this PR gets merged, I'll test it on `main` to ensure it works as expected and still creates an insertion PR for changes merged into `main`.
> Publish nuget package to internal feed

- Python/Product/PythonTools/PythonTools/Environments/AddCondaEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddExistingEnvironmentControl.xaml
- Python/Product/PythonTools/PythonTools/Environments/AddVirtualEnvironmentControl.xaml
- azure-pipelines.yml
Reason:
Visual indicator (*) is not provided for the programmatically defined required field "Project Combobox" in the Add Environment dialog: A11y_Accessibility Testing for Python in VS_ Create a Virtual Environment_Devtools
fixes #2432913
> Accessibility fixes for Environments controls

- Python/Product/EnvironmentsList/images/images.xaml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2430766
The fix is to get rid of the redundant parent class of the images. They already inherit background color from the grid.
Current icons without fix:
Icons after fix:
> Fix icons for dark mode

- Python/Product/Cookiecutter/Model/CookiecutterClient.cs
fixes https://github.com/microsoft/PTVS/issues/8245
The error shows that the cookiecutter package installed in the virtual environment has a regex pattern that's incompatible with Python 3.13.  Cookiecutter uses regular expressions internally to parse and validate template URLs/paths. Python 3.13 introduced stricter regex parsing rules, and the installed cookiecutter package is likely an older version that haven't been updated for Python 3.13 compatibility. Verified that it fixed the issue.
When playing with cookiecutter, I was also able to repro an issue that's been reported by multiple users before: 
```
[External Code]
Microsoft.VisualStudioTools.UIThreadExtensions.GetUIThread(System.IServiceProvider)
Microsoft.PythonTools.Environments.UserSpecifiedCondaLocator.CondaExecutablePath.get() …
```
> Add cookiecutter support for Python 3.13

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2411245/?view=edit
Looking at the call stack, there's a crash caused by `System.Linq.Enumerable.ToArray` being called in the `GetSettings` method. The `context.SearchPaths` is likely to return null instead of an empty array in some cases, and calling `.ToArray()` on a null object throws a `NullReferenceException`.
The fix ensures that if `searchPaths` is null, we use an empty array instead.
> Fix a waston crash

- Python/Product/PythonTools/PythonTools.vsct
fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2135867/?view=edit
The VS version control team said our keyboard shortcut for opening interactive window is in conflict with their commit command. I have changed to shortcut to `Ctrl+K, I` to resolve the conflicts, I chose this shortcut because it also follows the conventions of the rest of the Python specific commands on this list.
> Update the keyboard shortcuts for opening interactive window

- Python/Product/PythonTools/PythonConstants.cs
- Python/Product/PythonTools/PythonToolsPackage.cs
Addresses https://github.com/microsoft/PTVS/issues/8271
Support for .pyt files has been requested by multiple users in the PTVS repo over the years. This PR adds support for Python Toolbox (.pyt) files in PTVS. These files are used by ArcGIS software for creating custom geoprocessing tools.
.pyt files are 100% Python syntax, so with this change, users will get syntax highlighting, intellisense, code navigation.
> Add support for Python Toolbox (.pyt) files in PTVS

- Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs
guard against no context elements on shutdown.  A context is created for the project or for each workspace or for each repl.
We need to send tasklist info when sending default settings with "workspace/didChangeConfiguration".  
alternatively we could pass in the uri into GetSettings() when "TriggerWorkspaceUpdateConfig" is called.
Fix for https://github.com/microsoft/PTVS/issues/8121
> Fix for missing default settings at startup.

- Build/templates/create_vs_bootstrapper.yml
The build pipeline currently generates a Dev17 Visual Studio installer with the latest PTVS changes for testing purposes. This needs to be updated for Dev18.
Part of https://github.com/microsoft/PTVS/issues/8201
> Update VS Bootstrapper Configuration

- Python/Product/VSCommon/Infrastructure/VisualStudioApp.cs
Fixes https://github.com/microsoft/PTVS/issues/8277
The error message:
System.InvalidOperationException: Could not find VS DTE object for process 6620
at Microsoft.PythonTools.Infrastructure.VisualStudioProxy.GetDTE()
at Microsoft.PythonTools.TestAdapter.Services.ExecutorService.DetachFromSillyManagedProcess(VisualStudioProxy app, PythonDebugMode debugMode)
at Microsoft.PythonTools.TestAdapter.UnittestTestExecutor.TestRunner.Run()
Connected to socket
is caused by build pipeline now only supports building ptvs in dev17 environment, but the process is running in dev18. Fixing it by supporting both versions, but we should revert back once pipeline tool supports dev18.
> Fix issue with test explorer

- Python/Product/VCDebugLauncher/VCDebugLauncher.csproj
- package.json
fixes https://github.com/microsoft/PTVS/issues/8290.
It's caused by the same reason: PTVS is built in dev17 environment but run in dev18 environment.  Before msbuild@1 supports dev18 build environment, hardcode the path for now. See https://github.com/microsoft/PTVS/issues/8201#issue-2936315398
> Fix the issue where the option "Python/Native Debugging" is missing

- Python/Product/Cookiecutter/Cookiecutter.vsct
- Python/Product/Cookiecutter/CookiecutterPackage.cs
This change does two things:
1) Visual Studio 2026 has a new drop down with the same contents as File -> New. However, in this mode, the commands text should include "New". This changes the text to follow the same pattern as the other New commands, where Button text is used for the drop down, and MenuText used for File -> New. Also fixed the canonical name which was wrong.
You can see that "Repository..." and "From Cookiecutton..." are both missing the prefix "New". This change fixes Cookiecutter.
2) Fixed the enabled state of these commands, these commands, similar to their equivalent, should be disabled when building and/or debugging.
> Fix text/enabled state of new project/file commands
