Python/Product/PythonTools/visualstudio_py_debugger.py

Updates debugger for changed API in stackless to follow http://stackless.readthedocs.org/en/latest/library/stackless/debugging.html

#46 Debugger fails to run with Stackless

---

Python/Product/Analysis/ExportedMemberInfo.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Intellisense/ExpansionClient.cs
Python/Product/PythonTools/PythonTools/Intellisense/ImportSmartTagAction.cs
Python/Product/PythonTools/PythonTools/Intellisense/MissingImportAnalysis.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonAnalysisExtensions.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSourceProvider.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagAction.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagController.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagControllerProvider.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagSourceProvider.cs
Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs

Also improves/simplifies the old smart tags slightly.

Adds lightbulb support for VS 2015.

---

Common/Tests/Utilities.UI/TestUtilities.UI.csproj
Common/Tests/Utilities.UI/UI/EditorWindow.cs
Common/Tests/Utilities.UI/UI/SmartTagSessionWrapper.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/SmartTagController.cs
Python/Tests/Core.UI/AddImportTests.cs
Python/Tests/PythonToolsMockTests/SmartTagTests.cs

Fixes build on VS 2015 due to smart tag tests.

Smart tag tests

---

Python/Product/TestAdapter/TestAnalyzer.cs
Python/Tests/TestAdapterTests/TestDiscovererTests.cs

@hawkerm discovered that we do not match the python docs.  I am
committing his fix on his behalf.  I also have altered our tests to
reflect the change.

#99 'runTest' not discovered

---

Python/Product/Analysis/Analysis.csproj
Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
Python/Product/Analysis/Interpreter/InterpreterUIMode.cs
Python/Product/Analysis/Interpreter/PythonInterpreterFactoryExtensions.cs
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/EnvironmentsList/ToolWindow.xaml.cs
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/InterpreterView.cs
Python/Product/PythonTools/PythonTools/Options/PythonInterpreterOptionsControl.cs
Python/Product/PythonTools/PythonTools/PythonInterpreterFactoryExtensions.cs
Python/Product/Uwp/Interpreter/PythonUwpInterpreterFactoryProvider.cs
Python/Product/VSInterpreters/InterpreterOptionsService.cs
Python/Tests/Core/EnvironmentListTests.cs

Makes it possible to hide environments or make them ineligible to be the default environment.
Makes the UWP environment ineligible to be the default.

Hide environments

---

Python/Product/EnvironmentsList/images14.0/images.xaml

Removes failed attempt at correctly handling the background colour.

#129 Python Package icon appears with white background

---

Python/Product/EnvironmentsList/PipExtension.xaml.cs
Python/Product/EnvironmentsList/PipExtensionProvider.cs
Python/Tests/Core/EnvironmentListTests.cs

Prevents progress bar from getting stuck when pip is not installed.
Improves detection of whether pip is installed so we don't have to check as often.

Improve pip detection

---

Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs

Also fixes the copyright header.

Prevents exceptions in projection buffers when suggesting missing imports

---

Python/Product/EnvironmentsList/PipExtensionProvider.cs
Python/Product/PythonTools/PythonTools.csproj

#200 PTVS does not compile at ToT with VS 2013

---

Python/Product/Analysis/Interpreter/InterpreterUIMode.cs
Python/Product/Analysis/Interpreter/PythonInterpreterFactoryExtensions.cs
Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/PythonTools/PythonTools/Options/PythonInteractiveOptionsControl.cs
Python/Product/PythonTools/PythonTools/Options/PythonInterpreterOptionsControl.cs
Python/Product/PythonTools/PythonToolsService.cs
Python/Product/VSInterpreters/DerivedInterpreterFactory.cs

Fixes environments not being deleted
Fixes settings being changed if you remove an environment and then cancel the change
Fixes virtual environments appearing in Tools-Options

#159 Cannot delete custom environment via tools options

---

Python/Product/Django/Project/DjangoAnalyzer.cs
Python/Product/Django/Project/DjangoProject.cs
Python/Tests/Django/DjangoAnalyzerTests.cs
Python/Tests/Django/DjangoTemplateParserTests.cs
Python/Tests/TestData/DjangoAnalysisTestApp/test_render/views.py

Adds specialization for simple_tag
Also clears tags/filters that came from a file whenever that file is reanalyzed

#171 Django template IntelliSense doesn't understand simple_tag

---

Python/Tests/Core.UI/AddImportTests.cs

(First reviewer can go ahead and merge)

Improves robustness of smart tag tests.

---

Python/Product/Analysis/Analysis.csproj
Python/Product/Analysis/AnalysisDictionary.cs
Python/Product/Analysis/AnalysisHashSet.cs
Python/Product/Analysis/AnalysisSet.cs
Python/Product/Analysis/AnalysisUnit.cs
Python/Product/Analysis/AnalysisValue.cs
Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs
Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
Python/Product/Analysis/Analyzer/FunctionScope.cs
Python/Product/Analysis/Analyzer/InterpreterScope.cs
Python/Product/Analysis/Analyzer/IsInstanceScope.cs
Python/Product/Analysis/IEnumerableExtensions.cs
Python/Product/Analysis/LockedEnumerable.cs
Python/Product/Analysis/ModuleAnalysis.cs
Python/Product/Analysis/ModuleTable.cs
Python/Product/Analysis/ProjectEntry.cs
Python/Product/Analysis/PythonAnalyzer.Specializations.cs
Python/Product/Analysis/SaveAnalysis.cs
Python/Product/Analysis/SingleDict.cs
Python/Product/Analysis/Values/CallChain.cs
Python/Product/Analysis/Values/ClassInfo.cs
Python/Product/Analysis/Values/FunctionInfo.cs
Python/Product/Analysis/Values/MemberReferences.cs
Python/Product/Analysis/Values/ModuleInfo.cs
Python/Tests/Analysis/AnalysisTests.csproj
Python/Tests/Analysis/NamespaceSetTest.cs
Python/Tests/Analysis/ThreadingTest.cs
Python/Tests/Utilities.Python.Analysis/PythonTestExtensions.cs

Prevents direct access to dictionaries inside scopes and adds locking to all indirect access.
Adds locking to reference collections.
Not sure yet exactly what the perf impact will be, but there doesn't seem to be a cheaper way to avoid the race conditions we currently suffer from - suggestions welcome.
Test to follow (lots of cross-module analysis running on separate threads for a while and seeing whether we crash)

#225 Error while editing

---

Python/Setup/PythonToolsInstaller/PythonToolsInstaller.wxs

Writes product version into the registry on install.

Adds option to skip devenv /setup on install.

---

Build/Common.Build.settings
Common/Tests/MockVsTests/MockVs.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs
Python/Product/PythonTools/PythonTools/TokenCache.cs
Python/Tests/Core.UI/BasicProjectTests.cs
Python/Tests/Core/EditorTests.cs
Python/Tests/Core/PythonToolsTests.csproj
Python/Tests/PythonToolsMockTests/PythonEditor.cs
Python/Tests/PythonToolsMockTests/PythonToolsMockTests.csproj
Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs

General test improvements.
Updates interface of PythonSuggestedImportAction.
Updates VS 2015 build to target .NET 4.6.

Makes refactor rename tests into mock tests and fixes some of them.

---

Common/Tests/MockVsTests/MockDTE.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs

Fixes some issues with name resolution when building.

Fixes build issues.

---

Python/Product/PythonTools/PythonTools/Refactoring/ImportRemover.cs

Removes unnecessary +1 that was causing exceptions at the end of the file.

#255 Error when running Remove Imports, Current Scope

---

Python/Product/PythonTools/PythonTools/Repl/ReplOutputClassifier.cs

#228 Error from repl window classifier

---

Python/Product/Analysis/AnalysisHashSet.cs

#291 crashes analyzing winpython 3.4.3.3 64-bit

---

Python/Product/PythonTools/PythonTools/Intellisense/OVERRIDECOMPLETIONANALYSIS.CS
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Improves null handling when translating buffer indexes.

#290 null ref exception in editor

---

Python/Tests/Core/ReplEvaluatorTests.cs
Python/Tests/Core/SquiggleTests.cs
Python/Tests/Utilities.Python/MockInteractiveWindowCommandsFactory.cs

Fixes for null reference errors

---

Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes arithmetic for column and line number calculations.

#305 Error while editing

---

Python/Product/PythonTools/PythonTools/Options/InterpreterPlaceholder.cs
Python/Product/PythonTools/PythonTools/Project/PythonGeneralPropertyPageControl.cs

Adds a default InterpreterConfiguration for placeholders to ensure they can be displayed in the UI correctly.

#318 InterpreterPlaceholder instances are making it into saved options

---

Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs

Ensures we always call Done() after vising library nodes.
Also adds check to ensure we only visit nodes from Python projects
Improves handling of tasks and cancellation tokens.

#315 Not calling Done() after calculating Navigate To items

---

Python/Product/PythonTools/PythonTools.vsct
Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs
Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
Python/Tests/Core.UI/BuildTasksUITests.cs
Python/Tests/IronPython/ReplEvaluatorTests.cs

Fixes multiple overlapping outlining spans.
Fixes cancelled custom commands not throwing.
Fixes Project.AddExistingFolder missing.

Fixes a number of tests.

---

Build/vwdexpress.14.0.testsettings
Build/vwdexpress.14.0Exp.testsettings
Common/Tests/SharedProjectTests/SourceControl.cs
Common/Tests/Utilities.UI/UI/AutomationDialog.cs
Common/Tests/Utilities.UI/UI/OverwriteFileDialog.cs
Common/Tests/Utilities.UI/UI/VisualStudioApp.cs

Adds test configurations for Express for Web.

Adds handling for dialogs appearing when opening projects in tests.

---

Python/Tests/DebuggerTests/DebuggerTests.cs

Increase waiting period for process startup in AttachPtvsd test, as the original value is often not long enough.

Fix AttachPtvsd test to pass proper arguments to IronPython to allow ptvsd to work.

---

Common/Product/SharedProject/VsExtensions.cs
Common/Tests/MockVsTests/MockErrorProviderFactory.cs
Common/Tests/MockVsTests/MockVs.cs
Common/Tests/MockVsTests/MockVsShell.cs
Common/Tests/MockVsTests/MockVsTests.csproj
Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Core/PythonToolsTests.csproj
Python/Tests/PythonToolsMockTests/MockPythonToolsPackage.cs
Python/Tests/PythonToolsMockTests/PythonToolsMockTests.csproj
Python/Tests/PythonToolsMockTests/SquiggleTests.cs

Fixes a number of deadlocks and assertions within tests (and potentially within the product too)

Test fixes

---

Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes #427 Deadlock specializing methods while updating modules
Removes _contentsLock from PythonAnalyzer
Adds locking to CPythonInterpreter.

Fixes #427 Deadlock specializing methods while updating modules

---

Python/Product/TestAdapter/TestExecutor.cs

Fixes #450 NullReferenceException testing test adapter
Adds missing null check for _app.

Fixes #450 NullReferenceException testing test adapter

---

Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs

Fixes #460 Assertion closing project with open interactive window
Adds special handling for VS 2015 interactive window.

Fixes #460 Assertion closing project with open interactive window

---

Python/Product/PythonTools/PythonTools/Project/Pip.cs

Fixes #467 Exception when pip fallback does not work
Skips fallback entirely when directory does not exist.
Silences errors that are system related and not indicative of product issues.

Fixes #467 Exception when pip fallback does not work

---

Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/IMultipleScopeEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/SwitchModuleCommand.cs

Fixes #463 Debug interactive cannot switch scopes
Restores the IMultipleScopeEvaluator interface
Some related code tidying

Fixes #463 Debug interactive cannot switch scopes

---

Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Check whether span length is negative before trying to tokenize it.

Fix #442: Error editing code while debugging

---

Python/Tests/ReplWindowUITests/ReplWindowPythonTests.cs

Improves SyntaxHighlightingRaiseException test

---

Common/Tests/Utilities/Mocks/MockReplWindow.cs
Python/Product/PythonTools/Guids.cs
Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs

Fixes #514 Remove RC hacks
Removes the workarounds added to deal with bugs that have since been fixed.

Fixes #514 Remove RC hacks

---

Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs

Fixes #553 IPython interactive window has no colors in errors
Uses AppendEscapedText on VS 2015 instead of relying on extension methods.

Fixes #553 IPython interactive window has no colors in errors

---

Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs

Fixes #564 Crash on new analysis
Strengthens event handler against corrupt or unavailable settings and races.

Fixes #564 Crash on new analysis

---

Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
Python/Tests/Core/CPythonInterpreterTests.cs

Fixes #558 Crash when uninstalling Python
Handles IOException and retries getting subkeys if we race with external registry edits.
Adds test.

Fixes #558 Crash when uninstalling Python

---

Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs

Fixes image layout in interactive window.
By adding to the buffer, we ensure that FlushOutput does some work and correctly repositions the caret.

Fixes image layout in interactive window.

---

Build/BuildReleaseHelpers.psm1
Build/BuildReleaseMockHelpers.psm1

Removes unnecessary indentation.
Fixes log location.

Symbol submission

---

Python/Product/Analysis/AnalysisDictionary.cs
Python/Product/Analysis/AnalysisHashSet.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Product/Django/ProvideEditorExtension2Attribute.cs
Python/Product/EnvironmentsList/DBExtension.xaml.cs
Python/Product/EnvironmentsList/PipPackageCache.cs
Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
Python/Product/Profiling/Profiling/SessionsNode.cs
Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs

The two lock disposes are the only risky parts of this change at all, and I'm fairly sure they're fine.
I haven't fixed any of the complaints about all the classes that should have IDisposable, only the ones that were already disposable but weren't disposing everything.

Fixes code analysis warnings.

---

Common/Product/ReplWindow/Repl/OutputBuffer.cs

Backports the fix for #616 (but not the test - too many changes there and it's easy enough to test manually).

Backport #616

---

Common/Tests/SccPackage/source.extension.vsixmanifest
Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
Python/Product/AssemblyInfoCommon.cs
Python/Product/Django/source.extension.vsixmanifest
Python/Product/IronPython/Interpreter/RemoteInterpreter.cs
Python/Product/IronPython/source.extension.vsixmanifest
Python/Product/Profiling/source.extension.vsixmanifest
Python/Product/PythonTools/Dev10/source.extension.vsixmanifest
Python/Product/PythonTools/Dev11OrLater/source.extension.vsixmanifest
Python/Product/PythonTools/pip_downloader.py
Python/Product/PythonTools/ptvsd/setup.py
Python/Product/PythonTools/visualstudio_ipython_repl.py
Python/Product/ReplWindow/source.extension.vsixmanifest
Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Analysis/BaseAnalysisTest.cs
Python/Tests/ReplWindowUITests/ReplWindowProxy.cs
Python/Tests/ReplWindowUITests/ReplWindowPythonIPythonTests.cs
Python/Tests/ReplWindowUITests/ReplWindowPythonSmokeTests.cs
Python/Tests/ReplWindowUITests/ReplWindowUITests.csproj

Backport support for IPython 3 and infinite loop in recursive decorator analysis.

V2.1 backports

---

Python/Product/PythonTools/PythonTools/Commands/StartScriptCommand.cs

Gracefully handle exceptions from EnvDTE.ActiveSolutionProjects.

Fix #598: Start with/without debugging fails if Solution Explorer has never been opened

---

Python/Product/IronPython/Interpreter/IronPythonInterpreterFactoryProvider.cs
Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs

Fixes #681 ArgumentException when handling `Registry_PythonPath_Changed`
Switches to retrying on failure, and eventually giving up silently.

Fixes #681 ArgumentException when handling `Registry_PythonPath_Changed`

---

Python/Product/PythonTools/PythonTools/Intellisense/ReverseExpressionParser.cs

Tentatively fixes #739 NullReferenceException in ReverseExpressionParser.GetExpressionRange
Ensures that Classifier is always non-null.
I can't see anything else in the function that could potentially be null, so guessing this is it.

Tentatively fixes #739 NullReferenceException

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

#704 Generate Requirements.txt on Invalid Environment
Handles FileNotFoundException when listing packages.
Also disables generate/install requirements.txt commands when not able to install packages.

#704 Generate Requirements.txt on Invalid Environment

---

Python/Product/IronPython/Interpreter/RemoteInterpreter.cs

Fixes #697 Exception while editing IronPython code
Ensures generic types are wrapped and unwrapped correctly.

Fixes #697 Exception while editing IronPython code

---

Python/Product/EnvironmentsList/PipExtension.xaml.cs
Python/Product/EnvironmentsList/PipExtensionProvider.cs

Fixes #781 Error listing packages for misconfigured environment
Improves handling of misconfigured environments when listing or uninstalling packages.

Fixes #781 Error listing packages for misconfigured environment

---

Python/Product/Analysis/Parsing/CodeFormattingOptions.cs

Resource string was incorrect for SpacesWithinListExpression

fixes #811 by correcting resource string

---

Python/Product/PythonTools/visualstudio_py_debugger.py
Python/Tests/DebuggerTests/DebuggerTests.cs
Python/Tests/TestData/DebuggerProject/SysExitNone.py

Fixes #888 Sys.Exit not working
Handles any falsey code in SystemExit exception.

Fixes #888 Sys.Exit not working

---

Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs
Python/Product/PythonTools/visualstudio_py_debugger.py
Python/Tests/Core.UI/VirtualEnvTests.cs
Python/Tests/DebuggerTests/DebuggerTests.cs
Python/Tests/ReplWindowUITests/ReplWindowTests.cs
Python/Tests/TestData/DebuggerProject/SysExitNone.py

Forward port

---

Python/Product/Django/Microsoft.PythonTools.Django.targets

Fix working directory of commands in Microsoft.PythonTools.Django.targets

---

Python/Setup/PythonToolsInstaller/PythonToolsInstaller.wxs

Fixes #920 Uninstall on upgrade runs devenv /setup
Prevents running devenv /setup on upgrade.

Fixes #920 Uninstall on upgrade runs devenv /setup

---

Python/Product/Debugger/DkmDebugger/ExceptionManager.cs
Python/Product/Debugger/DkmDebugger/ExpressionEvaluator.cs
Python/Product/Debugger/DkmDebugger/LocalComponent.cs
Python/Product/Debugger/DkmDebugger/ModuleManager.cs
Python/Product/Debugger/DkmDebugger/RemoteComponent.cs
Python/Product/Debugger/DkmDebugger/TraceManagerLocalHelper.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs

Also reduces likelihood of crashing on build when a C++ project is referenced.
Ping @int19h - please just hit Merge if you don't see any issues.

Fixes mixed-mode debugging when certain Python functions have multiple exit points

---

Python/Product/Analysis/Interpreter/InterpreterFactoryCreator.cs
Python/Product/EnvironmentsList/PipExtensionProvider.cs

Fixes #944 All environments disappeared
Switch to non-throwing function for path processing.
Corrects detection of ability to launch interpreter.

Fixes #944 All environments disappeared

---

Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs

Fixes #966 VS crash when closing
Improves handling of errors writing to interactive window when closing.

Fixes #966 VS crash when closing

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs

Fixes crash when opening project with reference to C++ project.

Fixes crash when opening project with reference to C++ project.

---

index.html

https://github.com/Microsoft/PTVS/issues/1035

#1035 update 2.2.2 link and move latest to the top of the releases list

---

Python/Product/PythonTools/visualstudio_py_debugger.py

Fixes debugging of templates with Django 1.8+
Also fixes template offsets being messed up when line endings are not `\n`.

Issue 1043

---

Python/Setup/PythonToolsInstaller/Strings15.0.wxl
Python/Setup/signinstaller.ps1

Ensures we use the correct names

Branding fixes

---

Python/Setup/Django/DjangoFiles.proj

Fixes #1104 Add django app failure
Adds template file to installer.

Fixes #1104 Add django app failure

---

Python/Product/Django/Templates/Projects/DjangoProject/urls.py

Fixes #1152 Blank Django Web Project doesn't run
Removes unnecessary import

Fixes #1152 Blank Django Web Project doesn't run

---

Python/Product/ProjectWizards/CloudServiceWizard.cs

Adds fwlink for Azure Tools download (currently pointing to a generic download page until the tools are available).

Adds fwlink for Azure Tools download

---

Common/Product/SharedProject/CommonPropertyPage.cs
Python/Product/Django/Project/DjangoProject.cs
Python/Product/Django/Project/DjangoPropertyPage.cs
Python/Product/EnvironmentsList/PipExtensionProvider.cs
Python/Product/Profiling/Profiling/BaseHierarchyNode.cs
Python/Product/Uwp/Project/PythonUwpPropertyPage.cs

Fixes #1194 Make sure Dispose gets called
Removes or calls IDisposable implementations added with #1190

Issue 1194

---

Python/Product/PythonTools/PythonToolsPackage.cs

Delays package load until after the shell is initialized.

Fixes #1117 Auto indent default is block

---

Python/Product/PythonTools/PythonTools/Extensions.cs

Handles case where we try to get PythonToolsService before PythonToolsPackage is loaded.

Handles case where we try to get PythonToolsService

---

Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs
Python/Product/PythonTools/source.extension.vsixmanifest

Removes interactive version from vsixmanifest entirely.
Fixes process object being disposed while still in use on a background thread.

Removes interactive version from vsixmanifest entirely.

---

Python/Product/PythonTools/PythonTools/Commands/DiagnosticsCommand.cs

Fixes #1166 Crash opening diagnostic info
Improves exception handling when generating diagnostic info
Also improves output when some errors occur getting logs.

Fixes #1166 Crash opening diagnostic info

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Commands/AzureExplorerAttachDebuggerCommand.cs
Python/Product/PythonTools/PythonToolsPackage.cs

See also #1306 (same fix for 2.x branch)

Replaces Azure Remote Debug functionality with opening the help page.

---

Python/Product/WFastCgi/wfastcgi.py

Fixes wfastcgi.py not loading. Also improves use of application insights

Fixes wfastcgi.py not loading. Also improves use of application insights

---

Python/Product/Ipc.Json/Connection.cs

Fixes #1325 Crash when terminating analyzer
Handles serialization errors and reports an error unless it was because the stream ended.

Fixes #1325 Crash when terminating analyzer

---

Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs
Python/Product/Analysis/ModulePath.cs
Python/Product/Analyzer/PyLibAnalyzer.cs
Python/Product/Common/Infrastructure/PathUtils.cs
Python/Product/PythonTools/PythonTools/Project/Conda.cs
Python/Product/PythonTools/PythonTools/Project/ImportWizard/ImportSettings.cs
Python/Product/PythonTools/PythonTools/Project/Pip.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/VSInterpreters/DerivedInterpreterFactory.cs
Python/Tests/Core/EnvironmentListTests.cs

Fixes #1333 Error in DB view while analysis DB is changing
Switches to using safe enumeration functions instead of the Path ones.
Fixes EnvironmentList test

Fixes #1333 Error in DB view while analysis DB is changing

---

Python/Product/Analysis/Interpreter/PythonTypeDatabase.cs
Python/Product/Analysis/Parsing/Parser.cs
Python/Product/Analysis/Parsing/SourceLocation.cs
Python/Product/Analysis/XamlProjectEntry.cs
Python/Product/AnalysisBrowser/FunctionView.cs
Python/Product/Analyzer/Intellisense/OutOfProcMethodExtractor.cs
Python/Product/AzureSetup/AzureSetup.cs
Python/Product/Debugger/Debugger/DebugEngine/AD7Thread.cs
Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
Python/Product/PyDebugAttach/PyDebugAttach.cpp
Python/Tests/Analysis/AnalyzerTests.cs

Some fixes of obvious code mistakes or warnings.

fixes of obvious code mistakes

---

Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Django.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Web.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Worker.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.targets
Python/Product/Django/source.extension.vsixmanifest
Python/Product/Hpc/source.extension.vsixmanifest
Python/Product/IronPython/source.extension.vsixmanifest
Python/Product/ML/source.extension.vsixmanifest
Python/Product/Profiling/source.extension.vsixmanifest
Python/Product/PythonTools/Dev10/source.extension.vsixmanifest
Python/Product/PythonTools/Dev11OrLater/source.extension.vsixmanifest
Python/Product/PythonTools/Dev14OrLater/source.extension.vsixmanifest
Python/Product/ReplWindow/source.extension.vsixmanifest
Python/Product/Uwp/source.extension.vsixmanifest

Updates version number to 2.2.4

---

Python/Product/EnvironmentsList/DBExtension.xaml.cs

Fixes #1265 Intellisense view in environments window does not update after refresh
Updates comparison logic for view objects to ensure they are updated correctly.

Fixes #1265 Intellisense view in environments window does not update after refresh

---

Common/Tests/Utilities.UI/UI/ReplWindowProxy.cs
Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Tests/ReplWindowUITests/SendToReplTests.cs

Improves #88 to send the entire cell no matter where the cursor is.
Fixes race condition causing FileUpdate requests to fail.

Improves #88 to send the entire cell no matter where the cursor is.

---

Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
Python/Product/Ipc.Json/Request.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes race condition from unloading files before clearing local information
Improves AnalysisProtocol logging.

Fixes race condition from unloading files before clearing local information

---

Python/Product/PyKinect/PyKinect/pykinect/nui/__init__.py

Make sure that string formatting is consistent throughout the file, plus this is a better way to format strings.

Change string formatting in pykinect.nui.__init__.py to use `%`

---

Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs
Python/Product/PythonTools/PythonTools/Intellisense/CodeCellAnalysis.cs
Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/ReplEditFilter.cs
Python/Tests/Core/EditorTests.cs
Python/Tests/ReplWindowUITests/SendToReplTests.cs
Python/Tests/TestData/SendToInteractive/Cells.py

Improves #88 to also support IPython-style cells
Also treats preceding comments as part of the cell

Improves #88 to also support IPython-style cells

---

Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/EnvironmentsList/ToolWindow.xaml.cs
Python/Product/EnvironmentsListHost/MainWindow.xaml
Python/Product/EnvironmentsListHost/MainWindow.xaml.cs
Python/Product/IronPython/Interpreter/IronPythonInterpreterFactoryProvider.cs
Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs
Python/Tests/Core/EnvironmentListTests.cs
Python/Tests/Utilities.Python.Analysis/MockPythonInterpreterFactory.cs
Python/Tests/Utilities.Python.Analysis/MockPythonInterpreterFactoryProvider.cs

Loads vendor info from registry and displays in environments list.
Looks like this:

Vendor info

---

Common/Product/SharedProject/Navigation/Library.cs
Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProviderFactory.cs

Fixes #1393 Navigate To provider is failing before calling Done
Fixes UI threading issues in library and provider.
Ensures Done is called even when we fail early.

Fixes #1393 Navigate To provider is failing before calling Done

---

Common/Product/SharedProject/UIThread.cs
Python/Product/Analysis/Analysis.csproj
Python/Product/Analysis/AnalysisValue.cs
Python/Product/Analysis/IHasRichDescription.cs
Python/Product/Analysis/MemberResult.cs
Python/Product/Analysis/Values/BoundMethodInfo.cs
Python/Product/Analysis/Values/BuiltinClassInfo.cs
Python/Product/Analysis/Values/BuiltinFunctionInfo.cs
Python/Product/Analysis/Values/BuiltinMethodInfo.cs
Python/Product/Analysis/Values/ClassInfo.cs
Python/Product/Analysis/Values/CoroutineInfo.cs
Python/Product/Analysis/Values/FunctionInfo.cs
Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
Python/Product/VSCommon/Infrastructure/UIThreadBase.cs
Python/Tests/Analysis/AnalysisSaveTest.cs
Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Analysis/ProcessOutputTests.cs
Python/Tests/Utilities.Python/MockUIThread.cs

Fixes #1343 Tooltips do not include signature
Adds rich description protocol and improves content of descriptions.

Fixes #1343 Tooltips do not include signature

---

Python/Product/BuildTasks/Microsoft.PythonTools.targets
Python/Product/Profiling/Profiling/StandaloneTargetView.cs

Fixes framework checks in Python projects.

---

Python/Product/PythonTools/PythonTools/Extensions.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Setup/dirs.proj

Combining fixes for a potential v2.2.5 into this PR.

V2.2.5 fixes

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectFactory.cs
Python/Tests/Core/ProjectUpgradeTests.cs
Python/Tests/TestData/ProjectUpgrade/HasWebBrowserUrl.pyproj
Python/Tests/TestData/ProjectUpgrade/NoWebBrowserUrl.pyproj

Fixes badly coded upgrade.

---

Python/Product/BuildTasks/Microsoft.PythonTools.targets
Python/Tests/InstallIntoDev15.ps1

Overrides targets that fail when .NET targeting is not installed.

---

Python/Product/PythonTools/PythonTools/Intellisense/StringLiteralCompletionList.cs

Fixes #1492 Exception while editing
Ensures path is valid before passing it to IsPathRooted

Fixes #1492 Exception while editing

---

Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Python/Product/PythonTools/visualstudio_py_repl.py

Fixes #1491
I haven't run the tests yet.

Don't execute code if it's a blank string.

---

Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs

Fixes #1510 Test adapter crash
Prevents potential null reference exceptions when getting tests.

Fixes #1510 Test adapter crash

---

Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
Python/Product/PythonTools/PythonTools/Extensions.cs
Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs

Fixes #1502 Invalid cross-thread calls
Adds UI thread marshalling.
Also fixes null reference exception opening debug REPL
Fixes potential analysis crash due to invalid version number

Fixes #1502 Invalid cross-thread calls

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectFactory.cs
Python/Product/Uwp/Microsoft.PythonTools.Uwp.targets
Python/Product/Uwp/Project/PythonUwpProjectConfig.cs
Python/Templates/Uwp/ProjectTemplates/Python/Windows IoT Core/BackgroundService/PythonBackgroundService.vstemplate

- Update GUIDs for deployment packages
- Update the version number for Microsoft.VisualStudio.WinRT.TemplateWizards
- Python.Uwp project upgrade for the new interpreter id
- Fixed a bug in locating visualstudio_py_remote_launcher.py for deployment

Python.Uwp changes for Dev15

---

Common/Tests/SccPackage/SccPackage.cs
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Django.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Web.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.Worker.targets
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.targets
Python/Product/Django/source.extension.vsixmanifest
Python/Product/Hpc/source.extension.vsixmanifest
Python/Product/IronPython/source.extension.vsixmanifest
Python/Product/ML/source.extension.vsixmanifest
Python/Product/Profiling/source.extension.vsixmanifest
Python/Product/PythonTools/Dev10/source.extension.vsixmanifest
Python/Product/PythonTools/Dev11OrLater/source.extension.vsixmanifest
Python/Product/PythonTools/Dev14OrLater/source.extension.vsixmanifest
Python/Product/ReplWindow/source.extension.vsixmanifest
Python/Product/Uwp/source.extension.vsixmanifest

Updates version number to 2.2.5
Fixes build issue

Updates version number to 2.2.5

---

Python/Product/PythonTools/PythonToolsService.cs

Fixes #1532 due to a race condition when creating a custom environment.

Race condition fix

---

Common/Tests/MockVsTests/MockVs.cs
Common/Tests/Utilities/Mocks/MockVsShell.cs
Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Tests/PythonToolsMockTests/PythonEditor.cs

Fixes analysis only analyzer.
Ensures architecture is not null.
Ensures mock VS is initialized.

Fixes for tests

---

Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs

Fixes #1571 NullReferenceException when clicking "Install Python Package" without Python Environments window
Retries the selection operation lazily until the window is loaded.

Fixes #1571 NullReferenceException when clicking "Install Python Package"

---

Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs

Improves assertion for missing database check, and hopefully prevents it from triggering incorrectly.

Improves assertion for missing database check

---

Python/Product/PythonTools/PythonTools/Commands/DkmDebuggerCommand.cs

Fixes #1569 ObjectDisposedException in DkmDebuggerCommand
Handles ObjectDisposedException

Fixes #1569 ObjectDisposedException in DkmDebuggerCommand

---

Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
Python/Tests/DebuggerUITests/AttachTest.cs
Python/Tests/DebuggerUITests/DebuggerUITests.csproj

Improves disposal of VisualStudioApp class.

Fixes tests not using the UI thread correctly.

---

Python/Product/Analysis/Interpreter/PackageSpec.cs
Python/Product/Analysis/Interpreter/PackageVersion.cs
Python/Product/EnvironmentsList/PipExtension.xaml.cs

Fixes #1617 Packages upgrade button does not upgrade

Fixes #1617 Packages upgrade button does not upgrade

---

Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs

Fixes https://github.com/Microsoft/PTVS/issues/1630
Test to be added in a later PR.  It requires having git clones as part of test data, still trying to decide on how to arrange it (each template needs its .git folder to be checked in, which is over 20 files).

Fix description not being initialized.

---

Python/Product/Analysis/Analysis.csproj
Python/Product/Analysis/Analyzer/DDG.cs
Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs
Python/Product/Analysis/Parsing/Ast/ErrorExpression.cs
Python/Product/Analysis/Parsing/Ast/ExpressionWithAnnotation.cs
Python/Product/Analysis/Parsing/Ast/NameExpressionWithAnnotation.cs
Python/Product/Analysis/Parsing/Ast/PythonWalker.Generated.cs
Python/Product/Analysis/Parsing/Parser.cs
Python/Product/Analysis/Parsing/Tokenizer.cs
Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Analysis/MutateStdLibTest.cs
Python/Tests/Analysis/ParserRoundTripTest.cs
Python/Tests/Analysis/ParserTests.cs
Python/Tests/TestData/Grammar/VarAnnotation.py
Python/Tests/TestData/Grammar/VarAnnotationIllegal.py

Fixes #1616
Adds support for PEP 526 and PEP 498 syntax parsing and round-trip. Analysis is not yet implemented.

Issue 1616

---

Build/PreBuild.ps1
Python/Product/Analyzer/Analyzer.csproj
Python/Product/Cookiecutter/Cookiecutter.csproj
Python/Product/Core/Core.csproj
Python/Product/Core/source.extension.vsixmanifest
Python/Product/Ipc.Json/Ipc.Json.csproj
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Updates Newtonsoft.Json version for Dev15 build and removes hard dependency on the older version.

Json version

---

Python/Product/Common/Infrastructure/ProcessOutput.cs
Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx

Fixes #1599: Error trying to update 2+ python libs
Prevent race condition between choosing a port number and listening on it.

Fixes #1599: Error trying to update 2+ python libs

---

Python/Product/Analysis/Interpreter/PythonInterpreterFactoryExtensions.cs
Python/Setup/dirs.proj

Fixes #1678 Can't create virtual environment on Data Science workload Anaconda

Issue 1678

---

Python/Product/Cookiecutter/source.extension.vsixmanifest
Python/Product/Core/source.extension.vsixmanifest
Python/Product/Django/source.extension.vsixmanifest
Python/Product/IronPython/source.extension.vsixmanifest
Python/Product/Profiling/source.extension.vsixmanifest
Python/Product/Uwp/source.extension.vsixmanifest

Fixes #1702 Update vsixmanifest
Updates vsixmanifest files to contain correct installation details.

Fixes #1702 Update vsixmanifest

---

Python/Product/Cookiecutter/CookiecutterPackage.cs

Fixes https://github.com/Microsoft/PTVS/issues/1643

Move cookiecutter tool window default position

---

Python/Product/Cookiecutter/CookiecutterToolWindow.cs
Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml.cs
Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs

Fixes https://github.com/Microsoft/PTVS/issues/1676
Looks like this when visible:

Cookiecutter auto reset after success, link to open in explorer

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/ProjectWizards/InstallRequirementsWizard.cs
Python/Product/PythonTools/PythonConstants.cs
Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/PythonTools/PythonTools/Navigation/EditFilter.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/PythonTools/PythonTools/Repl/ReplEditFilter.cs
Python/Product/VSCommon/Infrastructure/VSTaskExtensions.cs

Adds exception logging for edit filters.
Switches to improved dialog for unhandled exception reporting.

Improved unhandled exception handling

---

Python/Product/Analysis/Interpreter/PythonInterpreterFactoryWithDatabase.cs

Fixes #1732: Infinite DB refresh loop
Checkes whether DB is actually generating when the flag is set and resets the state.

Fixes #1732: Infinite DB refresh loop

---

Python/Product/Cookiecutter/Cookiecutter.csproj
Python/Product/Cookiecutter/Cookiecutter.vsct
Python/Product/Cookiecutter/CookiecutterToolWindow.cs
Python/Product/Cookiecutter/Resources/ImageMonikers.cs
Python/Product/Cookiecutter/Resources/Images.imagemanifest
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Python/Product/Cookiecutter/ViewModel/TemplateViewModel.cs

Switches to new icons and some theming fixes.

cookiecutter icons and theming

---

Python/Product/Debugger/Debugger/PythonProcess.cs
Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs

Also fixes for the things I got wrong with my last set of crash fixes :)

More crash fixes

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Reported internally via crash reporting.

Prevents RemoveItem from crashing VS when racing with another removal.

---

Build/Common.Build.Cpp.settings
Python/Product/VsPyProf/PythonApi.cpp

Enables SDLCheck and PREfast on native code.
Fixes one reported issue.

Enables SDLCheck and PREfast on native code.

---

Python/Product/Ipc.Json/Connection.cs
Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes #1782 Task not observed assert
Handles access denied errors closing the analyzer
Handles racing with object disposal when calling directly into IPC connection
Improves handling of Intellisense session state

Fixes #1782 Task not observed assert

---

Python/Product/Analysis/Interpreter/InterpreterRegistryService.cs
Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs

Fixes #1806 NullReferenceException opening REPL
Correctly handles null or empty interpreter ID.

Fixes #1806 NullReferenceException opening REPL

---

Python/Product/Common/Infrastructure/TaskExtensions.cs

Fixes #1804 Crash in PipPackageManager
Converts ObjectDisposedException into OperationCanceledException in LockAsync (assuming that a disposed semaphore implies we want to cancel all pending operations)

Fixes #1804 Crash in PipPackageManager

---

Python/Product/Analysis/SaveAnalysis.cs
Python/Product/Analyzer/BuiltinScraper.py
Python/Product/Analyzer/PyLibAnalyzer.cs
Python/Product/Analyzer/PythonScraper.py

Fixes #1793 Analysis completed but looks incomplete
Prevents crash analyzing builtins
Avoids crashing during analysis save when a type is missing a name.
Improves error logging in analyzer

Fixes #1793 Analysis completed but looks incomplete

---

Python/Product/PythonTools/PythonTools/Project/ImportWizard/ImportSettings.cs
Python/Product/PythonTools/PythonTools/Project/ImportWizard/ProjectCustomizations.cs
Python/Tests/Core/ImportWizardTests.cs

Fixes https://github.com/Microsoft/PTVS/issues/1787 New Project From Existing Code creates upgrade files
All Import Wizard tests pass.

Fix new project from existing code wizard

---

Python/Templates/Core/ProjectTemplates/Python/KinectGame/KinectGame.pyproj
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/ClassifierTemplate.pyproj
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/ClusteringTemplate.pyproj
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/RegressionTemplate/RegressionTemplate.pyproj
Python/Templates/Core/ProjectTemplates/Python/PyvotProject/PyvotProject.pyproj
Python/Templates/IronPython/ProjectTemplates/Python/ConsoleProject/ConsoleProject.pyproj
Python/Templates/IronPython/ProjectTemplates/Python/SilverlightProject/SilverlightProject.pyproj
Python/Templates/IronPython/ProjectTemplates/Python/WinformsProject/WinformsApp.pyproj
Python/Templates/IronPython/ProjectTemplates/Python/WpfProject/WpfApp.pyproj

Fixes https://github.com/Microsoft/PTVS/issues/1814

Update some project templates.

---

Python/Product/Cookiecutter/Model/GitHubClient.cs
Python/Product/Cookiecutter/Model/GitHubTemplateSource.cs
Python/Product/Cookiecutter/Model/IGitHubClient.cs
Python/Product/Cookiecutter/Model/Template.cs
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml.cs
Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Python/Product/Cookiecutter/ViewModel/TemplateViewModel.cs
Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs
Python/Tests/CookiecutterTests/CookiecutterTests.csproj
Python/Tests/CookiecutterTests/MockGitHubClient.cs

Fixes https://github.com/Microsoft/PTVS/issues/1825 (I included a screenshot there).

Add cookiecutter template image in the description section.

---

Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs

Fixes #1792 NullReferenceException while typing parameter list
Protects against null references in UpdateCurrentParameter.

Fixes #1792 NullReferenceException while typing parameter list

---

Python/Product/PythonTools/ptvsd/attach_server.py
Python/Product/PythonTools/visualstudio_py_debugger.py
Python/Product/PythonTools/visualstudio_py_util.py

This fixes two issues that let debugging with Jython fail. Needs an review, because I am not deep in the code. Tested with Jython 2.7.0 and Python 3.5.

Fixing #1271 regarding debugging with Jython

---

Python/Product/Cookiecutter/Model/LocalTemplateSource.cs
Python/Tests/CookiecutterTests/CookiecutterIntegrationTests.cs

Fix https://github.com/Microsoft/PTVS/issues/1845

Prevent cookiecutter duplicates in installed section

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
Python/Product/PythonTools/PythonTools/Repl/InteractiveWindowProvider.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs

Fixes #1858 Send to Interactive doesn't select project context
Fixes #1857 Interactive window not getting search paths
Fixes #1859 No warning displayed in REPL when changing project config

Repl issues

---

Common/Product/SharedProject/Wpf/Controls.cs
Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
Python/Product/Cookiecutter/View/CookiecutterDictionary.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/EnvironmentsList/EnvironmentView.xaml

Couple of theming related fixes.
Fixes #1668 
Fixes #1745 
Fixes #1904

Fixes Theming

---

Common/Tests/AssemblyInfoCommon.cs
Common/Tests/MockVsTests/MockVs.cs

Updates VSVersionSuffix from 15 to 2017.

Fixes MSBuild tests in mock test suite.

---

Common/Product/SharedProject/VsExtensions.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs

Fixes #1992 Error thrown when opening project
Changes error report to a deferred retry, since it is benign and likely to succeed later.
Also suppresses another benign error message.

Fixes #1992 Error thrown when opening project

---

Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/VSInterpreters/InterpreterOptionsService.cs

Ensures default environment is correctly selected.
Prevents crash disposing an analyzer.

Ensures default environment is correctly selected.

---

Python/Templates/Django/ProjectTemplates/Python/Web/WebRoleDjango/urls.py

Fix #1340 Default Django Web Role template missing views.py

Fix django web role template

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Fixes #2034 No completions on packages
Revert asynchronous analyzer creation.

Fixes #2034 No completions on packages

---

Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml

Fixes #2033 Keyboard scrolling in completions list broken
Fixes definition of scroll viewer.

Fixes #2033 Keyboard scrolling in completions list broken

---

Python/Product/PythonTools/PythonTools/Commands/SendToReplCommand.cs

Fixes #2030 First repl command assumes multiple statements are supported
Switches to get the language version from a better API.

Fixes #2030 First repl command assumes multiple statements are supported

---

Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs

Fixes #2091 Null Reference exception getting completions
Coerces a potential null to an empty list.

Fixes #2091 Null Reference exception getting completions

---

Python/Product/Django/Debugger/DjangoLauncherProvider.cs
Python/Product/Django/Django.csproj
Python/Product/Django/DjangoLanguageInfo.cs
Python/Product/Django/Extensions.cs
Python/Product/Django/Intellisense/DjangoCompletionSource.cs
Python/Product/Django/Intellisense/DjangoCompletionSourceBase.cs
Python/Product/Django/Intellisense/ProjectBlockCompletionContext.cs
Python/Product/Django/Intellisense/ProjectBlockCompletionContextBase.cs
Python/Product/Django/Project/DjangoProject.cs
Python/Product/Django/Project/DjangoProjectFactory.cs
Python/Product/Django/Project/DjangoPropertyPageControl.Designer.cs
Python/Product/Django/Project/DjangoPropertyPageControl.resx
Python/Product/Django/Project/NewAppDialog.xaml
Python/Product/Django/ProvideDebugLanguageAttribute.cs
Python/Product/Django/Resources.Designer.cs
Python/Product/Django/Resources.resx
Python/Product/Django/TemplateParsing/DjangoBlock.cs
Python/Product/Django/TemplateParsing/DjangoBlocks/DjangoUrlBlock.cs
Python/Product/Django/TemplateParsing/DjangoFormatDefinitions.cs
Python/Product/Django/TemplateParsing/DjangoVariable.cs
Python/Product/Django/TemplateParsing/TemplateArtifact.cs
Python/Product/Django/Utilities.cs
Python/Product/Django/VsMenus.cs

For DjangoPropertyPageControl (a windows forms control), the only change I made was set Localizable property to true (the tool did the rest).

Move django strings into .resx file.

---

Build/PreBuild.ps1

Debugger interface definition now in sync with our implementation.

Fix VS 2015 build

---

Python/Product/Analyzer/Intellisense/OutOfProcMethodExtractor.cs
Python/Product/Analyzer/Intellisense/SelectionTarget.cs
Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx

I discovered https://github.com/Microsoft/PTVS/issues/2142 while attempting to test these error messages...

Move analyzer project strings to resx.

---

Python/Setup/swix/install.ps1

Updates install script to include dependencies.

Install script

---

Python/Product/Django/Project/NewAppDialog.xaml
Python/Product/Django/Resources.Designer.cs
Python/Product/Django/Resources.resx
Python/Product/Django/TemplateParsing/DjangoFormatDefinitions.cs

Fixes #2149 Django template tag not localized
Fixes #2153 Add Django app dialog title not localized

Django loc fixes

---

Python/Product/Analyzer/PyLibAnalyzer.cs
Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx

Fixes #2157 Environment window completion db progress not localized
Switches analyzer to using resource strings for status updates.

Fixes #2157 Environment window completion db progress not localized

---

Python/Product/Django/DjangoPackage.cs
Python/Product/Profiling/PythonProfilingPackage.cs
Python/Product/Profiling/VSPackage.resx
Python/Product/PythonTools/PythonTools/Project/PythonProjectPackage.cs
Python/Product/PythonTools/PythonToolsPackage.cs
Python/Product/PythonTools/VSPackage.resx

Fixes #2158 Open Project filter not localized
Fixes #2159 Open File filter not localized
Also moves Formatting string to resource.

Fixes #2158 Open Project filter not localized

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectReferenceNode.cs

Fixes #2200 Error changing solution configuration
Changes UpdateSearchPathAsync() to retry on all exceptions.

Fixes #2200 Error changing solution configuration

---

Python/Product/WFastCgi/README.rst
Python/Product/WFastCgi/setup.py
Python/Product/WFastCgi/wfastcgi.py

Note that the rich diff view for README.rst (near the "View" button) works for ReST files.

Updates wfastcgi in preparation for release.

---

Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/Ipc.Json/Connection.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/TestAdapter.Executor/TestExecutor.cs

Adds support for logging all messages sent over IPC.
This will be helpful for debugging Intellisense, test discovery and soon debugging issues.

Adds support for logging all messages sent over IPC.

---

README.md

This is not to be merged until VS 2017 is released, but figured it may trigger some discussion and wanted to get that resolved sooner rather than later.

Update the front page readme.

---

Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs

This should help identify telemetry being sent back that relates to our commands.
(Internal request from the VS team)

Action provider telemetry

---

Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs

Fixes some performance issues:
* response to AddBulkFiles was delayed until after all parsing had completed
* reduce logging in TaskProvider by default
Also fixes a null reference crash when hovering over text.

Fixes some performance issues

---

Python/Setup/swix/Packages/Microsoft.CookiecutterTools.Vsix.swixproj
Python/Setup/swix/Packages/Microsoft.PythonTools.Core.Vsix.swixproj
Python/Setup/swix/Packages/Microsoft.PythonTools.Django.Vsix.swixproj
Python/Setup/swix/Packages/Microsoft.PythonTools.IronPython.Vsix.swixproj
Python/Setup/swix/Packages/Microsoft.PythonTools.Profiling.Vsix.swixproj
Python/Setup/swix/Packages/Microsoft.PythonTools.Uwp.Vsix.swixproj
Python/Setup/swix/swix.generate.targets

Adds resource packages as install dependencies.

Resource package installation

---

Python/Product/Django/Project/DjangoProject.cs
Python/Product/TestAdapter/TestContainerDiscoverer.cs

Fix call to RegisterExtension to pass in a regular file path, not a URI.

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.dll.lcl

LEGO: Pull request from lego/hb_839_20170315232242945 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170315232242945 to master

---

Python/Product/EnvironmentsList/ConfigurationExtension.xaml.cs
Python/Product/EnvironmentsList/DBExtension.xaml.cs
Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/EnvironmentsList/IEnvironmentViewExtension.cs
Python/Product/EnvironmentsList/PipExtensionProvider.cs
Python/Product/EnvironmentsList/Resources.Designer.cs
Python/Product/EnvironmentsList/Resources.resx
Python/Product/EnvironmentsList/ToolWindow.xaml

Fixes #2225 Missing automation names on overview page
Fixes #2226 Missing automation name of combobox

Fixes #2225 Missing automation names on overview page

---

Python/Product/PythonTools/PythonTools/Intellisense/ExtractMethodSuggestedActionSourceProvider.cs

Fixes #2308 ArgumentNullException getting extract method preview
Don't try to get a preview if anything is null

Fixes #2308 ArgumentNullException getting extract method preview

---

Python/Product/Profiling/PythonProfilingPackage.cs
Python/Product/PythonTools/PythonTools/Commands/ExecuteInReplCommand.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Fixes #2279 ExecuteInRepl command may let exception escape
Handles exceptions and displays appropriate user feedback.

Fixes #2279 ExecuteInRepl command may let exception escape

---

Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs
Python/Product/Debugger/Debugger/DebugEngine/AD7Events.cs

Fixes #2316 Mixed-mode attach fails
Corrects the AD7LoadCompleteEvent parameters

Fixes #2316 Mixed-mode attach fails

---

Python/Product/PythonTools/PythonTools/Refactoring/LocationPreviewItem.cs
Python/Product/PythonTools/PythonTools/Refactoring/PreviewChangesEngine.cs
Python/Tests/PythonToolsMockTests/RefactorRenameTests.cs

Fixes refactor/rename crash from #2271
Rewrites name analysis for ease of reading

Fixes refactor/rename crash from #2271

---

Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.EnvironmentsList.dll.lcl

LEGO: Pull request from lego/hb_839_20170331100529535 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170331100529535 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170331144036797 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170331144036797 to master

---

Python/Product/Debugger/Debugger/DebugConnection.cs

Fix https://github.com/Microsoft/PTVS/issues/2349

Fix hang at the end of a remote debug session

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170331204025620 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170331204025620 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170401024026389 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170401024026389 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170403144028494 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170403144028494 to master

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170405024030343 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170405024030343 to master

---

Python/Product/PythonTools/visualstudio_py_debugger.py

Fixes https://github.com/Microsoft/PTVS/issues/2369
Removes unused internal error function.

Ensure that threads list lock is always released.

---

Python/Product/Common/Strings.resx
Python/Product/Cookiecutter/Strings.resx
Python/Product/PythonTools/PythonTools.vsct

Improve comments in resource files.
Fixes typo in PythonTools.vsct

Improve comments in resource files.

---

Python/Product/PythonTools/PythonTools/Commands/ImportCoverageCommand.cs
Python/Product/PythonTools/PythonTools/Extensions.cs
Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntryService.cs
Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs

Fixes #2379 Import coverage file error
Switches AnalysisEntryService to use existing helper function
Minor refactoring

Fixes #2379 Import coverage file error

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170412204032469 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170412204032469 to master

---

Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Analysis/BaseAnalysisTest.cs

Fixes analysis logging in tests.
Adds test for #2271 (currently expected to fail)

Fixes analysis logging in tests.

---

Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs

Fixes #2204 Crash getting analyzer from non-UI thread
Ensures outlining tags are updated from UI thread.

Fixes #2204 Crash getting analyzer from non-UI thread

---

Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentOperation.cs

Fixes #1114 Error creating virtual environment
Handles errors thrown when installing packages.

Fixes #1114 Error creating virtual environment

---

Python/loc/lcl/JPN/Microsoft.PythonTools.EnvironmentsList.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20170418084035048 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170418084035048 to master

---

Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Django.dll.lcl

LEGO: Pull request from lego/hb_839_20170418204044237 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170418204044237 to master

---

Python/Product/Common/Infrastructure/StringExtensions.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs

Improves command line comment for interactive window analyzers
See #2420

Improves command line comment for interactive window analyzers

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20170421144032565 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170421144032565 to master

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs

Fixes #1938 No completions for Django variables
Creates virtual environment factories with file system watchers enabled.
Also prevents racing when recreating a project analyzer.

Fixes #1938 No completions for Django variables

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20170425024029380 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170425024029380 to master

---

Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs

We shouldn't be assuming that it's in My Documents.
According to #2447 there may still be an actual crash involved here, and I don't think this will necessarily resolve it.

Fixes how the default scripts location is determined.

---

Python/Product/Analyzer/PyLibAnalyzer.cs

Reduce the amount of "good" log messages and increase the number of "bad" messages to help with debugging issues.

Analyzer logging improvements

---

Python/Product/WFastCgi/wfastcgi.py

This should fix the https://github.com/Microsoft/PTVS/issues/2471 issue.
I also modified the `read_fastcgi_data()` definition in the same fashion as `read_fastcgi_input()`, however I am not sure what `wsgi.data` variable is used for, since I don't see it as being a part of the WSGI specification. Perhaps I am missing something, so please double-check that part.

Efficiently buffer FastCGI input data.

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Fixes semaphore not being correctly disposed.

---

Python/Product/TestAdapter/TestContainerDiscoverer.cs

Fixes #2456 Unexpected error after adding unit test.

Lock access around test containers dictionary

---

Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/classifier.py
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/clustering.py
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/RegressionTemplate/regression.py

Fix #2197 sklearn deprecation triggered by ML samples
Also target latest version of azure storage lib.

Fix ml project templates

---

Common/Tests/Utilities.UI/UI/ReplWindowProxy.cs
Python/Tests/Django.UI/DjangoProjectTests.cs
Python/Tests/TestData/DjangoApplication/manage.py

8/9 of DjangoProjectTests now pass
The remaining failure is due to UI automation being broken right now on Dev15 for the app designer tabs. Filed a bug against VS.

Fix DjangoProjectTests

---

Python/Tests/Core.UI/VirtualEnvTests.cs

UnavailableEnvironments still fails.  All others can now pass but they are still flaky.

Some fixes for virtual environment tests

---

Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20170519084030814 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170519084030814 to master

---

Common/Product/SharedProject/Wpf/Controls.cs
Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
Python/Product/EnvironmentsList/DataListBox.cs
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/EnvironmentsList/EnvironmentView.xaml
Python/Product/EnvironmentsList/EnvironmentsList.csproj
Python/Product/EnvironmentsList/Resources.Designer.cs
Python/Product/EnvironmentsList/Resources.resx
Python/Product/EnvironmentsList/ToolWindow.xaml
Python/Product/PythonTools/PythonTools.csproj

Fixes some high contrast color issues
Synchronises Controls.xaml
Fixes some resource strings

Fixes some high contrast color issues

---

Common/Product/SharedProject/Wpf/Controls.cs
Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml

Fixes #2595 Use interactive mode checkbox is invisible on high contrast
Removes checkbox hover color.
Fixes button hover colors.

Fixes #2595 Use interactive mode checkbox is invisible on high contrast

---

Python/Product/PythonTools/PythonTools/Project/CustomCommand.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs

Fixes #2305 Django Management Console error
Skips resetting configuration based on project for custom commands.

Fixes #2305 Django Management Console error

---

Common/Product/SharedProject/Wpf/Controls.cs
Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.cs
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml

Fixes #2606 Combo box text unreadable on High Contrast White
Fixes button, check box and radio button colors
Removes hover color for multiline text box.

Fixes #2606 Combo box text unreadable on High Contrast White

---

Python/loc/lcl/KOR/Microsoft.PythonTools.EnvironmentsList.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.EnvironmentsList.dll.lcl

LEGO: Pull request from lego/hb_839_20170601084023464 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170601084023464 to master

---

Python/Product/BuildTasks/BuildTasks.csproj
Python/Product/BuildTasks/TestTargets/Microsoft.PythonTools.uwp.targets
Python/Product/Common/Infrastructure/PathUtils.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectPackage.cs
Python/Tests/Core/PathUtilsTests.cs

Fixes debugging UWP support
Fixes PathUtils.FindFile not handling search depth correctly.
Adds FindFile test.

Fixes UWP and FindFile

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/EnvironmentsList/PipExtension.xaml
Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironment.xaml

Fixes #2619 Some High Contrast Black issues
Fixes some high contrast issues.
Slightly improves a string.

Fixes #2619 Some High Contrast Black issues

---

Python/loc/lcl/CHT/Microsoft.PythonTools.EnvironmentsList.dll.lcl
Python/loc/lcl/CHT/Snippets/Python/with.snippet.lcl

LEGO: Pull request from lego/hb_839_20170602144024928 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170602144024928 to master

---

Python/Product/VSInterpreters/PipPackageCache.cs

Looks like we also need to reduce the number of calls overall, but I'll do that as a separate issue.

Adds a user agent string for requests to pypi.org.

---

Python/loc/lcl/RUS/Microsoft.PythonTools.EnvironmentsList.dll.lcl

LEGO: Pull request from lego/hb_839_20170603024025714 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170603024025714 to master

---

Python/loc/lcl/JPN/Snippets/Python/except.snippet.lcl

LEGO: Pull request from lego/hb_839_20170605084024452 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170605084024452 to master

---

Python/Product/VSInterpreters/PipPackageCache.cs

Fixes #2639 Too many requests to pypi.org
Stops making parallel requests for the same package
Stops making repeated requests for package info when it likely has not changed

Fixes #2639 Too many requests to pypi.org

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20170608204023483 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170608204023483 to master

---

Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs

Fixes #2661 Language version passed to debugger has format mismatch
Enables parsing of multiple version formats.

Fixes #2661 Language version passed to debugger has format mismatch

---

Python/Product/Cookiecutter/Cookiecutter.csproj
Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/Cookiecutter/View/LiveTextBlock.cs
Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Python/Product/EnvironmentsList/DBExtension.xaml
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/VSCommon/Infrastructure/LiveTextBlock.cs
Python/Product/VSCommon/VSCommon.csproj

Enables live region support using internal VS API. This should be replaced with proper WPF support when that is added.
Simplifies status display in cookiecutter.
Fixes some missing help text properties.

Enables live region support using internal VS API.

---

Python/Product/Workspace/Microsoft.PythonTools.SuppressDpl.pkgdef
Python/Product/Workspace/Workspace.csproj

This resolves a range of issues when lightweight solution load is enabled.

Disables lightweight solution load for Python projects

---

Python/Product/PythonTools/PythonTools/Repl/LoadReplCommand.cs
Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.CommandProcessorThread.cs

Fix #2688 CSV paste in REPL functionality missing 
Also fixes 2 NullReferenceException found by tests.
More fixes for REPL tests will come in a later PR. The changes included here are the only fixes in product code I had accumulated so far.

REPL fixes

---

Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml
Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs
Python/Product/EnvironmentsList/EnvironmentView.cs
Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Python/Product/VSInterpreters/PipPackageManager.cs

Fixes #2301 Cannot customise interactive scripts path
Enables customization of the path
Also prevents calculating the path too eagerly
Prevents calling pip list too eagerly

Fixes #2301 Cannot customise interactive scripts path

---

Python/Product/Analysis/Parsing/CodeFormattingExampleAttribute.cs
Python/Product/Analysis/Parsing/CodeFormattingOptions.cs
Python/Product/Analysis/Resources.Designer.cs
Python/Product/Analysis/Resources.resx
Python/Product/PythonTools/PythonTools/Options/PythonAdvancedEditorOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonDebuggingOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonFormattingGeneralOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonInteractiveOptionsControl.Designer.cs

Fix localization issues.
Makes examples localizable
Enables auto-ellipsis on text that may be truncated in check boxes.
These were all reported on the internal tracker.

Fix localization issues.

---

Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170621144026374 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170621144026374 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs
Python/Tests/ReplWindowUITests/ReplWindowPythonSmokeTests.cs
Python/Tests/ReplWindowUITests/ReplWindowPythonTestEntryPoints.cs
Python/Tests/ReplWindowUITests/ReplWindowPythonTests.cs
Python/Tests/Utilities.Python/PythonReplWindowProxySettings.cs

Fix #2708 Expected span to be non-empty assert
Fix #2683 Images in REPL no longer auto minimize
(fixed the test to no longer expect this behavior)
Other small fixes in REPL tests

Some REPL test fixes

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170624024026467 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170624024026467 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseControllerProvider.cs

Fixes #2730 Error pop-up when viewing git merge window on .py file
Handles error cases initializing key bindings.

Fixes #2730 Error pop-up when viewing git merge window on .py file

---

Python/Templates/Django/ProjectTemplates/Python/Web/WebRoleDjango/ConfigureCloudService.ps1
Python/Templates/SharedFiles/ConfigureCloudService.ps1
Python/Templates/SharedFiles/update_templates.ps1
Python/Templates/Web/ItemTemplates/Python/AzureCSWebRole/ConfigureCloudService.ps1
Python/Templates/Web/ItemTemplates/Python/AzureCSWorkerRole/ConfigureCloudService.ps1
Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleBottle/ConfigureCloudService.ps1
Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleEmpty/ConfigureCloudService.ps1
Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleFlask/ConfigureCloudService.ps1
Python/Templates/Web/ProjectTemplates/Python/Web/WorkerRoleProject/ConfigureCloudService.ps1

Fixes #2706 $appcmdargs miscalculated in default web role template
Uses correct syntax to concatenate lists in Powershell.
Avoids joining absolute paths together.

Fixes #2706 $appcmdargs miscalculated in default web role template

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170629204025192 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170629204025192 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170630084025788 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170630084025788 to master

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170630144027930 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170630144027930 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170701024032543 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170701024032543 to master

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170702024024316 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170702024024316 to master

---

Python/loc/lcl/FRA/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170704144031799 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170704144031799 to master

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Analysis.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170705084022553 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170705084022553 to master

---

Python/Product/Cookiecutter/CookiecutterPackage.cs

Fix #2778 Disable add from cookiecutter command when debugging

Fix query status of Add From Cookiecutter command.

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Analysis.dll.lcl

LEGO: Pull request from lego/hb_839_20170712144027857 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170712144027857 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fix #2782 NullReferenceException in editor tooltip handling

Fix NRE in editor tooltip handling

---

Python/Product/TestAdapter/PythonStackTraceParser.cs

Fix #2749 Invalid path parsing stack frame

Fix invalid path parsing stack frame

---

Python/Prerequisites/deploy_test_targets.cmd
Python/Product/TestAdapter/visualstudio_py_testlauncher.py

Fix imports broken by ptvsd refactor.

Fix #2784: Test Explorer - Debug Test no longer works

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170721144025835 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170721144025835 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170722024020244 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170722024020244 to master

---

Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170724084028125 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170724084028125 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170724144025083 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170724144025083 to master

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170724204029000 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170724204029000 to master

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170725084024278 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170725084024278 to master

---

Python/Product/PythonTools/ptvsd/__main__.py

Fix #2833: ptvsd can't be used as a program

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Uwp.Wizards.dll.lcl

LEGO: Pull request from lego/hb_839_20170726144033746 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170726144033746 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Uwp.Wizards.dll.lcl

LEGO: Pull request from lego/hb_839_20170726204020854 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170726204020854 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170727024019994 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170727024019994 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Uwp.Wizards.dll.lcl

LEGO: Pull request from lego/hb_839_20170727144042931 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170727144042931 to master

---

Python/Product/Analysis/PythonAnalyzer.Specializations.cs
Python/Tests/Analysis/AnalysisTest.cs

Issue #731 Add analysis specializations
Adds more specializations for builtin functions.
This does not complete the issue, by any means, but it was a quick and easy improvement to make.

Issue #731 Add analysis specializations

---

Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj

Fixes #2839 Extension module template has wrong WinSDK version
Updates default WinSDK version
Also fixes debug options

Fixes #2839 Extension module template has wrong WinSDK version

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Uwp.Wizards.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Uwp.Wizards.dll.lcl

LEGO: Pull request from lego/hb_839_20170728144020825 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170728144020825 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fix NRE in GetDataTipText

---

Python/Product/Analysis/Values/ConstantInfo.cs
Python/Tests/Core/EnvironmentListTests.cs

Fixes #2867 Invalid characters in analysis log output
Replaces unprintable characters.

Fixes #2867 Invalid characters in analysis log output

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Analysis.dll.lcl

LEGO: Pull request from lego/hb_839_20170803144023869 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170803144023869 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170804144031460 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170804144031460 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170808144030184 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170808144030184 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl

LEGO: Pull request from lego/hb_839_20170809084040217 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170809084040217 to master

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl

LEGO: Pull request from lego/hb_839_20170809144017710 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170809144017710 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl

LEGO: Pull request from lego/hb_839_20170809204037821 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170809204037821 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170810024022717 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170810024022717 to master

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170810084033034 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170810084033034 to master

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170810144020890 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170810144020890 to master

---

Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.VCDebugLauncher.xaml.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.VCLauncher.dll.lcl

LEGO: Pull request from lego/hb_839_20170811204029142 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170811204029142 to master

---

Python/Product/VCDebugLauncher/VCTargets/Win32/ImportBefore/Microsoft.PythonTools.Debugger.VCDebugLauncher.props
Python/Product/VCDebugLauncher/VCTargets/x64/ImportBefore/Microsoft.PythonTools.Debugger.VCDebugLauncher.props

Fixes #2903 VC debug launcher should set property
Adds property to ImportBefore headers.

Fixes #2903 VC debug launcher should set property

---

Python/Setup/loclayout.proj

Suppresses missing loc comment warnings.

Suppresses missing loc comment warnings.

---

Python/Product/PythonTools/ptvsd/attach_server.py
Python/Product/PythonTools/ptvsd/setup.py

Adds ptvsd.repl package to setup.py
Removes unused reference in attach_server
(Backport of #2931)

[Backport] Adds ptvsd.repl package to setup.py

---

Python/Product/PythonTools/PythonTools/Editor/PythonEditorServices.cs
Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Python/Product/PythonTools/PythonTools/Intellisense/ExpansionClient.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSourceProvider.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedImportAction.cs
Python/Product/PythonTools/PythonTools/Navigation/DropDownBarClient.cs

Fixes #2944 Errors splitting/new windows
Updates suggested actions to avoid relying on the text view.
Updates drop down client to allow multiple sinks.

Fixes #2944 Errors splitting/new windows

---

Python/Product/PythonTools/ptvsd_repl_launcher.py

Fixes #2950 python interactive window crashed
Insulates ptvsd_repl_launcher.py against failure due to its members being cleared.

Fixes #2950 python interactive window crashed

---

Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs

Fixes #2921 Crash in PythonAnalysisClassifier
Switches to Linq OrderBy and key selection to order the values.
I don't actually know how we ever got "unstable comparer" errors before, but we're definitely doing normal integer comparisons now so it shouldn't happen again.

Fixes #2921 Crash in PythonAnalysisClassifier [3.1]

---

Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170830144024360 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170830144024360 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes for issues found in tests

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170831024019389 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170831024019389 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170831144040812 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170831144040812 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20170901024031399 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170901024031399 to master

---

Python/Product/BuildTasks/Microsoft.PythonTools.Web.targets

Exclude cloud service files for app service projects.

Fix #2201: Web projects are always rebuilt

---

Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Options/ExperimentalOptions.cs
Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.cs
Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.resx
Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsPage.cs
Python/Product/PythonTools/PythonToolsPackage.cs
Python/Product/PythonTools/PythonToolsService.cs
Python/Product/PythonTools/VSPackage.resx
Python/Product/VSInterpreters/ExperimentalOptions.cs
Python/Product/VSInterpreters/MSBuildProjectInterpreterFactoryProvider.cs
Python/Product/VSInterpreters/PythonInterpreterInformation.cs
Python/Product/VSInterpreters/VSInterpreters.csproj

Adds UI option for experimental DB flag.
Updates Options category localized name to just "Python"

Adds UI option for experimental DB flag.

---

Python/Setup/swix/Microsoft.PythonTools.vsmanproj
Python/Setup/swix/copysdkvsix.proj
Python/Setup/swix/dirs.proj

Fixes manifest build to ensure hash information is correctly created.

---

Common/Product/SharedProject/CommonPackage.cs
Common/Product/SharedProject/FileNode.cs
Common/Product/SharedProject/FolderNode.cs
Common/Product/SharedProject/HierarchyNode.cs
Common/Product/SharedProject/ProjectNode.CopyPaste.cs
Common/Product/SharedProject/ProjectNode.cs
Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/Ipc.Json/Connection.cs
Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs
Python/Product/PythonTools/PythonTools/Project/PythonFileNode.cs
Python/Tests/PythonToolsMockTests/PythonEditor.cs

Fixes #1575 Rename folder failed to "reparent" folder
Fixes most of the renaming issues.

Fixes #1575 Rename folder failed to "reparent" folder

---

Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20170925144126489 to master with localized lcls

LEGO: Pull request from lego/hb_839_20170925144126489 to master

---

Common/Product/SharedProject/Wpf/Controls.xaml
Python/Product/Cookiecutter/Shared/Wpf/Controls.xaml
Python/Product/EnvironmentsList/EnvironmentsList.csproj
Python/Product/EnvironmentsList/NoDBExtension.xaml
Python/Product/EnvironmentsList/NoDBExtension.xaml.cs
Python/Product/EnvironmentsList/Resources.Designer.cs
Python/Product/EnvironmentsList/Resources.resx
Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/VSInterpreters/ExperimentalOptions.cs

Make the no DB experiment enabled by default.
Adds UI informing the user and allowing them to disable it.

Make the no DB experiment enabled by default.

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/PythonTools/PythonTools.vsct

Fix https://github.com/Microsoft/PTVS/issues/2314

Rename the import coverage command

---

Python/Product/Analysis/AnalysisSet.cs
Python/Product/Analyzer/Intellisense/AnalysisProtocol.cs
Python/Product/Ipc.Json/Connection.cs
Python/Product/Ipc.Json/Response.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/TestAdapter.Analysis/TestAnalysisExtension.cs
Python/Product/TestAdapter/TestContainerDiscoverer.cs

Reduces JSON packet size by omitting default values for common properties
Batches test requests to avoid overwhelming analyzer
Improves handling of analysis set edge case
These all popped up while I was working with a large project from a customer.

Reduces JSON packet size by omitting default values for common properties

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171001144043718 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171001144043718 to master

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171002084031890 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171002084031890 to master

---

Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171002144036535 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171002144036535 to master

---

Python/Product/Analysis/scrape_module.py
Python/Tests/Analysis/AstAnalysisTests.cs

Fixes module scraping producing invalid code by doing repr on container contents
Updates tests to store scraped outputs.

Fixes module scraping producing invalid code

---

Python/Product/Analysis/Interpreter/Ast/AstPythonMultipleMembers.cs
Python/Tests/TestData/AstAnalysis/MultiValues.py

Fixes multiple assignments clearing existing members.
Adds test

Fixes multiple assignments clearing existing members.

---

Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171004144044424 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171004144044424 to master

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Suppress non-critical exception coming from IVsStatusbar.

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171004204031879 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171004204031879 to master

---

Python/Product/PythonTools/PythonTools/Navigation/CodeWindowManager.cs
Python/Product/PythonTools/PythonTools/Navigation/DropDownBarClient.cs

Fix #2678
Fix navigation bar not appearing on the active document on project load.
Fix navigation bar contents being empty after toggling on navigation bar in tools/options.

Navigation bar fixes

---

Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171006024111255 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171006024111255 to master

---

Common/Tests/MockVsTests/MockClassifierAggregatorService.cs
Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs
Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs

Fixes #3136 CompletionTest occasional failures
Prevents race condition in test versions
Improves range validation of arguments
Handles exceptions better in tests to ensure useful information is collected

Fixes #3136 CompletionTest occasional failures

---

Python/Product/Analysis/AnalysisLogWriter.cs

Yet another attempt to fix test timeouts due to an infinite loop on the finalizer thread.

Yet another attempt to fix test timeouts

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171009084037573 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171009084037573 to master

---

Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/Snippets/Python/arg_path.snippet
Python/Product/PythonTools/Snippets/Python/arg_path_positional.snippet
Python/Product/PythonTools/Snippets/Python/arg_str.snippet
Python/Product/PythonTools/Snippets/Python/arg_str_positional.snippet
Python/Product/PythonTools/Snippets/Python/arg_switch.snippet
Python/Product/PythonTools/Snippets/Python/argparse.snippet

I started writing a script (for another bug) and decided that I was sick of not having snippets for argparse. So here are some snippets for argparse :)

Adds argparse snippets.

---

Python/Product/PythonTools/ptvsd/repl/__init__.py
Python/Tests/ReplWindowUITests/ReplWindowUITests.cs
Python/Tests/ReplWindowUITestsRunner/ReplWindowSmokeUITests.cs
Python/Tests/TestData/ReplSysPath.sln
Python/Tests/TestData/ReplSysPath/ReplSysPath.pyproj
Python/Tests/TestData/ReplSysPath/Sub/module.py
Python/Tests/TestData/ReplSysPath/Sub/module2.py

Fix #2449 Execute in Interactive does not use debug settings
See my new comments in bug description for details.

Include the script's folder in sys.path for Execute Project in REPL

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/PythonTools/PythonTools/Repl/PythonReplEvaluatorProvider.cs
Python/Product/PythonTools/PythonToolsService.cs
Python/Tests/ReplWindowUITests/ReplWindowUITests.cs
Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs

Respect the clear PYTHONPATH option when creating the REPL launch configuration

---

Python/Tests/ReplWindowUITests/ReplWindowUITests.cs
Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs

Fix HistoryUpdateDef and HistoryAppendDef tests.

---

Python/Product/Profiling/Profiling/ProjectTargetView.cs
Python/Product/Profiling/PythonProfilingPackage.cs
Python/Product/PythonTools/PythonTools/Extensions.cs
Python/Tests/ProfilingUITests/ProfilingUITests.cs
Python/Tests/ProfilingUITestsRunner/ProfilingUITests.cs
Python/Tests/TestData/ProfileTestSolutionFolder.sln
Python/Tests/TestData/ProfileTestSolutionFolder/ProfileTestSolutionFolder.pyproj
Python/Tests/TestData/ProfileTestSolutionFolder/Program.py

Fix #1566 
Refactored some of the test code to avoid duplication and moved some functions around to keep all test cases together.

Fix profiling project inside solution folder

---

Python/Product/Analysis/scrape_module.py
Python/Tests/Analysis/AstAnalysisTests.cs

Fixes #3181 Cannot scrape special float types
Adds special cases for nan and inf

Fixes #3181 Cannot scrape special float types

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171020024034917 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171020024034917 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171020144108222 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171020144108222 to master

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171020204042524 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171020204042524 to master

---

Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs

This is a servicing fix for 15.4.2 to resolve the issue where you don't see any squiggles.

Fixes incorrect last-parse caching.

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171022144034900 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171022144034900 to master

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171023084020025 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171023084020025 to master

---

Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171023144035472 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171023144035472 to master

---

Python/Product/Analysis/AnalysisVariable.cs
Python/Product/Analysis/LocationInfo.cs
Python/Product/Analysis/ModuleAnalysis.cs
Python/Tests/PythonToolsMockTests/NavigableTests.cs

Fixes null location

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20171023204039490 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171023204039490 to master

---

Python/Product/Cookiecutter/Model/GitClient.cs
Python/Tests/CookiecutterTests/GitClientTests.cs

Prevent git from prompting in terminal

---

Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs

Fixes #3159 (again) No error squiggles
Corrects sense of comparison to exclude invalid squiggles.

Fixes #3159 (again) No error squiggles

---

Python/Product/PythonTools/PythonTools/PythonClassifier.cs
Python/Tests/PythonToolsMockTests/ClassifierTests.cs

Fixes #3143 No completions on multi line strings
Updates the classifier to produce a single coherent token for multiline strings.

Fixes #3143 No completions on multi line strings

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/arg_path.snippet.lcl
Python/loc/lcl/CHT/arg_path_positional.snippet.lcl
Python/loc/lcl/CHT/arg_str.snippet.lcl
Python/loc/lcl/CHT/arg_str_positional.snippet.lcl
Python/loc/lcl/CHT/arg_switch.snippet.lcl
Python/loc/lcl/CHT/argparse.snippet.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171026084032508 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171026084032508 to master

---

Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs
Python/Product/Analyzer/PyLibAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs

Fixes #3222 No IntelliSense on newly installed package
Re-enables file system watchers in out-of-proc analyzer.

Fixes #3222 No IntelliSense on newly installed package

---

Python/Product/Django/Microsoft.PythonTools.Django.targets
Python/Tests/DjangoUITests/DjangoProjectUITests.cs
Python/Tests/DjangoUITestsRunner/DjangoProjectUITests.cs
Python/Tests/TestData/DjangoAnalysisTestApp/DjangoAnalysisTestApp.pyproj
Python/Tests/TestData/DjangoAnalysisTestApp/DjangoAnalysisTestApp/settings.py

Prevent Django AppRegistryNotReady error in Django shell

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/arg_path.snippet.lcl
Python/loc/lcl/CSY/arg_path_positional.snippet.lcl
Python/loc/lcl/CSY/arg_str.snippet.lcl
Python/loc/lcl/CSY/arg_str_positional.snippet.lcl
Python/loc/lcl/CSY/arg_switch.snippet.lcl
Python/loc/lcl/CSY/argparse.snippet.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/arg_path.snippet.lcl
Python/loc/lcl/ITA/arg_path_positional.snippet.lcl
Python/loc/lcl/ITA/arg_str.snippet.lcl
Python/loc/lcl/ITA/arg_str_positional.snippet.lcl
Python/loc/lcl/ITA/arg_switch.snippet.lcl
Python/loc/lcl/ITA/argparse.snippet.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/arg_path.snippet.lcl
Python/loc/lcl/JPN/arg_path_positional.snippet.lcl
Python/loc/lcl/JPN/arg_str.snippet.lcl
Python/loc/lcl/JPN/arg_str_positional.snippet.lcl
Python/loc/lcl/JPN/arg_switch.snippet.lcl
Python/loc/lcl/JPN/argparse.snippet.lcl

LEGO: Pull request from lego/hb_839_20171027084106360 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171027084106360 to master

---

Python/Product/Analysis/Values/FunctionInfo.cs
Python/Tests/Analysis/AnalysisTest.cs

Fixes #388 Wrong parameter suggestion in IntelliSense when using decorator
Handles updates to __doc__ better
Includes overloads from __wrapped__

Fixes #388 Wrong parameter suggestion in IntelliSense when using decorator

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/arg_path.snippet.lcl
Python/loc/lcl/KOR/arg_path_positional.snippet.lcl
Python/loc/lcl/KOR/arg_str.snippet.lcl
Python/loc/lcl/KOR/arg_str_positional.snippet.lcl
Python/loc/lcl/KOR/arg_switch.snippet.lcl
Python/loc/lcl/KOR/argparse.snippet.lcl

LEGO: Pull request from lego/hb_839_20171030084047493 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171030084047493 to master

---

Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
Python/Product/PythonTools/PythonTools/PythonAnalysisClassifierProvider.cs

Fixes #3256 No analysis classifications in repl
Classifications now work, so re-enable them.

Fixes #3256 No analysis classifications in repl

---

Python/Product/PythonTools/ptvsd/debugger.py

fixes this issue:
https://github.com/mwaskom/seaborn/issues/1307

fix debugger channel name.

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20171101084035962 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171101084035962 to master

---

Common/Tests/Utilities.UI/UI/Keyboard.cs
Common/Tests/Utilities/Mocks/MockTextSnapshot.cs
Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs
Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Python/Product/PythonTools/PythonTools/TokenCache.cs
Python/Tests/Core.UI/EditorTests.cs
Python/Tests/Core/AutoIndentTests.cs

Fixes #3261 Smart indent being dumb
Fixes issues with smart indent.

Fixes #3261 Smart indent being dumb

---

Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171101204059213 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171101204059213 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171102204042116 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171102204042116 to master

---

Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
Python/Product/Analysis/Interpreter/Ast/NameLookupContext.cs
Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs
Python/Product/Analysis/KnownTypes.cs
Python/Product/Analysis/NoneType.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Tests/Analysis/BaseAnalysisTest.cs

Fixes #3248 Intellisense fails to scrape modules from other projects
Fixes lock statement to avoid failing.

Fixes #3248 Intellisense fails to scrape modules from other projects

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171103204126790 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171103204126790 to master

---

Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs
Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs
Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/PythonTools/PythonTools/SearchPathManager.cs
Python/Setup/signlayout.proj

Fixes #3248 and #3269 for v3.2.1.
Merges other changes from 3.2

Fixes #3248 and #3269 for v3.2.1

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Django.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Django.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171104204035065 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171104204035065 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171106094023346 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171106094023346 to master

---

Python/Product/Analysis/Parsing/Ast/PythonAst.cs
Python/Product/Analysis/Parsing/Tokenizer.cs
Python/Product/Debugger/Debugger/DebugEngine/AD7MemoryAddress.cs
Python/Product/Debugger/Debugger/PythonProcess.cs
Python/Tests/DebuggerUITests/DebugProjectUITests.cs

Fix #3270 
Also fixes EnumModules test.

Fixes breakpoints on first and last line

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171106214042093 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171106214042093 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171107094025355 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171107094025355 to master

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171107214036954 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171107214036954 to master

---

Python/Tests/Analysis/AstAnalysisTests.cs
Python/Tests/Analysis/UpdaterTests.cs
Python/Tests/Utilities.Python.Analysis/PythonAnalysis.cs

Also some test fixes
CodeFlow may be better at showing the actual changes - most lines just have increased indentation
Edit: I can confirm that CodeFlow is much better for this one

Reduce test output for AstAnalysisTests

---

Python/loc/lcl/JPN/Microsoft.PythonTools.Profiling.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171108214047410 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171108214047410 to master

---

Common/Tests/Utilities/Mocks/MockTextEdit.cs
Python/Product/Analyzer/Intellisense/OutOfProcMethodExtractor.cs
Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs

Fixes MockTextEdit having incorrect offsets.
Fixes extracting class
Fixes detecting possible expression

Fixes MockTextEdit having incorrect offsets.

---

Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs
Python/Product/PythonTools/PythonTools/TokenCache.cs

Fixes #3306 System.InvalidOperationException: uninitialized token cache
Switches to more conservative locking strategy.

Fixes #3306 System.InvalidOperationException: uninitialized token cache

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Profiling.dll.lcl

LEGO: Pull request from lego/hb_839_20171109214033497 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171109214033497 to master

---

Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171110094059520 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171110094059520 to master

---

Python/Product/PythonTools/ptvsd/repl/jupyter_client.py

Fixes #3310 No inline graph with jupyter client
Fixes incorrect result status check
Removes broken code
Makes error handling less silent

Fixes #3310 No inline graph with jupyter client

---

Python/loc/lcl/CSY/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171114094220237 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171114094220237 to master

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Analysis.dll.lcl

LEGO: Pull request from lego/hb_839_20171114214024525 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171114214024525 to master

---

Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs

Fixes the existing completions so that they are correct when the user changes the current frame. Also includes parameters in the completions, not just the locals.
Return completions when an expression (text) is supplied when executing in current frame.
I'm hesitant to do more at this time given our planned debugger improvements, and the consequences it may have on the debug repl implementation.

Some IntelliSense improvements in Debug REPL

---

Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Django.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20171115214037027 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171115214037027 to master

---

Python/Product/PythonTools/PythonTools/Options/PythonGeneralOptionsControl.resx
Python/Product/VSInterpreters/CondaPackageManager.cs

Fix elevation check for conda package manager.

---

Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreter.cs

Fixes all the currently failing AST analysis tests.

Fixes incorrect Unknown type.

---

Python/Product/PythonTools/ptvsd_launcher.py
Python/Tests/DebuggerUITests/DebuggerUITests.csproj
Python/Tests/DjangoUITests/DjangoUITests.csproj
Python/Tests/ReplWindowUITests/ReplWindowUITests.csproj

Adds a new command line switch to skip the bundled ptvsd package.

Add experimental basic ptvsd-pydevd support to launcher.

---

Build/15.0/packages.config
Build/Common.Build.targets
Python/Product/Core/Core.csproj
Python/Product/Core/VSCodeInterop.pkgdef
Python/Product/PythonTools/ProvidePeekSupportedContentTypeAttribute.cs
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Intellisense/InvalidEncodingSquiggleProvider.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/PythonAnalysisClassifier.cs
Python/Product/PythonTools/PythonToolsPackage.cs

Deploys debugger interop DLL if it is not installed.
Adds latest threading DLL so that tests can run.
Fixes #2959 Enables colorization in peek
Fixes analysis classifications not appearing on first file open

Assorted fixes for next release

---

Build/Common.Build.CSharp.targets
Python/Product/Analysis/AnalysisLog.cs
Python/Product/Analysis/AnalysisLogWriter.cs
Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/Ipc.Json/Connection.cs
Python/Product/PythonTools/PythonTools/Intellisense/InvalidEncodingSquiggleProvider.cs

Also fixes a string in the encoding warnings.

Few fixes to make tests work better.

---

Python/Templates/NativeDevelopment/ProjectTemplates/VC/Python/PythonExtensionModule/PythonTemplate.vcxproj
Python/Tests/TestData/ProjectReference/NativeModule/NativeModule.vcxproj

Fix #3397 
Match the SDK installed by C++ desktop AND Python native development tools.

Update Windows SDK version in native module template

---

Python/Product/IronPython/Interpreter/IronPythonInterpreterFactory.cs
Python/Product/PythonTools/PythonTools/Intellisense/ExtractMethodSuggestedActionSourceProvider.cs
Python/Product/PythonTools/PythonTools/Intellisense/PythonSuggestedActionsSource.cs
Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs
Python/Tests/Utilities.Python.Analysis/PythonPaths.cs

Waited for the build machine results to come back - it built fine.
Will try to fix the django stuff in a follow up PR.

Some build fixes.

---

Python/Product/PythonTools/PythonTools/Options/PythonFormattingGeneralOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonFormattingGeneralOptionsControl.resx

Removed format on paste option.

---

Python/Product/Analysis/AnalysisLogWriter.cs
Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs

Dump log synchronously if we are about to dispose of it.

---

Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs

Wrong path used in error message.

---

Python/Product/PythonTools/VSPackage.resx

Added cookiecutter to ML project names

---

Python/Product/Django/Intellisense/DjangoCompletionSource.cs

FromTextBuffer always returned null when using _buffer.

---

Common/Tests/MockVsTests/MockCompletionBroker.cs
Common/Tests/MockVsTests/MockCompletionSession.cs
Common/Tests/Utilities/AssertListener.cs
Python/Product/Analyzer/Intellisense/ExtractedMethodCreator.cs
Python/Tests/VSInterpretersTests/VSInterpretersTests.cs

Still validating that it _actually_ fixes the assertion issues, but figured I'd put the code up anyway.

Fixes some test issues

---

Python/Product/Analysis/Analyzer/ExpressionEvaluatorAnnotationConverter.cs
Python/Product/Analysis/Analyzer/FunctionScope.cs
Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
Python/Product/Analysis/Interpreter/InterpreterFactoryCreationOptions.cs
Python/Product/Analysis/ModuleAnalysis.cs
Python/Product/Analysis/Values/BuiltinClassInfo.cs
Python/Product/Analysis/scrape_module.py
Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs
Python/Product/IronPython/Interpreter/IronPythonInterpreterFactory.cs
Python/Product/IronPython/Interpreter/IronPythonInterpreterFactoryProvider.cs
Python/Product/IronPython/Interpreter/RemoteInterpreter.cs
Python/Product/IronPython/IronPython.Interpreter.csproj
Python/Tests/Analysis/AstAnalysisTests.cs
Python/Tests/IronPython/IronPythonAnalysisTest.cs
Python/Tests/IronPython/IronPythonDatabaseTest.cs
Python/Tests/IronPython/ReplEvaluatorTests.cs

Fixes #3449 IronPython still use IntelliSense DB when new style IntelliSense is enabled
Makes AST analysis subclassable
Adds IronPython subclass for AST analysis

Fixes #3449 IronPython still use IntelliSense DB when new style IntelliSense is enabled

---

Common/Tests/MockVsTests/MockQuickInfoBroker.cs
Python/Product/Django/Intellisense/TemplateCompletionController.cs
Python/Product/Django/Intellisense/TemplateCompletionControllerProvider.cs
Python/Product/PythonTools/PythonTools.csproj
Python/Product/PythonTools/PythonTools/Editor/PythonEditorServices.cs
Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Python/Product/PythonTools/PythonTools/Intellisense/QuickInfoSource.cs
Python/Product/PythonTools/PythonTools/Intellisense/QuickInfoSourceProvider.cs

Fix #3466 
I'll open another bug for us to switch to the new APIs, which is not as urgent as building successfully.

Disable deprecation warnings for quick info API changes

---

Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171212214029345 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171212214029345 to master

---

Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171213094021178 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171213094021178 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171213214029899 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171213214029899 to master

---

Python/Product/PythonTools/PythonTools.csproj
Python/Tests/DjangoTests/DjangoAnalyzerTests.cs
Python/Tests/DjangoTests/DjangoTests.csproj

Fixes build due to some incorrect references.
Disables tests that do not build.

Fixes build due to some incorrect references.

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20171214094016072 to master with localized lcls

LEGO: Pull request from lego/hb_839_20171214094016072 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.TestAdapter.Executor.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180103214057333 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180103214057333 to master

---

Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.Designer.cs
Python/Product/PythonTools/PythonTools/Options/PythonExperimentalOptionsControl.resx

Hiding the VSCode Debugger experimental option.

---

Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180119094018306 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180119094018306 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/AnalysisEntryService.cs
Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs
Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/PythonDebugProcessReplEvaluator.cs

Fixes #3573 Unexpected error analysis/debug interactive
Ensures DocumentUri is checked for null

Fixes #3573 Unexpected error analysis/debug interactive

---

Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs
Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs
Python/Product/PythonTools/PythonTools/Repl/PythonInteractiveEvaluator.cs

Fixes #3559 Improves error message when scripts path is unusable

Fixes #3559 Improves error message when scripts path is unusable

---

Python/Product/AnalysisMemoryTester/Program.cs

Fixes #3582 AnalysisMemoryTester build error

Fixes #3582 AnalysisMemoryTester build error

---

Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180119214024228 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180119214024228 to master

---

Python/Product/PythonTools/ptvsd/debugger.py

Check if __stdout__ is None

---

Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180121094021776 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180121094021776 to master

---

Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs

Fixes #3538 Assertion failed when using snippets
Removes change merging

Fixes #3538 Assertion failed when using snippets

---

Python/Product/PythonTools/PythonTools/Intellisense/TaskProvider.cs

Fixes #3403 Long list of errors hang VS
Moves squiggles off UI thread

Fixes #3403 Long list of errors hang VS

---

Python/Product/AssemblyVersion.cs

Fixes #3609 Product/file version doesn't have a build number

Fixes #3609 Product/file version doesn't have a build number

---

Python/Product/Profiling/Profiling/ProfilingTarget.cs

Fix #3610 Profiling no longer works
XmlSerializer requires types to be public.

Fix profiling

---

Python/Product/Profiling/Profiling/ProfilingTarget.cs

Fix profiling (master branch)

---

Python/Product/ProjectWizards/ProjectWizards.csproj
Python/Product/ProjectWizards/Properties/AssemblyInfo.cs
Python/Product/Uwp.Wizards/Properties/AssemblyInfo.cs
Python/Product/Uwp.Wizards/Uwp.Wizards.csproj
Python/Templates/Core/ProjectTemplates/Python/KinectGame/KinectGame.vstemplate
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClassifierTemplate/ClassifierTemplate.vstemplate
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/ClusteringTemplate/ClusteringTemplate.vstemplate
Python/Templates/Core/ProjectTemplates/Python/Machine Learning/RegressionTemplate/RegressionTemplate.vstemplate
Python/Templates/Core/ProjectTemplates/Python/PyvotProject/PyvotProject.vstemplate
Python/Templates/Django/ProjectTemplates/Python/Web/DjangoProject/DjangoApp.vstemplate
Python/Templates/Django/ProjectTemplates/Python/Web/PollsDjango/PollsDjango.vstemplate
Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject/StarterDjangoProject.vstemplate
Python/Templates/Django/ProjectTemplates/Python/Web/WebRoleDjango/WebRoleDjango.vstemplate
Python/Templates/Uwp/ProjectTemplates/Python/Windows IoT Core/BackgroundService/PythonBackgroundService.vstemplate
Python/Templates/Web/ItemTemplates/Python/AzureDebugWebConfig/AzureDebugWebConfig.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/CloudService/CloudService.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/PollsBottle/PollsBottle.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlask/PollsFlask.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/PollsFlaskJade/PollsFlaskJade.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/StarterBottleProject/StarterBottleProject.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskJadeProject/StarterFlaskJadeProject.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskProject/StarterFlaskProject.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectBottle/WebProjectBottle.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectFlask/WebProjectFlask.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleBottle/WebRoleBottle.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/WebRoleFlask/WebRoleFlask.vstemplate
Python/Templates/Web/ProjectTemplates/Python/Web/WorkerRoleProject/WorkerRoleProject.vstemplate

Fixes #3631 Error creating new bottle project
Updates all templates for new version number.

Fixes #3631 Error creating new bottle project

---

Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180123214047038 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180123214047038 to master

---

Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs

Fixes #3635 Uncallable decorator results in no function

Fixes #3635 Uncallable decorator results in no function

---

Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs
Python/Product/Analysis/PythonAnalyzer.cs
Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs
Python/Product/VSInterpreters/Interpreter/InterpreterOptionsService.cs

Fixes #3636 Code analysis not updated after changing packages
Adds event handling for changed packages.
Adds ObjectDisposedException handling for timers.

Fixes #3636 Code analysis not updated after changing packages

---

Python/Product/PythonTools/PythonTools/Debugger/ProvideDebugAdapterAttrributes.cs

This should be reverted after https://github.com/Microsoft/ptvsd/issues/21 is implemented.

Suppressing modules request on attach

---

Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180130062722234 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180130062722234 to 15.6rel

---

Python/loc/lcl/CHS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CHT/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/CSY/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/DEU/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ESN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/FRA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/ITA/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/JPN/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/KOR/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PLK/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/PTB/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/RUS/Microsoft.CookiecutterTools.dll.lcl
Python/loc/lcl/TRK/Microsoft.CookiecutterTools.dll.lcl

LEGO: Pull request from lego/hb_839_20180130214025982 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180130214025982 to 15.6rel

---

Python/Product/Django/Project/IDjangoProject.cs
Python/Product/Django/Project/ProjectSmuggler.cs

Fix #3627 No completions in django templates
Reverts change that made some types internals.

Fix IntelliSense in django templates

---

Python/Product/Analysis/Infrastructure/StringExtensions.cs
Python/Product/Common/Infrastructure/StringExtensions.cs
Python/Product/Cookiecutter/Shared/Infrastructure/StringExtensions.cs

Fix #3690 and probably a bunch of other stuff

Fix EndsWithOrdinal extension method

---

Common/Tests/Utilities/Mocks/MockNormalizedTextChangeCollection.cs
Python/Product/Analysis/Analyzer/FunctionAnalysisUnit.cs
Python/Product/Analysis/LanguageServer/Messages.cs
Python/Product/Analysis/LanguageServer/Server.cs
Python/Tests/Analysis/AnalysisTest.cs
Python/Tests/Analysis/LanguageServerTests.cs

Adds missing method to mock
Improves fallback for unhelpful decorators

Fixes tests and decorators

---

Common/Tests/Utilities/Mocks/MockTextEdit.cs
Python/Product/Analysis/Analysis.csproj
Python/Product/Analysis/Intellisense/LineInfo.cs
Python/Product/Analysis/Intellisense/LinePreservingCodeReplacer.cs
Python/Product/Analysis/Intellisense/LongestCommonSequence.cs
Python/Product/Analysis/Parsing/Tokenizer.cs
Python/Tests/Analysis/AnalysisTests.csproj
Python/Tests/Analysis/LongestCommonSequenceTests.cs
Python/Tests/Core/CodeFormatterTests.cs

This also fixes https://github.com/Microsoft/PTVS/issues/3662 (at least it correctly works with repro sample), but I'm not sure if we should merge this into 15.6 or into master.

Fix #3566: Improve LinePreservingCodeReplacer.ReplaceCode

---

Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs

Fix NullReferenceException in IntellisenseController.DisconnectSubjectBuffer

---

Python/Product/Cookiecutter/View/CookiecutterOptionsPage.xaml
Python/Product/Cookiecutter/View/CookiecutterSearchPage.xaml
Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs
Python/Product/ProjectWizards/CookiecutterWizard.cs

Fix #3707 Cookiecutter should respect create solution folder option in new project dialog
Fix #3661 Cookiecutter progress bar should not move the button when it shows up
(similar fix for the second page also included)

Cookiecutter fixes

---

Python/Product/PythonTools/PythonTools/Project/AddVirtualEnvironmentOperation.cs
Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Fix #3483 Install from requirements error when using conda

Always use pip when installing or generating requirements.txt.

---

Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs

Reverts Microsoft/PTVS#3726
The change introduced regressions, see screenshots at #3722

Revert "Fixes #3722 REPL indent is not calculated properly"

---

Python/Product/Django/Django.csproj
Python/Product/Django/Resources.Designer.cs

Fix #3741
Regression from when a lot of types were made internal.

Fix the Add Django App command 

---

Python/Product/Debugger/DebugAdapterProcessStream.cs

Fixes #3734 VSC debugger fails to write data

---

Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180220094019365 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180220094019365 to 15.6rel

---

Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180220034051864 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180220034051864 to 15.6rel

---

Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180220214020888 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180220214020888 to 15.6rel

---

Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180221094015131 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180221094015131 to 15.6rel

---

Python/Product/Debugger/DebugAdapterProcess.cs

Launches the browser if there is a web url present in the options.

---

Common/Tests/Utilities.UI/UI/VisualStudioApp.cs
Python/Tests/Core.UI/PythonToolsUITests.csproj
Python/Tests/Core.UI/TestExplorerTests.cs
Python/Tests/PythonToolsUITestsRunner/PythonToolsUITestsRunner.csproj
Python/Tests/PythonToolsUITestsRunner/TestExplorerTests.cs
Python/Tests/TestData/TestExplorer.sln
Python/Tests/TestData/TestExplorer/TestExplorer.pyproj
Python/Tests/TestData/TestExplorer/test1.py
Python/Tests/Utilities.Python/MockPackageManager.cs
Python/Tests/Utilities.Python/MockReplWindow.cs
Python/Tests/Utilities.Python/PythonTestExplorer.cs
Python/Tests/Utilities.Python/PythonVisualStudioApp.cs
Python/Tests/Utilities.Python/ReplWindowProxy.cs
Python/Tests/Utilities.Python/TestUtilities.Python.csproj

Add smoke test (UI) for test explorer integration

---

Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180221214016856 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180221214016856 to 15.6rel

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180222034019416 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180222034019416 to 15.6rel

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180222070417637 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180222070417637 to 15.6rel

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180222094257438 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180222094257438 to 15.6rel

---

Python/Product/PythonTools/PythonTools/Editor/AutoIndent.cs

Fixes #3722 REPL indent is not calculated properly
Moves buffer correction to after caret line correction
Maps back from the correct line for indent adjustment

Fixes #3722 REPL indent is not calculated properly

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180222214025616 to 15.6rel with localized lcls

LEGO: Pull request from lego/hb_839_20180222214025616 to 15.6rel

---

Python/Product/Debugger/DebugAdapterProcessStream.cs

Fixes issue with debugger socket connection after application exits

---

Python/Product/PythonTools/ptvsd/repl/jupyter_client.py

Fix #3799 Jupyter client raw_input handling

Fix NameError exception handling.

---

Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs

Fix #3805 Error in interactive window after enabling conda support without anaconda installed
There was one place where `found` was being used without checking for null. I 'reversed' the code so the variable is initialized to non null and never changes after that.

Prevent a NullReferenceException when a global conda is not found.

---

Python/Tests/PythonToolsMockTests/NavigableTests.cs

All 7 tests were failing, now it's down to 3 failures, where analysis is returning more locations than expected.

Navigable tests

---

Python/Product/PythonTools/ptvsd/ipcjson.py
Python/Product/PythonTools/ptvsd/repl/jupyter_client.py

Fixes #3800 Unhandled errors in Jupyter client
Adds handling for errors that are expected in certain circumstances.

Fixes #3800 Unhandled errors in Jupyter client

---

Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180308034306421 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180308034306421 to master

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180309095622617 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180309095622617 to master

---

Python/Product/Analysis/Values/GeneratorInfo.cs

Fixes #3853 Stack overflow analyzing generators
Fix union comparison and merging of generators.

Fixes #3853 Stack overflow analyzing generators

---

Python/Product/Analysis/Values/GeneratorInfo.cs

Fixes #3853 Stack overflow analyzing generators.
Fix union comparison and merging of generators.

Fixes #3853 Stack overflow analyzing generators.

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/Debugger/DebugAdapterProcess.cs
Python/Product/PythonTools/ptvsd_launcher.py

Show a message box with details in case of ptvsd ImportError

---

Python/Product/Analysis/Infrastructure/ProcessHelper.cs

Fixes #3863 Crash getting list of packages with invalid environment
Handles all exceptions when a process fails to start

Fixes #3863 Crash getting list of packages with invalid environment

---

Python/Product/Analyzer/Interpreter/LegacyDB/CPythonInterpreter.cs

Fixes #3861 Stack overflow resolving lazy module import.
Adds recursion checks when importing modules.

Fixes #3861 Stack overflow resolving lazy module import.

---

Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs

Fixes #3830 Attaching existing virtual environment
Ensures Include path is not empty.

Fixes #3830 Attaching existing virtual environment

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHS/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180314154023295 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180314154023295 to master

---

Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180315154038154 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180315154038154 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CSY/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180314214030028 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180314214030028 to master

---

Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180316034039953 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180316034039953 to master

---

Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/TRK/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180316154024656 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180316154024656 to master

---

Python/Product/Common/Strings.Designer.cs
Python/Product/Common/Strings.resx
Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs
Python/Product/VSInterpreters/Interpreter/ExperimentalOptions.cs

Fix #3782 Enable conda package/env management by default
Fix #3885 Duplicate environments detected for root Anaconda
Also cosmetic change to package manager command UI.

Enable conda support by default

---

Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Debugger.Concord.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180316214038889 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180316214038889 to master

---

Python/Product/EnvironmentsList/Resources.Designer.cs
Python/Product/EnvironmentsList/Resources.resx

Fix #3884 Clarify removed DB message in environments window

Clarify the "No IntelliSense DB" message.

---

Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180317094021123 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180317094021123 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/DEU/Microsoft.PythonTools.Debugger.Concord.dll.lcl

LEGO: Pull request from lego/hb_839_20180317214024655 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180317214024655 to master

---

Python/Product/Analysis/Interpreter/Ast/NameLookupContext.cs
Python/Product/Analysis/Parsing/Parser.cs
Python/Product/Analysis/ProjectEntry.cs
Python/Product/Analysis/scrape_module.py
Python/Tests/Analysis/AstAnalysisTests.cs

Improves scraping
Fixes buffer not resetting last parse correctly.

Improves scraping

---

Python/Product/Analysis/Interpreter/InterpreterConfiguration.cs
Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs

Use full description for conda environments.

---

Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs

This will handle when a newer version of the analysis DLL is installed, and automatically regenerate any cached files. This is transparent to users - it will be a little slower to get completions for the imported module, but only once.

Ensures analysis cache is reset after installing updates.

---

Python/Product/Analysis/PythonAnalyzer.cs

Fixes #3918 NullReferenceException in GeneratorInfo while analyzing a simple module
Adds more explanatory error message when using an improperly initialized analyzer.

Fixes #3918 NullReferenceException in GeneratorInfo while analyzing a simple module

---

Python/loc/lcl/CHS/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/CHT/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ESN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/ITA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/JPN/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/KOR/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/RUS/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180322154034604 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180322154034604 to master

---

Python/loc/lcl/CSY/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180322214023510 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180322214023510 to master

---

Python/loc/lcl/DEU/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/FRA/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PLK/Microsoft.PythonTools.Common.dll.lcl
Python/loc/lcl/PTB/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180323034030359 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180323034030359 to master

---

Python/loc/lcl/TRK/Microsoft.PythonTools.Common.dll.lcl

LEGO: Pull request from lego/hb_839_20180324034018382 to master with localized lcls

LEGO: Pull request from lego/hb_839_20180324034018382 to master

---

Python/Product/Common/Strings.resx

I briefly considered pulling out the part that shouldn't be translated but then realized that would force localization to deal with these strings once more and felt bad about it.
fix #3912

Clarify localization comments.

---

Python/Product/VSInterpreters/Interpreter/ExperimentalOptions.cs

Fix #3953 Reset new IntelliSense to be enabled by default

Rename registry key for New Style IntelliSense option

---

Python/Product/Debugger/DebugAdapterProcess.cs
Python/Product/Debugger/DebugAdapterRemoteProcess.cs
Python/Product/Debugger/PtvsdVersionHelper.cs

Fixes serialization issue with ptvsd system info
